### ISSUE TITLE
Homepage category: Water

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#1004]
This category replaces the Portraits & People homepage category.

Aggregate using metadata from:

Subjects:
Bottled water
Distilled water
Drinking water
Drinking water--Analysis
Drinking water--Arsenic content
Drinking water--Contamination
Drinking water--Government policy
Drinking water--Health aspects
Drinking water--Law and legislation
Drinking water--Lead content
Drinking water--Microbiology
Drinking water--Purification
Drinking water--Safety measures
Drinking water--Standards
Drinking water--Testing
Groundwater
Mineral waters
Mineral water industry
Oceanography
Oceanography--Research
Safe Water Drinking Act of 1974 (United States)
Saline water conversion plants
Seawater
Seawater--Analysis
Seawater--Composition
Seawater corrosion
Seawater--Distillation
Selters water
Water
Water--Analysis
Water filters
Water--Fluoridation
Water--Fluoridation--Health aspects
Water--Fluoridation--Standards
Water-supply
Water pollution
Water-power
Watershed management
Watershed restoration
Watersheds
Watersheds--Analysis
Watersheds--Environmental aspects
Watersheds--Research
Watersheds--Recreational use
Water-wheels
Water purification chemicals industry
Water quality
Water quality--Measurement
Water quality management
Water--Hardness
Water--Hardness--Health aspects
Water--Hardness--Physiological effect
Water--Purification
Water--Purification--Distillation process
Water--Softening
Water--Softening--Equipment and supplies
Water--Testing
Water resources development
Water treatment plants
Waterways
Wells

Curatorial note: in its current iteration, this subject list purposely excludes specific forms and bodies of water, including ice, rivers, oceans, etc.

**Comment by HKativa** [comment]
Text for collection description:

This digital collection features a broad spectrum of materials related to water quality, testing, and analysis, including advertisements, oral history interviews, photographs, and print materials. Other subjects represented in the collection include water-power and the chemical treatment of water, as well as the extraction of magnesium from seawater. 

Use this image for thumbnail: water_c247ds80n_cropped.tif (P:\Othmer Library\Digital Collections - External Access\Crops for Hydra Redesign\cropped_tiffs\categories)

**Comment by eddierubeiz** [comment]
The thumbnail needs to be just a bit taller -- it doesn't quite make it to the label underneath.
![this screenshot](https://user-images.githubusercontent.com/94723/110244082-1eae6900-7f2b-11eb-906b-dbb7669b469d.png).

**Comment by eddierubeiz** [comment]
We seem to have lost the instructions for creating thumbnails, so I've recreated them in the wiki at https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/1646428165/Creating+a+thumbnail+for+a+Featured+Topic+landing+page.
