### ISSUE TITLE
Plan for future ingest of video interviews

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/scihist_digicoll#1006]
Not required for retiring the microsite, but we'll have to address this because almost all of the Science and Disability OHs were with video. (Possibly about two dozen.) Atmospheric Science OHs were mostly audio but some video at the end. Not sure if/how these transcripts will since with these hybrid AV files.

**Comment by jrochkind** [comment]
This was really about doing the R&D we've already ended up doing for our archival video. 

We now do know how to host video, and are doing it!

While we may need to develop slightly different ways of displaying it for video OH... I think we'll make ticket(s) for that when there is some push to do video OH's. 

This ticket to my mind was really about the R&D to learn how to host video at all, which we've done, so I'm going to close it!
