### ISSUE TITLE
Test Set Trials for 5-7 batches of oral histories with restrictions

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/scihist_digicoll#1009]
Hillary will test sample sets of oral histories that Lee has given her. After testing the functionality for these 5-7 different buckets, she will inform us on whether we need any additional features or front-end development work.

**Comment by HKativa** [comment]
Two interviews from test batch "Permissions required" are now available on staging:
https://staging-digital.sciencehistory.org/works/ravrl1u (interview includes PDF transcript and audio files)
https://staging-digital.sciencehistory.org/works/481l5bg (interview includes PDF transcript, no audio files)

For context, the permissions for files and metadata associated with oral histories in this category are as follows: 
•	Metadata: Public
•	Front Matter and Index: Public 
•	Full Transcript: Private
•	Audio Files: Private

Assets categorized as “private” are made available to users upon request following a manual review, initiated through the Digital Collections site, by oral history staff.

During test, back-end functionality worked as expected. In terms of front-end display, no further work is necessary unless anyone wants to tweak the blurb under "Access this interview."

**Comment by HKativa** [comment]
Notes from test batch "Metadata Only, No Synopsis/Abstract" category. Test records:
https://staging-digital.sciencehistory.org/works/j171kq6
https://staging-digital.sciencehistory.org/works/ggjg0eq

Permissions for files and metadata associated with oral histories in this category are as follows: 
•	Metadata: Public 
•	Full Transcript: Private
•	Audio Files: Private
Note: The Front Matter and Index file is NOT uploaded to oral histories in this category. 

Assets categorized as “private” are made available to users upon request following a manual review, initiated through the Digital Collections site, by oral history staff.

During test, back-end functionality worked as expected, and no further work is needed. A couple of outstanding questions:

- What information, if any, should appear in the description field? Lee to draft blurb and share with Dave for review.

- The cover page of the transcript currently serves as the representative image for these records, even though the transcript is set to "private." The representative image is only visible as a thumbnail when the interview comes up in search results. In conversation with Hillary, Lee confirmed this is probably fine - alternatives would be a portrait, if we had one, or some kind of generic icon, like the box image for Collection pages without a representative image.

**Comment by lsberry16** [comment]
For all interviews in the "Metadata Only, No Synopsis/Abstract" category, the description field should say:

At the request of the interviewee, the abstract of the interview and interviewee’s biographical data have not been included. For more information, please contact the Center for Oral History.

I believe the COH email address (oralhistory@sciencehistory.org) will be right there on the page in the "Access this Interview" box, so it doesn't need to be repeated in the Description field.

**Comment by MDiMeo** [comment]
@HKativa will do a batch edit to add @lsberry16's request and then we can close this ticket.

**Comment by HKativa** [comment]
Records in the "Metadata Only, No Synopsis/Abstract" have been batch edited to add Lee's note to the description field.
