### ISSUE TITLE
OH Microsite URL Redirects

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/scihist_digicoll#1011]
Before we eradicate the microsite, we need to redirect oh.sciencehistory.org to the Oral History Collection landing page on Digital Collections, and make sure that links to oral histories (like from Wikipedia) go to the oral history record in Digital Collections instead.

**Comment by jrochkind** [comment]
Back to backlog to remind us that we need to do a final data sync right before we shut down microsite and re-point it's DNS.

**Comment by lsberry16** [comment]
I Googled site:oh.sciencehistory.org and identified some categories of links that I think are going to need manual intervention, or that we can just declare dead. I have this info in a Word doc if that's more helpful.

MISC:

https://oh.sciencehistory.org/oral-histories/projects
Redirect to new OH Projects page on main site, which I’m asking Clare to create

https://oh.sciencehistory.org/oral-histories/resources
This will be a dead link

https://oh.sciencehistory.org/oral-histories/access-levels
This will be a dead link


BROWSE ALPHABETICALLY:

For example: https://oh.sciencehistory.org/oral-histories/B
These links to lists of interviewees by initial letter of last name will be dead.


INTERVIEW-BY-SPONSOR

For example: https://oh.sciencehistory.org/interview-by-sponsor/54
I had forgotten these existed and to the best of my knowledge there are no live links to these anywhere in the wild. I assume they’ll be dead, and I believe that’s totally fine. I believe we have a creator field for “sponsor” now, so if we want to add a faceted search by sponsor in the future, we could do that.


PROJECTS:

https://oh.sciencehistory.org/project-name/69
redirect to https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Pew+Biomedical+Scholars

https://oh.sciencehistory.org/project-name/36
redirect to
https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Chemical+History+of+Electronics

https://oh.sciencehistory.org/project-name/38
redirect to
https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Mass+Spectrometry

https://oh.sciencehistory.org/project-name/43
redirect to
https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Scientific+and+Technical+Information+Systems

https://oh.sciencehistory.org/project-name/42
redirect to
https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=REACH+Ambler

https://oh.sciencehistory.org/project-name/44
redirect to
https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Oral+History+of+the+Toxic+Substances+Control+Act

https://oh.sciencehistory.org/project-name/40
redirect to
https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Nanotechnology

https://oh.sciencehistory.org/project-name/66
redirect to https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Atmospheric+Science

https://oh.sciencehistory.org/project-name/78
redirect to https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Life+Sciences+Foundation

https://oh.sciencehistory.org/project-name/79
redirect to
https://digital.sciencehistory.org/collections/gt54kn818?f%5Bproject_facet%5D%5B%5D=Origins+of+Science+and+Technology+Studies

**Comment by lsberry16** [comment]
Incidentally, I'm also working with Nic to make sure that the lists of interviewees by project we're redirecting to actually match the lists from the microsite. I noticed significant discrepancies in some, which just means the project field in the digital collections data needs to be updated.

**Comment by jrochkind** [comment]
@lsberry16 No problem! We'll probably wait until you have them all to do them, so we don't get confused about which we have implemented and which we have not. Although I guess the only one we're waiting for is "Redirect to new OH Projects page on main site, which I’m asking Clare to create"?

@eddierubeiz I could just add redirects to the existing config/.yml file, but then if you re-generate it, it from fresh database, it would overwrite them. How should we handle this as far as code management, do you think?

**Comment by lsberry16** [comment]
@jrochkind Yep, there's only that one that we're waiting for.

**Comment by eddierubeiz** [comment]
Nah, @jrochkind  -- the rake task writes to stdout. Do your thing! I'll replace the appropriate chunk with the output of the rake task in due course.

**Comment by jrochkind** [comment]
@eddierubeiz OK cool, maybe we can put the manual ones at the top of the file, and then the pasted auto-generated ones after them, after a comment like "# AUTO-GENERATED AFTER HERE" or something. 

I think I'll wait for the missing URL to do em all at once.

**Comment by eddierubeiz** [comment]
The missing URLs are in (as of yesterday, the mapping is complete), so I went ahead and added the project URLs and made a PR (see above.)

**Comment by jrochkind** [comment]
Hooray! Nice work! Do you think this is the last time we have to do this, it's complete? Should we close this ticket?

**Comment by jrochkind** [comment]
We're still waiting for one URL that needs to be created on SHI website, to redirect to.

**Comment by eddierubeiz** [comment]
Yes, this ticket can be closed. Any further changes to the redirect URLs can be done as separate tickets.

**Comment by jrochkind** [comment]
We still need that one URL, no?

**Comment by eddierubeiz** [comment]
Nope - all the pdf and interview URLS are mapped and already deployed to production.

**Comment by jrochkind** [comment]
@eddierubeiz Just to make sure we are talking about the same thing, confirm we have this in code already?

> https://oh.sciencehistory.org/oral-histories/projects
> Redirect to new OH Projects page on main site, which I’m asking Clare to create

**Comment by eddierubeiz** [comment]
Oh, no, you're absolutely right. Let me rectify that -- Clare did create the page and it's at https://www.sciencehistory.org/oral-history-projects .
Glad you caught this!
