### ISSUE TITLE
maintain S3 configuration in infrastructure-as-code

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1023]
Once we move to heroku and away from our existing ansible playbooks. We will still need to maintain our S3 buckets, and using an infrastructure-as-code tool for them specifically is a good idea (they have gotten a bit complex). 

Either pull it out of the ansible, or I'd like to consider doing a terraform thing just for our S3 buckets.

**Comment by jrochkind** [comment]
If we do terraform for our S3 buckets, perhaps we could for our other AWS resources too -- SES (email), and Cloudfront?

**Comment by jrochkind** [comment]
Dup of #875

**Comment by jrochkind** [comment]
This is done!  Terraform config for both S3 and cloudfront. https://github.com/sciencehistory/terraform_scihist_digicoll

@eddierubeiz can you review readme, and maybe install terraform and try to do a few things? We can do a "pair" screenshare/teleconf to look at it if you want!

**Comment by eddierubeiz** [comment]
Already looked at readme, but need to educate myself. Let me just install terraform and check out your code and mess around. I'll probably have a bunch of questions, so stay tuned for a meeting request later this week.
