### ISSUE TITLE
24 interviewers have no profile text in the microsite

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1057]
We may choose to relax the restriction on blank interviewer profiles in the digital collections, *or* enter a summary (possibly boilerplate) bio in the microsite.

For now [the profile for profile-less interviewers reads "No profile for this interviewer."](https://staging-digital.sciencehistory.org/admin/interviewer_profiles/3251/edit); obviously we'll want to change that.

```
{"interviewer_id":3236,"interviewer_name":"Neil D. Hathaway"},
{"interviewer_id":3245,"interviewer_name":"Steven J. Novak"},
{"interviewer_id":3250,"interviewer_name":"William Van Benschoten"},
{"interviewer_id":3251,"interviewer_name":"Andrea R. Maestrejuan"},
{"interviewer_id":3253,"interviewer_name":"Marcia L. Meldrum"},
{"interviewer_id":3254,"interviewer_name":"Helene L. Cohen"},
{"interviewer_id":3256,"interviewer_name":"Robert Kohler"},
{"interviewer_id":3258,"interviewer_name":"Susan M. Lindee"},
{"interviewer_id":3259,"interviewer_name":"Naomi Morrissette"},
{"interviewer_id":3262,"interviewer_name":"Robin Mejia"},
{"interviewer_id":3264,"interviewer_name":"Nicole C. Nelson"},
{"interviewer_id":5865,"interviewer_name":"Natalie Konrad"},
{"interviewer_id":5870,"interviewer_name":"Sarah Goldfine"},
{"interviewer_id":5879,"interviewer_name":"Richard Sawyer"},
{"interviewer_id":5884,"interviewer_name":"Frances Kohler"},
{"interviewer_id":5900,"interviewer_name":"Stephanie Morris"},
{"interviewer_id":6183,"interviewer_name":"Ron Doel"},
{"interviewer_id":6205,"interviewer_name":"Paul J. Anderson"},
{"interviewer_id":6282,"interviewer_name":"Audra J. Wolfe"},
{"interviewer_id":6312,"interviewer_name":"Michael Wronski"},
{"interviewer_id":7073,"interviewer_name":"Mary Ellen Bowden "},
{"interviewer_id":7171,"interviewer_name":"Charles Price"},
{"interviewer_id":7500,"interviewer_name":"Jennifer Dionisio"},
{"interviewer_id":7501,"interviewer_name":"Pei Koay"},
```

**Comment by jrochkind** [comment]
@eddierubeiz 

> We may choose to relax the restriction on blank interviewer profiles in the digital collections, or enter a summary (possibly boilerplate) bio in the microsite.

There is no requirement in Digital Collections that every Work have an interviewer profile, is there? 

So I think this is just a Work without a linked profile, right? How is it showing up as "No profile for this interview", are you importing that as text? Don't do that, just don't import or link a blank profile, right?

Am I missing something?

I am pretty sure I wrote the code to be fine if there's no linked profile -- if not, we can fix that.

**Comment by jrochkind** [comment]
Also please remmeber to add oral histories label to all relevant issues, or we're going to miss it on reviewing oral histories work.

**Comment by eddierubeiz** [comment]
No, this is much easier to fix than that -- it's just a matter of relaxing the validation on the profile object so that it allows null text in the profile text field. Didn't want to do it silently though -- just creating this ticket so I didn't forget to mention it.

**Comment by eddierubeiz** [comment]
This is resolved: we are simply not creating entries in the "interviewer profile" table for interviewers unless we have profile text for them.
