### ISSUE TITLE
Carbon copy oralhistory@sciencehistory.org on emails responding to oral history access requests

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1069]
When a staff member approves or rejects an oral history access request, send a cc of the response email to oralhistory@sciencehistory.org for our records.

From @lsberry16  who somehow doesn't have Github permission to create Github issues (I didn't even know you had to have special permissions to create GH issues on this project, weird).

**Comment by jrochkind** [comment]
I did it as a "Bcc", because that seemed appropriate, I think?

**Comment by lsberry16** [comment]
I agree--thanks!
