### ISSUE TITLE
URL alias rake task adjustments

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1093]
Put strings in double-quotes.
Drupal aliases should be lowercased.

**Comment by jrochkind** [comment]
Once this is done, the rails route end needs to also normalize to lowercase when looking up redirects. 

Let's leave this ticket open until we've done both?

**Comment by eddierubeiz** [comment]
OK, great. I could prob. do that too- just lowercase the incoming Drupal URL right before performing the lookup in the mapping.
