### ISSUE TITLE
Import "Sponsor" creator metadata from the microsite automatically?

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1102]
I'm seeing that in at least some cases, . e.g. [Charron](https://oh.sciencehistory.org/oral-histories/charron-maureen-j) --> [Charron](https://digital.sciencehistory.org/works/c0lar63), sponsor metadata has been entered manually.

Meanwhile, [the initial description of the metadata import ](https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1665728517/Migration+from+the+OH+microsite+to+the+digital+collection) listed that field as part of the import.

Currently, the import doesn't touch this field. This was an oversight on my part, and I'd be happy to fix that now. It's an easy change now that all the rest of the infrastructure is in place.

However, this is only worth doing if we *want* the manually entered data to be overwritten by the corresponding data from the microsite. @lsberry16 and @HKativa and @apinkney0696, and Nic, I defer to you on this.

**Comment by HKativa** [comment]
@eddierubeiz unless there's a reason for the Sponsor metadata to be in two places, I vote for not overwriting the manually entered data that's already there.

**Comment by eddierubeiz** [comment]
Noted. Yeah, I'm pretty sure the correct thing in this case is to do nothing, but I wanted to make a note of it.

**Comment by eddierubeiz** [comment]
This was done manually. No need to import this data automatically.
