### ISSUE TITLE
Stray interviewee honors records

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1109]
Due to a presumed bug in Drupal, a number of interviews have "interviewee honors" records with only a date.

Examples:
- https://oh.sciencehistory.org/node/7656/edit has a 2018 "honor" -- no end date, no description, just "2018".
- https://oh.sciencehistory.org/node/7656/edit also has a 2018 "honor". Ditto.

These are duly imported and displayed in the digital collection, of course; there's nothing wrong with the import code per se here.

Proposed solution: once the import is complete, we write a simple piece of code (a rake task) that iterates over the oral histories and remove these bogus "honors" records automatically.

**Comment by jrochkind** [comment]
I'm guessing Drupal just doesn't display them -- we could fix our display code to just not display them, but I agree with you it's better to get our data right, if these don't mean anything, they shouldn't be in our data. 

The obvious solution to me would be fixing the import code to not import them, if we don't want them imported. Is there a reason to prefer the solution you propose instead, with a second process to remove them after they were imported?

**Comment by eddierubeiz** [comment]
I'm undecided. Point taken: I could definitely just skip incoming "honors" records with only dates, right?
