### ISSUE TITLE
Double-interview is not importing both bios

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1111]
See:
https://staging-digital.sciencehistory.org/works/eb9ongs
Only Jean Aitchison's bio is shown.

**Comment by eddierubeiz** [comment]
This is caused by a missing leading zero in Thomas M. Aitchison OH interview.
Jean's interview number is correctly listed as `0200` but Thomas' is listed as `200`, so his info isn't making it over.
https://oh.sciencehistory.org/node/5439/

**Comment by eddierubeiz** [comment]
@apinkney0696  -- could you fix this in the microsite when you have a second? Thanks much!

**Comment by apinkney0696** [comment]
Hi @eddierubeiz -- I don't think I have access to edit the microsite, only the DC, but I'm pretty sure Nicole does!

**Comment by eddierubeiz** [comment]
Ah, I see. I'll send her a note on Slack! Thanks!

**Comment by eddierubeiz** [comment]
Nicole fixed -- thanks.
