### ISSUE TITLE
New dropdown term in 'Genre' field

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1117]
Please add the term "Personal Correspondence" (FAST ID: 1919948 http://id.worldcat.org/fast/1919948) to the Genre field's dropdown menu. Thanks!

**Comment by jrochkind** [comment]
Thanks! We don't currently track FAST IDs in the software itself for this controlled vocab, but still good to have it doc'd here!

**Comment by jrochkind** [comment]
Hey @apinkney0696 , it looks to me like "Personal Correspondence" is already in the list. It looks like it was added... actually years ago at the start of this project. 

Double-checking to make sure it shows up for me... I'm seeing it! 

Can you confirm you see it there too? Thanks!

**Comment by apinkney0696** [comment]
Hi @jrochkind ! You're totally right, I see it on my end too. Thanks for catching that! Don't know how I missed it... sorry for any inconvenience!

**Comment by jrochkind** [comment]
No worries!
