### ISSUE TITLE
Archive OH microsite

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1129]
The database, files and PHP code for the OH microsite should be archived in a secure location.

We may not want to keep them forever; their value will diminish over time as Drupal 7 becomes obsolete and the digital collections continue to evolve independently.

See #393 for some notes about how we archived the old Sufia site. In short, the files were archived at `https://chf-hydra-backup.s3-us-west-2.amazonaws.com/sufia_legacy_data/`

**Comment by eddierubeiz** [comment]
The combined, compressed files total 1GB of space.

**Comment by eddierubeiz** [comment]
The compressed files total 1.1GB.
I'm uploading them to `https://chf-hydra-backup.s3-us-west-2.amazonaws.com/sufia_legacy_data/` as `Glacier Deep Archive` storage.

**Comment by jrochkind** [comment]
We have never done Glacier before, I don't know anything about how it works. I advise talking to Chuck (@CHF-IT-Staff ) about where to put it. I think maybe chuck wanted it just on local storage, not AWS at all. 

I don't care at all.

**Comment by eddierubeiz** [comment]
Just document this in the wiki before closing this

**Comment by eddierubeiz** [comment]
(Documented at https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1665728517/Migration+from+the+OH+microsite+to+the+digital+collection#Wrap-up ).
