### ISSUE TITLE
Customized Oral History collection splash page

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1133]
- [x] Bigger image
- [x] Projects with graphics
- [x] "Born on this date" 
- [x] remove search results from splash page, you have to actually do a search, no default list of results, cause all this other stuff will take up that space. 
- [x] Maybe other links like "ones with synchronized audio"?

**Comment by lsberry16** [comment]
Instead of the standard oral history image of transcripts/recorder, for the splash image I've assembled a folder containing images of 7 of our interviewees here: https://files.sciencehistory.org/app/index.do#storage/files/1/Shared/P/Institute%20for%20Research/Oral%20History/Digital%20Collections/Images/Interviewees%20for%20main%20page Annabel will combine them into a collage to serve as the splash image image for the OH Collection landing page, once she knows what specs to use.

**Comment by MDiMeo** [comment]
@apinkney0696 See above!

**Comment by jrochkind** [comment]
@apinkney0696 ok, thinking about actual design of this page.... I guess @lsberry16 suggested the Dig Col home page as a model, so let's start out consistent with the big splash image there. 

That one is a pretty large image, 1982 × 1451 pixels. 

It's possible we could get by with (or prefer, not sure) lower resolution at same aspect ratio (not sure why those aren't even numbers, you can make them even numbers too), if you don't have high-res enough source material.  But for comparison... facebook recommends 1,080 x 1,350 for uploaded share images... so maybe the higher res one is not excessive. We can always downsample a higher res one if you have the source material for it. 

Additionally, it would be nice for smaller screen sizes to have an image that can be a lot shorter. Depending on the composition of the image, we could just cut off and only display the top half from the image above.... or we could prepare a different image for that different aspect ratio maybe more like 500x725 (or double that, but roughly that aspect ratio).  It might be possible for me to use just the top portion of one image, instead of requiring another image, we can start with that and see how it looks! 

Still working out the exact design, but I think these are the specs! Make sense?

**Comment by jrochkind** [comment]
Actually wait, I'm rethinking that @apinkney0696 and @lsberry16  ! I think I got ahead of myself. Maybe don't start on this yet, I need to do some more design work first. I'll use placeholder images first.

**Comment by jrochkind** [comment]
@lsberry16 instead of default sorting by "most recently added to collection" (which is kind of broken too), we could default sort by date of interview. Oldest or newest. Would either of those be better?

**Comment by apinkney0696** [comment]
@jrochkind the splash image options are located here: P:\Othmer Library\Digital Collections - Internal Access\Oral History\Splash Image 
https://files.sciencehistory.org/app/index.do#storage/files/1/Shared/P/Othmer%20Library/Digital%20Collections%20-%20Internal%20Access/Oral%20History/Splash%20Image

**Comment by jrochkind** [comment]
@apinkney0696 nice! I think the second one might end up working, but, sorry to be doing this, I'm still feeling my way through this stuff too, but -- can you make the "photo border" in the second image something other than white? More off-white, beige, grey, whatever. Since it's over a white background without borders, when it gets cut off such that the white is on the edge, it ends up disconcerting. 

![Screen Shot 2021-05-20 at 2 11 21 PM](https://user-images.githubusercontent.com/149304/119028281-45e6d500-b975-11eb-862f-165af0a20e92.png)

**Comment by jrochkind** [comment]
@apinkney0696 actually hold off on that, there might be other changes needed too, I jumped the gun, let's just wait until I get it all working and take a look!

**Comment by apinkney0696** [comment]
@jrochkind no worries. These really didn't take much time and were intended to be more like drafts anyway. Things like changing the border color is a super easy adjustment and totally doable. Take your time and get back to me when you're ready with the changes you'd like to see!

**Comment by jrochkind** [comment]
@apinkney0696 

OK, no other changes! But I think it would look better with a non-white (off white, grey, beige, whatever) photo border, so the whole image can stay distinct from it's white background. 

Some people did notice you had re-used some photos as "background" under the pile for convenience, but didn't think most users would definitely notice that or if it would be a problem.  If that's not super easy to change (with other photos I guess), then don't worry about it, was the consensus. 

In general, we're really happy with the illustration, nice work.

No rush on this, but let me know (perhaps by posting it here) when you have a new version of illustration, thanks!

**Comment by apinkney0696** [comment]
@jrochkind I have made the outlines a very slight beige-y tone (I am hoping it is enough to distinguish it from the background, but not so much it's unnatural), I moved the pictures around ever so slightly, and I added a subtle 'glow' to the images to make their outlines a little more distinctive and 3-D. The new file is located in  P:\Othmer Library\Digital Collections - Internal Access\Oral History\Splash Image and is named OH_Splash_2_EDIT   

https://files.sciencehistory.org/app/index.do#storage/files/1/Shared/P/Othmer%20Library/Digital%20Collections%20-%20Internal%20Access/Oral%20History/Splash%20Image?p 

Let me know if you have any additional feedback!

**Comment by lsberry16** [comment]
@jrochkind Annabel also edited the images I found for the different projects and saved them here:

https://files.sciencehistory.org/app/index.do#storage/files/1/Shared/P/Othmer%20Library/Digital%20Collections%20-%20Internal%20Access/Oral%20History/Project%20images

Would you please replace Philly Energy Futures with Mass Spectroscopy and add these images in lieu of the placeholders?

**Comment by jrochkind** [comment]
Thanks! I am not sure we ever discussed sizes for the project images. 

I had mocked them up as square in my design. I am not sure the ones delivered are all the same aspect ratio, or are all square? I may not know which files I should be looking at in that directory, there are subdirectories each of which has more than one file, in different formats, taht don't always match?

Which ones should I be looking at as the final versions to use? Are they square, or different aspect ratio? Would we like to use square, or standardize on a different aspect ratio?

**Comment by lsberry16** [comment]
They're the TIF files with "edit" in their filename.

**Comment by jrochkind** [comment]
I found em! Nice!

So... I think it might look better when an image does not have a white background, so it makes a nice square matching the others. Thinking about EPA one with white background, but maybe it's just fine, 
![Screen Shot 2021-05-25 at 2 03 59 PM](https://user-images.githubusercontent.com/149304/119546696-33e4a800-bd62-11eb-8aa7-e2f44341280c.png)
what do you think?

**Comment by lsberry16** [comment]
It doesn't bother me as is, but maybe @apinkney0696 could add a square border around the outside? Some of the images I saw when I did a google image search for the Toxic Substances Control Act  had the EPA seal under the letters TSCA, so that could be another option: shrink the seal down, add the letters TSCA above it, and put a border around the whole thing.

**Comment by jrochkind** [comment]
Your call, if it's fine with you how it is, we can just leave it, up to y'all.
