### ISSUE TITLE
Fixity check report consistently reports items that have not been checked for 90 days.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1136]
The fixity check report https://digital.sciencehistory.org/admin/fixity_report consistently reports the following "problems":

- roughly 4000 items with _"Fully ingested, stale checks (have not been checked for 90 days, or ever)"_
- A _"Fully-ingested Asset with oldest most-recent fixity check"_ with a latest check date of 100 days ago, instead of 90.

We strongly suspect nothing is actually wrong. We need to change either the reporting recipes, or the fixity check routine, or both, so that this page reports the usual behavior of our fixity checks as normal, and only flags aberrant behavior.

See also https://github.com/sciencehistory/scihist_digicoll/issues/633, which this ticket will replace.

**Comment by jrochkind** [comment]
Some nightly logging might be good, especially now that we have accessible logs. 

Logging *every* asset fixity checked will be too much (for our papertrail plan).  But maybe some summary "descriptive statistics"

*  number we are going to check. Within that, how many have *no* previous fixity checks, vs oldest ones?
* total number found not checked in PERIOD days, which may be greater than the number we are going to check
* A *sample* record we're going to check that had  no previous fixity check, including it's created_at date. 
* A sample record we're going to check that did have a previous fixity check , including it's created_at and date of last fixity check.

**Comment by jrochkind** [comment]
We decided we will:

* do an initial fixity check right after ingest for newly ingested files (#1263), which we think will fix the problem with our algorithm checking 1/90th -- the new ones were pushing aside old ones due for a check. So we do new ones right away still, but not in the nightly cronjob, taking up those 1/90th slots, but instead just in the ingest process. 

* While that should take care of it, we also, just in case, adjust the nightly job to check if there any assets past their 90-day required fixity check, and if so, just check them too! Just an additional cleanup step for any problems, not expected to be triggered much. In #1267
