### ISSUE TITLE
Fix two out-of-date test files.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1144]
Two files in our test suite were not named correctly:
```
spec/models/asset/derivatives.rb
spec/models/work/work_all_descendent_members.rb
```
Because of this, they weren't being run regularly as part of our test suite, and have fallen out of date.
The files should be renamed, and the tests contained in them should be updated so they pass.

We may want to add a test that fails if e.g.
`find  spec/ -type f | grep -v 'spec\.rb$'  | grep -v '^spec/test_support\|^spec/factories\|^spec/fixtures\|preview.rb$\|helper.rb$'` returns any other incorrectly named files in the future.

**Comment by jrochkind** [comment]
@eddierubeiz Can you please make sure this ticket lists the specific files that it is saying need to be fixed? 

And let's bring it up today for prioritization.
