### ISSUE TITLE
Housekeeping: remove a couple references to obsolete versions of the Shrine library.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1146]
We have some obsolete code that only executes on (obsolete to us) Shrine v. 2. These can be removed now.

**Comment by jrochkind** [comment]
@eddierubeiz Can you provide more context in this ticket? I don't understand what this means, or where we'd have such references. Can you link to or describe an example?

**Comment by jrochkind** [comment]
oh wait, I see you already had a PR. OK, is your intention that I should move this issue to "In Progress" or "Review" or what, @eddierubeiz ?

**Comment by eddierubeiz** [comment]
I moved it to In Progress -- sorry for the confusion.
