### ISSUE TITLE
New Image for Bredig Collection

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1150]
We'd like to make the [Bredig Collection](https://digital.sciencehistory.org/collections/qfih5hl) public and add an image to the collection level icon (i.e. get rid of the box icon). @eddierubeiz or @jrochkind, could you please confirm that the new image should have 700 x 700 px dimensions and let me know if there are any other specifications it should have? Then I'll drop a link to the image we'd like to have put in. Thanks!

**Comment by eddierubeiz** [comment]
Hi there Annabel,
Awesome news. You can use these instructions for the Bredig collection thumbnail:
https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/1646428165/Creating+a+thumbnail+for+a+Featured+Topic+landing+page
Best,
Eddie


__________________________________

Eddie Rubeiz, MLIS, CA   (he, him, his)
Library Applications Developer
Othmer Library of Chemical History
t. +1.215.873.8297

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
Learn about the scientific discoveries that changed our world without leaving home at sciencehistory.org/learn<https://www.sciencehistory.org/learn>
From: Annabel Pinkney ***@***.***>
Reply-To: sciencehistory/scihist_digicoll ***@***.***>
Date: Tuesday, May 18, 2021 at 11:59 AM
To: sciencehistory/scihist_digicoll ***@***.***>
Cc: "Rubeiz, Edward" ***@***.***>, Mention ***@***.***>
Subject: [sciencehistory/scihist_digicoll] New Image for Bredig Collection (#1150)


We'd like to make the Bredig Collection<https://digital.sciencehistory.org/collections/qfih5hl> public and add an image to the collection level icon (i.e. get rid of the box icon). @eddierubeiz<https://github.com/eddierubeiz> or @jrochkind<https://github.com/jrochkind>, could you please confirm that the new image should have 700 x 700 px dimensions and let me know if there are any other specifications it should have? Then I'll drop a link to the image we'd like to have put in. Thanks!

**Comment by apinkney0696** [comment]
Great, thanks! I've added the image to the folder specified in the instructions @eddierubeiz. The file is called 'georg_max_bredig_cropped.'

**Comment by eddierubeiz** [comment]
Awesome. Thanks! :)

**Comment by jrochkind** [comment]
Actually @apinkney0696 , it turns out Collection thumbnails are a bit different than "Featured Topic Landing Pages". What you did works, and we can take care of it, but for future reference...

You all can actually upload and change Collection thumbnails yourself through the admin screens, just click the "edit" button on a collection page or next to a collection name in admin interface. At the bottom there is a space to add or change an image. The instructions there suggest:

"Image for collection, should be square and at least 532x532 pixels. No need to resize—full-size crop is great for possible future uses."

(700 is fine of course!)

**Comment by apinkney0696** [comment]
Oh great, thanks so much!! Sorry for not realizing that prior to! I'm learning slowly, but surely...

**Comment by jrochkind** [comment]
no need to apologize, we had forgotten too!

**Comment by eddierubeiz** [comment]
My bad! I'd totally forgotten this interface existed. I'll amend the wiki to reflect the above.

**Comment by jrochkind** [comment]
It looks like this has been taken care of at this point? Shall we close ticket?

**Comment by apinkney0696** [comment]
Yes, it's taken care of!
