### ISSUE TITLE
Deal with empty interviewee bios

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1154]
On importing restricted interviews such as [Gregory A. Clark](https://digital.sciencehistory.org/works/49j2s7t), it appears the import code wound up creating an empty shell of an interviewee biography. This shows up as an irritating "Interviewee biographical information" title on the page, with no actual bio underneath it.

These objects should be deleted.

**Comment by jrochkind** [comment]
It is likely this applies to all "restricted" interviews. We don't have them clearly identified with metadata, but one way to find them is to search for the common string "At the request of the interviewee, the abstract of the interview and interviewee’s biographical data have not been included.", which sould probably appear in description field for all of them.
