### ISSUE TITLE
heroku: sync prod to staging routine

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1170]
And make sure to document https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1908834305/Heroku

**Comment by jrochkind** [comment]
May be related to #876, in that we will be using postgres backup files?

**Comment by jrochkind** [comment]
Note the postgres sync may be basically built into heroku:

https://devcenter.heroku.com/articles/heroku-postgres-backups#direct-database-to-database-copies

**Comment by eddierubeiz** [comment]
No need to involve the backup process unless we want to. This works fine:
```
heroku maintenance:on --app scihist-digicoll-staging
heroku pg:copy scihist-digicoll-production::DATABASE_URL DATABASE_URL -a scihist-digicoll-staging  --confirm scihist-digicoll-staging
heroku run rake scihist:solr:reindex        --app scihist-digicoll-staging
heroku run rake scihist:solr:delete_orphans --app scihist-digicoll-staging
heroku maintenance:off --app scihist-digicoll-staging
```
If we *want* to involve the SQL backups, we can use a variation on this:
```
heroku maintenance:on --app scihist-digicoll-staging
yes | aws s3 cp s3://$BACKUP_BUCKET/$BACKUP_PATH .
gunzip $BACKUP.gz
heroku pg:psql --app scihist-digicoll-staging < $BACKUP
heroku run rake scihist:solr:reindex        --app scihist-digicoll-staging
heroku run rake scihist:solr:delete_orphans --app scihist-digicoll-staging
rm -rf $BACKUP
heroku maintenance:off --app scihist-digicoll-staging
```

**Comment by jrochkind** [comment]
@eddierubeiz What do you think is best? We had talked about involving the S3 backups as a way of testing they work, but I'm not sure, what do you think?

Where do we currently have this process documented, can you link to it?  Does the current process involve manually running an `aws s3 cp`?    

I was imagining a single command someone could run to "do the sync", but I guess if that involves having `aws` CLI installed anyway, and would be hard to do, then maybe we just update the current docs for a manual process? This would be another thing to have @CHF-IT-Staff (Chuck) demo from docs.

**Comment by eddierubeiz** [comment]
- The old process is documented at https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/950730760/Syncing+scihist-digicoll+production+to+staging .

- Credentials needed: for 1 you need Heroku credentials, for 2, you need Heroku _and_ s3 credentials.

- Involving S3 backups is of course a good thing in theory, but on the other hand, the `pg:copy` creates an effectively instantaneous copy. Let's discuss.

- As far as the single command, I was testing the sequence using a local shell script, which I could of course check into the codebase, but again, I wanted to get your thoughts first. Would Capistrano work for something like this, maybe?

- Whatever we end up choosing can also be useful for #1201 : `create custom html for maintenance page + upload html to s3 + point site at that html + put site into maintenance mode.`

**Comment by jrochkind** [comment]
> Credentials needed: for 1 you need Heroku credentials, for 2, you need Heroku and s3 credentials.

I don't understand what you mean by "1" and "2"? 

I had anticipated we were going to stop using Capistrano once we move to Heroku.  Capistrano is for ssh'ing to remote machines; but I don't think it can be used for ssh'ing to heroku machines (but heroku has it's own tools for this). But maybe I'm missing something, I'm not sure what you were thinking about using capistrano for. You could try to write some code and see where it gets you?

It's not obvious to me that we need to share any logic with #1201. What's even the commonality? Just uploading something to S3?  The sync process doesn't even upload any individual things from local site or repo to S3, does it?  I don't see any need to confuse things by expanding the scope here, let's just concentrate on the sync.

**Comment by eddierubeiz** [comment]
Oh, sorry, 1 and 2 were the first and second "recipes" I listed -- the ones with`pg:copy` and `pg:psql`, respectively.

**Comment by eddierubeiz** [comment]
I'm just thinking of common sequences of housekeeping commands that are easy to get wrong, and that we might until recently have used Ansible for. Should I use a Rake task? If so, I should probably use a Rake task for 1201 as well.
