### ISSUE TITLE
Create heroku staging

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1188]

**Comment by jrochkind** [comment]
@eddierubeiz Please assign this ticket to yourself and move it to 'in progress' zenhub. 

Please set dyno sizes/counts as suggested in the Heroku proposal document for what we planned to use on staging, we want them closer to production than they are now. https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1488093185/Heroku+Proposal

**Comment by eddierubeiz** [comment]
Ah great. OK, I set up db and web dynos per the wiki docs.

**Comment by jrochkind** [comment]
Maybe postgres too? Or look up what makes the 'hobby' postgres plan differ from the "standard-0" one and doc here if you think staging doesn't need to match prod here?

**Comment by jrochkind** [comment]
Realized HONEYBADGER_API_KEY wasn't set on heroku staging.  I will set that one. There may be others missing too? Not sure how that got missed, as it is in local_env.yml as `honeybadger_api_key`? I will set that one myself, as I need it for my work. 

There may be others we are missing, either from local_env.yml, or new things we added to heroku config vars in production that we need in staging too?

@eddierubeiz , to close this ticket, can you go down the list of config vars actually set on heroku production, and compare to heroku staging? Thanks! Moving this back to "in progress" for now.

**Comment by eddierubeiz** [comment]
$ heroku config --app scihist-digicoll-production > prod.txt
$ heroku config --app scihist-digicoll-staging > stag.txt
$ diff stag.txt prod.txt | grep -o '.*\: '

< APP_URL_BASE:
> APP_URL_BASE:
< DATABASE_URL:
> DATABASE_URL:
< HEROKU_POSTGRESQL_CHARCOAL_URL:
> HEROKU_POSTGRESQL_COBALT_URL:
> HIREFIRE_TOKEN:
< PAPERTRAIL_API_TOKEN:
> PAPERTRAIL_API_TOKEN:
< RAILS_ASSET_HOST:
< REDIS_URL:
> REDIS_URL:
> S3_BACKUP_ACCESS_KEY_ID:
> S3_BACKUP_BUCKET_REGION:
> S3_BACKUP_FILE_PATH:
> S3_BACKUP_SECRET_ACCESS_KEY:
< SERVICE_LEVEL:
> SERVICE_LEVEL:
> WEB_CONCURRENCY:

**Comment by eddierubeiz** [comment]
**Should be present and different:**
`APP_URL_BASE`; `DATABASE_URL`; `HEROKU_POSTGRESQL_*_URL`; `PAPERTRAIL_API_TOKEN`; `REDIS_URL`; `SERVICE_LEVEL`.

**Should only be present in production:**
`HIREFIRE_TOKEN`; `S3_BACKUP_*`; `WEB_CONCURRENCY`

**Still working on this feature in staging:**
`RAILS_ASSET_HOST`
