### ISSUE TITLE
"translator" field for bredig 

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1193]
@apinkney0696 suggested that we need a "translator" field for our Bredig stuff. 

This is a little bit different than most of our metadata, because it does not apply to the "item in hand", it applies to our processing/digital copy only. 

So it's probably not one of our "Creator" fields. We might want to call the field something like "Translator (digital)" (probably  not exactly that). 

It is somewhat comparable to our "File creator" field, for which we don't allow free entry, but have a choice of "registered" file creators. 

We haven't decided exactly how to do this yet, so leaving this as record of conversation, and a placeholder to remind us to. 

@MDiMeo , I won't work on this until someone tells me to! :)

**Comment by apinkney0696** [comment]
Yes! I definitely think it is important to make space for crediting our translators/transcribers in some way.

If not creating another field, we might consider adding another option to the 'Additional Credit' drop-down menu. Currently, we only have 'Photographed by.' We could potentially add 'Translated by' and 'Transcribed by' to that list. However, this field currently removes the default _Courtesy of the Science History_ Institute line, which we would want to maintain. 

If we decide on creating another field, I'll think of some options for what we should name it. 

Another question for consideration: Our File creator field is not publically viewable - would we want the translator/transcriber to be internally facing administrative metadata or do we want it to be public?

**Comment by eddierubeiz** [comment]
I like the idea of just using `Additional Credit`, @apinkney0696 .
Maybe `Transcription by` and `English translation by` ?

(I can't imagine e.g. Jay Muhlin objecting to being credited publicly for photographing the "work in hand". Are there any other cases in which we might somehow compromise anyone's privacy by making the `File Creator` field public?)

**Comment by apinkney0696** [comment]
Hm. I wasn't thinking of it from the perspective of privacy, though that's a good point. My thought is the File Creator field should remain private simply because it might be unfamiliar (and even confusing) to our users and also take up room on the public record which is primarily descriptive. It's important for us to have for admin purposes, but not necessarily adding anything to our user's experience. 

I was thinking about the long term, if we ever have an external contribution of a transcription or translation from someone who is not staff, it might be nice to publically recognize. We have, so far, only publically credited Digitization funding organizations and Donors on the public side of the digital collections (unless I have forgotten something else).

**Comment by jrochkind** [comment]
>  However, this field currently removes the default Courtesy of the Science History Institute line,

That could be a bug, or at any rate can be changed.

**Comment by eddierubeiz** [comment]
Sorry! I was in fact confusing "additional credit" and "file creator". Please disregard my comment!

**Comment by MDiMeo** [comment]
Create a publicly viewable field for "Translator". Restrict this to selecting a name from a pre-populated field. At the moment, we should have only one possible entry: Jocelyn R. McDaniel.

**Comment by jrochkind** [comment]
@MDiMeo you definitely don't want to use the "Additional Credit" field? It already exists with a choice of what kind of "additional credit", although the only choice is "photographer" at present, which is kind of weird, and what makes me think it was expected to expand to other additional credits, such as this?

If the "additional credit" field makes the "courtesy of science history institute" not show up -- I think that's a bug! As you can see, the "hint" says it is meant to "append". 

<img width="881" alt="Screen Shot 2021-06-11 at 9 35 19 AM" src="https://user-images.githubusercontent.com/149304/121694772-6992cc00-ca98-11eb-8323-1127a32f58ea.png">

Also, we generally won't do any of this work until it's been prioritized at a weekly meeting... but maybe we can work out a different way to do that since we don't have a weekly meeting until end of week next week, maybe we should plan to keep trying to work one day a week on non-heroku things, and you can just drag them into the 'ready' column to see what to work on?   We also still need confirmation that the new new transcription/translation fields are sufficient to close the ticket and merge them!   A bit challenging to keep track of all this work now, interspersed with heroku, but we can figure it out!

**Comment by jrochkind** [comment]
@MDiMeo says, yes, let's use "Additional Credit". 

Let's double check and make sure it "Appends Credit Line" (as the hint says), and does not replace it. "Appends" is desired, it's a bug if it "replaces".

**Comment by apinkney0696** [comment]
One addendum: may I request we double-check this can be batch edited, please! Then we can add Jocelyn's name to many records at once.
