### ISSUE TITLE
get heroku accepting our custom domains

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1220]
Both digital.sciencehistory.org and now oh.sciencehistory.org

See: https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1350041601/DNS+and+SSL+management+for+Heroku+sites

**Comment by eddierubeiz** [comment]
What I did:
```
heroku certs:add wildcard.cert  wildcard.key  --app scihist_digicoll_staging
heroku certs:add wildcard.cert  wildcard.key  --app scihist-digicoll-production
heroku domains:add digital.sciencehistory.org --app scihist-digicoll-production
heroku domains:add staging-digital.sciencehistory.org --app scihist-digicoll-staging
```

**Comment by eddierubeiz** [comment]
Check the results:
```
heroku certs -a scihist-digicoll-staging
heroku certs -a scihist-digicoll-production
heroku domains --app scihist-digicoll-staging
heroku domains --app scihist-digicoll-production
```

**Comment by jrochkind** [comment]
@eddierubeiz Can you make sure oh.sciencehistory.org works on production too, and test it with a custom /etc/hosts?  Thanks!

**Comment by eddierubeiz** [comment]
At launch time:
point the CNAME for digital.sciencehistory.org to `peaceful-basilisk-lhtznpb53fvrt1mv8yt398yy.herokudns.com`
point the CNAME for staging-digital.sciencehistory.org to `convex-pelican-rsz77g7eof8bvxziiakaer03.herokudns.com`

**Comment by eddierubeiz** [comment]
As of Wed. afternoon you can test all the above settings by adding the following URLS to your `/etc/hosts` file:
```
3.226.182.14        oh.sciencehistory.org
3.226.182.14        digital.sciencehistory.org
34.203.109.182      staging-digital.sciencehistory.org
```

**Comment by eddierubeiz** [comment]
Note that I also changed the `APP_URL_BASE` setting for `scihist-digicoll-production` from `https://scihist-digicoll-production.herokuapp.com/` to `https://digital.sciencehistory.org` (yes, without the trailing slash.)

**Comment by eddierubeiz** [comment]
Likewise changed `APP_URL_BASE` on staging to `https://staging-digital.sciencehistory.org` (also without the trailing slash.)

**Comment by eddierubeiz** [comment]
I am now confident that it will really work. Not sure about maximally confident.
