### ISSUE TITLE
Details for "Extent" on OH interviewee page

### ISSUE THREAD

**Issue by dcaruso-scihist** [sciencehistory/scihist_digicoll#1237]
I was pulling information from individual interviewee pages in the Digital Collections and noticed that the information under Extent needed some clarity. We include total length of interview information in HRS:MIN:SEC format but do not specify that as the format. Visitors simply see a set of numbers with colons between them. Is it possible to add a clarifier that the numbers are actually HRS:MIN:SEC? Also, in the Extent section of the record for Alison Adams (https://digital.sciencehistory.org/works/3417dff), the number 108 is not followed by the word "pages," yet all of the other records I checked today included it. Was that a problem with the data in the old microsite?

**Comment by apinkney0696** [comment]
Hi @dcaruso-scihist,

Thanks for bringing this up. Outside of the biographical data, all of the metadata transferred from the microsite was crosswalked manually by myself, Nicole, and Hillary, so what you've found on Alison Adams record looks to be a typo. I've already fixed it, but if you see anything else small like this, it's likely human error from the transfer and if you just let me or Nicole know, either of us can fix it.

The time length in the extent field was added according to our metadata guidelines, though I agree with you that units would be helpful clarifiers.  When Gabriela gets settled as the new Senior Tech Services Librarian, I wanted to have a larger conversation about amending some aspects of our content standards and documentation, and this is something I can bring up for improving.

Thanks!

**Comment by dcaruso-scihist** [comment]
Thanks so much. Sounds great.


__________________________________

David J. Caruso, Ph.D.
Director
Center for Oral History
t. +1.215.873.8236

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
Learn about the scientific discoveries that changed our world at sciencehistory.org/learn<https://www.sciencehistory.org/learn>

On Jul 12, 2021, at 11:45 AM, Annabel Pinkney ***@***.******@***.***>> wrote:



Hi @dcaruso-scihist<https://github.com/dcaruso-scihist>,

Thanks for bringing this up. Outside of the biographical data, all of the metadata transferred from the microsite was crosswalked manually by myself, Nicole, and Hillary, so what you've found on Alison Adams record looks to be a typo. I've already fixed it, but if you see anything else small like this, it's likely human error from the transfer and if you just let me or Nicole know, either of us can fix it.

The time length in the extent field was added according to our metadata guidelines, though I agree with you that units would be helpful clarifiers. When Gabriela gets settled as the new Senior Tech Services Librarian, I wanted to have a larger conversation about amending some aspects of our content standards and documentation, and this is something I can bring up for improving.

Thanks!
