### ISSUE TITLE
digital.chemheritage.org redirect

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1244]
[Slightly edited, from @jrochkind]
http://digital.chemheritage.org/ no longer redirects properly to current digital.sciencehistory.org. 

Do we care? Was it time to retire it anyway?
www.chemheritage.org IS still redirecting, so maybe we should fix digital.chemheritage.org too?

**Comment by eddierubeiz** [comment]
If we decide to do this, this will need new stanza in `routes.rb` and we'll need to set up [a new domain](https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1350041601/DNS+and+SSL+management+for+Heroku+sites) for the site.

**Comment by eddierubeiz** [comment]
DNS target will be `limitless-snowdrop-tjrmx895f890icdh2spzapgm.herokudns.com`.

**Comment by eddierubeiz** [comment]
Clare was able to get this working with an a2 cert.

**Comment by jrochkind** [comment]
Reopening, because the cert on digital.chemheritage.org is expired, and unclear who/how to fix that, needs some attention if we want to keep it working (or, we could, again, decide to retire it).
