### ISSUE TITLE
Derivative storage auditor ran out of memory.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1249]
Last night the scheduler job running `AssetDerivativeStorageTypeAuditor.new.perform!` ran out of memory:

```
heroku/scheduler.6957 Starting process with command `bin/rails runner 'AssetDerivativeStorageTypeAuditor.new.perform!'`
heroku/scheduler.6957 State changed from starting to up
heroku/scheduler.6957 Process running mem=520M(101.0%)
heroku/scheduler.6957 Error R14 (Memory quota exceeded)
heroku/scheduler.6957 Process exited with status 0
heroku/scheduler.6957 State changed from up to complete
```

**Comment by eddierubeiz** [comment]
We can allocate more resources to the task if we need to. Let's see if this happens again.

**Comment by eddierubeiz** [comment]
This happened again last night. I'm assigning a `Standard-2X` dyno to this job, which should cost us about a nickel extra every month.

**Comment by jrochkind** [comment]
Part of me wants to figure out why it was using so much memory and if there's a way to fix it to not do so. But how to do memory profiling/optimization well isn't something totally in my toolbelt yet. 

If a standard-2x works, that's probably a fine solution!

It was upped to standard-2x 7 days ago -- has it avoided running out of memory in that time? If so, sounds good!
