### ISSUE TITLE
use honeybadger check-in feature for important scheduled jobs

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1258]
https://docs.honeybadger.io/guides/check-ins/

Can alert us if an important scheduled job failed to run. We have a limited number of "check-ins" available. I think it makes sense to use for:

* backup process
* fixity check

**Comment by eddierubeiz** [comment]
OK - these are set up. See the checkins on [Honeybadger](https://app.honeybadger.io/projects/58989/check_ins/) and on [Heroku](https://dashboard.heroku.com/apps/scihist-digicoll-production/scheduler).

We could wrap the calls to `curl` in a rake task, we could do that, I suppose, but my sense is that's probably not worth doing. This is pretty lighweight.

**Comment by jrochkind** [comment]
I agree, looks good!

**Comment by jrochkind** [comment]
We might need more than a 3-hour "Grace period" on honeybadger, depending on how it all works out. I guess we'll find out! 

(if a given fixity check run takes 3 hours longer than the one the night before... it'll alert us right now. We might actually want like a 12-hour grace period or something, not sure)

**Comment by jrochkind** [comment]
> bundle exec rake scihist:copy_database_to_s3 && curl https://api.honeybadger.io/v1/check_in/xoIxVG &> /dev/null

Is this sending the results of the ENTIRE `bundle exec` command to `&> /dev/null`, and if so, is that okay?  I think maybe it's not okay, we want this output to show up in our logs normally. 

Is there a way to phrase the bash to make make sure it's just the last part, the curl, that's going to /dev/null? Or is this already doing that?  Can we confirm?

Also, the point of this is that if the rake task fails, the curl should *not* be executed. I *think* that's what the bash `&&` will do, but can you confirm and be sure, demonstrate it somehow?

**Comment by jrochkind** [comment]
Also, can we make sure we know where alerts are going for missed check-ins? I guess we want them to slack and email to digital-tech@sciencehistory?

**Comment by eddierubeiz** [comment]
Nightly fixity checks take 33 minutes on average, but recently have fluctuated between 4 minutes and 86 minutes. We can increase the grace period if needed, but I felt 3 hours was a good place to start.

**Comment by eddierubeiz** [comment]
"&&" is used to chain commands together, such that the next command is run if and only if the preceding command exited without errors. This is a common idiom. The &> /dev/null definitely only applies to the curl command.

**Comment by eddierubeiz** [comment]
That said, I created a test checkin and `curl`ed it. The response is zero-length anyway, so I suppose there's really no need to send the results to /dev/null. I'll get rid of that part.

**Comment by eddierubeiz** [comment]
Let's discuss at an upcoming meeting who (in addition to developers and the Slack error channel) should be notified if the backups or the fixity checks fail to check in with Honeybadger.

Options:

- Nobody else
- digital-tech@
- digital@
- Chuck
- Some combination of the above

**Comment by eddierubeiz** [comment]
Both jobs checked in last night, btw
https://app.honeybadger.io/projects/58989/check_ins

**Comment by eddierubeiz** [comment]
I'm changing the `curl` command to `curl -s` so it doesn't show download progress in the logs.

**Comment by jrochkind** [comment]
Before closing, let's add alerting to digital@sciencehistory.org

**Comment by eddierubeiz** [comment]
After a false alarm this morning, I doubled the "grace period" for the fixity checks from 3 to 6 hours.

**Comment by eddierubeiz** [comment]
Added alerting to `digital@sciencehistory.org.`. Closing this.
