### ISSUE TITLE
Tweak to work_all_descendent_members_spec.rb

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1261]
This test failed on CI just now, but un-failed spontaneously when I reran the test.

We may want to sort the two arrays of descendants by `position` (or even by `id`) before comparing them, so they return from the DB in a consistent order.

`rspec ./spec/models/work/work_all_descendent_members_spec.rb:11 # Work#all_descendent_members finds all`

```
  1) Work#all_descendent_members finds all
     Failure/Error: expect(work.all_descendent_members.to_a.collect(&:id)).to match([intermediate_work.id, asset.id])
       expected ["2cebf7df-8893-4a3d-a0c0-77b17615fdf4", "5a16b239-1a48-4577-98a7-df5811921729"] to match ["5a16b239-1a48-4577-98a7-df5811921729", "2cebf7df-8893-4a3d-a0c0-77b17615fdf4"]
     # ./spec/models/work/work_all_descendent_members_spec.rb:12:in `block (2 levels) in <main>'
```

**Comment by jrochkind** [comment]
There is a built-in rspec matcher to compare two lists order-independent. It sounds like this test should just be switched to use that? Whcih could be like 5 minutes of work.

**Comment by eddierubeiz** [comment]
Did not know that. Yes, that would fix it.

**Comment by eddierubeiz** [comment]
It looks like @jrochkind already fixed this https://github.com/sciencehistory/scihist_digicoll/pull/1322/ . Moving this to "review".
