### ISSUE TITLE
Genre term updates

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1275]
1.  Store authority information and URIs for each term. Is it possible to integrate this information into your code or store it on GitHub somewhere? [GenreTerm_Authorities.xlsx](https://github.com/sciencehistory/scihist_digicoll/files/7009508/GenreTerm_Authorities.xlsx)

2. Edit the following terms to match the authority entry:

- Clothing & Dress -> Clothing and dress
- Documents -> Records (Documents)
- Illustrations -> Illustrated works
- Medical equipment & supplies -> Medical instruments and apparatus
- Money (Objects) -> Money
- Negatives -> Negatives (Photographs)
- Textiles -> Textile fabrics

3. Add Postcard as a genre term and apply to all records with 'postcard' in the work's title.

**Comment by jrochkind** [comment]
Do you want each record to have URI and other authority metadata stored with it? And/or such things to be available with an export?

Or we just want a reference list for our own use?  If the latter, we could just make a wiki page maybe?

**Comment by apinkney0696** [comment]
Eventually, I would like this information to be stored with the record as an attribute to the element, but I'm not sure if our metadata application profile allows for that presently. 

There is already an old wiki page I can update with this information. I had found [this file](https://github.com/sciencehistory/chf-sufia/blob/master/config/authorities/resource_types.yml) in the chf-sufia files, so I wasn't sure if something similar in GitHub would be appropriate for this info.

**Comment by jrochkind** [comment]
I am not familiar with our "Metadata Application Profile" and am not totally sure if I understand what you mean by that, but on the software end I can say it would require some additional custom development to store controlled vocab terms like that, but should be do-able. Just a question of our priorities!

**Comment by apinkney0696** [comment]
Okay - it's not a high priority for me at the moment. I'm still working with Gabriela to work out some metadata structure issues so I'll get back to you about what we might need on the software side.

I also have an addition to the original request. Could we please delete the genre term "Minutes (Records)." Thanks!

**Comment by jrochkind** [comment]
Thinking through changing the genre terms... this will break any existing bookmarks to genre-based searches. That's probably fine. 

Is there any other functionality it may break? Aha.  Our "featured topic" definitions can be based on genres, if any of them are based on any genres to be changed, they'll have to be changed. 

@eddierubeiz can you think of any other features that might rely on hard-coded genre terms? I can't at present. 

Changing the genre terms is relatively straightforward, but there is some tricky stuff we'll have to take care of to do it with no downtime, haven't totally thought through that, it's a bit of a challenge.

**Comment by eddierubeiz** [comment]
I believe we can change the genre terms with impunity, yes. And it doesn't look like any of our featured topics is using any of the above-mentioned genres.

**Comment by apinkney0696** [comment]
> Have we been in the habit of putting this on any work that has illustrations in it? 
So yes. Typically what happens is that this gets applied to the illustrated book or parent work. Then, as child works are created, the parent metadata with the genre terms gets carried over into the individual plates in the book. 

I am glad you caught this because I touched base with Gabriela about this and I misrepresented here what we actually want to happen! Could you please instead add "Illustrated works" as another genre term so we can differentiate between the parent and children items? I think this might require I go in and manually change a bunch of books that are labeled with "Illustrations" to "Illustrated works," but if you have any thoughts on how to automate that process, that would be awesome.

Thanks!

**Comment by apinkney0696** [comment]
In response to Jonathan's note about request 1 here, I agree!

> Store authority information and URIs for each term. Is it possible to integrate this information into your code or store it on GitHub somewhere? GenreTerm_Authorities.xlsx

I will work on storing this information locally as I condense and update our metadata documentation. We can have another conversation down the line if we want to store this info in the metadata form in the app as well, but definitely a future discussion.

**Comment by eddierubeiz** [comment]
> Could you please instead add "Illustrated works" as another genre term so we can differentiate between the parent and children items?
Of course.

> I think this might require I go in and manually change a bunch of books that are labeled with "Illustrations" to "Illustrated works," but if you have any thoughts on how to automate that process, that would be awesome.
We can probably figure out something clever, yeah. We can chat today about the best way to do it.

**Comment by jrochkind** [comment]
> I think this might require I go in and manually change a bunch of books that are labeled with "Illustrations" to "Illustrated works," but if you have any thoughts on how to automate that process, that would be awesome.

Is the spec perhaps:

If something is NOT a child work (ie, it has no parent itself), and it has the genre term "Illustrations", then replace it with "Illustrated Works"?

**Comment by apinkney0696** [comment]
Tentatively, yes. But before you do that, let me just make sure there aren't any exceptions. I'm thinking I might amend this to:

If something is NOT a child work (ie, it has no parent itself), it has the genre term "Illustrations," AND contains the genre term "Publications," then replace "Illustrations" with "Illustrated Works."

I think there are a few figures that are technically parent works because they were created pre-child-work days that I want to catch.

**Comment by eddierubeiz** [comment]
(Whatever we end up doing, @apinkney0696  can review a list of items changed in Staging before we make any changes in production.)

**Comment by eddierubeiz** [comment]
@jrochkind and @apinkney0696 : I have broken the Illustrations and Illustrated Works conversation into [its own issue](https://github.com/sciencehistory/scihist_digicoll/issues/1294) that I will not be working on this week.

**Comment by eddierubeiz** [comment]
To be clear: as part of the work on this CURRENT issue (1275),  which I would like to wrap up soon, I
- WILL create a new `Illustrated works` genre.
- WILL NOT tag any works with the new `Illustrated works` genre.
- WILL NOT modify any works currently tagged with `Illustrations` genre.

**Comment by eddierubeiz** [comment]
Attaching a [final list of changes](https://github.com/sciencehistory/scihist_digicoll/files/7078326/monday_results.txt) before I run this in production.

**Comment by apinkney0696** [comment]
This looks great to me. Greenlight! Thanks!

**Comment by eddierubeiz** [comment]
[Uploading a record of the results in production.](https://app.zenhub.com/files/153306763/66d84ab0-7ba1-4292-bc0c-9de903b0faaf/download)
