### ISSUE TITLE
sign up for free for open source Scout APM account

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1293]
Switch our production app over to use that instead of heroku-plugin (which we can't get free for open source); remove heroku plugin. 

> Scout APM is free for open source! Contact us for a free account support@scoutapm.com.

https://scoutapm.com/info/pricing

Email from Scout support said:

> Thank you for reaching out! We do offer free plans for open source projects up to our large tier, however we are not able to provide this through Heroku because they have a separate billing system than us. 

> To get set up with an open source project with us you first need to switch to a direct Scout account. We are able to monitor on any environment for your monitoring needs, we would just need a github link to confirm that it was indeed an open source project. 

> To get set up with a direct Scout account here are the steps you would need to follow:
> * Visit Scoutapm.com and login to your new/personal account and input your billing information.
> * Please change your Scout key in Config Var in Heroku to SCOUT_KEY = "" (your new key will become available once your Scout account is created)
> * If you need to maintain the visibility into Heroku for data purposes I would suggest downgrading your account to the free plan.

**Comment by eddierubeiz** [comment]
Got word from Scout administrators that they've applied our open source "coupon" and we should be paying $0 for our `Scout APM Pro` plan from now on.
Note that the [billing settings page](https://scoutapm.com/billing) does not reflect any evidence of this at the moment.

**Comment by jrochkind** [comment]
Sweet! So last step is switching our production instance to use that scout account, de-provision the heroku add-on scout account?

**Comment by eddierubeiz** [comment]
Correct, and I'm going to go ahead and do that this morning.

**Comment by eddierubeiz** [comment]
I de-provisioned the old Heroku add-on from both staging and production.
The `SCOUT_KEY`, 'SCOUT_LOG_LEVEL`, `SCOUT_MONITOR` and `SCOUT_NAME` config vars on [our production instance](https://dashboard.heroku.com/apps/scihist-digicoll-production/settings) are now set to the proper values.
Production should now be reporting to the new account.

**Comment by jrochkind** [comment]
Sweet! How do I log into the new account to see scout? Just go to scoutapm.com and log into my personal account I guess?

Should we document this somewhere? So people (say hypothetical new staff) would know that we have Scout and how to get there?

 Maybe either on https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1915748368/Heroku+Operational+Components+Overview, or mention scout on there and link to another page? 
 
 Also, confirm here just for the record that @CHF-IT-Staff  has a login to our Scout account, as per policy?

**Comment by eddierubeiz** [comment]
Yes, Chuck has an account (under his personal email address). His user is also listed as `owner`.

**Comment by eddierubeiz** [comment]
Added a one-sentence description of Scout with a link on the [overview](https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1915748368/Heroku+Operational+Components+Overview) page.
