### ISSUE TITLE
Adjustments to "Illustrations" genre

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1294]
As part of our discussion at https://github.com/sciencehistory/scihist_digicoll/issues/1275, we would like to make some programmatic modifications to the `Illustrations` genre and the (newly added) `Illustrated Works` genre.

I am breaking this work into a separate issue, so that I can wrap up 1275 and come back to this in September.

The specification will be a variation on the following:
```
IF something is NOT a child work (i.e., it has no parent itself),
AND it has the genre term "Illustrations"
AND it has the genre term "Publications"
THEN replace genre "Illustrations" with genre "Illustrated Works."
```

This will need to be run in staging first, with a report run of changed items, checked by @apinkney0696 .
Only then will we run it in production.

**Comment by apinkney0696** [comment]
Hi @eddierubeiz ,
I've gone through a lot of the collections, and I did some manual updates to some records from "Illustrations" to "Illustrated Works," so I don't think there's a need to automate at this point. Adding the subject term, "Illustrated Works" was the biggest step, which is already done, so I think we can go ahead and close this!

**Comment by eddierubeiz** [comment]
OK! Feel free to reopen or create a new ticket if you see a way to save time via some form of automation.
