### ISSUE TITLE
add additional github projects to zenhub 

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1305]
All our github projects (terraform, ansible, archivespace-scripts) should be on our zenhub board. 

Make sure issues show up in "Inbox" when they are created and show up on Zenhub board generally. 

Pretty sure it's possible for zenhub to cover more than one github project, but I don't know how to set it up.

**Comment by eddierubeiz** [comment]
I seem to have gotten this working.

**Comment by eddierubeiz** [comment]
Let's just leave this in Review until we can demo the new repos for Michelle and make sure it's configured right for her.
