### ISSUE TITLE
Scout is claiming WorksController#Show contains an n+1.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1310]
https://scoutapm.com/apps/347458/endpoints/Q29udHJvbGxlci93b3Jrcy9zaG93/trace/1005443310?nplusone=204.933961&section=timing

It appears to be pointing at:
[decorator.interviewee_biographies.present?](https://github.com/sciencehistory/scihist_digicoll/blob/3776922cd3db47b6e7af0e835d6b203a7f5f1f11/app/views/works/oh_audio_work_show.html.erb#L148)

in `/app/views/works/oh_audio_work_show.html.erb`.

**Comment by jrochkind** [comment]
The view component refactor in #742 is likely going to change the stack trace compared to what Scout originally reported , but probably won't change the n+1 situation. Maybe Scout will report again?

**Comment by jrochkind** [comment]
Sadly the scout trail linked to isn't there anymore, our plan doesn't keep em forever (reminder to selves, paste relevant context like a backtrace into ticket for this reason). 

But I think we still have enough for me to investigate.

**Comment by jrochkind** [comment]
Hmm, having trouble finding it. Scout might have been wrong... or it might have been refactored out already. 

The way this code works with multiple branches for multiple kinds of views does make it hard to manage the loading to avoid n+1 though, might rethink it....

**Comment by jrochkind** [comment]
Scout currently lists `0` for "n+1 insights" over the past 24 hours. (It only shows 24 hours, but that should catch our typical pages no problem).
