### ISSUE TITLE
Enhance "related items" feature (automatic similar/more-like-this from Solr)

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1317]
Over the past year, the manual "related items" feature seems to have been used a lot more than initially, often listing just other things with the same author. 

We could automatically generate "related items" based on similar metadata -- same creators and/or subjects for instance. This might be valuable if we think "related items" bring viewers to more items of interest and value to them, and want to avoid some of the tedious manual labor of manually listing things mechanistically that have the same author etc. 

We could use the Solr "more like this" feature to implement this. 

@MDiMeo just an idea

**Comment by jrochkind** [comment]
(moving this back to top of backog, as we need more specs before 'ready')

**Comment by apinkney0696** [comment]
Let's move ahead with this when we have the time! Automating related items based on subject headings (and maybe descriptions? other facets?) will be useful, I just want to make sure I can edit the related items and manually select related items when necessary. Any other considerations we need to think about?

**Comment by jrochkind** [comment]
My thought for the simplest way to implement would be -- use automated related items only if the item has no manual related items specified. 

If there are manual related items, the automated related item finder isn't used. 

We'll still have to play with the solr feature and see if we can configure it to produce results we are satisfied with for automated related items at all!  That might be something @eddierubeiz finds engaging, although I'm happy to do it too.

**Comment by jrochkind** [comment]
@eddierubeiz I'm very interested in the recipe:  subjects + creators + description

(Yes, including description text in there!)
