### ISSUE TITLE
Better indexing for works in German

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1336]
As part of the Bredig project, we will be ingesting, transcribing and translating a significant corpus of works written exclusively in German. Currently these are indexed in a catch-all field that does not provide stemming for either English or German. Once enough German content accumulates, we may want to tweak our search settings to make it easier to find German words.

This is a broad ticket that covers:
- Gathering some test searches from researchers familiar with German, with current and desired results: `I searched for X and I only got Y, when I had hoped to get Z.`;
- Researching German-language indexing we can get out of SOLR;
- Creating a new German full-text field and indexing all German-only works into that field;
- Incorporating search results from that field into our existing full-text index;
- Running test searches to establish that the new setup actually does a better job matching German words.

**Comment by eddierubeiz** [comment]
The initial results in dev and staging were so promising that I skipped the "gather test searches" step. The fact that the number of useful matches for the term `buch` doubles speaks for itself.

**Comment by jrochkind** [comment]
Also search for `potato` you get a lot of German matches for `tat`, which is unfortunate. 

We should look into fine tuning or other options.
