### ISSUE TITLE
Do the replication rules from production s3 buckets to backup ones include deletes?

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1337]
Quick note to remind myself to document this; peripherally related to our work on orphaned files.

**Comment by jrochkind** [comment]
I'd really like to continue with the "orphaned work" push and keep getting through these before moving on to any other major projects (whcih we don't have any urgent ones). No time like the present!

**Comment by eddierubeiz** [comment]
All three replication rules have "delete marker replication" turned on. Items deleted in the source bucket are deleted in the destination bucket as well, @CHF-IT-Staff .


https://s3.console.aws.amazon.com/s3/management/scihist-digicoll-production-originals/replication/view?region=us-east-1&id=Backup
https://s3.console.aws.amazon.com/s3/management/scihist-digicoll-production-derivatives/replication/view?region=us-east-1&id=Backup
https://s3.console.aws.amazon.com/s3/management/scihist-digicoll-production-dzi/replication/view?region=us-east-1&id=Backup

**Comment by jrochkind** [comment]
By "replication rules", I guess we're talking about the rules to replicate to "backup" buckets?  That's what we use replication rules for? 

I wasn't sure whether this ticket was about production->staging sync, which could be called a form of "replication", but would not use "replication rules". 

But I guess you made the ticket, only 5 days ago, so you know what it was about, ok!   In general, always good to be more specific in a ticket so it's clear what it's about, and why it's being filed.

**Comment by eddierubeiz** [comment]
Correct. This was just in response to a question from Chuck -- more of a to-do item than an issue, frankly.
