### ISSUE TITLE
Estimate cost of a single run of the latest orphan-checker code.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1339]
To get a sense of whether it's actually worth running it nightly (as opposed to, e.g., weekly or monthly or sporadically.)

**Comment by eddierubeiz** [comment]
Today's check ran for 36 minutes.
My understanding is that for scheduler-run `Standard-1x` dynos, [costs are prorated to the minute at a rate of $25 / month](https://devcenter.heroku.com/articles/usage-and-billing#cost).
So I'm going to estimate our monthly cost for these checks at 64¢ / month.

**Comment by jrochkind** [comment]
I was actually more worried about the AWS costs for cycling through all the buckets? It's possible that is trivial though, not sure.

**Comment by eddierubeiz** [comment]
Behind our `app/services/s3_path_iterator.rb` is a series of calls to [list_objects_v2](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Client.html#list_objects_v2-instance_method).

**DZI checks:**
You discuss the cost of the dzi check in https://github.com/sciencehistory/scihist_digicoll/blob/ac90dec5587239c8fdfef68e3b623c7e81542ccf/app/services/orphan_s3_dzi.rb#L24 . I'm guessing running it nightly might run us about $5 a month. Hm -- we might want to put the dzi check on a weekly schedule.

**Others:**
The other checks are very, very cheap. `list_objects_v2` costs 0.5¢ for a thousand calls to `list_objects_v2`, each of which returns a chunk of up to a thousand S3 URLs. 
49,663 originals + 429,369 regular derivs + 2,754 restricted derivs = 481,786 non-DZI files, which can be listed in under 500 calls, so one cent every two days.

**Comment by eddierubeiz** [comment]
For now, I'm running the check [once a week on Wednesday nights at 1 am](https://dashboard.heroku.com/apps/scihist-digicoll-production/scheduler).

**Comment by jrochkind** [comment]
Oh I see, DZI discussed above, ok, thanks! We can discuss with Chuck (@CHF-IT-Staff) what schedule he wants for what price?

**Comment by jrochkind** [comment]
Sorry for all the scattered comments. I'd also be interested to see an estimate of how much the "orphaned" files you found on production were costing us for storage monthly.

**Comment by eddierubeiz** [comment]
Based on the graphs of storage usage in the [originals](https://s3.console.aws.amazon.com/s3/bucket/scihist-digicoll-production-originals/metrics/bucket_metrics?region=us-east-1&tab=storage&period=2w) and [derivatives](https://s3.console.aws.amazon.com/s3/bucket/scihist-digicoll-production-derivatives/metrics/bucket_metrics?region=us-east-1&tab=storage&period=2w) buckets, which are effectively flat, I'm estimating we did not save a lot of money at all per month by deleting the orphans last week. I assume on the order of a dollar or two; probably less.

Originals
Before (9/26): 4.2 TB (couldn't figure out how to get a more precise number based on a cursory look.)
After (10/01): 4.2 TB

Derivatives
Before(9/26): 256.2 GB
After(10/01): 258.5 GB (the number actually rose, since there were ingests that day too.)

The exact number of bytes deleted, and thus the number of pennies saved, is possible to calculate using the [list of deletions](https://github.com/sciencehistory/scihist_digicoll/files/7254403/deletions.txt), because S3 saves size metadata after files are deleted.
