### ISSUE TITLE
Facets in URLs from old app to new app -- keep them from breaking?

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#135]
[applies to sort_fields too]

We had intended to keep URLs from old app working as-is in new app. 

But I realized some Solr configuration changes have broken some in new app. Because Blacklight, when applying limits from facets, exposes the Solr field names in browser URLs.

In old app, all our facets were in solr fields ending in `_sim`, which was defined in the solr schema (that came from sufia) as dynamic fields which were `type="string" stored="false" indexed="true" multiValued="true"`. ("sim" => s=string, i=indexed, m=multivalued)

In the new app, I had created a new dynamic field definition in Solr for `*_facet`, defined appropriately for facets. It was multi-valued, and defined in term of a Solr field definition I created `string_dv`, which is equivalent to the old definition _except_ I turn on Solr "docValues", because that is appropriate for best performance in Solr facetting, even though Sufia was not using it. 

So at first I thought I should switch all our facet fields to be `*_sim` fields to match sufia behavior and keep old URLs working. But that would not have docValues, missing out on best Solr configuration. I could redefine "*_sim" to have docValues on, but that would be confusing with the system used to define dynamic field definitions with those suffixes meaning certain things (what if you wanted a string/indexed/multivalued field that did not have docValues on?)

(Blacklight 7 suggests some dynamic field definitions too, which used to be just samvera doing that. And it does use docValues in some places, but not actually for any string fields. But we know docValues on a string field used for facet is appropriate. https://github.com/projectblacklight/blacklight/blob/master/lib/generators/blacklight/templates/solr/conf/schema.xml)

So I dunno, now I'm thinking maybe we need to define some redirects in the new app that just catch the old URLs and do an HTTP 301 ("moved permanently") redirect to a URL using the new "_facet" fields. 

Any thoughts @eddierubeiz ?

**Comment by eddierubeiz** [comment]
I do have some thoughts, and the first one is "there are URLs and URLs". I think we *should* keep URLs from old app working as-is in new app, and we *have to* for most URLs. But it's not clear to me that we need to follow this principle all the way to achieving total backwards compatibility for Blacklight search URLs. Maybe I don't have the full picture; happy to discuss. :)

**Comment by jrochkind** [comment]
I guess in theory someone might have bookmarked a particular search results, or even linked to it from a web page. Ah, I believe we did put search forms on Institute web pages pre-selected to have facet limits....

See the "Digital Collections" search form on: https://www.sciencehistory.org/rare-books

Results in a URL which has had the genre facet pre-selected, eg:

https://digital.sciencehistory.org/catalog?f%5Bgenre_string_sim%5D%5B%5D=Rare+books&q=science

We could change those on the Institute web page (synchronized with new app release). Or we could just keep all URLs working (possibly through a redirect). 

I hadn't actually recalled this functionality when I originally wrote this ticket. We could count on us to know about and remember any place that people may be using URLs... or we can just commit to keeping all URLs working.

**Comment by jrochkind** [comment]
applies to sort fields too
