### ISSUE TITLE
Provenance field front-end

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#136]
The data entry and display for the provenance field should be consistent with Sufia:
- [ ] Instructions on metadata screen
- [ ] Treatment of HTML tags, inbound to database
- [ ] Treatment of HTML tags, outbound from database to template
- [ ] Method to split the notes out of the field
- [ ] Notes should be hidden on page load
- [ ] "Notes..." link (or equivalent) to show notes; whatever we decide to do in Sufia, it should work the same way here.
- [ ] Tests to ensure the splitter method works as advertised (port from Sufia)

**Comment by jrochkind** [comment]
Is this done @eddierubeiz ? Or done enough to close?

**Comment by jrochkind** [comment]
Did #151 close this? Or this still work left to do?

**Comment by eddierubeiz** [comment]
Yeah this is all done. Closing!
