### ISSUE TITLE
Recently Added items to populate based on "Publication Date"

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1410]
This will put the most recently published items onto the homepage, rather than the most recently edited as it is set at present.

**Comment by apinkney0696** [comment]
I definitely use the sort by "created date" and "last modified date". Both are useful. 

I agree, end-users probably don't need any more sorts than "recently added" and the date of the physical object

**Comment by eddierubeiz** [comment]
Assuming our intent is to keep track of "the date the item first went public", temporarily unpublishing and republishing a work should leave the publication date intact. @apinkney0696 , can you confirm please?

(Context: our workflow when something is wrong with a work's assets  or derivatives often involve temporarily taking a work offline while we modify its contents.)

**Comment by eddierubeiz** [comment]
I also want to make sure that this date never gets confused, in the code or the UI, with the bibliographical publication date. I think it's a moot point as long as the value of the date is never displayed to the public; my understanding of the above implies that we would only use this date to sort items in three places:

1) the recently added items on the home page
2) the "Recently added" sort of [public search results](https://digital.sciencehistory.org/catalog?search_field=all_fields&q=&range%5Byear_facet_isim%5D%5Bbegin%5D=&range%5Byear_facet_isim%5D%5Bend%5D=

I think that's it -- let me know if I'm missing anything.
3) a new sortable column in the [staff work listing](https://digital.sciencehistory.org/admin?q%5Bparent_id_null%5D=true&q%5Bs%5D=created_at+desc)

**Comment by jrochkind** [comment]
I was assuming that unpublishing and re-publishing a work would re-set the publication date... because it's not obvious to me that would be wrong either, and seems more straightforward.  Either one can be implemented. 

How often do staff unpublish a published work anyway?  I didn't think that was a part of workflow, but my understanding of workflow may again be outdated. 

I agree that we don't show this date on the screen anywhere. We *already* offer a publically visible "recently added" sort, we're just making it accurate.

**Comment by jrochkind** [comment]
@eddierubeiz Also, how about doing the setting of the publication_date on the model as a `before_save` hook (or maybe `before_validate` actually), and doing that as a separate PR of it's own?

**Comment by eddierubeiz** [comment]
Agreed - now that I think about it, it belongs in a hook, totally.

**Comment by apinkney0696** [comment]
@jrochkind I will unpublish and re-publish records every so often. I typically will do this if I notice something wrong/insufficient with the metadata, but don't have time to fix it at the moment and need to come back to it. Or if I need to reorder or reupload an image, I'll typically unpublish until I have fixed the assets. It's not very frequent, but it definitely happens. I would like to maintain some record of the first record publication date if possible, but it's not a big deal to me if republishing causes it to show up in the Recently Added items again.

In terms of your familiarity with staff workflow, it's really me, Nicole, and Jahna (plus Sarah S. and Jocelyn) who are using the DC the most. Because we are all so new to the Institute, I'm sure we could have developed different workflows/habits from previous staff. If you have any other questions about use, or just want to talk through "a day in the life of Annabel using the DC," I'm more than happy to walk you through some of my processes!
