### ISSUE TITLE
Updated NACO Authority Subject and Creator Headings

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1432]
Whenever y'all have an opportunity (no rush), could I please have records with the following two headings updated from

**Bredig, Georg, 1868-** to **Bredig, Georg, 1868-1944** (764 creator entries, 388 subject headings)

and 

**Caruso, David J.** to **Caruso, David J., (David Joseph), 1978-** (34 creator entries)

Thanks!

**Comment by eddierubeiz** [comment]
I ran a draft of this code in staging @apinkney0696  - take a quick look when you have a chance.

**Comment by apinkney0696** [comment]
Looks great to me! I don't see any issues - thank you!
