### ISSUE TITLE
Derivative creation failed

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1450]
> [scihist_digicoll/production] TTY::Command::ExitError: Running `vipsthumbnail /tmp/shrine20211109-374-f2ijxk.tif --eprofile /app/vendor/bundle/ruby/2.7.0/gems/kithe-2.1.0/lib/vendor/icc/sRGB2014.icc --delete --size 54x65500 -o /tmp/kithe_vips_cli_image_to_jpeg20211109-374-llf3es.jpg\[Q\=85,interlace,optimize_coding,strip\]` failed with  exit status: 255  stdout: ...

>...(vipsthumbnail:379): VIPS-WARNING **: 13:37:45.524: profile incompatible with image
> vipsthumbnail: unable to thumbnail /tmp/shrine20211109-374-f2ijxk.tif
icc_transform: no input profile

I don't understand what's going on, is derivative creation broken in general? Why does it feel like things that have always worked are mysteriously not working! 

## Backtrace

    line 38 of [PROJECT_ROOT]/app/uploaders/asset_uploader.rb: block (2 levels) in <class:AssetUploader>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/58989/faults/73028093)

**Comment by jrochkind** [comment]
@apinkney0696 

So, regarding that collection thumb you were trying to upload. The warning "should be a square" is just a warning, normally it does let you upload a thumb anyway that's not square, it just warns you. 

But something else (not about it not being a square!) went wrong -- it was having trouble creating a thumbnail from the TIFF you were trying to use.  For technical and still mysterious reasons. 

Could you send us the TIFF you were tryin to use somehow, so we can try to reproduce?  I don't think I have a record of which Collection it was in our error report, I'm relying on your memory, when you told me you had just tried to upload a collection thumb!

**Comment by apinkney0696** [comment]
Here is the link to the download I accessed: https://www.archives.gov/nhprc/about/logo.html 

I uploaded it from my Downloads folder on my work computer so I don't have the original file I used with me. Redownloading should give you the same thing.

**Comment by apinkney0696** [comment]
Oh and I had tried to upload it to the Immigration and Innovation Collection https://digital.sciencehistory.org/collections/wkppqzw

**Comment by jrochkind** [comment]
The thumb does look like it is in fact working in that collection though! So maybe I just won't worry about it. 

I'm not sure putting a sponsor logo as the collection thumbnail is the best move in the long run, we maybe want to add a separate feature, and let the collection thumbnail be something more visually appealing and of interest to users?

**Comment by apinkney0696** [comment]
Not quite, here was my process:

1. Downloaded the image from NARA site
2. Uploaded image into the digital collections from my downloads folder
3. This upload failed, gave me the error message that it wasn't square
4. Opened the image in photoshop (photoshop gave me an error that the colors weren't RGB color mode)
5. Changed the image to a square in photoshop and to RGB color
6. Saved photoshopped image as a .tif and uploaded this successfully into the DC

**Comment by apinkney0696** [comment]
> I'm not sure putting a sponsor logo as the collection thumbnail is the best move in the long run, we maybe want to add a separate feature, and let the collection thumbnail be something more visually appealing and of interest to users?

I agree, and that's something I'd love to address when we get to the Collections pages (after the homepage refresh)!

**Comment by jrochkind** [comment]
Aha, that totally makes sense, it *worked* after you opened and saved in photoshop, I didn't understand that part!

OK, I think maybe we're not going to worry about this "bug" in digital collections, where an odd TIFF missing a color profile causes thumb generation to fail. There's a clear workaround, fix the TIFF in Photoshop, as you did. 

Yeah, in general the thumb also needs to be square to look right on collections list page once published, although it'll let you upload it anyway... it might make sense to just remove this non-ideal thumb from the collection for now, it's not going to work well like that. 

But okay, I'm going to close this ticket!

**Comment by jrochkind** [comment]
(Oh sorry, I see it already is a square! Just with a lot of empty whitespace. OK, anyway, for another time).
