### ISSUE TITLE
Homepage Collections Ribbon refresh

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1453]
Jonathan and Annabel came up with the following structure for the Collections ribbon:

> Collections
> Digitized materials are selected from four collecting areas at the Science History Institute.
> [four department icons]
> [[View all collections](https://digital.sciencehistory.org/collections)]

Images for the icons are located here: P:\Othmer Library\Digital Collections - Internal Access\Website images\Final Images

The background color has yet to be decided. Will depend on accessibility.

The following text can then be added to the Collections Page (linked above)

> Digitized items in the Digital Collections make up a selection of all [Science History Institute materials](https://www.sciencehistory.org/collections). View Institute Collections with digitized content below.

**Comment by jrochkind** [comment]
@apinkney0696 I'm having trouble finding the images.  I don't see a `Homepage images` folder at `P:\Othmer Library\Digital Collections - Internal Access`

**Comment by apinkney0696** [comment]
Whoops, just renamed it "Website Images"

**Comment by jrochkind** [comment]
Yes, thanks, I found it, and accessed them. I'll edit the issue description to match.
