### ISSUE TITLE
Adjust "Digitization funder" field

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1456]
Based on Jonathan's comment in #1427 

> So we could add that additional option to "additional credits." But if you're just doing that because it's already there and it doesn't really fit best there, we can also do literally whatever makes sense. I think right now "additinoal credit" is all in-house staff involved in the production of the records, photograph, translation, etc. Maybe we want to keep it for that?
> 
> We can add another field. We can put this wherever you want. We could take some existing field and change/generalize it (maybe generalize "digitization funder" to like "funder/sponsor", with a drop-down for what type of funder?).

Here is what I'm thinking:

1. Change "Digitization funder" field to "Funder"
2. Add a Drop down menu with two choices: Digitization funder and Oral history sponsor
3. Add a blank field next to the dropdown for the Sponsor/Funder data to be entered
4. Make the field repeatable (for oral histories that have a sponsor and had OHMS funded by the NHPRC)

I'll send an update for the instructional text for above the field in the metadata form.

Then we'll have to move all of the names listed as sponsors in the creator field into this field and delete the Sponsor option from the Creator drop-down list, but I'll create another ticket for that when the time comes.

Thoughts/feedback?

**Comment by jrochkind** [comment]
That seems reasonable and do-able to me!

i guess the choice of "Digitization Funder" or "Oral History Sponsor" will also show up on the public view -- ie, existing digitization funders should show up in public view the same as they do now.

**Comment by jrochkind** [comment]
@apinkney0696 so I remembered one reason for the current creator/sponsor field -- so it shows up in the "Creator" **facet**, and you can use that to easily assemble the list of "all works with sponsor X". 

Does this apply to this use case? 

We probably don't want to add all "Funders" (including the digitization funders which I think are often one-off) to the creator facet (or any other facet)... 

I wonder if for this current use we should just add it as Creator/Sponsor after all, and all it a day?

**Comment by apinkney0696** [comment]
Decisions from today's (11/15) meeting and following up with Sarah S.

Will keep the fields as need be.

Sponsors will remain in the Sponsor creator field. Even though this is a little confusing with regards to the organization of the data, the Sponsors will continue to be searchable facets, which is a priority for Oral History folks.

Sarah S., Nic, and I agreed that the Digitization Funder field as-is would work for inputting the crediting information. We will write a canned sentence for the field along the lines of "This oral history's transcript synchronization was generously funded by the National Historical Publications and Records Commission."
