### ISSUE TITLE
List all oral history interviews without a published asset

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1463]
There are oral history records without a published asset in the Digital Collections. These were published prior to the application of ticket #496 (prevent published works without representatives). Oral History staff needs to be able to unpublish and republish these records for editing but are unable to without any public assets.

@eddierubeiz confirmed that we should maintain the rules created in ticket #496 and upload a new, "publishable" asset to each oral history.

@sunicolita confirmed that she would be able to upload an image of the first page of each .pdf to each oral history this problem applies to. This will not violate any agreements between SHI and the interviewee.

Annabel and Nic determined that there was _not_ a pattern between an oral history record's restriction status and the presence of a public "Front Matter" asset. This ticket is to request a list of all the oral history records in the digital collections without a published asset so that Nic has a list to work through updating. 

Let me know if I forgot anything. Thanks, all!

**Comment by eddierubeiz** [comment]
OK -- these have a representative, but it's unpublished:

[["Steller, Hermann", "https://digital.sciencehistory.org/admin/works/2d0455x"],
 ["Cox, Jeffery S.", "https://digital.sciencehistory.org/admin/works/2yodtq9"],
 ["Etchison, Diane O.", "https://digital.sciencehistory.org/admin/works/bjw01wt"],
 ["Altman, John D.", "https://digital.sciencehistory.org/admin/works/bu760aw"],
 ["Koomey, John Michael", "https://digital.sciencehistory.org/admin/works/rrbcqvl"],
 ["Harding, Sandra G.", "https://digital.sciencehistory.org/admin/works/qlvzx3b"],
 ["Holy, Timothy Eric", "https://digital.sciencehistory.org/admin/works/vt6wfug"],
 ["Kalderon, Daniel D.", "https://digital.sciencehistory.org/admin/works/32i1yh2"],
 ["Kohorn, Bruce D.", "https://digital.sciencehistory.org/admin/works/sgi5rre"],
 ["Berman, Helen M.", "https://digital.sciencehistory.org/admin/works/bkxtllo"],
 ["Lettow, Charles F.", "https://digital.sciencehistory.org/admin/works/dlbdlba"],
 ["McConnell, Susan K.", "https://digital.sciencehistory.org/admin/works/uwitvhe"],
 ["Hanein, Dorit", "https://digital.sciencehistory.org/admin/works/dk3bga5"],
 ["Karplus, Martin", "https://digital.sciencehistory.org/admin/works/z3ji7rh"],
 ["Costantini, Franklin D.", "https://digital.sciencehistory.org/admin/works/uthde6e"],
 ["Franz, John E.", "https://digital.sciencehistory.org/admin/works/8o6ohiw"],
 ["Folkers, Karl", "https://digital.sciencehistory.org/admin/works/369f1qt"],
 ["Cooper, Julia P.", "https://digital.sciencehistory.org/admin/works/tdtfvqt"],
 ["Carrasco, Nancy", "https://digital.sciencehistory.org/admin/works/t2cnssq"],
 ["Meade-Tollin, Linda C.", "https://digital.sciencehistory.org/admin/works/crztv9x"],
 ["Van Voorhis, Wesley C.", "https://digital.sciencehistory.org/admin/works/3umab6c"],
 ["Lemke, Greg E.", "https://digital.sciencehistory.org/admin/works/cb8liyu"],
 ["Molkentin, Jeffrey D.", "https://digital.sciencehistory.org/admin/works/xz0icab"],
 ["Brown, Anthony M. C.", "https://digital.sciencehistory.org/admin/works/vlbd155"],
 ["Landau, Ralph", "https://digital.sciencehistory.org/admin/works/alsteij"],
 ["Snyder, Michael", "https://digital.sciencehistory.org/admin/works/m0t10am"],
 ["Padgett, Richard", "https://digital.sciencehistory.org/admin/works/qxawc0w"],
 ["Nemerow, Glen", "https://digital.sciencehistory.org/admin/works/fz55iu8"],
 ["Bevilacqua, Michael P.", "https://digital.sciencehistory.org/admin/works/2kcrho8"],
 ["Pike, Marilyn C.", "https://digital.sciencehistory.org/admin/works/z9ml4ow"],
 ["Crawford, Emmett D.", "https://digital.sciencehistory.org/admin/works/pihpigh"],
 ["Jenkins, Marc K.", "https://digital.sciencehistory.org/admin/works/7m0w1fa"],
 ["DeSimone, Douglas W.", "https://digital.sciencehistory.org/admin/works/j9s3nv5"],
 ["Omary, M. Bishr", "https://digital.sciencehistory.org/admin/works/w56ftpd"],
 ["Magnuson, Terry", "https://digital.sciencehistory.org/admin/works/xz0j08m"],
 ["Keene, Jack D.", "https://digital.sciencehistory.org/admin/works/41ox0d5"],
 ["Brent, Roger", "https://digital.sciencehistory.org/admin/works/80u8jkw"],
 ["Stavropoulos, William Spyros", "https://digital.sciencehistory.org/admin/works/evdjnrk"],
 ["Ross, Christopher A.", "https://digital.sciencehistory.org/admin/works/2eysdqc"],
 ["Whitehead, Alexander S.", "https://digital.sciencehistory.org/admin/works/z16crn5"],
 ["Klymkowsky, Michael W.", "https://digital.sciencehistory.org/admin/works/j3mf7i2"],
 ["Rogalski-Wilk, Adrienne A.", "https://digital.sciencehistory.org/admin/works/t8n11bc"],
 ["Forbes, Douglass Jane", "https://digital.sciencehistory.org/admin/works/nxd38nu"],
 ["Holm, Connie", "https://digital.sciencehistory.org/admin/works/nmciejn"],
 ["Posakony, James", "https://digital.sciencehistory.org/admin/works/5ba5rxv"],
 ["Matsudaira, Paul T.", "https://digital.sciencehistory.org/admin/works/rwg0whl"],
 ["Lemons, Richard", "https://digital.sciencehistory.org/admin/works/c8mmpws"],
 ["Boswell, Robert", "https://digital.sciencehistory.org/admin/works/dhgr6ul"],
 ["Jones, Katherine A.", "https://digital.sciencehistory.org/admin/works/ln6wfev"],
 ["Rimel, Rebecca W. (Rebecca Webster)", "https://digital.sciencehistory.org/admin/works/o89oyep"],
 ["Murthy, Venkatesh", "https://digital.sciencehistory.org/admin/works/tuwgcym"],
 ["Lagunoff, Michael", "https://digital.sciencehistory.org/admin/works/2y5oqt1"],
 ["Baumann, Peter", "https://digital.sciencehistory.org/admin/works/egz9osw"],
 ["Sorge, Joseph", "https://digital.sciencehistory.org/admin/works/5hzc2z1"],
 ["Cerione, Richard A.", "https://digital.sciencehistory.org/admin/works/7uq2903"],
 ["Thomas, John B.", "https://digital.sciencehistory.org/admin/works/9y9exj9"],
 ["Shaw, George M.", "https://digital.sciencehistory.org/admin/works/2cpyqn7"],
 ["Aderem, Alan", "https://digital.sciencehistory.org/admin/works/jip7nai"],
 ["Noebels, Jeffrey L.", "https://digital.sciencehistory.org/admin/works/ckikh2w"],
 ["Salama, Nina R.", "https://digital.sciencehistory.org/admin/works/lq5jaje"],
 ["Huang, Z. Josh", "https://digital.sciencehistory.org/admin/works/nab78zv"],
 ["White, Judith", "https://digital.sciencehistory.org/admin/works/uu5l29a"],
 ["Ravetch, Jeffrey V.", "https://digital.sciencehistory.org/admin/works/5eb63n8"],
 ["Solnica-Krezel, Lilianna", "https://digital.sciencehistory.org/admin/works/r706kyj"],
 ["Krause, James E.", "https://digital.sciencehistory.org/admin/works/80r1hts"],
 ["Eisen, Michael B.", "https://digital.sciencehistory.org/admin/works/56kwsil"],
 ["Lin, Jim Jung-Ching", "https://digital.sciencehistory.org/admin/works/g2xfi2a"],
 ["Chiu, Shing", "https://digital.sciencehistory.org/admin/works/gldoidp"],
 ["Miller, Virginia", "https://digital.sciencehistory.org/admin/works/im1hr1n"],
 ["Welch, Rodney", "https://digital.sciencehistory.org/admin/works/q6s6di2"],
 ["Cowin, Pamela", "https://digital.sciencehistory.org/admin/works/axa9zpv"],
 ["Clark, Gregory A.", "https://digital.sciencehistory.org/admin/works/49j2s7t"],
 ["Ehrlich, Barbara E.", "https://digital.sciencehistory.org/admin/works/6yjgubm"],
 ["Stryer, Lubert", "https://digital.sciencehistory.org/admin/works/4z1tri9"],
 ["Luskin, Marla B.", "https://digital.sciencehistory.org/admin/works/vfryv48"],
 ["Kuo, Lawrence", "https://digital.sciencehistory.org/admin/works/13g67ah"],
 ["Krause, James E.", "https://digital.sciencehistory.org/admin/works/pgirlis"],
 ["Rosoff, Philip M.", "https://digital.sciencehistory.org/admin/works/kp1aay6"],
 ["Horton, Jay D.", "https://digital.sciencehistory.org/admin/works/xt30n7c"],
 ["Doublié, Sylvie", "https://digital.sciencehistory.org/admin/works/eqlc9cf"],
 ["Scheller, Richard H.", "https://digital.sciencehistory.org/admin/works/kd9q8kd"],
 ["Goode, Bruce L.", "https://digital.sciencehistory.org/admin/works/v2f31n7"]]

**Comment by eddierubeiz** [comment]
And these don't have a representative at all:

[["Farber, Steven A.", "https://digital.sciencehistory.org/admin/works/q5utwex"],
 ["Jensen, E. William", "https://digital.sciencehistory.org/admin/works/xuuzidp"],
 ["McAllister, A. Kimberley", "https://digital.sciencehistory.org/admin/works/f7cj34e"],
 ["Oreffice, Paul", "https://digital.sciencehistory.org/admin/works/4bpxix6"],
 ["Roberts, John D.", "https://digital.sciencehistory.org/admin/works/rtbme0d"],
 ["White, Morris F.", "https://digital.sciencehistory.org/admin/works/q5x77xh"],
 ["Taunton-Rigby, Alison", "https://digital.sciencehistory.org/admin/works/k5ipayy"],
 ["Sarett, Lewis Hastings", "https://digital.sciencehistory.org/admin/works/t7iecnw"]]

**Comment by eddierubeiz** [comment]
I'm thinking that given the number of these we should consider automating part or all of the process of generating one-page public representatives.

**Comment by sunicolita** [comment]
That sounds great to me, as the one who would be manually generating and uploading them. Because we would be pulling the first page from everyone’s individual transcript, is that still possible to do?

**Comment by eddierubeiz** [comment]
Yeah. It may take us some days to actually get to this task -- assuming we go ahead with it -- so in the meantime are you OK with doing the ones you need to work on manually, @sunicolita ?

In other words, if you need to temporarily unpublish and republish e.g. Doublié, is it OK to ask you to manually create a new PDF from the first page of the transcript and upload that as the new representative as part of the publishing process?

**Comment by sunicolita** [comment]
It shouldn’t be difficult to do, just tedious and time consuming- and may have to do a little here and there if it’s not an emergency. Happy to do it, but any automation or shortcuts are more than welcome.

**Comment by eddierubeiz** [comment]
Note to self -- some code to generate the above list:
```
Work.where("json_attributes -> 'genre' ?  'Oral histories'").select { |oh| oh.published? && oh.representative != nil && oh.representative.published == false }.map { |w| [ w.oral_history_content.interviewee_biographies.first.name , "https://digital.sciencehistory.org/admin/works/#{w.friendlier_id}" ] }
```

**Comment by jrochkind** [comment]
if you add an image of a title page you create as a "representative", it's going to show up in the "Downloads" list unless we do additional work. (I guess an additional asset "role" would be how we'd do it?)

But I'm confused about the desired setup of these works. I thought OH's with restricted transcript PDFs always had an additional "front matter & index" PDF which was not restricted, and that one would/could be set as a representative? No?

**Comment by apinkney0696** [comment]
>  I thought OH's with restricted transcript PDFs always had an additional "front matter & index" PDF which was not restricted and was marked public, and that one would/could be set as a representative? No?

That was the assumption, but unfortunately, not the case. The presence (or lack thereof) of a "Front Matter" seems to be loosely linked to the restriction status of the oral history, but also it sounds like there was a little inconsistency in OH practices over time (@sunicolita could speak more to that). 

Let's talk more about options for a "public" asset today.

**Comment by sunicolita** [comment]
Yep, @apinkney0696 answered it before I did. We chose to add the Front Matter files for records that could be accessed by the public - AKA manual review files. The problematic records are the ones that are restricted to have little to no metadata available whatsoever, which included providing the Front Matter file which consists of things like CVs, birthdays, and interview abstract ect.

**Comment by eddierubeiz** [comment]
Heads up, @sunicolita  -- we're going to remove the requirement of a published representative, so no need for now to add published items to oral histories *just* to serve as a representative.

**Comment by sunicolita** [comment]
Thanks everyone - sorry for all of the trouble and extra work you've had to put into this for us!

**Comment by jrochkind** [comment]
We did all we are going to do on our side for now, if there's anything else you need feel free to open another issue!
