### ISSUE TITLE
S3 Bucket Changes

### ISSUE THREAD

**Issue by CHF-IT-Staff** [sciencehistory/scihist_digicoll#1486]
I did some AWS S3 cost analysis and found that the S3 IA (Infrequent Access) is saving us money on all the buckets except for scihist-digicoll-production-originals and scihist-digicoll-production-derivatives.  Those 2 buckets should be changed to S3 Standard Access.
I also found that 2 buckets that are Standard Access and should be changed to IA - scihist-digicoll-production-dzi and scihist-digicoll-production-dzi-backup
Do those changes need to be made through Terraform?

**Comment by jrochkind** [comment]
I believe they do need to be done in terraform. i forget exactly what the configuration is, it may be a lifecycle rule that transfers things to IA so-many days after upload. 

In addition to turning that off, you want us to move everything in IA on those buckets *back* to standard?  (not worrying about one-time cost of that?).  

We'll know more once we spend time looking at current configuration, and I will confirm what we want here before doing it. 

I will move this to "Ready" column now.

**Comment by CHF-IT-Staff** [comment]
Thanks.  Right, don’t worry about a one-time cost to go from IA to Standard.


__________________________________

Chuck Hornstein   (he, him, his)
Director, Information Technology
t. +1.215.873.8272
f. +1.215.629.5272

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
Learn about the scientific discoveries that changed our world at sciencehistory.org/learn<https://www.sciencehistory.org/learn>

**Comment by CHF-IT-Staff** [comment]
Good info on intelligent tiering - https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-userguide.pdf#intelligent-tiering

**Comment by CHF-IT-Staff** [comment]
Did some reading then set up lifecycle rules in 4 buckets to Transition to Intelligent-Tiering.
scihist-digicoll-production-originals 
scihist-digicoll-production-derivatives
scihist-digicoll-production-dzi 
scihist-digicoll-production-dzi-backup

I'm not clear on when the lifecycle rules that are in Terraform will overwrite (or be added to) those new rules.

**Comment by jrochkind** [comment]
Cool!

They'll be overwritten by what's in our terraform config whenever we next run terraform. There's no automatic schedule for it, just next time we make a change to our infrastructure in terraform and then execute it. 

So we just have to copy those rules you made to our terraform config, either "import" them automatically (kind of tricky, terraform doesn't love this), or just look at them and manually make the same change in our terraform config.

**Comment by jrochkind** [comment]
@CHF-IT-Staff, former employee Dan somehow noticed this ticket and sent some advice/warning, not sure if impacts this, I'll leave it for you who's been working on this (thanks!). 

> I did notice something you may want to be aware of. The S3-IA standard for buckets charges on a minimum file size of 128 KB. For the DZI tiling that difference might be a notable change in storage cost.

(In that many of our files on DZI bucket may be less than 128KB currently, I guess).

**Comment by CHF-IT-Staff** [comment]
Thanks Daniel!

**Comment by jrochkind** [comment]
I believe these have all been done and this issue can be closed. But I'm not totally sure. 

@CHF-IT-Staff , can you tell if this issue still represents outstanding work to be done, or if we've just accidentaly left it open and should close it now?
