### ISSUE TITLE
Estimate how much material is in the Digital Collections

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1490]
Before the Digital Collections Care meeting on Monday Dec. 13th, please send Sarah Newhouse estimates of how much material is contained in the Digital Collections. Include whatever information is accessible, which could mean:

 - Space taken up in storage (ex: 1TB, 300GB)
 - Location (ex: J:\ drive; M:\ drive; external hard drive in storage; Amazon S3 storage)
 - File types (ex: PDF; TIFF; WAV; unknown audio; stored as JSON but available as XML or CSV export)
 - Number of items (ex: 3 external hard drives; 150 CDs)
 - Number of files (ex: 58,944 on J:\ drive; 20 PDFs on each CD; 11,000 records and 50,000 images)
 - Any notes someone outside of your department might need to make sense of this info! Like, “some of these files are probably duplicated on CDs in archives storage” or “there are also a lot of a/v files that I don’t know the format of”). 
 
This isn’t intended to be exhaustive, but to tell us where we need more information and to get a broad, ballpark estimate of our needs.

**Comment by eddierubeiz** [comment]
(Copy adapted from the invite to the meeting).

**Comment by eddierubeiz** [comment]
Space taken up in storage
	`4.3 TB`

Location
	`Amazon S3 storage`

File types
	`TIFF; PDF; MP3; FLAC`

Number of items (ex: 3 external hard drives; 150 CDs)
	`9397 "works", each of which can be comprised of one or more files (a.k.a "assets")`

Number of files (ex: 58,944 on J:\ drive; 20 PDFs on each CD; 11,000 records and 50,000 images)
	`51040 files`

Any notes someone outside of your department might need to make sense of this info! Like, “some of these files are probably duplicated on CDs in archives storage” or “there are also a lot of a/v files that I don’t know the format of”).
	`These numbers don't include derivatives.`

**Comment by eddierubeiz** [comment]
To estimate the size of originals on s3, I started at the [originals bucket](https://s3.console.aws.amazon.com/s3/buckets/scihist-digicoll-production-originals?region=us-east-1&tab=objects), selected the `asset` directory, then selected `Calculate total size`  in the `Actions` menu.

**Comment by jrochkind** [comment]
Also worth noting that these numbers don't include backup copies. 

I didn't know you could get AWS dashboard to tell you the file size of just one directory/prefix, maybe that's a new feature!
