### ISSUE TITLE
Metadata form "hints" updates

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1493]
See attached .txt for updated hint text:
[Metadata_Form_Hints.txt](https://github.com/sciencehistory/scihist_digicoll/files/7643710/Metadata_Form_Hints.txt)

**Comment by jrochkind** [comment]
Skimming the text, I noticed something about Getty AAT autocomplete; as we won't have that implemented right away, I'll change the text:

> Field auto-suggests terms from the Getty Art & Architecture Thesaurus.

To instead be:

> Use terms from the Getty Art & Architecture Thesaurus where possible.

?

**Comment by apinkney0696** [comment]
That would be great! I definitely had written that while assuming we could get AAT to auto-suggest. Thanks!
