### ISSUE TITLE
Medium field autosuggest from Getty AAT

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1494]
Medium field to auto-suggest from the [Getty AAT](https://www.getty.edu/research/tools/vocabularies/aat/) standard vocab.

**Comment by jrochkind** [comment]
Just for our records in attempts to debug, some technical info on other issues with Getty in the qa gem is in this open ticket on qa here: https://github.com/samvera/questioning_authority/issues/84

**Comment by jrochkind** [comment]
Filed a ticket on the qa gem at https://github.com/samvera/questioning_authority/issues/346

**Comment by jrochkind** [comment]
Yeah, this isn't going to "just work" for our needs from the existing code library we were working. 

We could invest time in "fixing" it for our needs -- ideally contributing our improvements back, but if we can't get agreement with the community on that, alternatively as a custom "adapter" for the `qa` gem. 

It would probably take a few days or a week of work. 

We may be able to do it as part of our "samvera maintenance pledge".  

For now, I'll move this back to "backlog"!

**Comment by jrochkind** [comment]
We decided the default QA behavior was good enough, and implemented that.
