### ISSUE TITLE
OH Projects to Collections final changes

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1496]
On the [Oral History Collection ](https://digital.sciencehistory.org/collections/gt54kn818)page, everything can stay the same, but the links to the projects need to be set to lead to the new collection pages, rather than the results lists with the project facet selected.

The links on [this page](https://www.sciencehistory.org/oral-history-projects), also need to be reconfigured to lead to the new collection pages instead of the projects. Do I need to talk to Clare about this?

**Comment by jrochkind** [comment]
Yeah, we have no ability to edit https://www.sciencehistory.org/oral-history-projects. I think Clare is the one to talk to. 

Weirdly, I thought I noticed some of those links already edited, I thought you had already made it happen somehow, but I guess I got confused!

**Comment by apinkney0696** [comment]
Just sent Clare an email and cc'd you Jonathan. And yeah, I realized I created these tickets in the wrong order so I made sure to stick it above #1492 on Zenhub!

**Comment by jrochkind** [comment]
No worries, thanks for ordering! it's good to explicitly mention the dependency on the ticket too so we don't miss it, which I now have.

**Comment by jrochkind** [comment]
@apinkney0696 can you confirm that everything is fixed at https://www.sciencehistory.org/oral-history-projects , so we are safe to go ahead and remove destinations of previous facet-based links?

**Comment by apinkney0696** [comment]
@jrochkind yes! Clare has updated all of the links. Should be good to go.

**Comment by jrochkind** [comment]
Thanks. 

i realized it's not just changing the links, it's also changing the code that comes up with the "count" for each project -- needs to come up with it by counting members of the new collections, not via project facet. 

Really should get the "description" on the OH home/splash page from the projects now in the database too, instead of just being hard-coded on the screen.
