### ISSUE TITLE
Increase tolerance of tests that insist on time differences < 1 second.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1513]
A test I wrote recently just failed on CI:

`./spec/indexers/work_indexer_spec.rb:77`

```
  1) WorkIndexer oral history indexes created, modified, and published dates
     Failure/Error: expect(Time.parse(output_hash["date_created_dtsi"  ].first)).to be_within(1.seconds).of Time.now
       expected 2021-12-13 19:08:04.000000000 +0000 to be within 1 of 2021-12-13 19:08:05.004951380 +0000
     # ./spec/indexers/work_indexer_spec.rb:79:in `block (3 levels) in <main>'

```

Make that 5.seconds. We don't really care if the two dates are a bit over 1 second apart.

**Comment by jrochkind** [comment]
On testing for time in rspec, a more reliable way might be to use https://github.com/travisjeffery/timecop

Better than guessing how much time something might take.

**Comment by kinduff** [comment]
Better alternative without introducing a new dependency:

```ruby
RSpec.configure do |config|
  config.include ActiveSupport::Testing::TimeHelpers
end
```

Then you can use it in a `before` block like so:

```ruby
before { travel_to Time.local(2021) }
after { travel_back }
```

This will freeze time during the test execution.

**Comment by jrochkind** [comment]
Hey thanks for that @kinduff !

**Comment by kinduff** [comment]
I'm pretty curious and always looking for projects that need contributions. If there's something I can help with, please let me know.

**Comment by jrochkind** [comment]
Hey @eddierubeiz , looking for places to improve this (by searching project for the `be_within(1.second)` pattern), I noticed the test file `./spec/models/record_pubished_at.rb` -- note that it's an error that it doesn't end in `_spec.rb`, all spec files need to end in `_spec.rb` for our rspec suite to run them automatically. Will fix that too. 

I'm actually using the Rails time helper `freeze_time` method. 

https://api.rubyonrails.org/v5.2.6/classes/ActiveSupport/Testing/TimeHelpers.html#method-i-freeze_time

**Comment by jrochkind** [comment]
@kinduff Thanks! While we work in the open, and produce open source, this particular application is really meant only for use of the non-profit Science History Institute (https://sciencehistory.org), and we both work for that org. I'm not sure it would be a good fit for outside contribution. 

The more shared/collaborative open source repos involved in this app is at https://github.com/sciencehistory/kithe and https://github.com/jrochkind/attr_json, although nothing immediatley comes to mind as an easily shareable task. 

We're also part of a community of non-profit library/archives developers called "Samvera", https://github.com/samvera. Although we don't ourselves use too much Samvera code right now, it is a large community of people collaborating on open source mostly Rails-based code for libraries, archives, and museums.  If you were interested in learning more about that, you could join the slack or listservs. https://samvera.atlassian.net/wiki/spaces/samvera/pages/405211682/Get+in+touch
