### ISSUE TITLE
Download transcription and translation as a .pdf

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1524]
Ticket for changing the download format for the transcription and translation text from .txt to .pdf.

In the tech team meeting yesterday, we discussed the .pdf layout will include a science history branding mark, followed by the transcription/translation text in an Institute branding approved font. The line breaks from the webpage that associate the text sections with the images don't need to be included. 

I was thinking it could be helpful to include the work's citation and the credit "Translated by Jocelyn R. McDaniel" at the end of the document. Is that possible?

**Comment by apinkney0696** [comment]
Some additional inspo for this ticket:
[pdf download layout.docx](https://github.com/sciencehistory/scihist_digicoll/files/8365119/pdf.download.layout.docx)

**Comment by jrochkind** [comment]
Thanks! Pretty similar to what I was thinking but:

* I would have only put logo on first page, not repeated header
* I would have put the citation at the top before the transcription/translation, instaed of at the bottom

Let me know if either of those appeal, otherwise we'll do it your way. 

Two more:

* I don't mind the indent of the text after Translation/Transcription heading, although I wouldn't have done it -- but if we have trouble figuring out how to make that happen we might skip it
* The repeated footer with address does seem like a good idea, but again if we have trouble figuring out how to do it, might skip it.

**Comment by apinkney0696** [comment]
That all sounds totally fine to me! I just wanted to put a visual out there to have something to go off of. I think the citation and credit are important to have, but I'm not picky about where they end up on the page. Thanks!

**Comment by jrochkind** [comment]
I was going to say should we try to do it with institute brand fonts -- but i don't know if we have a license to embed them in PDFs we distribute? We could check with Communications to see if this can be done, or we could just use default fonts.

**Comment by jrochkind** [comment]
@apinkney0696 in our current text-file downloads, we have transcription and translation as separate files. 

Do you think it's preferable to combine them into one file?

I have no real opinion, I don't totally understand how these will be used. 

If combining them especially, I wonder if we want to reconsider where the button(s) to download go.

**Comment by eddierubeiz** [comment]
Possible additional feature: QR code linking back to the digital collections.

**Comment by jrochkind** [comment]
@eddierubeiz Intersting idea! I'm guessing most of these PDFs won't actually be printed out, and a clickable link will be sufficient, but that's just a guess!

**Comment by eddierubeiz** [comment]
Yeah; I feel like it couldn't hurt, but I'd ask @apinkney0696 . Should you decide to go ahead, it looks pretty easy to do with e.g. [rqrcode](https://github.com/whomwah/rqrcode ).

**Comment by apinkney0696** [comment]
Hi Jonathan, as you probably saw in the email chain, Dana suggested and Caitlin supported using the font Verdana for the .pdfs. Let me know if you need me to ask anything else!
