### ISSUE TITLE
Additional Credit Field additions

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1525]
(1) Add "Transcribed by" as a drop-down option

(2) Add "Transcribed by Jocelyn R. McDaniel" to Bredig documents that currently have the metadata "Translated by Jocelyn R. McDaniel" 

(3) Add "Gudrun Dauner" to the name drop-down options

**Comment by jrochkind** [comment]
@apinkney0696 fyi this is live and complete on production!
