### ISSUE TITLE
Consider dismantling the R & R workflow in the D. C.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1527]
To the extent that [the new support portal](https://support.sciencehistory.org/new)  is supplanting [the R&R workflow in the digital collections](https://digital.sciencehistory.org/admin/r_and_r_items/new), let's examine whether any parts of that workflow are obsolete and can be removed.

**Comment by apinkney0696** [comment]
The support portal is going to function as a tool for me to track and run reports on requests that come through more easily (I was using a google form and my email to keep track of requests previously). Not all requests require digitization, but when I do need to digitize something, as of right now I still intend to use the R&R queue. Give me a few months of using the new system and then I'll be able to better judge whether or not the R&R workflow in the digital collections is lacking or redundant.
