### ISSUE TITLE
Technical notes for backup

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#153]
Document backup and recovery in step-by-step process for the current, staging, environment of the application.

**Comment by sanfordd** [comment]
Our wiki's backup section now includes a fully detailed section on the new application at the end of the Backups and Recovery page.

**Comment by sanfordd** [comment]
Forgot we don't close this here but wait on the zenhub.

**Comment by jrochkind** [comment]
@eddierubeiz will review notes and close this issue once he's approved them.
