### ISSUE TITLE
Handle reported orphaned S3 asset

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1534]
We got report of an orphaned asset on S3! https://app.honeybadger.io/projects/58989/faults/83340039

Eddie says:

> Just one, an original. The asset is https://digital.sciencehistory.org/admin/asset_files/9tmkkl7 . The current file was ingested 10 am last Thursday. The orphaned file itself is here: https://s3.console.aws.amazon.com/s3/buckets/scihist-digicoll-production-originals?region=us-east-1&prefix=asset%2Fa989320f-b090-45a3-97c6-07a25c0a0012%2F&showversions=false

Let's see what we can do to diagnose and take care of this particular thing reported (maybe not much), as well as take a step back now that our "orphan checker" has made contact with a problem, to see what we can do to improve our systems to increase our developer ergonomics and chances of diagnosing next time.

- [x] Make absolutely sure the asset is not referenced by present app -- it's easy to see search through DB to make sure the UUID in the asset path isn't there, but also maybe search through entire DB to make sure no asset has a `file_data/id` with the path either, in case something is weird there?
- [x] Actually delete the orphaned asset
- [x] Should we log all deletes the app does?  Then we might have a better chance of figuring out "wait, why is this orphaned asset here? What asset/work was it previously assoicated with, and where did that go?"   Right now we only have the asset path of the orphaned file, which gives us the UUID fo the asset it (used to) belong to, but nothing more. 
   - Log on deletion could be using ActiveRecord lifecycle callbacks on asset model
   - Things to log could include: asset friendlier_id and title; parent_work (if present) friendlier_id and title; logged-in-user doing the deleting if any (actually this may not be easily available from a model callback, so no big deal); the asset path to match up with the orphan report!
- [x] HoneyBadger notification says "Orphaned items found. See report in the admin pages." -- how about including the direct URL to the relevant admin page right there in the HB notification, to make it even easier to get to?
- [x]  the link from the report points to a download link. More helpful would be a link to the place in S3 where you can see the metadata e.g. https://s3.console.aws.amazon.com/s3/buckets/scihist-digicoll-production-originals?region[…]89320f-b090-45a3-97c6-07a25c0a0012%2F&showversions=false
  *  (let's actually make a method on Asset to provide this DRY, since we use it in several places, and it could change if we change platforms or if AWS changes their admin UI)
- (**not for now**) Hypothetically the report could have an actual "delete it" link(s) to do it right there, but this may be more trouble than it's worth (or dangerous?) unless this really starts happening a lot.  If it was there, the action should DEFINITELY be logged. 
- [x] We run the orphan report on a weekly basis, which is fine. We just need to update the copy in the report so it doesn't say the report runs nightly.

These are all just ideas, for initial investigation. This ticket is about spending some time on it. if some of these ideas seem infeasible or hard after investigation, they can be eliminated from plan, or separate tickets can be made in backlog to get to later. Also things not in this list can be done if they occur.

**Comment by eddierubeiz** [comment]
All great ideas. Also, I wonder if we could store some work-related metadata along with the file in AWS - e.g. a tag with the URL of the work.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html

**Comment by jrochkind** [comment]
That (tagging with metadata) is a good idea worth doing some more investigation of. But it does have some potential gotchas:

One issue with that is that which work an Asset is atatched to can theoretically change; as well as the metadata on the work of course.  Trying to keep S3 tags up to date doesn't seem feasible... but if we name the tags something tha tmakes it clear this was an initial value snapshot that won't be kept up to date, that's fine. 

It's shrine that's responsible for uplaoding the files to s3... I'm not sure how easy it would be intervene in that process to add S3 tags, and w'ed want to make sure it was done in a performant/cost-effective way. (Can you set tags when you intiially PUT to S3?  Can we get that into our code? Does adding tags later require effectively re-writing the whole value, with expensive/perf implications?). Also right now our code (esp ingest code) is *mostly* platform agnosticc, like if we moved to a non-S3 API, we just change the Shrine adapter and it Just Works. The more platform-specific code we add the less that's true.

**Comment by eddierubeiz** [comment]
All good points. When you create (or un-create) a child work, you are changing the work associated with the child assets.

**Comment by jrochkind** [comment]
Confirmed no Asset model in DB references this path with:

```ruby
Asset.where("file_data ->> 'id' = 'asset/a989320f-b090-45a3-97c6-07a25c0a0012/211439ce4cf86f96a8e3867b06c06315.tif'").count
# => 0
```

deleting it.

**Comment by jrochkind** [comment]
Ah, just for the record before I delete, the content-disposition header set as metadata does reveal the original filename of this file: `2019.011.B8F16.013.001.tif`
