### ISSUE TITLE
re-think browser support policy

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1538]
We decided to stop supporting IE, but otherwise haven't been very clear about our browser support policy. 

I think I had an assumption that anyone using Firefox/Chrome/Edge was using the latest version, but I have seen some evidence lately (including from reading) that this isn't really a safe assumption. One reason it might not be is people with mobile devices that are out of support and no longer updating. 

Another reason occured in-house today. Annabel had a two-year-old Chrome on the "digital studio" mac, on which some of my CSS failed. 
 
I don’t know why an institute machine has a two year old version of chrome, but if it’s annabel it’s probably other people too… we should think about our browser support policy again… the assumption that “if you’re running Chrome you’re running the latest Chrome” is I think not safe so we should not be so cavalier about only supporting/testing on latest version. 

 Maybe we want to try to support up to two-year-old on popular browsers? (Chrome, FF, Safari, Edge).  Or three years? I don't know. 

Also could have a class "works fine but looks messy with missing margins and such". Not sure.

**Comment by jrochkind** [comment]
First step is checking with Communications to see if they have a policy, written or otherwise.

**Comment by apinkney0696** [comment]
From Clare: 

> Hi Annabel,
> 
> I do not believe we have ever written out a policy detailing our browser support. What we do have is a warning on the donation form, although that has more to do with what Raiser’s Edge supports.
> 
> I compiled the attached reports of what our visitors are using and our devs will get back to us with some thoughts. Were you thinking of more of an internal policy, or something public that we could put on the website footer near the Accessibility link? Any models from other libraries?
> 
> In a little bit of research I noticed that airline websites have a nice concise page that acknowledges the fact that the browser apps get updated in rapid fire and it’s pretty hard to verify compatilbility each time. The main difference is that they claim their support goes waaaay back to versions like Safari 8.0, which of course they have the resources to do. But otherwise a document like this (whether on the site or as an in-house reference) could be doable? https://www.aa.com/i18n/customer-service/support/browser-compatibility.jsp?anchorEvent=false&from=footer
> 
> Hope this is a start at being helpful!
> 
> Clare


[Digital Collections Browsers FY22.pdf](https://github.com/sciencehistory/scihist_digicoll/files/8187593/Digital.Collections.Browsers.FY22.pdf)
[Website Browsers FY22.pdf](https://github.com/sciencehistory/scihist_digicoll/files/8187608/Website.Browsers.FY22.pdf)

**Comment by apinkney0696** [comment]
After a brief investigation, I couldn't find much documentation from other digital libraries stating a browser support policy, but I thought the following examples might be useful in helping us determine what we want to support:

https://www.lva.virginia.gov/about/policies/browsers.htm

https://www.ieee.org/about/help/browser-policy.html

https://web.library.uq.edu.au/site-information/web-browser-compatibility

https://help.oclc.org/Librarian_Toolbox/Browser

https://www.drupal.org/docs/system-requirements/browser-requirements
