### ISSUE TITLE
OHs in DC with generated audio players

### ISSUE THREAD

**Issue by sunicolita** [sciencehistory/scihist_digicoll#1561]
Hi there! In an effort to solve the issue of silences in our audio files, could I have a list of all of our published OHs in the DC that have the generated audio players? We'll have to weed through them and edit them by hand as we have the time to do so. Thanks for all of your help!

**Comment by jrochkind** [comment]
(Also again, no pressure from my end to clean these up on any particular timeline! It might make sense to focus on QA'ing for this in new ones added going forward, but that's not up to me either!)

**Comment by eddierubeiz** [comment]
After chatting with Nic I think it's basically OHs that are [published, with audio, and available immediately.](https://digital.sciencehistory.org/collections/gt54kn818?f%5Boh_availability_facet%5D%5B%5D=Immediate&f%5Boh_feature_facet%5D%5B%5D=Audio+recording&f%5Bpublished_bsi%5D%5B%5D=true&q=)

**Comment by jrochkind** [comment]
Oh right, that makes sense, thanks for helping to figure that out @eddierubeiz !

Does that close this ticket?

**Comment by sunicolita** [comment]
Yes - this is everything I needed, thanks a lot you two!
