### ISSUE TITLE
Oral history requests buttons: add a little bit more space in between (low priority)

### ISSUE THREAD

**Issue by rachellane12** [sciencehistory/scihist_digicoll#1562]
Hi tech team,

Now the oral history requests buttons (approve/reject) are fairly close together. 

<img width="133" alt="Screenshot 2022-02-02 120544" src="https://user-images.githubusercontent.com/98541497/152201985-369399b4-512c-4b99-84bb-c19cd75f3e4c.png">

I'm wondering if you'd be willing to add a little bit more space in between like these buttons. 

![image](https://user-images.githubusercontent.com/98541497/152201598-ecff0069-6e28-46dd-9d21-44d437486465.png)

Thanks for all you do!

**Comment by jrochkind** [comment]
How about if we bump them all the way to the edges of the display, on the right and left margin?

**Comment by rachellane12** [comment]
@jrochkind I think that could work!

**Comment by rachellane12** [comment]
Also, if you're doing that, could you put the approve button on the left margin and the reject on the right margin?

**Comment by jrochkind** [comment]
Of course. I'm curious what your motivation is for preference of which is left and which is right?

**Comment by rachellane12** [comment]
Great question. It just makes more sense to me. I can't completely articulate why. Maybe because we read left to right? Plus, I think the left margin button is closer to where my mouse normally is when I'm filling an oral history request, and we typically always approve (and rarely reject). It makes more sense to me to have the reject button farther away.
