### ISSUE TITLE
Export Spreadsheet of data for DC Audit

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1563]
Hi J & E, I'm doing a diversity audit of the digital collections and was hoping to get an export of metadata in an excel sheet

For all parent works in the digital collections (no child works please), could I have the following information:
- Title
- URL
- Department
- Genre
- Creator

Genre may be tricky because there is the possibility of having multiple, and Creator could also be difficult for the same reason and because of the marcrelator term subcategories. I don't need any of the information about Creator type, I just need the names. Let me know if this is possible. Not a huge rush, but would be great to have in the next couple of weeks. Thanks!

**Comment by jrochkind** [comment]
@apinkney0696 do you want only published items, or all items?

**Comment by apinkney0696** [comment]
All items, please.

**Comment by jrochkind** [comment]
@apinkney0696 I'm trying to email you a .CSV file you can open in Excel. 

Let me know if you succesfully get the email and if it meets your needs!
