### ISSUE TITLE
Promoting child records to parent records

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1571]
I digitized some chemistry set manuals for Molly a while back for the digital collections. When I first started these, I made them child records of their chemistry set. But Gabriela and I ended up deciding that they should be their own records. Is there a way to automate child records and their assets into parent records? There are only five l want to change. There's also no rush.

The children records that I would like to become parents are:

Parent ID | Child ID
-- | --
c247ds99c | 41tk1tx
db78tc833 | cqmqcyh
db78tc833 | 4kvkrsz
zk51vh70w | e7ft0h9
w6634461k | so1jbnu

**Comment by jrochkind** [comment]
I thought there was staff UI to do this -- but now I can't find it, so I guess there isn't!

Yes, we can easily do that in our developer's console. 

You could also make a ticket asking for staff UI to do this (and in the opposite direction), if it comes up much.

**Comment by apinkney0696** [comment]
Thanks! It's not a common occurrence, so I don't think staff UI is necessary. If a situation that I need it arises again though, I will definitely consider it.

**Comment by eddierubeiz** [comment]
Ran in staging, then production:
```
['41tk1tx','cqmqcyh','4kvkrsz','e7ft0h9','so1jbnu'].each { |fid| Work.find_by_friendlier_id(fid).update!(parent: nil) }
```

**Comment by eddierubeiz** [comment]
@apinkney0696  -- this is done:

- https://digital.sciencehistory.org/works/41tk1tx
- https://digital.sciencehistory.org/works/cqmqcyh
- https://digital.sciencehistory.org/works/4kvkrsz
- https://digital.sciencehistory.org/works/e7ft0h9
- https://digital.sciencehistory.org/works/so1jbnu

**Comment by apinkney0696** [comment]
Amazing, thank you, Eddie! Just what I needed!
