### ISSUE TITLE
Separate bucket for video

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1575]
This may be split into separate tickets. We want separate buckets for video. 

We will need to mess with shrine plugin/configuration to let it store originals on different buckets depending on content-type. 

- [x] video originals bucket https://github.com/sciencehistory/terraform_scihist_digicoll/pull/9 and #1582
- [x] video originals backup bucket with replication https://github.com/sciencehistory/terraform_scihist_digicoll/pull/9
-  video derivatives (postpone until we know what we are doing with video derivatrives)

Associated code

- [x]  enhance orphan checker for these buckets
- [x] local backups target video originals
- [x] Production->staging sync needs to sync these buckets
- [x] Rake task to copy from staging to dev copy -- might just work?
- What else aren't we thinking of?

- [x] Go through all IAM policies and add the 3 new buckets where they belong.

**Comment by jrochkind** [comment]
OK, we already have two sepearate derivatives buckets -- one for "public" and one for "restricted". 

How should this new feature interact with that?  What happens if you choose "restricted" storage for video derivatives?

Or, I guess, really, we probably should prohibit you from doing that, video derivatives can't be stored "restricted". (We don't have a use-case for it at present). 

@CHF-IT-Staff @apinkney0696 

This is an example of how adding new special case features like this leads to a kind of combinatoric complexity as they all interact with each other, alas.

**Comment by eddierubeiz** [comment]
All IAM policies are now up to date. The only one that still needed to be updated was `s3_staging_readonly`.
