### ISSUE TITLE
Add new video buckets to permissions for `dev_users`

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1602]
Noticed the need for this when working on ref #1600 .

**Comment by eddierubeiz** [comment]
There may be other work in S3 identity management (`IAM`)  to be done -- this just covers the minimum number of changes to get the `dev_users` policies to know about the new buckets.

**Comment by eddierubeiz** [comment]
I added:
- `scihist-digicoll-production-originals-video` permissions to `read_production`
- `scihist-digicoll-staging-originals-video` permissions to `write_staging`
- `scihist-digicoll-production-originals-video-backup` permissions to `read_backups`

**Comment by jrochkind** [comment]
Ah right! I think that's probably it. Thanks!

**Comment by jrochkind** [comment]
If you added *write* permission to staging-originals-video, I assume that means staging-originals already had "write" permission? As long as it matches! I get confused thinking through what it should be.

**Comment by eddierubeiz** [comment]
In this context `write_staging` really means `read_and_write_and_*_staging`. It's spelled out in the policy itself.
