### ISSUE TITLE
Use MockS3Client in both orphaned deriv tests

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1603]
Now that we have `MockS3Client` we can use it to clean up the code in the orphaned (restricted and non-restricted) derivative tests.

**Comment by jrochkind** [comment]
@eddierubeiz When making this ticket, can you specify what these "two more places" are?  In case it's a while until we get to this, or someone other than you is the one who gets to it, I'm not sure they'll know what this means. Thanks!
