### ISSUE TITLE
Video Metadata Updates

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1610]
After chatting with Sarah this afternoon, we have come up with the following list of additions to the metadata form to accommodate video:

- [x] To the Genre field, add "[Video recordings](http://id.worldcat.org/fast/1692913/)"

- [x] Change the Medium field to public-facing (Annabel will clean up museum data)

- [x] To the Creator field, add "Director" and "Producer"

**Comment by jrochkind** [comment]
Cool!

Medium field is already public facing, always has been. You can verify this by opening up an "incognito" window (so you aren't logged in you are just the public), and viewing a record with Medium data, like: https://digital.sciencehistory.org/works/n7ci4v7

What isn't  public is the medium *facet* navigation.  I'm not sure if you meant to ask to make that public?  One concern there is that when most of our records don't have this field filled out (it's been used only for museum), it can be misleading to users to have a facet field that only covers a subset of the corpus, I think users assume they are getting something different. Another concern is that we have *so many* facets, I think it's already overwhelming -- I think the more facet fields we add, the less users will find the ones that are actually useful for their needs. 

Have we have any users asking for this as a facet? 

I wonder if I can find any original notes on why we reserved medium facet for staff in the first place...  I did find the GH issue, from before our initial public launch. Unfortunately, the issue doesn't document the reasoning. (I think this was from like my third week on the job! This was a way back decision!). https://github.com/sciencehistory/chf-sufia/issues/364

**Comment by apinkney0696** [comment]
No kidding, sheesh I honestly did not do that! I had either had someone tell me or I just assumed that one came with the other, i.e. the medium field was private so the faceting was also not visible to the public. In this case, just ignore that point and I'll give a little more thought to whether or not the faceting should be public, though I don't really see why not.

**Comment by jrochkind** [comment]
Yeah, us forgetting or not understanding how we set things up is definitely one danger of doing "just so" configuration/setup like this!

**Comment by eddierubeiz** [comment]
@apinkney0696  -- I went ahead and made the facet public but it's very easy to reverse. Let me know either way. I'll mark the PR as "draft" so we don't merge it by accident.

**Comment by apinkney0696** [comment]
Let's make it public so we can utilize it for video. I cleaned up the metadata already being used in the field earlier this week so what's in there should make more sense now. Glad to know it's easy to change back though just in case! Thank you!
