### ISSUE TITLE
Delete Files from S3 ingest bucket

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1651]
<html>
<body>

2019.011 Bredig Box 10 Folder 34, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
-- | -- | -- | -- | --
2019.011 Bredig Box 2 Folder 33, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 2 Folder 48, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 10, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 15, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 19, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 25, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 26, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 27, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 28, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 3, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 5, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 3 Folder 8, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 4 Folder 13, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 4 Folder 14, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 4 Folder 4, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 4 Folder 40, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 4 Folder 41, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 13, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 15, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 19, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 24, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 26, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 27, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 3, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 35, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 36, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 38, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 7 Folder 4, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 1, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 10, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 12, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 13, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 16, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 25, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 3, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 34, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 36, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 8 Folder 7, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2019.011 Bredig Box 9 Folder 4, folder |   | 0 bytes | application/x-directory | 2022-04-13 10:38
2021.003 Welsbach Mantle
Box 21

**Comment by eddierubeiz** [comment]
Done!

**Comment by apinkney0696** [comment]
Thanks so much! Sorry again for the hassle!
