### ISSUE TITLE
Rewrite the DZI orphan checker.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1656]
We have good reason to believe the DZI orphan checker is not doing its job right.

See #1653 for at least one example in which it did not detect DZI files that had belonged to 3 deleted assets.

~~A rewrite would hinge on our ability to get a list of top-level objects in the `scihist-digicoll-production-dzi` bucket, and nothing else.~~
~~These objects (all "folders", in this case) should line up, one to one, with assets that are supposed to have DZI tiles.~~

(Later edit: it turns out the existing setup works mostly fine; it was looking at the top two levels of the dzi directory but only reporting / deleting the dzi tiles *iff* it found an orphaned dzi manifest file first.)

We do **not** want to attempt a full traversal of the bucket, as there are **lots** of files down there. They must be detected, and deleted, in batches.

**Comment by eddierubeiz** [comment]
A variation on `aws s3 ls s3://scihist-digicoll-production-dzi` should work.

**Comment by jrochkind** [comment]
I _believe_ that `aws s3 ls` will actually need to retrieve every key for every object under the hood, and then it just only prints out the unique prefixes. 

So I believe that could take a while for our 25 million object bucket. If my calculations are correct, it will cost...  12.5 cents every time you do it. (Also my calculations may not be correct). 

There are ways to do the equivalent with ruby SDK API, it should be the same for either.
