### ISSUE TITLE
Create HLS derivatives

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1659]
* Bucket to hold HLS derivatives (will be publically accessible, per project specs considered okay)
* Maybe more infrasturucture in terraform
* Ruby code to fire off HLS creation in AWS MediaConvert (via ActiveEncode adapter)

* Once you fire off a job to MediaConvert, you have to poll to see when it finishes. ActiveEncode adapter is capable of polling by calling `reload` on it. But what's going to do the polling? 
   * While there is something built-in to ActiveEncode to persist state for in-progress jobs and use ActiveJob background jobs to poll -- we're going to do our own thing instead. The thing built into ActiveEncode isn't documented so is a bit hard to use -- and assumes you have an ActiveJob adapter that you can schedule future jobs for, which we don't currently!
   * We'll just make a table listing in progress jobs, with status. And probably an hourly cronjob that updates them all, and for ones that are finished then "installs" the HLS
* We'll probably add an `attr_json` to *Assets* for `video_hls_path` ro something -- or wait, can we actually put a shrine attachment inside the json attributes, without adding another field? That'd be convenient. We want to avoid having to fetch another associated table when displaying video files, if possible.  It's okay to add an attr_json field to Asset that will only be used for video assets. 
* Our video display code will display using MP4 if that's all that's available, but HLS if we have it. 
* Admin pages for video Assets will display whether an HLS exists, and maybe the in progress status of any in progress from our in-progress table. 

Wiki page doc'ing feature: https://sciencehistory.atlassian.net/l/c/MXeDCSjw

**Comment by jrochkind** [comment]
Once Chuck is back, let's be sure to discuss with @CHF-IT-Staff whether to create replicated bucket or other backups for this bucket. For now we're not doing so.

**Comment by jrochkind** [comment]
https://github.com/shrinerb/shrine/discussions/579

**Comment by jrochkind** [comment]
@eddierubeiz The current ActiveEncode code for using MediaConvert... just uses the AWS SDK withotu setting it up with an `aws_access_key_id` etc, so it will just pick those up from the environment in the default AWS ways. 

It won't actually use our `ScihistDigicoll::Env` for AWS account... but I think we've gotten our `ScihistDigicoll::Env` stuff consistent enough that it will arrive at the same answer anyway....

Is this ok? Or should I PR to ActiveEncode to allow configuration of a `aws_access_key_id` and `aws_secret_access_key`? Thoughts?

**Comment by eddierubeiz** [comment]
Bypassing our `env` code and just using default AWS credential setup is great. Possibly even preferable.

**Comment by jrochkind** [comment]
Now that HLS support is merged in: For the two production videos that already existed, queued up HLS creation. 

In a heroku console:


    CreateHlsVideoJob.perform_later(Asset.find_by_friendlier_id("9j8ug8s"))
    CreateHlsVideoJob.perform_later(Asset.find_by_friendlier_id("o0fdcpc"))
