### ISSUE TITLE
More work on German and English searching.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1667]
We currently have no way of guessing the language of any given search phrase.

Now that #1336 is in production, an English search (e.g. `potato`)  can match works that are exclusively in German: (e.g. on by matching `Tat` "action").

Good news: these extra matches are usually at the bottom of the search results (as our  "full text" matches rank relatively low). Bad news: we are concerned that they are crowding out legitimate English matches in the oral history transcript or other full-text fields -- also at the bottom of the search results. We'd like to examine some of the tradeoffs we have in front of us:

- Look at a sampling of real-life English searches and estimate how bad the problem is in practice;
- Find out what our peers have done, looking at both indexing tweaks and UI solutions;
- Consider tweaking or scaling back German indexing in some way;
- Consider an attempt to guess the language of search phrases;
- make/let the user choose a switch saying if they are intending to search in German or English
- Consider different matching behavior depending on where the user is searching: we assume the Bredig collection is where a user is most likely to *want* German matches;
- relevance rank German-configured-field matches really really low so they are always below English matches
- Last but not least, consider rolling back German indexing to the status quo ante.

**Comment by jrochkind** [comment]
This particular problem resolved by #1934, with more work ongoing.
