### ISSUE TITLE
Document the effects of the change to block robots from downloading originals.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1668]
Following up on  #1615 and #1626: we think we are saving money, but it's time to try to pin down how much.
- Analyze the detailed s3 logs we created
- Look at 2 or 3 weeks of AWS cost explorer logs for the production originals buckets and compare costs before and after the switch (April 11th).

**Comment by jrochkind** [comment]
If I take a look at logs just for a sanity check... search papertrail for `app/web /downloads/orig/` I do see plenty of orig downloads, mostly by bots -- a brief scan shows most of them of  `/downloads/orig/pdf`, so that's a good sign! 

Hmm, actually I do still see plenty of `app/web /downloads/orig/image` though. 

Some of the ones I'm seeing claim non-bot user-agents, which is also a good sign.  Either they are lying about their user-agent, or these are real users doing downloads? No great way to tell the difference. (we could try to guess from IP addresses looking suspicious). 

Some of the ones I'm seeing are... still "Applebot".  A LOT of them actually. Maybe Applebot hasn't gotten the message yet... or  doesn't understand our robots.txt somehow?  Confirmed our [live robots.txt](https://digital.sciencehistory.org/robots.txt) does try to disallow /downloads/images that isn't /pdf.  Applebot docs seem to suggest it oughta be well-behaved: https://support.apple.com/en-us/HT204683. not sure why it does not seem to be following our robots.txt...

**Comment by jrochkind** [comment]
Verified that according to google our robots.txt ought to be doing what we want, using this tool https://www.google.com/webmasters/tools/robots-testing-tool

**Comment by jrochkind** [comment]
One story I found says:

> If you notice unusual AppleBot activity, you can reach Apple about it at Apple-NOC “at” apple.com.

We could try emailing them and be like why does applebot not respect our directives?

**Comment by eddierubeiz** [comment]
Bad news, unfortunately. Please take everything below with a grain of salt. I'm so disappointed I am doubting my calculations; hopefully I'm terribly, terribly wrong.

I am going to spend some time checking my work against subsets of the data and against the Papertrail logs.

The numbers below are really surprising to me because:
- The numbers overall are *remarkably* similar before and after the `robots.txt` change.
- All 3 of our main bot "customers" show no perceptible change in their behavior (having *one* badly behaved bot would be much better news)

The `Before` results are from Friday April 1, 15:00 UTC to Friday April 8th, 15:00 UTC
The `After` results are from Tuesday April 12, 14:00 UTC to Friday April 8th, 14:00 UTC
Dates above are accurate to within an hour.

The top 3 bots account for almost all the bot traffic (and cost).

|                      | GB   | $   | %   | GB   | $   | %   |
|----------------------|------|-----|-----|------|-----|-----|
|                      | Before   | Before   | Before   | After   | After   | After   |
| Total served         | 2151 | 194 |     | 2159 | 194 |     |
| Total served to bots | 917  | 83  |     | 922  | 83  |     |
| Percentage to bots   |      |     | 43% |      |     | 43% |
| Top 3 bots           |      |     |     |      |     |     |
| Applebot             | 667  | 60  |     | 670  | 60  |     |
| SemanticScholar      | 201  | 18  |     | 202  | 18  |     |
| Blexbot              | 49   | 4   |     | 49   | 4   |     |

**Comment by eddierubeiz** [comment]
First batch of results:

|                 | Before | Before | Before | After | After | After |
|-----------------|--------|--------|--------|-------|-------|-------|
|                 | GB     | $      | %      | GB    | $     | %     |
| Total           | 1254   | n/a  | 100%   | 1080  | n/a  | 100%  |
| Bot             | 737    | 66.4   | 59%    | 461   | 41.5  | 43%   |
| Other           | 516    | 46.5   | 41%    | 619   | 55.7  | 57%   |
| Applebot        | 448    | 40.3   | 36%    | 335   | 30.2  | 31%   |
| Blexbot         | 205    | 18.5   | 16%    | 25    | 2.2   | 2%    |
| SemanticScholar | 54     | 4.8    | 4%     | 101   | 9.1   | 9%    |

**Comment by eddierubeiz** [comment]
Notes re: the above data:
- The "Before" columns are from Friday, April 1 to Friday, April 8, starting and ending roughly at 15:00 UT
- The "After" columns are from Tuesday, April 12 to Tuesday, April 19, starting and ending roughly at 14:00 UT
- Dollar amounts assume 9 cents per GB out (not available for the total).

**Comment by eddierubeiz** [comment]
Semrush, Yandex, Googlebot and Googlebot Image, which accounted for a total of 54GB, or $4.8, or 4%  of our outbound S3 data, all disappeared from the top 20 user agents in the "after" data. This makes me wonder if we didn't wait long enough before starting our "after" sample.

**Comment by eddierubeiz** [comment]
Note: there are some, but not a lot, of recent hits for Applebot downloading original [images](https://my.papertrailapp.com/systems/scihist-digicoll-production/events?q=app%2Fweb+%2Fdownloads%2Forig%2Fimage+ua%3Dbot%3AApplebot)

Roughly 124 images since May 7th. That's certainly more than zero GB, but unlikely to be consistent with our pre-switch rate of 448 GB / week.

**Comment by eddierubeiz** [comment]
Bash script I used to turn the contents of the s3 logs into useable data:
```bash

BEFORE_FILE_SUBSET='files/2022-04-0[1-8].*'
AFTER_FILE_SUBSET='files/2022-04-1[2-9].*'
for FILE in `find files -regex $BEFORE_FILE_SUBSET`; do
   cat $FILE | while read LINE; do
      BYTES_SENT=`echo $LINE | cut -d ' ' -f 15`
      if [ "$BYTES_SENT" != '-' ]; then
         USER_AGENT=`echo $LINE | cut -d '"' -f 6`
         echo "\"$BYTES_SENT\",\"$USER_AGENT\"" >> before.txt
      fi
   done
done
for FILE in `find files -regex $AFTER_FILE_SUBSET`; do
   cat $FILE | while read LINE; do
      BYTES_SENT=`echo $LINE | cut -d ' ' -f 15`
      if [ "$BYTES_SENT" != '-' ]; then
         USER_AGENT=`echo $LINE | cut -d '"' -f 6`
         echo "\"$BYTES_SENT\",\"$USER_AGENT\"" >> after.txt
      fi
   done
done
```

**Comment by eddierubeiz** [comment]
Redid the same analysis with another weeklong batch of "after" statistics ending yesterday afternoon, June 2.
Better results. The $ figures are rough estimates, and don't really apply for the totals (which include calls that are not charged at the same rate.)

But we can conclude that the robots.txt is working nicely to prevent robots from downloading our originals.

|                 | Before | Before | Before | After | After | After |
|-----------------|--------|--------|--------|-------|-------|-------|
|                 | GB     | $      | %      | GB    | $     | %     |
|                 |        |        |        |       |       |       |
| Total           | 1254   | n/a  | 100%   | 1092  | n/a  | 100%  |
| Bot             | 737    | 66.4   | 59%    | 9     | 0.8   | 1%    |
| Other           | 516    | 46.5   | 41%    | 1082  | 97.4  | 99%   |
| Applebot        | 448    | 40.3   | 36%    | 9     | 0.8   | 1%    |
| Blexbot         | 205    | 18.5   | 16%    | 0     | 0.0   | 0%    |
| SemanticScholar | 54     | 4.8    | 4%     | 0     | 0.0   | 0%    |

**Comment by eddierubeiz** [comment]
I think it's safe to say our monthly s3 costs have gone down significantly due to the change in robots.txt (which, again, took place roughly in the middle of April.)

| Dec 2021 | Jan 2022 | Feb 2022 | Mar 2022 | Apr 2022 | May 2022 |
|----------|----------|----------|----------|----------|----------|
| $592.04   | $578.46   | $577.81   | $671.53   | $449.71   | $312.40   |

**Comment by eddierubeiz** [comment]
Here's a graph of the cost per day of all s3 buckets(orange) and just our originals bucket (blue). It's a bumpy graph, but you can definitely see the average cost going down after mid-April.
![Cost per day](https://user-images.githubusercontent.com/94723/171902135-9097159d-425c-4e86-87c9-a7c07fa0a5cf.png)
