### ISSUE TITLE
Swap Hirefire and Honeybadger credentials

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1681]
In response to the email mail from Heroku this morning, go through the following list and update auth info if needed.

```
=== Drains
https://logdrain.hirefire.io
https://logplex.honeybadger.io/heroku/v1
=== Add-on Drains
papertrail:forsta
```
(somewhat redacted)

**Comment by eddierubeiz** [comment]
For the purposes of this ticket we're only looking at HireFire and Honeybadger.

**Comment by eddierubeiz** [comment]
Oh, the email claims staging isn't affected, but we should consider swapping credentials anyway.

**Comment by eddierubeiz** [comment]
Quoting the email below:

At Salesforce, we understand that the confidentiality, integrity, and availability of your data are vital to your business, and we take the protection of your data very seriously. We value transparency and wanted to notify you that, to ensure the protection of your data and in response to [this incident](https://status.heroku.com/incidents/2413), we have identified a subset of your applications that have custom (non-add-on-provider) log drains configured.

We recommend updating and refreshing the credentials used with those log drains as soon as possible.

NOTE: This action is only required for log drains that have been manually added to your application.

No action is required for logging performed by Heroku logging add-ons provisioned through the Heroku Elements Marketplace.

Please follow the instructions [here](https://devcenter.heroku.com/articles/log-drains) to refresh your apps below:

- scihist-digicoll-production
- scihist-digicoll-production

**Comment by eddierubeiz** [comment]
mrrooijen at Hirefire was able to help us out:
```
Heroku is referring to the logdrain id. You'll want to remove and re-add the drain to generate a new drain id.
Do the following:
1. $ heroku drains:remove https://logdrain.hirefire.io/
2. $ heroku drains:add https://logdrain.hirefire.io/
3. $ heroku drains (copy the new drain id)
4. Login to the manager.hirefire.io, navigate to the settings of the application in question, and replace the old drain id with the new one.
```

**Comment by eddierubeiz** [comment]
For Honeybadger it was:

- https://app.honeybadger.io/  ➡️  settings ➡️  API Keys
- Generate a new API key
And then:
```
heroku drains:remove  'https://logplex.honeybadger.io/heroku/v1?api_key=[OLD_API_KEY]&env=production'
heroku drains:add     'https://logplex.honeybadger.io/heroku/v1?api_key=[NEW_API_KEY]&env=production'
```

**Comment by eddierubeiz** [comment]
Dank u wel, @mrrooijen !

**Comment by mrrooijen** [comment]
👍
