### ISSUE TITLE
Reconsider HLS levels/logic

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1693]
Upon double-checking HLS production, I have realized that the HLS adaptive bitrate levels and logic don't work out as well for us as I thought. I was getting height and width confused!

We based our HLS preset levels on configuration [found in avalon](https://github.com/avalonmediasystem/avalon/blob/366ae85557b30ba61fc57ff60cb749020495363e/config/ffmpeg_presets.yml).  (I [asked on Slack](https://samvera.slack.com/archives/C1C3C4F5L/p1652279677336029) if anyone knew how Avalon came up with these, have not yet had a response). 

* low == 480 pixels high, 500 kbps
* medium == 720 pixels high, 1.5 Mbps
* high == 1080 pixels high, 3 Mbps

Avalon -- I think -- creates ALL these variants for any input, even if it would be "upsizing".  So you might have an input video that's 320 pixels high and 500 kbps, but Avalon will still create the 1080p 3Mbps variant, even though it's kind of not needed. 

We tried to do one better, and only create variants if they are needed, based on pixel size. So unless the video is at least 720 pixels high (or a bit smaller maybe), we won't create the "medium" variant. 

But our sample video ingested copies are all 480 pixels high, and around 1000-1500 kbps.  This means our logic currently *only* creates "low" variant, because it says, oh, this is only 480 high, we don't need the 720 or the 1080 one.  But the low variant is 500 kbps, so it has significantly reduced the quality. So our HLS view offers only a reduced quality view. 

This isn't great -- I got confused and thought it wouldn't happen becuase our videos are 720 pixels _wide_, I got height and width confused!

### Change our levels?

Those bitrates are a bit low for other guidance I find on the web, such as [here](https://www.dacast.com/blog/encoder-settings-hls-live-streaming/) or [here](https://www.wowza.com/docs/how-to-encode-source-video-for-wowza-video#recommended-encoding-presets3).

So we could keep those three levels, but just bump up the bitrates:

* low == 480 pixel high, 1500 kbps
* medium == 720 pixel high, 2500 kbps
* high == 1080 pixels high, 4200 kbps

Or we could start with that and add in one more extra-low one to still meet people on slow networks that might want 500kbps  

* extra low = 240 pixel high, 500 kbps. [This is hagley's standard, btw]
* low == 480 pixel high, 1500 kbps
* medium == 720 pixel high, 2500 kbps
* high == 1080 pixels high, 4200 kbps

## Change our logic?

And/or we could also change our logic for deciding what bitrate variants to create. 

We could do like avalon and create ALL of them for ANY input -- so if you had a 480 1.5Mbps input, it would (under our original levels) still make a 720 1.5 Mbps variant -- it would be "upscaling", but you'd at least get a variant at 1.5 Mbps that isn't losing quality. 

Or we could do slightly better and still use logic to decide what variants to create, but take both size and bitrate into account. So for our original levels, if the video is over 480 pixels high **or** over 500kbps, then you definitely need a 'medium', not just a 'low'.  And if it's over 720 OR 1.5 Mbps, then you definitely need a 'high' too. 

Or we could combine both of these change the levels and the logic. I think I am inclined to do that maybe, move to the 4 levels with "extra low", AND change the logic to be more willing to make larger variants. 

Ref #1659

## Background: Various HLS bitrate examples or advice we could find

* https://github.com/avalonmediasystem/avalon/blob/366ae85557b30ba61fc57ff60cb749020495363e/config/ffmpeg_presets.yml
* https://github.com/avalonmediasystem/avalon/blob/master/config/elastic_transcoder_presets.yml
* https://www.dacast.com/blog/encoder-settings-hls-live-streaming/
* https://www.wowza.com/docs/how-to-encode-source-video-for-wowza-video#recommended-encoding-presets3
* https://developer.android.com/guide/topics/media/media-formats#video-encoding
* Hagley told us they aim for very small, "320x240 and .500 Mbps"
* Northwestern told us theirs were not super considered, but were 
  * large: wifi 1920x1080, 16:9, 8500kbps [HD]
  * medium: 1280x720 16:9 5000 [HD]
  * low: 960x540 16:9 3500kbps [SD]
* Chrome Dev Tools throttler has:
  * "slow 3g"  at 400 kbps
  * "fast 3g" at 1.5Mbps
  * source: * https://stackoverflow.com/a/61384041/307106
* Our existing examples from vendors were kind of all over the place, but included:
     * 480p at 2000 - 2200 kbps
     * HD 1440p at 10000kbps
     * Sarah's sample 480p access copies tended to be 1000-1500kbps

**Comment by archivistsarah** [comment]
Your four presets sound great -- I'm fine going with those.

But just to clarify: if a video is 483 pixels high, that video will will get extra low, low, and medium HLS files? But if it's 473 it only gets extra low and low?

And just so this isn't a surprise -- this is going to result in us having a lot of in-house generated files that only get extra low and low HLS versions because the access versions/mp4s are fewer than 480 pixels high. The preservation/master copy may be 480 or over (as that's the standard for NTSC), but in most cases I'm editing out (expected & normal but undesirable for access) overscan lines from the bottom of the image, so we're always losing a few pixels from the height.

**Comment by jrochkind** [comment]
I added documentation of ALL the advice and examples I had in my notes too, to refer back to later. 

Let's see, if a video is 483, it'll get extra low, low, and medium -- since 483 is higher than low (480), it gets a medium. It's not higher than medium, so it stops there. 

If a video is 473 it only gets extra low and low, yep. It's higher than extra low, so it gets a low; but it's not higher than low, so it stops there at low. 

So, yes! 

> this is going to result in us having a lot of in-house generated files that only get extra low and low HLS versions because the access versions/mp4s are fewer than 480 pixels high

OK, I hadn't totally realized this -- hadn't heard your final decision about the "overscan", but I think it works wtih this decision. If it started out 480, but you edit out a few lines so it goes down to say 476 -- it'll still get a 480 copy!  Which we'd want it to, we wouldn't want editing out a few lies to mean it *only* gets an extra-low 320.  

So this is closer to what we want. 

It does still mean that if you edit down from 480 to 475... our HLS process will bump it up to 480 again by upscaling... but at a somewhat odd aspect ratio.  

The odd aspect ratio was guaranteed, that's what you expect if you're removing a few vertical lines from a standard aspect ratio, an odd aspect ratio necessarily results. But that our HLS process then upscales it to 480 again is... not necessarily ideal?  

This honestly seems to be a reason to cover up the overscan lines with black instead of just deleting them, if I remember right you were considering between those two options. Then the video would remain at 480, a standard resolution, and the HLS process wouldn't have to scale it up to 480. 

However, I realize there may be other reasons to make the choice you did. This stuff is all very confusing to me, where lots of choices end up interacting with each other in odd ways! It's possible nobody will really notice no matter what we do.

**Comment by archivistsarah** [comment]
Hm, ok this is demonstrating how little I understand about the HLS process. There's no way to bump up the bitrate but keep the original resolution (or just the original aspect ratio) of the ingested file?

**Comment by jrochkind** [comment]
I'm not sure I understand how I'd write logic like that, what the rules would be. 

The way the code we're using works, we have to decide certain fixed "presets" for HLS.  That's the way every other software package I know does it, and the way the ActiveEncode library we're using works. As opposed to deciding what sorts of things to make entirely on the fly, they are from presets. 

The presets defintiely need to have a fixed bitrate -- that's kind of the point of HLS adaptive bitrate.  you never _increase_ the bitrate from the "source copy", you are just making alternate copies with decreased bitrate to support people on slower networks. 

Right now our presets also have fixed pixel heights. (But the pixel width is variable, will just end up based on the aspect ratio). **So we are already keeping the original aspect ratio of the ingested file.** We just aren't keeping the original *size* of the original file -- we are decreasing it to get a smaller video that can more easily have a smaller bitrate, to make the various copies to serve people on slower networks. Or in some cases, we're _increasing_ it, if the next smallest preset would be a big reduction, we don't want to only give people the big reduction, so we jump up to the next preset too. 

I guess you could have presets that instead always left the height and width exactly as the source file was, but only reduced the bitrate.  However, if you submit a large 720p file at like 10Mbps, I think it probably doesn't make sense to reduce it's bitrate to 500kbps while still keeping it at 720p -- every example I have seen also reduces it's pixel size, because, I think, you can't really do 720p at 500kbps, that's too low a bitrate for 720p, you need to make the width/height smaller too. 

I'm not sure if I'm explaining it clearly or not.
