### ISSUE TITLE
"orphan" file checker for video derivatives bucket

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1695]
This is potentially kind of.a pain due to the multi-file nature of HLS. 

Also note that we use cloudfront CDN for video derivatives bucket, so the hostname you get from calling `file.url` or `file.public_url` doesn't necessarily reveal the S3 bucket. Not sure if this matters for any logic or not (maybe only for the link-to-AWS-console logic, which isn't a big deal), but beware. 

Ref #1659

**Comment by eddierubeiz** [comment]
See also #1656. We may wish to tackle these two ornery but worthwhile projects as a pair.
