### ISSUE TITLE
Pull Data for CLIR Year One Reporting

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1698]
Michelle contacted me about required reporting for Year One of the CLIR grant, which is due May 31st. Michelle will be writing the narrative report and Suzanne will do the financial, but it appears that they also require a rather intensive manifest of all digital content created for this grant. Please see attached. Among other items, they want the file name, URL, and checksum for every file created for this grant. More guidelines are below:

> Provide the information requested in both sheet 1, "GRANT DATA," and sheet 2, "MANIFEST DATA." CLIR asks you to provide either:
> 
> 1. all the filenames and URLs for all unique access files produced through your grant, or
> 
> 2. a representative sampling of filenames and URLs for unique access files produced through your grant that includes information for at least 25 files for each month of project work. For example, you should provide information about a minimum of 300 files for a 12-month project, 600 files for a 24-month project, or 900 files for a 36-month project.
> 
> Choose the option that will be the most convenient for your team.
> 
> Provide the full filename, including the file extension(.jpg, .jpeg, .tiff, .mp3, .mp4, etc.) , and (in Step 3) the full URL to the location of that file. Note that this URL may be different from the URL for the related metadata for the file. CLIR strongly prefers that you provide a permanent link to the file itself if one is available. If a permanent link to the digitized item is not available, you may provide a permanent URL to the metadata record.
> 
> Finally, enter the date each file was last checked for availability and integrity. Do not change the column order or field headings in sheet 2 or delete any columns

[Copy of CLIR_Digitization_File_Manifest_Template_2020.xlsx](https://github.com/sciencehistory/scihist_digicoll/files/8700220/Copy.of.CLIR_Digitization_File_Manifest_Template_2020.xlsx)

Would you guys be able to automatically gather at least some of this data? We can discuss at the meeting later. Pushing to high priority.

**Comment by jrochkind** [comment]
I think so. Can you help me spec out what we need more though?

I forget what "CLIR Grant" applies to -- is this everything in Bredig, and nothing else?  Or remind me what the criteria are for identifying the relevant files. 

"Full URL to the location of the file" means to download the actual file?  They don't want the URL for the Work show/metadata included at all? 

Can you specify the columns that should exist in the output, as you understand it? 

Also, in general, with this kind of thing -- more advance notice would have been preferable, in the future, where possible.

**Comment by jrochkind** [comment]
@apinkney0696 there are currently 2 unpublished Assets in Bredig. https://digital.sciencehistory.org/collections/qfih5hl?f%5Bpublished_bsi%5D%5B%5D=false

Would you like me to include them in the report, or leave them out of the report?

**Comment by apinkney0696** [comment]
Oh that's right, I'm waiting to hear from our translator Gudrun to see if she can decipher who the signatures belong to so I can bulk up their metadata a bit. Those two can be left out in this report, please. Thank you thank you!

**Comment by jrochkind** [comment]
@apinkney0696 I think this should work, let me know if it doesn't! 

[clir_report.csv](https://github.com/sciencehistory/scihist_digicoll/files/8701827/clir_report.csv)

**Comment by jrochkind** [comment]
oops, second try, the first one had some noise at the top. 

@apinkney0696 , I think this should work, let me know if it doesn't or anything needs to be different! 

[clir_report.csv](https://github.com/sciencehistory/scihist_digicoll/files/8701835/clir_report.csv)

**Comment by apinkney0696** [comment]
Thank you, Jonathan! This looks perfect. I don't think there is anything else needed. What would you recommend I put for the preservation file location? I am not sure what they mean by that... they just say "provide information about where the file is stored." Where do we save our backups? S3?

**Comment by jrochkind** [comment]
I'm sorry, I didn't understand the instructions either, I have no idea! You might have to ask them what they mean or Michelle what she thinks?

I guess we do have that backup location on another S3 bucket... I'm not sure what to enter for that exactly either. We also have an additional extra copy stored on tapes on-premises.

**Comment by apinkney0696** [comment]
Okay, no worries at all! Thanks! I'll check in with Michelle about it.
