### ISSUE TITLE
auto-complete subject entry

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#170]
Not yet implemented in new app like it is in chf_sufia, is needed.

**Comment by jrochkind** [comment]
## Front-end

I was having trouble finding a general purpose JS auto-complete/typeahead/autosuggest library that wasn't for react or vue. Ideally we'd want one that didn't depend on JQuery either. 

Having trouble finding a good one that is maintained. 

Some possibilities:

https://github.com/itb2k13/pughound-js

https://github.com/devbridge/jQuery-Autocomplete

Or do we write it completely ourselves, maybe using Bootstrap dropdown as a basic starting point? But Bootstrap dropdown isn't meant to connect to a text input exactly. 

# On the back-end 

Whatever is supplying suggestions to the auto-complete -- will probably still use the "questioning_authority" gem (`qa`) which can provide suggestions from a number of vocabularly services, including the ones we currently use, mostly "FAST".

**Comment by jrochkind** [comment]
Adding FAST autocomplete to:

* place
* subject
* creator

Those all seem to have FAST autocomplete in original chf_sufia (although that doesn't always match what the hint instructions we wrote SAY will be autocompleted, creator implies VIAF for instance. But that is pre-existing mismatch in chf_sufia). 

In addition to Language autocomplete (from local list of languages), tracked in #249 , does this get all the fields that should be autocompleting, do you know if am I missing any?

@yonyitz @HKativa

**Comment by yonyitz** [comment]
I just double-checked the metadata guidelines and you are correct those are the fields with the autocomplete feature.  Thanks!
