### ISSUE TITLE
Oral History Citations

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1701]
@rachellane12 @dcaruso-scihist, I'm going to do my best to summarize your request here, please chime in if I inaccurately describe the goals!

The COH is adopting a new standard for citing oral histories inspired by [Baylor University](https://www.baylor.edu/content/services/document.php/66439.pdf). For example:

Current Citation for Carl Djerassi interview: 

> Carl Djerassi, interviewed by Arnold Thackray and Sturchio, Jeffrey L. (Jeffrey Louis) in Stanford University on July 31, 1985. Philadelphia: Science History Institute, n.d. Oral History Transcript 0017. https://digital.sciencehistory.org/works/hm50ts561.

Proposed Citation for Carl Djerassi interview:

> Carl Djerassi, interview by Jeffrey Sturchio and Arnold Thackray at Stanford University, Stanford, California, 31 July 1985. Format: digital transcript (Philadelphia: Chemical Heritage Foundation, Oral History # 0017). Available at: https://digital.sciencehistory.org/works/hm50ts561 (accessed on DATE).
> 
> Carl Djerassi, interview by Jeffrey Sturchio and Arnold Thackray at Stanford University, Stanford, California, 31 July 1985. Format: digital recording (Philadelphia: Chemical Heritage Foundation, Oral History # 0017). Available at: https://digital.sciencehistory.org/works/hm50ts561 (accessed on DATE): BEGINNING TIME STAMP - ENDING TIME STAMP.

The significant differences here are the two separate citations for the transcript and audio and the individual style differences of the citation formats. The goal is to indicate to users that audio and transcripts require different citations and to suggest the preferred citation format. What changes could be made to achieve this? Here are some ideas to get us started:

- Create a new automatic citation generator with manual logic by creating a different code path unique to Oral Histories
- Build an interface for OH staff to manually input the citations for each oral history
- Replace the auto-generated citations on OH pages with a suggested citation format outline
- Remove the citations completely, users must view the transcript for the citation
- Do nothing, there is a disclaimer for errors under the citation already. OH staff could recommend citation guidelines when responding to requests.

Other considerations:
- Do users use our citation suggestions? (e.g. how much work is it really worth?)
- Edge cases: want to avoid too many exceptions and tweaking to specific cases
- Zotero and EndNote: we can't control how those citations are formatted
- Everywhere else in the DC we use Chicago-style citations

**Comment by apinkney0696** [comment]
From @dcaruso-scihist:

> Maybe the best (easiest?) option would be to replace what is currently there with a link to a static page on the website with our recommended citation styles? Or would that require new, extensive coding? 

We already have an FAQ question that says "How do I cite an image?" [here](https://digital.sciencehistory.org/faq). What if we added another FAQ question that says "How do I cite an oral history interview?" and write out the style guide as the answer? Would it be complicated to replace the automatic citation section of the oral history record pages with a link to that FAQ question @jrochkind? Do you feel like that's a logical solution?

**Comment by eddierubeiz** [comment]
(I'm done with Staging, by the way -- feel free to deploy to it at any time today.)

**Comment by apinkney0696** [comment]
This looks great and is ready to be pushed to production. 

In addition, we decided to add the visibility of the identifier field to be visible on only oral history pages. The "Oral history number" field should appear beneath the Collection and above the Physical container fields. Include leading zeros in the number.

Thanks!
