### ISSUE TITLE
batch edit

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#171]
Not yet implemented in new app, is a feature that exists in chf_sufia, has been asked for in new app. 

It may not be easy to implement *exactly* like it was in chf_sufia (the admin UI's it's based around have changed), and not entirely sure if the UI in chf_sufia was actually beloved or easy to use for needed functions. So needs a bit more user-investigation to understand use case/needs, and figure out the cheapest way to provide for them.

**Comment by jrochkind** [comment]
After investigating what @yonyitz needs to do with batch edit, determined that it makes a lot more sense to do the searching (for things to 'stage' for batch edit) from the public front-end, with full solr-based search functionality supported there. 

So this is blocked by #432 as a pre-requisite.

**Comment by jrochkind** [comment]
@yonyitz Consider multi-element/repeatable fields like "subject". 

If you are "batch editing", and specify some subjects in the "batch edit", but the record(s) already had subjects (possibly not all the same) -- should the subjects you specify be _added_ to any existing subjects on the record, or should they *replace* any existing (diverse) subjects on the record?

Or do you need a control to decide which, on a case-by-case basis?

I'm not sure what the chf_sufia feature did, I don't totally understand it.

**Comment by yonyitz** [comment]
My recollection is the current app only allows for adding new subject headings and not replacing.  So let's keep it as-is and see if we find we need a replace feature, if that sounds good!

**Comment by jrochkind** [comment]
OK, that will apply to all "multi-valued" fields, not just subject. Not sure how many fields you use for batch edit, but all (or nearly all) of them were in chf_sufia, and it seems to be that any of them hypothetically could be used, so they're all going to be there.

**Comment by yonyitz** [comment]
That sounds great.  Thanks!

**Comment by jrochkind** [comment]
OK, what chf_sufia appears to have been doing is stranger than this. 

chf_sufia actually does seem to _overwrite any existing_ values in batch edit. After you do a batch edit, if you edited subjects via the batch edit -- all Works in the batch will have exactly the same subjects. If they differed before, they no longer differ after the batch edit. 

But chf_sufia _preloads_ the values to _any_ value that appeared in _any_ in the batch. So if you were batch editing three works, each with a different subject (call it "A", "B", and "C") -- the chf_sufia batch_edit form will show you three subjects "A", "B", and "C". If you press 'save' without editing it, all three works will now have three subjects, each will have A, B, and C. 

If you edit it to, say just have A, all three Works will have the same one subject, only A. Etc. 

I can totally see this not being what all users expected or knew they were doing or wanted though. (and the listing of the combination of any subject that appeared on any record in batch -- is a performance problem if you have large batches. Although can maybe done if needed). 

So unless I hear otherwise, I will continue with plan to make batch edit function _add_ to values, for multi-valued fields, rather than _replacing_ them. 

This does mean there is no way to _remove_ values using 'batch edit', only add values. For multi-valued fields. 

Single-valued (non-repeatable) fields will still have their values _replaced_ by what's entered in batch-edit, cause that's the only thing that can be done.

**Comment by yonyitz** [comment]
Thanks, Jonathan!  That all sounds good to me!
