### ISSUE TITLE
BrowseEverything error

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1737]
Error at:
https://app.honeybadger.io/projects/58989/faults/85794580

First PR that reproduces this error is https://github.com/sciencehistory/scihist_digicoll/pull/1712 . The commit is dc4142fde.

To reproduce in staging:
Create a new work, enter minimal metadata, click "Create new work".
At https://staging-digital.sciencehistory.org/admin/works/[ID]/ingest, click "Add from cloud".
S3 file list doesn't come up; instead browse-everything modal background div covers everything else.

**Comment by eddierubeiz** [comment]
First thing to try is downgrade BE to a less recent version to see if that fixes it.

**Comment by eddierubeiz** [comment]
This wasn't the problem -- BE has been at its current version for over a year. Used git-bisect to figure out the problem -- whatever it is -- originates with our upgrade to Ruby 3.1 last week.

**Comment by eddierubeiz** [comment]
We're on the same page. I'm becoming increasingly convinced that this is just about browse_everything and Ruby 3.1 . For one thing, If you *only* revert `.ruby-version` back to `3.0.4` and leave `Gemfile` exactly as it is in `master`, everything looks good. I'm considering doing that in this PR (and erasing some of these commits in the process). Seems more tractable.

And yes. I believe there is an easy test we can add to detect this bug.

**Comment by jrochkind** [comment]
Reported to browse-everything https://github.com/samvera/browse-everything/issues/389
