### ISSUE TITLE
Fix HoneyBadger API key for staging

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1739]
API key is invalid, so HB is not reporting errors in staging to either email or Slack. 

From Papertrail:

```
Jun 02 16:36:32 app/web.1 INFO: ** [Honeybadger] Reporting error id=e5dbea03-bcba-46d9-b44c-2a254dad0972 level=1 pid=8
Jun 02 16:36:32 app/web.1 WARN: ** [Honeybadger] Error report failed: API key is invalid. id=e5dbea03-bcba-46d9-b44c-2a254dad0972 code=403 level=2 pid=8
```

**Comment by eddierubeiz** [comment]
See also ref #1681

**Comment by eddierubeiz** [comment]
Created a new API key and then ran the following for the staging heroku app:
```
heroku drains:add 'https://logplex.honeybadger.io/heroku/v1?api_key=NEW_KEY&env=staging'
```

You can run `heroku drains` on staging to see the new drain.

**Comment by eddierubeiz** [comment]
Also updated HONEYBADGER_API_KEY accordingly in the Heroku staging settings. (It was still set to the old API key I deleted a month ago; oops.)

**Comment by jrochkind** [comment]
Awesome, thanks. 

We aren't getting deploy notifications to slack for staging. They nromally work by notifying honeybadger of the deploy, which it both tracks and slack notifies us of. 

There may be an additional place API key needs to be updated for the HN deploy notifications. 

Becuase, yeah, the HB list of deployments doesn't include any staging deploys either. https://app.honeybadger.io/projects/58989/deploys

HB docs on heroku deployment tracking: https://docs.honeybadger.io/guides/heroku/#heroku-deployment-tracking

Yeah, it looks like there's a deploy hook set there, which may also need to be reset with new API key?

**Comment by eddierubeiz** [comment]
HB is not aware of any deployments to heroku staging in the past month or so:
https://app.honeybadger.io/projects/58989/deploys?environment=heroku-staging&project_id=58989

**Comment by eddierubeiz** [comment]
Deployments noted here:
https://app.honeybadger.io/projects/58989/deploys?start=2020-01-01&stop=2022-06-08&environment=production

But not any of these places:
https://app.honeybadger.io/projects/58989/deploys?start=2020-01-01&stop=2022-06-08&environment=staging
https://app.honeybadger.io/projects/58989/deploys?start=2020-01-01&stop=2022-06-08&environment=heroku-staging
https://app.honeybadger.io/projects/58989/deploys?start=2020-01-01&stop=2022-06-08&environment=heroku-production

**Comment by eddierubeiz** [comment]
Created the new hook:
```
heroku addons:create deployhooks:http --url="https://api.honeybadger.io/v1/deploys?deploy[local_username]={{user}}&deploy[revision]={{head}}&deploy[repository]=git@github.com/username/projectname&deploy[environment]=staging&api_key=asdf" --app scihist-digicoll-staging
```

Noticed the old hook:
```
heroku addons:info deployhooks --app scihist-digicoll-staging
 ▸    Ambiguous identifier; multiple matching add-ons found: deployhooks-vertical-23161, deployhooks-round-44007.
```

Removed the old hook:
```
heroku addons:destroy deployhooks-vertical-23161 --app scihist-digicoll-staging
```
