### ISSUE TITLE
ONE video is not playing in Firefox

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1741]
I shared our video content with other library tech colleagues, one found a video that does not play in Firefox:

https://digital.sciencehistory.org/works/x8peubh

I reproduced on MacOS Firefox:

![Screen Shot 2022-06-06 at 12 54 01 PM](https://user-images.githubusercontent.com/149304/172208146-23975310-f9e0-4570-bed9-fb551c6d1092.png)

I tested the other 12 videos -- they all work fine on Firefox!

I have no idea what would be different about this one video, since it should be using HLS derivatives produced via an identical automated process. It is a mystery. Apparently video is hard. 

First thing to do might just be to re-create the HLS derivatives. If it still isnt' working, then we have to do hard debugging.

**Comment by jrochkind** [comment]
Worse, Edsu tells us:

> [edsu](https://app.slack.com/team/U0CAHP25R)  [1 minute ago](https://code4lib.slack.com/archives/C0B3ELJQM/p1654535333188999?thread_ts=1654526752.322269&cid=C0B3ELJQM)
Wild, I just cleared the cookies and site data for [digital.sciencehistory.org](http://digital.sciencehistory.org/) and it works now.

Since I can currently reproduce, I don't really want ot clear my own cookies, cause then I won't be able to anymore!

**Comment by jrochkind** [comment]
OK, I did not clear cookies but DID do a command-shift-R hard-refresh… no longer reproduces for me either. So yeah, clearly a cache issue of some kind.

May be hard to debug beyond that since no longer reproduces for me. Hope it never happens again?

**Comment by archivistsarah** [comment]
I can't think of a thing about this file that would have caused this (vendor generated mp4, so I haven't touched it much)! But I'll flag it in my notes, too, in case it happens again.

**Comment by jrochkind** [comment]
@archivistsarah I think it's unlikely it was anything about this file, or anything else you did. 

 I think it was something weird in the tech stack. 

@eddierubeiz Corruption in the CloudFront cache, somehow? Which is disturbing. 

Can't currently reproduce, so I'm going to go ahead and close this.

**Comment by eddierubeiz** [comment]
I'm getting a sense that CDN caching drama is just something we are going to have to live with. As long as I have it on hand as a possible explanation for this sort of behavior it won't drive me crazy :) .
