### ISSUE TITLE
Check that backups and fixity checks are OK.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1752]
The scheduled rake tasks that were supposed to run in the early morning hours of Thursday were not called. It looks like this was due to a glitch that won't reoccur tomorrow morning.

If the same rake tasks run tomorrow morning, it's OK to do nothing.

If they don't we will need to investigate.

**Comment by jrochkind** [comment]
[Honeybadger](https://app.slack.com/team/BFALFNZ62)APP  [5:02 AM](https://315chestnut.slack.com/archives/G6UC83ADV/p1655370125344439)
[scihist_digicoll] MISSING: [Digital collections backup](https://app.honeybadger.io/projects/58989/check_ins) hasn't checked in for 1 day
Project
scihist_digicoll






[Honeybadger](https://app.slack.com/team/BFALFNZ62)APP  [9:07 AM](https://315chestnut.slack.com/archives/G6UC83ADV/p1655384826615169)
[scihist_digicoll] MISSING: [Digital collections fixity check](https://app.honeybadger.io/projects/58989/check_ins) hasn't checked in for 1 day
Project
scihist_digicoll

**Comment by jrochkind** [comment]
Quite possibly due to this advertised heroku outage, and will be back tonight. 

https://status.heroku.com/incidents/2437

**Comment by eddierubeiz** [comment]
Tasks ran early this morning; it was indeed just a glitch.
