### ISSUE TITLE
Store `hls_playlist_file_data` keys and values properly

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1757]
1) Currently, hls_playlist_file_data key and value are escaped and stored as a string:

```
select distinct jsonb_typeof(json_attributes->'hls_playlist_file_data')
    from kithe_models
    where kithe_model_type = 2
    and file_data ->> 'storage' = 'video_store';
```
will return "string" and null.

This blog post describes the problem: https://dev.to/mrmurphy/so-you-put-an-escaped-string-into-a-json-column-2n67 .

A sample value for this string, as currently stored in the DB would be:
```
 "{\"id\":\"hls/fd660b63-6603-4584-ad7b-1263ecf2b53b/426eac8d0062d9384bd1dfa2588e1991/hls.m3u8\",\"storage\":\"video_derivatives\",\"metadata\":{}}"
```

2) Say you're interested in the `hls/fd660b63-6603-4584-ad7b-1263ecf2b53b/426eac8d0062d9384bd1dfa2588e1991/hls.m3u8`  part of the string. To get at it you need to parse the string inside the DB using an ugly hack like:
```
select (json_attributes->'hls_playlist_file_data' #>> '{}')::jsonb->>'id'from kithe_models where id='SOME_ID';
```
3) Of course, we'd rather not; what we should really do is store the string as jsonb, just like the rest of `json_attributes`.

This ticket would cover the work of:

- editing the code that stores info about video derivatives so that the data is stored as `jsonb`
- writing a migration that converts the (currently very few) existing video deriv records in the DB to the new format
- editing the code in method `get_hls_derivs_from_db` in file  app/services/orphan_s3_video_derivatives.rb (see ref #1748 ) to simplify it, once the hack is no longer required.

**Comment by jrochkind** [comment]
It's already being stored in a jsonb column -- the problem is that it's being escaped first!

I think I may know why and how to fix it; the migration will be trickier, yeah!
