### ISSUE TITLE
upgrade postgres to pg 14

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1764]
We currently accidentally have different pg versions in staging and prod:  13 in staging and 12 in prod. 

Postgres 14.x is the latest supported by heroku. We should upgrade both prod and staging to PG 14. 

This may involve some downtime. 

https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases

**Comment by eddierubeiz** [comment]
```heroku pg:copy scihist-digicoll-production::DATABASE_URL DATABASE_URL -a scihist-digicoll-staging  --confirm scihist-digicoll-staging``` is currently failing, which may well be connected to this issue.

**Comment by jrochkind** [comment]
Let's actually prioritize this... getting to latest postgres may avoid the need to install pg extension for UUID, which is what gets is in trouble at #1817. 

If we can get to latest supported pg, we may be able to fix our `schema.rb` file to no longer try to enable the `pgcrypto` extension, which may avoid the issue at #1817.

**Comment by eddierubeiz** [comment]
Just noting we upgraded staging to 14 last night without issue, and plan to do production next Monday, Oct. 3rd, in the late afternoon.
