### ISSUE TITLE
Make exhibit field private

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1767]
Make the exhibit metadata field only viewable to staff. 

I'm thinking we could want to use some data in this field as we improve the"related items" feature, but eventually, I would like to fully delete the field.

**Comment by jrochkind** [comment]
note this applies to facet as well as display of field on individual page. 

@apinkney0696 would you like the facet, displayed as a limit in search results, to remain, as staff-only too?  Or remove the facet, while leaving the data visible on individual pages as staff-only?

(Leaving the facet public but making the individual page data staff-only is an incompatible and undesirable combo of course!)
