### ISSUE TITLE
Add "Read More" Works Description Expander 

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1774]
**This is just an idea I wanted to throw out there. Not a necessity by any means and definitely something I would want to user test. Curious to hear what you think!

We have talked about how our works page is generally pretty busy. Limiting the number of lines that the description takes up on the page might help this. Sometimes the descriptions can be on the longer side, and consequently require a lot of scrolling for the user to see the rest of the metadata. If the description exceeds more than 6-7 lines, we could hide line numbers 8+ and add a small link that says "read more" underneath that could be selected to reveal the rest of the description.

See ticket #1777 for an illustration of this suggestion.

**Comment by jrochkind** [comment]
We've decided we want to do this, but allowing a fairly large amount of text, maybe around the size of what fits on an example 13" laptop screen, or 2/3rds of a 13" laptop screen, or something. 

I am also thinking there will be no way to "re-hide" the content after expanding -- you click "Read More", and it's all there and there's no way to put it back to hidden with "read more" link showing. (Well, if you reload the page it will be hidden again).  I think this is common in "read more" implementations I've seen on the web. 

We'll try it, at least experimentally -- I am also worried that it will be annoying to have to click the "read more" to get the whole description!  Might want to allow even more content on the page. I have ambivalence!

**Comment by apinkney0696** [comment]
I'm closing as this I'm thinking now that this would likely be more annoying than helpful for users and generally unnecessary. Metadata descriptions can simply be shorter rather than using section expanders.
