### ISSUE TITLE
Adding MP3 or M4A derivatives to OH requests?

### ISSUE THREAD

**Issue by rachellane12** [sciencehistory/scihist_digicoll#1783]
From Slack (@jrochkind):

I wonder if we should also just create MP3 derivatives, and offer people FLAC or MP3 options (when we have FLACs).  If we’re thinking about improving the OH download experience. Maybe we should make a placeholder Issue for that to consider it too.

1. Decide if we want MP3 or M4A (I haven't identified any other candidates), based on some combo of:
    * interviewing (local?) users
    * google or peer research as to common/best practices, including ensuring common consumer OS's/software can play m4a, that they are accessible

2. Make our ingest process create the mp3/m4a derivative, only for flac originals
    * At first I was wondering if we could use AWS MediaConvert for this (that we use for video transcodes). But while it does support some audio-only transcoding, it actually doesn't look like FLAC is an input format it can recognize! https://docs.aws.amazon.com/mediaconvert/latest/ug/supported-codecs-containers-audio-only.html. Also it's just generally kind of hard to work with, we have to do extra custom things like we did with our video transcode to keep track of it at all. So we'll probably just do ffmpeg in a bg job as we do for say combined audio derivs. 

3 Create the derivatives for existing flac originals

4. Make sure the derivative shows up in the "Download" menu when present.

5. Make sure the derivative is available in the email for by-request OHs.

2, 3, 4, and 5 could be separate PR's.

**Comment by rachellane12** [comment]
From Slack (@sarahschneiderSHI):

I do know that Mia prefers using mp3s (or WAV files) when she's using our collections, rather than trying to work with the FLACs. So this would help her for social media use!

**Comment by sarahschneiderSHI** [comment]
I sent a message to Mia asking her about this and will let you know what I hear back. I believe mp4 is a good format for her, but I am not sure about AAC. Thanks!

**Comment by sarahschneiderSHI** [comment]
Oh, I misunderstood, sorry! That is good to know!

**Comment by jrochkind** [comment]
Btw, just testing to see how much space an m4a (lossy compressed) can save over FLAC, with default settings the m4a is around 10% the size of the FLAC!  Knowing it’s audio and can handle lower-quality lossy probably without anyone noticing, it can probably be even smaller. 

We’ll still be storing the FLAC, so we won’t actually save our own disk space (in fact we’ll add another 10%), but we can make things much easier on people that want to listen to or download them.

**Comment by sarahschneiderSHI** [comment]
I heard back from Mia (since I had already sent her the message), and here's what she said:
"If possible, I would prefer not to work with FLAC files, as it is not compatible with the editing software I use (Adobe). MP3/MP4 and AAC files are easier for me to download and work with." I know that she is able to work with WAV files also. So, it sounds like most file types except for FLAC work well for her.

**Comment by CHF-IT-Staff** [comment]
FYI - I believe the Mia uses Adobe Audition.  It does support FLAC - https://helpx.adobe.com/audition/using/supported-file-formats.html


__________________________________

Chuck Hornstein   (he, him, his)
Director, Information Technology
t. +1.215.873.8272
f. +1.215.629.5272

Science History Institute
Chemistry * Engineering * Life Sciences
315 Chestnut Street * Philadelphia, PA 19106 * U.S.A.
Learn about the scientific discoveries that changed our world at sciencehistory.org/learn<https://www.sciencehistory.org/learn>

**Comment by jrochkind** [comment]
Thanks Chuck, interesting! I guess she doesn't realize they are supported by Audition! 

FLAC files definitely are harder to work with, in the sense that they are much larger files, which take longer to download, more space to store, and are slower for software to work with. (I could imagine working with a very large FLAC file might conceivably take more RAM, maybe more RAM than someone's laptop has?)

Regardless of if we want to let Mia know that she could use FLAC if she wanted to, I thinks it's still good feedback that is likely to be representative of more users -- that many users are going to prefer a smaller lossy file format.

**Comment by eddierubeiz** [comment]
@archivistsarah - I'm requesting your official opinion re: mp3 vs. m4a, per our discussion today. Could you issue a recommendation below please?

**Comment by archivistsarah** [comment]
Yes, m4a is fine. It's pretty widely accessible and it's what many other institutions are using for audio access.

**Comment by archivistsarah** [comment]
Additional caveat! Did some extra digging and it looks like MP4/AAC or MP4/HE-AACv2 are the best container/codec combinations in terms of efficiency and compatibility with players.

**Comment by eddierubeiz** [comment]
Yup. We're talking about MP4/AAC  here.

**Comment by archivistsarah** [comment]
Great! (sorry, should have asked about the codec earlier)

**Comment by eddierubeiz** [comment]
Derivs are created in production. Used (Standard-2X).
```
bundle exec rake scihist:data_fixes:add_m4a_derivative_to_audio_assets on ⬢ scihist-digicoll-production...
0.62/s 4614/4614 100% Time: 02:03:24
```

**Comment by eddierubeiz** [comment]
We created the m4a derivatives in production yesterday.
An upper bound for the cost would be $8.22, which is the cost of 30 `standard-2x` dynos for 4 straight hours. The actual cost was less, but it's not worth spending a lot of time finding out how much less; I'd guess around $5.
