### ISSUE TITLE
Fixity report doesn't know about video asset s3 buckets

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1785]
The fixity report at `/admin/fixity_report` incorrectly lists video assets as "not fully ingested".  The assets are ingested just fine, but are stored in a bucket the report doesn't know about.

Easy to fix: update two methods in `fixity_report.rb`
```
  def not_stored_file_sql
    "file_data ->> 'storage' != 'store' or file_data ->> 'storage' is NULL"
  end

  def stored_file_sql
    "file_data ->> 'storage' = 'store'"
  end
```

**Comment by jrochkind** [comment]
Also verify video files are actually being checked for fixity

**Comment by eddierubeiz** [comment]
Fixity checks for video files are working fine, by the way.
