### ISSUE TITLE
Consistent handling of non-public represnetatives in VIDEO works

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1793]
Right now, video pages show players for represnetative assets. 

They will do so, for non-logged in viewers, even if those assets are marked "private". 

For consistency of our access model they should not -- a video asset marked "private" definitely should not be viewable by a non-logged-in-user. 

Should a private video asset still be viewable on the work display page by a logged-in-user? Some of our existing non-video displays WILL let logged-in staff see private items "as if" they were public, so they can demo it and make sure it's ready to publish. The pitfall of this is that it's easy for staff *not to notice* that non-logged-in public users can't actually see everything like staff can, that they haven't actually fully published it. Any opinion on this last paragraph, @apinkney0696 or @ArchivistSarah?

**Comment by apinkney0696** [comment]
I think some sort of visual indicator that an asset (both video or image) is not publically visible for logged-in staff would be extremely worthwhile. I have made the mistake of accidentally publishing the record, but not the assets, a handful of times, and it always takes me a while before I notice because I'm almost always logged into staff view.

**Comment by jrochkind** [comment]
@apinkney0696 one visual indicator would be if the video was not in fact playable if it were not public -- if it was just a big X'd out box instead. 

But that doesn't work if staff wants/needs to be able to watch the video from the "public" display page, even before the asset and work are published. 

What do you think?

**Comment by apinkney0696** [comment]
Yeah, I do think it should maintain its functionality for staff testing purposes. Would it be possible to overlay a little caution symbol (such as below) in an unobtrusive area like a corner? 
![image](https://user-images.githubusercontent.com/78036563/180220382-b3370908-fa13-4eaa-ba79-833388733792.png)

**Comment by jrochkind** [comment]
OK! Yes, I'll work out something like that, as best I can!

**Comment by jrochkind** [comment]
Interesting, I thought a little "private" warning was already being used for image-based display, and was going to try to match that... but now I can't see it happening on the image-based display pages either! 

I wonder if there is such a feature but it's not working, will try to look into it.

**Comment by jrochkind** [comment]
OK the "private" badge on private assets on image display page was there in code, but had somehow gotten broken in CSS to be invisible behind the image instead of in front of it like expected!

I'll fix that too, and try to add a test for it.
