### ISSUE TITLE
Consider how to handle grouping Works that belong to same museum exhibition

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1803]
We're currently using a "facet", but this is not great end-user UI or data modelling, AND the data hasn't been kept up. 

We'll need to think more about this and talk to museums. Maybe it will be something more "collection"-like, whether it is actually included in current lists of "collections" or not, but a page where you can get the exhibition context, link to the exhibition elsewhere on institute website, and a list of D.C. Works of items in the exhibition. 

We'd want to think about use cases. Linking from a D.C. item out to an exhibition -- a digital exhibition (eg Google A&C); but also the website page or brochure page describing a physical exhibition?   Getting from one item that was included in an exhibition to others in the same exhibition, as a way of accessing similar/related/also-of-interest items?  A way of getting more interpretive content or context about the item you are looking at?  Want to look at all items from a certain exhibition? 

This has been extracted from #1776 and #1777

**Comment by apinkney0696** [comment]
Intend to make a meeting with Jesse from exhibits to discuss this. Going to wait until other "related URL" work has been completed.

**Comment by apinkney0696** [comment]
Following our meeting with Jesse, we determined we would like to create "collection-like" formatted pages to keep track of digital objects that exist in physical or digital exhibits. We are meeting on 10/31 to discuss two test pages and create new tickets for specific development needed.
