### ISSUE TITLE
Expand "related URLs" to be structured sub-models instead of just strings

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1804]
A "related URL", perhaps re-named "related Link", should, in addition to having a URL, have a "label" (to be used as link text?), a "category" (possibly to be displayed to the user, but also for our own internal management, as we may display different ones in differnet ways), and maybe more?

Existing "related URLs" will need to be migrated.  For this and other reasons "label" will probably be optional, if not present URL/hostname will be used, as at present. 

Categories may be:

* Distillations Articles
* Distillations Podcasts
* Historical Biographies
* Blog Posts
* Library Guides (LibGuides)
* Archival Description (EAD)  
    * for now; in the future perhaps we can automate this based on identifiers? But they are currently listed in "related URL" and we will probably begin by migrating them?
    * Actually, the fact that not every collection has a public EAD in ArchiveSpace, means we'd probably need something manual to say "yes there's a public EAD to link to", so just manually listing this in related links is probably just fine for a while here -- oh wait, but would we want to link it on the *collection* instead? I think so.... 
* External Links/Other
* Related Works (still using this feature at present)

Use these for "Collection" "related url" too!

Some existing "related URLs" may be cleaned up or deleted, see https://github.com/sciencehistory/scihist_digicoll/issues/1776#issuecomment-1191823073.  
* We may want to get rid of those "provenance" links, perhaps hard-code that link in for any record with provenance info, if that's desired?
* All existing links to OPAC in "related URLs" can I think be deleted, they should all be automatically made from OPAC id?

For ways this might be displayed see #1777 , the "Learn More" section

This has been extracted from #1776 

See also #1803 -- we're not sure if Museum Exhibitions will end up part of this feature, or a different feature.

**Comment by jrochkind** [comment]
@apinkney0696 @eddierubeiz @archivistsarah

Regarding links from Digital Collections to ArchiveSpace EADs....

Historically we haven't done this, for historical reasons. Recently, perhaps mainly/only in Bredig, we've started doing this -- listing links to the ArchiveSpace EAD on individual work records. 

eg https://digital.sciencehistory.org/works/1atx812

It occurs to me -- why don't we list these on the *collection* instead?  That link to Bredig EAD would only have to be listed ONCE on the *collection*.  If we wanted to *display* it on every Work, we could do that in logic, if we wanted.  (Easier after our re-design of 'related link' metadata to be structured). And then it would also be available on the Collection page too.  And it would be one less thing for staff creating records to have to do, copy this link into every (eg) Bredig record!

We could bulk-migrate existing bredig (and other if present) EAD links, then just change practice/workflow going forward to say "enter link to EAD, if available, in the *collection* record, you don't need to copy it to every Work record". 

Thoughts?

**Comment by archivistsarah** [comment]
I think this (work inherits link from collection) sounds great and let's do it. Less manual data entry is almost always a good thing.

It might be worth noting that I think years ago, when we were discussing the possibilities of the ASpace PUI + DC, we thought about linking from the work in DC to the most granular level of description available in the finding aid. So, rather than linking back to the whole collection, we'd link from an image work to the folder that image appears in (think of it kind of like an anchor link although that's not a perfect analogy). I have mixed feelings about this now, but it may be something we want to discuss in the future.

**Comment by jrochkind** [comment]
I think linking to things at the granular level would be great if there were a way to do it; I have never understood if there is in fact a way to do it. I am definitely interested in that. 

But for now, trying to deal with what we have, which is just links to the EAD top level. 

If you were going to use a term to describe an online EAD-based description to an end-user, what would it be? Like, hey, we have this other document related to this thing you may be interested in, it's.... an "Archival Collection Description"? "Description of the archival collection"? Or what?
