### ISSUE TITLE
` pg_restore` fails in staging upon attempting to restore from a copy of the production database.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1817]
Run `heroku pg:backups:info c044` on the staging app for more details.

The first error (which may or not be relevant) is:

```sql  pg_restore: creating EXTENSION "plpgsql"
 pg_restore: creating COMMENT "EXTENSION "plpgsql""
 pg_restore: while PROCESSING TOC:
 pg_restore: from TOC entry 4148; 0 0 COMMENT EXTENSION "plpgsql"
 pg_restore: error: could not execute query: ERROR:  must be owner of extension plpgsql
 Command was: COMMENT ON EXTENSION "plpgsql" IS 'PL/pgSQL procedural language';
```
Another similar error follows (`must be owner of extension pg_stat_statements`)

Then, pg_restore has trouble installing `pgcrypto`.

Finally, our own PL/SQL code to set up `gen_random_uuid` fails.

To reproduce:

```sh
heroku pg:copy scihist-digicoll-production::DATABASE_URL \
DATABASE_URL -a scihist-digicoll-staging  \
--confirm scihist-digicoll-staging
```

(This is the first step of our regular routine to copying the production database to staging.)

**Comment by eddierubeiz** [comment]
Heroku support got back to us with:  ```We are still working on a fix for this issue, but in the meantime, we have seen the following workarounds temporarily unblock customer's workflows: [...]```

So for now: just wait.

**Comment by eddierubeiz** [comment]
Hi there,

Thanks for reaching out to us and we’re very sorry for the inconvenience caused here.

We are still working on a fix for this issue, but in the meantime, we have seen the following workarounds temporarily unblock customer's workflows:

**Manually migrating Postgres plugins by:**

- pulling the affected database into a local database
- manually migrating the relevant extensions locally
- creating a new database on the app
- pushing the local DB with migrated extensions into the new database
- promoting the new database

**Manually updating schema references. For example:**

Changing all instances of `WITH SCHEMA public;` to `WITH SCHEMA heroku_ext;` and all instances of `DEFAULT public` to `DEFAULT heroku_ext` by using find & replace in a text editor or by changing the output of pg_dump using `sed`

While these workarounds are only temporary they may help to unblock you for the moment. We apologize again for the inconvenience caused and as we work to remediate the issue, we will update you with more information and the next steps.

Please let us know if you have anything else to ask.

Regards,
CJ

**Comment by jrochkind** [comment]
pg:copy is now transparently Just Works fixed for us, but pg:restore may still require some manual steps. There is an FAQ on it now from heroku.  

We still need to spend some time with this and address this:

https://help.heroku.com/ZOFBHJCJ/heroku-postgres-extension-changes-faq

**Comment by eddierubeiz** [comment]
The following allows you to `pg:restore` from a database (like the current production DB) that has extensions in `public`:
```
heroku pg:backups:restore scihist-digicoll-production::a661 DATABASE_URL \
	--extensions 'public.pg_stat_statements,public.pgcrypto' \
	--app scihist-digicoll-staging
```

**Comment by eddierubeiz** [comment]
Assuming you're working with a production database without pgcrypto:
```
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description
--------------------+---------+------------+-----------------------------------------------------------
 pg_stat_statements | 1.9     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
```

it's now possible to run:
````
heroku pg:backups:restore \
    scihist-digicoll-production::b674 \
    --app scihist-digicoll-staging
```

and have all the tables copy over normally.

The errors are still occurring, but they are ignored.
```
$ heroku pg:backups:info c072 --app scihist-digicoll-staging | grep -i error
2022-10-04 16:56:19 +0000 pg_restore: error: could not execute query: ERROR:  must be owner of extension plpgsql
2022-10-04 16:56:19 +0000 pg_restore: error: could not execute query: ERROR:  Extensions can only be created on heroku_ext schema
2022-10-04 16:56:55 +0000 pg_restore: warning: errors ignored on restore: 2
```

**Comment by eddierubeiz** [comment]
```
heroku pg:psql --app scihist-digicoll-staging < heroku-scihist-digicoll-backup.sql
```
using a recent logical (human-readable SQL) backup of the prod database pulled from s3 is working too.

**Comment by jrochkind** [comment]
Nice!

My guess is maybe those pretty standard plugins come already installed on heroku db, so when our backup file tries to install them, and fails -- it doesn't matter, they were already there anyway (in the heroku_ext schema, but in a way that Just Works, as heroku intended).
