### ISSUE TITLE
New Featured Topic: Rare Earths

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1825]
Please create a new featured topic with the following:

**Title:**
Rare Earths

**Description:**
In the collection below, find materials related to rare earth elements, a group of 17 elements composed of scandium, yttrium, and the lanthanides. These abundant elements, characterized by similar geochemical and magnetic properties, are mined for a variety of uses including magnets, alloys, glasses, and electronics. The diverse collection of materials found below demonstrates the range of uses for rare earths throughout the twentieth and twenty-first centuries. Browse the topic to find materials related to fine art, lasers, cathode ray tube televisions, the first incandescent lights, and more!

**List of Subject Terms:**
Cathode ray tubes
Cerium
Dysprosium
Erbium
Europium
Gadolinium
Holmium
Lanthanum
Lutetium
Neodymium
Organorare earth metal compounds
Phosphors
Praseodymium
Promethium
Rare earth borides
Rare earth fluorides
Rare earth halides
Rare earth industry
Rare earth industry--Accidents
Rare earth ions
Rare earth ions--Spectra
Rare earth lasers
Rare earth metal alloys
Rare earth metal catalysts
Rare earth metal compounds
Rare earth metal compounds--Magnetic properties
Rare earth metal compounds--Thermal properties
Rare earth metals
Rare earth metals--Magnetic properties
Rare earth metals--Magnetic properties
Rare earth metals--Metallurgy
Rare earth metals--Spectra
Rare earth nitrates
Rare earth nuclei
Rare earth oxide thin films
Rare earth phosphates
Rare earths
Rare earth-silicon-iron-aluminum alloys
Rare earths--Magnetic properties
Rare earths--Spectra
Samarium
Scandium
Terbium
Thulium
Ytterbium
Yttrium

**Icon Image:** 
P:\Othmer Library\Digital Collections - External Access\Crops for Hydra Redesign\cropped_tiffs\categories
Rare_Earths_3.tif

https://sciencehistory.atlassian.net/wiki/spaces/HDC/pages/1646428165/Creating+a+thumbnail+for+a+Featured+Topic

**Comment by jrochkind** [comment]
@apinkney0696 I'm going to change "In the collection below" to "In this collection" -- we don't want words in there that assume a certain page layout, we may re-use the description in other contexts. 

(Other featured topic descriptons tend to say "This digital collection", btw)
