### ISSUE TITLE
New Featured Topic: Plastics & Synthetic Fibers

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1827]
Please create a new featured topic with the following:

**Title:**
Plastics & Synthetic Fibers

**Description:**
Plastics encompass a wide range of synthetic and semi-synthetic materials created from large repeating molecules called polymers. The Institute’s collections include a wide variety of materials documenting the history of the study of polymers, the development of plastics, the plastic industry, synthetic fibers, microplastics, works depicting or created by early pioneers of the field, and other related topics. Browse the digitized materials below to learn more about plastics and synthetic fibers from the lab to your living room. 

**List of Subject Terms:**
Acrylic fiber industry
Acrylic resin industry
Acrylic resins
Advertising--Plastics
Bakelite
Biodegradable plastics
Celluloid
Dyes and dyeing--Plastics
Injection molding of plastics
Microplastics
Plastic films
Plastic kitchen utensils
Plastic tableware
Plastic tiles
Plastic toys
Plasticizer industry
Plasticizers
Plastics
Plastics in medicine
Plastics in packaging,
Plastics industry and trade
Plastics machinery industry
Plastics--Analysis
Plastics--Coloring
Plastics--Deterioration
Plastics--Extrusion
Plastics--Handbooks, manuals, etc.
Plastics--Molding
Plastics--Molds
Plastics--Periodicals
Plastics--Research
Plastics--Testing
Polyethylene
Polyethylene terephthalate
Polyolefins
Polypropylene
Polypropylene fibers
Polystyrene 
Polyvinyl chloride
Polyvinyl chloride industry
Styrene
Synthetic fabrics
Synthetic products
Thermoplastic composites
Thermoplastics
Thermosetting composites 
Dyes and dyeing--Nylon
Dyes and dyeing--Rayon
Nylon
Rayon
Rayon industry and trade
Synthetic fabrics
Synthetic products
Textile fibers, Synthetic
Thermosetting composites
Polytef

**Icon Image:**
P:\Othmer Library\Digital Collections - External Access\Crops for Hydra Redesign\cropped_tiffs\categories
Plastics_3_full.tif

https://sciencehistory.atlassian.net/wiki/spaces/HDC/pages/1646428165/Creating+a+thumbnail+for+a+Featured+Topic

**Comment by jrochkind** [comment]
" Browse the digitized materials below" --

We don't want language that assumes the page layout, that this description will always forever only be displayed "above" materials. 

How about "browse the digitized materials in this digital collection" instead?

**Comment by apinkney0696** [comment]
I didn't even think about that - thanks for the suggestion! "browse the digitized materials in this digital collection" is perfect
