### ISSUE TITLE
Resolve orphaned DZI files report

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1832]
The new DZI file orphan checker reported orphans, from report 146 at `24 Aug 01:00` (don't know what timezone that is, that's what the report is lableled as -- it really ought to have a timezone in output display).  https://app.honeybadger.io/projects/58989/faults/86977432

These need to be resolved -- we don't want an orphan checker report flagging things every week and us just ignoring them, "crying wolf" we'll stop paying attention to them. 

https://digital.sciencehistory.org/admin/orphan_report

Since this is the first time we've used this orphan checker, we also should manually confirm that each thing it found really is an orphan. 

At least one I spot-checked appears to possibly be a false positive, where deleting it would result in missing DZI tiles?  Flagged path at: https://s3.console.aws.amazon.com/s3/buckets/scihist-digicoll-production-dzi?region=us-east-1&prefix=0004a36e-7b18-4f4d-b8d4-256d85dbb06c/&showversions=false

**Comment by eddierubeiz** [comment]
I can't find any Assets by those IDs - all these return ActiveRecord::RecordNotFound .

Asset.find("12716a18-d835-4c1b-972e-ba36a46537ba")
Asset.find("1f1ceccd-a31f-4408-a262-1039b2708897")
Asset.find("3db65965-b0f2-4eb1-a29c-284c714647e7")
Asset.find("553b8d8f-bcbb-49f9-9ad4-ed50bc1eb88f")
Asset.find("5ea3f9ca-0997-4a60-916f-7734a2cfe41e")
Asset.find("636368d5-b96c-494a-820a-ae69abad5db7")
Asset.find("7b6de542-8756-4afe-a3e6-4d4195b60e6c")
Asset.find("7ca72216-9753-42c7-8083-020a8e9e01b7")
Asset.find("8097f308-998f-49f4-a1cc-898b981e2d67")
Asset.find("81c85983-36a4-48b6-a9ee-e9f0ebfc946d")
Asset.find("9f52b862-236c-4d08-9bae-d2ef592eaa8b")
Asset.find("a39b5adc-371f-4912-837e-c5fc9befa78c")
Asset.find("a9f55907-9732-4e61-a293-900be9ccb1d6")
Asset.find("bdb0a1db-ea52-4fed-aacf-cdc1fcb2d5db")
Asset.find("be2799bd-baaf-470f-9d72-595f027849f1")
Asset.find("c7797928-88c3-4875-8e72-c34352440f08")
Asset.find("e54f5542-0a3d-4128-8fdf-49a15f2335c1")
Asset.find("f359798d-500a-47fc-8d09-21b25008079b")
Asset.find("f3dc06c0-f3c9-4004-b408-c229bf1e16c7")

**Comment by eddierubeiz** [comment]
Let's now go back to the link flagged as a false positive:

https://s3.console.aws.amazon.com/s3/buckets/scihist-digicoll-production-dzi?region=us-east-1&prefix=0004a36e-7b18-4f4d-b8d4-256d85dbb06c/&showversions=false

In that s3 folder, we see two subfolders:

- md5_2091f3a83769d64a478a5428af9690b3_files/
- md5_2091f3a83769d64a478a5428af9690b3.dzi

This is definitely not an orphaned set of DZI tiles.

- There is an asset at https://digital.sciencehistory.org/admin/asset_files/n009w320g;
- Its ID is `0004a36e-7b18-4f4d-b8d4-256d85dbb06c`
- Its md5 is indeed `2091f3a83769d64a478a5428af9690b3`

**Comment by eddierubeiz** [comment]
However, it doesn't look like asset `0004a36e-7b18-4f4d-b8d4-256d85dbb06c` is in the list of reported DZI orphan directories.

**Comment by eddierubeiz** [comment]
Running 
```ruby
heroku run "bundle exec rails runner 'OrphanS3Dzi.new(show_progress_bar: false).delete_orphans'"
```

```
deleted a folder and its contents at scihist-digicoll-production-dzi: 12716a18-d835-4c1b-972e-ba36a46537ba/
deleted a folder and its contents at scihist-digicoll-production-dzi: 1f1ceccd-a31f-4408-a262-1039b2708897/
deleted a folder and its contents at scihist-digicoll-production-dzi: 3db65965-b0f2-4eb1-a29c-284c714647e7/
deleted a folder and its contents at scihist-digicoll-production-dzi: 553b8d8f-bcbb-49f9-9ad4-ed50bc1eb88f/
deleted a folder and its contents at scihist-digicoll-production-dzi: 5ea3f9ca-0997-4a60-916f-7734a2cfe41e/
deleted a folder and its contents at scihist-digicoll-production-dzi: 636368d5-b96c-494a-820a-ae69abad5db7/
deleted a folder and its contents at scihist-digicoll-production-dzi: 7b6de542-8756-4afe-a3e6-4d4195b60e6c/
deleted a folder and its contents at scihist-digicoll-production-dzi: 7ca72216-9753-42c7-8083-020a8e9e01b7/
deleted a folder and its contents at scihist-digicoll-production-dzi: 8097f308-998f-49f4-a1cc-898b981e2d67/
deleted a folder and its contents at scihist-digicoll-production-dzi: 81c85983-36a4-48b6-a9ee-e9f0ebfc946d/
deleted a folder and its contents at scihist-digicoll-production-dzi: 9f52b862-236c-4d08-9bae-d2ef592eaa8b/
deleted a folder and its contents at scihist-digicoll-production-dzi: a39b5adc-371f-4912-837e-c5fc9befa78c/
deleted a folder and its contents at scihist-digicoll-production-dzi: a9f55907-9732-4e61-a293-900be9ccb1d6/
Error: timed out
```

**Comment by eddierubeiz** [comment]
Running the whole thing again...

**Comment by eddierubeiz** [comment]
```
deleted a folder and its contents at scihist-digicoll-production-dzi: bdb0a1db-ea52-4fed-aacf-cdc1fcb2d5db/
deleted a folder and its contents at scihist-digicoll-production-dzi: be2799bd-baaf-470f-9d72-595f027849f1/
deleted a folder and its contents at scihist-digicoll-production-dzi: c7797928-88c3-4875-8e72-c34352440f08/
deleted a folder and its contents at scihist-digicoll-production-dzi: e54f5542-0a3d-4128-8fdf-49a15f2335c1/
deleted a folder and its contents at scihist-digicoll-production-dzi: f359798d-500a-47fc-8d09-21b25008079b/
deleted a folder and its contents at scihist-digicoll-production-dzi: f3dc06c0-f3c9-4004-b408-c229bf1e16c7/

Deleted 6 files or folders from DZI.
```
