### ISSUE TITLE
http => https redirect adds extra slash

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#184]
If I go to `http://kithe.sciencehistory.org/catalog?q=science`, I get a redirect (intended to https) with  `https://kithe.sciencehistory.org//catalog?q=science`.

There's an extra slash in there, `//`.

While the URL works with the extra slash, it's sloppy, and in theory could have SEO implications, better to do it right.

**Comment by sanfordd** [comment]
This needs to be edited in Ansible, the nginx template will be updated.

**Comment by sanfordd** [comment]
@jrochkind I've put a fix in place if you'd like to check that it is working for you as well. My tests with the sample URL showed a correct number of slashes.

**Comment by jrochkind** [comment]
Seems to be working properly to me now!
