### ISSUE TITLE
Change Related Links Category: "Historical Biography" to "Scientific Biographies"

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1867]
Dana informed me that Historical Biographies are going to be called "Scientific Biographies" in the future. I'm not sure when this change is going to take place (probably with the new website update) but wanted to keep it in mind. I don't think it would be the worst thing to change our related link heading in advance if we wanted to just do it now.

Further, Dana also let me know that there are two different podcasts, one called "Distillations" and the other called "The Disappearing Spoon." Do we want to distinguish between the two productions in the heading or just change the heading to "Podcast"? Currently they are only listed as "Distillations Podcast". Dana said they are really trying to promote the fact that they have two separate podcasts, so I think their team would be in favor of two separate headings, one per podcast.

**Comment by apinkney0696** [comment]
Discussed in weekly meeting:
Going to wait to change the historical biographies heading until the main website adjustment is made.
Annabel to verify with the Distillations staff the differences between "The Disappearing Spoon" and "Distillations" podcasts, but we are leaning towards fewer, broader categories.

**Comment by apinkney0696** [comment]
Okay, so I got in touch with the branding and podcast folks and noted that we wanted to go with a broader category for the podcast links. I suggested "Institute Podcast," but Caitlin requested the categories become simply "Podcast" and "Magazine" (Instead of Distillations Article) assuming that users on the site will understand it's an Institute link because they are on an Institute site. 

I am okay with this suggestion personally. If this works for everyone, let's go ahead and make the change.

**Comment by apinkney0696** [comment]
Adjusting this ticket to only reflect the historical biographies change - making another for the change with the distillations titles.

**Comment by jrochkind** [comment]
@apinkney0696 confirm this is intentionally in "ready" column, ready for us to do and deploy live whenever we get to it?

**Comment by apinkney0696** [comment]
Yes

**Comment by jrochkind** [comment]
@apinkney0696 Title says:

> "Historical Biography" to "Scientific Biographies"

Changing from the singular to plural.  But all the other headings we have for links are currently singular. Eg "Article", "Library Guide", "Podcast". 

Keep this one singular to be consistent? Or do we want to change them all to be plural? (a different ticket?)

**Comment by apinkney0696** [comment]
Oh no, that's just a typo on my part. Please keep everything singular, so it should read "Scientific Biography." Thank you for checking!
