### ISSUE TITLE
Google Classroom Integration

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1872]
**I'm pasting an email thread with Erin M. Below. Let's chat about this during our meeting on Monday.**

From: McLeary, Erin <EMcLeary@ScienceHistory.org>
Sent: Wednesday, September 28, 2022 3:53 PM
To: Pinkney, Annabel <apinkney@sciencehistory.org>
Subject: interesting (to me) examples of Google Classroom integration
 
Hi Annabel, 

A question for the digital tech team! I've been seeing some websites of organizations similar to us offering integration with Google Classroom, so a teacher who wants to assign a resource from that site can do so directly from the resource page. Here's an example from [DPLA ](https://dp.la/primary-source-sets/space-race)(under "cite this set") and here's an example from [Science Buddies](https://www.sciencebuddies.org/news/article?id=1261752) (top right corner, green and yellow icon). I'm curious about you all's opinion on how difficult it is to add this sort of integration, if this is something we might be interested in doing down the road. I like the Science Buddies example because it's not a full lesson plan (like the DPLA example), it's just an article that an educator might want to assign or use. It made me think of your work to add related resources to certain items in the digital collection and how something like Google Classroom integration could be very appealing for an educator looking at such a set of related resources. (Of course, the educator has to find our resources, but we can disaggregate the PR challenge from the technical challenge for the moment!)

This is just my curiosity at this point, but I'm interested in any thoughts the digital tech team has!

--Erin
__________________________________

From: Pinkney, Annabel <apinkney@sciencehistory.org>
Sent: Wednesday, September 28, 2022 4:08 PM
To: McLeary, Erin <EMcLeary@ScienceHistory.org>
Subject: Re: interesting (to me) examples of Google Classroom integration
 
Hi Erin,

What a neat idea! I will put in a GitHub ticket now and discuss this with the tech team at our weekly check-in meeting this coming Monday and get back to you with some initial reactions. 

To make sure I understand, Google Classroom seems to be a way for educators to compile online resources in one place to direct their students. If we were to enable Google Classroom integration, then our record pages would be able to be linked from these classroom sites. Let me know if this sounds accurate to you.

Best,
Annabel

Annabel Pinkney, M.L.I.S.   (she, her, hers)
Digital Collections Librarian
Othmer Library of Chemical History 
t. +1.215.873.8216

__________________________________
Erin McLeary   (she, her, hers)
Director of Strategic Initiatives
Office of the President 
t. +1.215.873.8230

I played around with the DPLA classroom integration and an old Google Classroom site I have access to as a UArts adjunct instructor, and it's a really nice feature! Google Classroom allows teachers to organize all their course material online. Teachers can post assignments, resources (my teen accesses her textbooks through Classroom), etc. I'm happy to do a quick video meeting with anyone who's interested to show how the integration works from the user perspective (maybe we stay on the call we are both in on Friday for a couple extra minutes and I show you?). I was prompted to choose which classroom (aka course) I wanted to post to and what type of post I wanted to create (assignment, ask a question, announcement). After I chose, the correct type of post opened in my classroom site, with the DPLA materials attached (see screenshot). The DPLA materials opened on the DPLA site. 

Erin McLeary   (she, her, hers)
Director of Strategic Initiatives
Office of the President 
t. +1.215.873.8230

**Comment by jrochkind** [comment]
I've never heard of this before, but can look into it. 

In general, I'd say it would be good to find at least *one* potential user who might actually use this before doing it. Both to give us some confirmation that _anyone_ would use it, and to serve as a stakeholder to give us information on what they need/want so we can develop to meet real user needs. Without a real user, we'd be doing a lot of guessing.

**Comment by jrochkind** [comment]
However, this also could be super simple to implement. The DPLA example seems to be nothing more than a link of this format:

    https://classroom.google.com/u/0/share?url=https://dp.la/primary-source-sets/space-race

https://developers.google.com/classroom/guides/sharebutton

**Comment by apinkney0696** [comment]
Spoke more about this with Erin on Friday - this seems to be widely used by teachers, including Erin herself when she taught at UArts, and a couple of folks on the call said that their kids use Google Classroom, so there are definitely use cases. She mentioned how useful the platform was as a teacher and that most teachers will recognize the Google Classroom icon immediately. They are planning to add Google Classroom Integration to Distillations articles and Scientific Biographies as well.

I was looking at Google Analytics, and it appears that in the time the Digital Collections app has been active, less than 1% of the total events have been clicking the social media sharing options. We're talking less than ~40 clicks in 5 years. I think it's worth considering replacing the social media sharing options with the Google Classroom icon. 

We can talk about logistics at our upcoming meeting, then I can either edit this ticket or create a new one to reflect this task.

Thanks!

**Comment by eddierubeiz** [comment]
Sent an email off to Erin so we can get to the bottom of this.

We can of course follow the recipe described at https://developers.google.com/classroom/guides/sharebutton --- but only after we rule out simply prefacing the link with `https://classroom.google.com/u/0/share?url=`

**Comment by eddierubeiz** [comment]
Did a quick live demo for Erin yesterday and I got a better sense of how the share is supposed to work. The link preface does work fine for our purposes (after a typo fix I tested briefly in staging this morning.

**Comment by eddierubeiz** [comment]
Note that the DPLA classroom uses a square grey image:
https://dp.la/static/images/google-classroom.svg
So I would propose one of four choices, ranked from least to most compatible with our branding:
- Square green (see https://commons.wikimedia.org/wiki/File:Google_Classroom_icon.svg )
- Square grey (see https://dp.la/static/images/google-classroom.svg )
- Round green (currently in this PR)
- Round grey (small change to the colors used in this PR)

**Comment by eddierubeiz** [comment]
Erin says: "What do you think of using the yellow and green version of the icon? As a google classroom user, the [round] grey version didn't visually scan "Google Classroom" to me and the logo itself is so tiny I'm not sure I would recognize it without the colors (as compared to the larger logos on the social media buttons, which are much easier to recognize)"

Here are screenshots of the two round (green and grey) options. We could use whatever colors we want.


![round grey](https://user-images.githubusercontent.com/94723/199567684-5285dd7b-c034-4d4b-b405-63b45eb4df06.png)
![round green](https://user-images.githubusercontent.com/94723/199567685-4fe478dd-db96-4eec-b0ff-809514a356a7.png)

**Comment by jrochkind** [comment]
I worry that yellow-and-green will look garish and attract too much attention on our site IMO -- A minority of users will be Google Classroom users, we don't need to make this button the most prominent and attention-grabbing element on the whole page!

If a more subtle gray button doesn't work in that spot (whether circle or square), we may need to find a differnet spot on page or other redesign of page, to allow the words "Share to Google Classroom" as on DPLA example.

**Comment by jrochkind** [comment]
Honestly even I don't think those example buttons -- with or without the splash of green -- are likely to be recognizable at size. :(.  What if we try using the DPLA square one exactly (or with slightly changed colors)?

**Comment by eddierubeiz** [comment]
I'm adding a rectangular option too. If we choose this one I'll have to spend a bit more time tweaking the exact alignment, but it is an option.

![rectangular_icon](https://user-images.githubusercontent.com/94723/200002660-b8a31d35-9a28-4b4b-879f-f92ca701af37.png)

**Comment by eddierubeiz** [comment]
And also tweaked the round icon a bit so it's more legible, per J's suggestion.

![better round icon](https://user-images.githubusercontent.com/94723/200002958-f8aac2c5-9b08-472a-97f9-8c53566f691f.png)

**Comment by apinkney0696** [comment]
I think this round option is the most aligned with our page design so far, but I don't mind the square version much either and I think it registers more like the Classroom logo and would be more recognizable. The dark black part is the only piece that seems a little out of place. Not to be nitpicky, but have you tried substituting the black for white or a light gray in the rectangle logo? Does it look funny?

**Comment by eddierubeiz** [comment]
Tweaking the colors within the icon is easy to do since we're using an inline svg. I get what you're saying. I can absolutely make an edit (on Monday) to make the darkest gray in the rectangle logo match the dark grey of the other social media icons.

**Comment by eddierubeiz** [comment]
Or something like that. We can figure it out.

**Comment by eddierubeiz** [comment]
(I am rooting for the round icon, though.)

**Comment by apinkney0696** [comment]
Sounds great! Either way, I think these are both great options and look good next to the social media icons. I agree, that the round icon looks really perfect. 

I wonder if should ask Ashley or Caroline if I could make a [libguide](https://guides.othmerlibrary.sciencehistory.org/homepage) about the digital collections where I could describe this feature among other tips for navigating and searching.

**Comment by jrochkind** [comment]
I agree the square version is fine if it's the most recognizable -- which I suspect it will be?

I also think the round one you ended up with is the best round one yet, as far as recognizability while blending in.
