### ISSUE TITLE
Enable Survey Pop-up in the Digital Collections

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1878]
I need to pay for the upgraded version of this program, but once that is complete (hopefully by tomorrow), I would like to integrate the SurveySparrow Survey that Jahna and I created in the Digital Collections. It looks like this so far: https://sprw.io/stt-7c269e

And it seems to be implemented with some Java Script:
`<div id="ss_survey_widget"></div><script>(function(){var e="ss-widget",t="script",a=document,r=window;var s,n,c;r.SS_WIDGET_TOKEN="tt-7cfb64";r.SS_ACCOUNT="sciencehistory.surveysparrow.com";r.SS_SURVEY_NAME="digitial-collections-survey";if(!a.getElementById(e)){var S=function(){S.update(arguments)};S.args=[];S.update=function(e){S.args.push(e)};r.SparrowLauncher=S;s=a.getElementsByTagName(t);c=s[s.length-1];n=a.createElement(t);n.type="text/javascript";n.async=!0;n.id=e;n.src=["https://","sciencehistory.surveysparrow.com/widget/",r.SS_WIDGET_TOKEN].join("");c.parentNode.insertBefore(n,c)}})();</script>`

I'll send you guys the login info for the SurveySparrow account privately so you can see the implementation information for yourselves. I can't tell if it's as simple as just plugging in the above script.

We would like to begin collecting responses probably sometime between October 19th and 28th if possible. Let me know if you need any other information from me!

**Comment by eddierubeiz** [comment]
Hey @apinkney0696  -- I popped the code above into my dev environment and it doesn't seem broken per se (I see the JS code executing without error), but I don't see any change to the interface after the code executes. I feel like I'm missing something. Are there other instructions I should be following?

**Comment by eddierubeiz** [comment]
Noting another bug: the JS code that closes the survey also in some cases removes *our* content, leaving a blank Digital Collections page with just the header and footer intact. Not good.
