### ISSUE TITLE
Mysterious solr index miss for "video ISI"  (due to German language field included)

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1883]
I expect to be able to search "video ISI"  to find this one: https://digital.sciencehistory.org/works/otbju0w

But I can't... not really sure why not, something weird is happening in solr.

**Comment by eddierubeiz** [comment]
Eh? We do index `genre` in `text2_tesim` and in `genre_facet`.
And https://digital.sciencehistory.org/catalog?search_field=all_fields&q=Video+ISI seems to work fine for finding that item. 
The genre for that work is "Video Recordings", for what it's worth.

**Comment by eddierubeiz** [comment]
Correction --  there's more than one item with that title, and the item is not in the list of results.

**Comment by jrochkind** [comment]
Weird, I'm very confused what's going on then, but does seem not right!

**Comment by jrochkind** [comment]
These all find it:

* https://digital.sciencehistory.org/catalog?q=%22video%22+%22putting+scientific+information%22
* https://digital.sciencehistory.org/catalog?q=%22video%22+ISI

Note that last one puts `"video"` in double quotes... when I drop the double-quotes, I get entirely different results... not how we expect Solr to work!

https://digital.sciencehistory.org/catalog?q=video+ISI

Changing title to "Solr mysterious lack of hit"....

**Comment by jrochkind** [comment]
Still very mysterious... Trying to reproduce with smaller and smaller solr case....

I have determined that the solr `qf` (query fields) property matters.. With our full multi-field qf, the failure reproduces. 

If I trim it to _just_ `text1_tesim^1000 description_text4_tesim^50` the failure does not reproduce. 

Somehow taking a query that produces a hit and _adding_ search fields to it... causes it to fail to hit. That's the mystery. Trying to get minimum fields that reproduce, so maybe it can be compared with more debugging.

**Comment by jrochkind** [comment]
Weird, no, I'm having trouble reproducing the _hit_ with the smaller `qf`; my actual app in dev does it, but I'm having trouble doing it against solr directly to more easily debug.

**Comment by eddierubeiz** [comment]
The plot thickens.

**Comment by jrochkind** [comment]
OK, if I redefine `searchable_fulltext_de` as `text_en` -- the same file type as the other two fields -- it _still_ seems to reproduce the problem to include it in `qf`. 

This makes little sense. 

What makes it different? That it contains no values for this document?  That may be, adding other fields to dismax that include no values for the document seem to also reproduce maybe? 

Could it be a bug in solr dismax? Even if it is, it could be in latest Solr too, but let's try more recent versions to see if there's a difference. 

 updating to latest solr 8.x, `8.11.2`...   no difference. 

Let's try recent solr `9.0.0`, although it's possible it will have other backwards breaking changes.... had to hack our solrconfig.xml a bit to get it to start under solr 9.0.0 at all -- once I did, no difference. 

This is a weird one. Maybe I'll try asking on slack, as well as googling/thinking on it.

**Comment by jrochkind** [comment]
OK, deleted last comment I made a mistake. 

If I change `searchable_fulltext_de` to be `text_en` instead of `text_de` -- the problem *does go away*. 

So it does have something to do with the different field definitions. 

Looking at them, there is a curious difference, they use different tokenizers. 

* `text_en` begins with an `ICUTokenizerFactory` (multi-lingual aware tokenizer) followed by `ICUFoldingFilterFactory` (multi-lingual aware lowercasing, plus removing diacritics and normalizing unicode).

* `text_de` begins with `StandardTokenizerFactory` (not multi-lingual aware tokenizer!), and a `LowerCaseFilterFactory` (not multi-lingual aware lowercaser). 

Of course we don't want to remove diacritics from the German one. But first let's try configuring it the same tokenizer and folder anyway....

Weirdly, that does **not** appear sufficient to resolve the problem anyway. 

OK, now I have to make chagnes one by one to see exactly what difference in field definition between our German and English is sufficient to cause the problem.

**Comment by jrochkind** [comment]
OK actually one difference in analysis. 

With the `text_en` field, the word `video` analysis into a single token, `video`. 

With the `text_de` field, the word `video` analyses into TWO tokens.  TWO `video` tokens, both at position `1`, it's somehow doubled up. 

This must have to do with what's going on. 

Even though in my tests the `searchable_fulltext_de` is _empty_, including it in the `qf` means when the _query_ goes through analysis... it winds up with that weird doubling, that breaks the search. (There must be something about the word `video` interpreted using German dictionaries that's weird?). 

We may not be able to keep using this fancy German approach, hm.

**Comment by jrochkind** [comment]
OK, so... after noticing the duplicate tokens was weird...

Inserting a `<filter class="solr.RemoveDuplicatesTokenFilterFactory"/>` in the chain immediately after the `HyphenationCompoundWordTokenFilterFactory` -- seems to resolve the problem!

I am not totally confident this thing wont' cause _other_ problems when used together in dismax with differently analyzed fields... we probably want to get more info and report this to the maintainer of the german thing.... I don't know, but it does solve this particular found problem.

**Comment by jrochkind** [comment]
OK, after sleeping on it.... 

While I find a workaround for this specific issue, I think the fundamental problem is:

* if the German-language field produces a *different number of tokens* than our English field, it will produce problems being used in a `dismax` multi-field query with both fields. 

And I think it _will_ do this in other cases, as it's designed to split up single German compound "words" into multiple tokens, where the English or langauge-agnostic analyzer tokenizing on whitespace would have only one token, right?

I thought I had read about problems like this before, but googling, what I found is [my own blog post](https://bibwild.wordpress.com/2010/04/14/solr-stop-wordsdismax-gotcha/) from 2010 (!!) about _stopwords_, as well as as this [drupal mailing list post](https://www.drupal.org/project/search_api_solr/issues/2948469) also about stopwords. 

However, I think the logic about stopwords actually still applies here, differnet stopwords in different fields ends up being _one_ exhibit of a more general problem: Different number of tokens from different fields. 

At least this is what I think -- Solr/lucene is esoteric enough and I'm not an expert that I'm not 100% sure I have this right, but I think i do. We could try getting help from someone more Solr expert (such as maybe mgibney, although he recently left library land). 

But if this is true -- we can't combine these two fields like this in solr dismax. 

* _Immediately_, I think we should change the field definition to not use the compounder, just use the simpler built-into-solr German stemmer and normalizer. (Loss of German language function, yes). 

Longer-term, I can think of a couple of possible solutions to change how the Solr querries work, each of which is kind of hard to implement. 

* I could imagine a Solr query that's more like `[dismax query over all fields except German] OR [dismax query over just German fields]`. 
   * Pro:  It should fix this problem. It will maintain our "just enter a search, google-style, we'll do our best" UI. 
   * Con:  Relevance ranking will be weird, possibly very broken, definitely harder to manage, not sure, we'd have to be very careful. It will be somewhat hard to figure out how to contruct this Solr query. It may be harder to figure out how to get Blacklight to _issue_ it!

* Have special German-langauge searching _only_ on Bredig collection search. Like when searching in Bredig collection, UI let's user choose to search "ordinary search" (not including German analysis) or, instead, to do a "German transcript search" that uses German analysis. 
  * pro:  Much more understandable treatment by Solr, for us developers. Easier control over relevance ranking in standard ways. 
  * con: User has to choose a German search, and notice it's there on Bredig collection search only. *ALSO* could be hard to get Blacklight to do -- Blacklight does have a "choose a field to search" function that could apply here, but we've disabled it in our app, changed some of the on-screen UI applying to it, and we'd want it only to apply to one collection... might be tricky, although actually probably should be do-able.

**Comment by jrochkind** [comment]
Oh actually, I just found another blog post from me 10+ years ago, that already expands the problem from stopwords to any differing analysis. Turns out I already got to the bottom of this problem in 2011 haha.  So, yeah. 

https://bibwild.wordpress.com/2011/06/15/more-dismax-gotchas-varying-field-analysis-and-mm/
