### ISSUE TITLE
Update code to account for new OPAC URLs

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1913]
The URL to the OPAC is being updated from [othmerlib.sciencehistory.org](http://othmerlib.sciencehistory.org/) to othmer**library**.sciencehistory.org. The old links will ideally be redirected to the new links. 

Inputting a bib ID in the ID metadata field automatically generates a link to the corresponding OPAC record. This ticket is for the necessary changes to the code that needs to occur to account for the link updates. 

I'm unsure of when the link updates will be live, but I will let you know when I know.

**Comment by apinkney0696** [comment]
@eddierubeiz on Slack: 

> We might want to take a minute to make the catalog URL easier to change in the future, too, just as a matter of good design.

**Comment by eddierubeiz** [comment]
Would be nice e.g. to create an env variable for just the OPAC URL instead of `:opac_link_template` , and amend `app/views/catalog/_search_sidebar.html.erb` accordingly.

**Comment by jrochkind** [comment]
@eddierubeiz How many places in code does this show up? It's so easy to search and replace to change it, and so unlikely to change much, that I'd argue for not adding more complexity to the code, but no big deal either way.

**Comment by eddierubeiz** [comment]
Yeah, only 2 places. Your argument makes sense. No need to complicate this.

**Comment by apinkney0696** [comment]
Reached out to Chuck and the library folks and this is no longer happening. Closing ticket as we are off the hook.
