### ISSUE TITLE
Changes to support "Exhibition"  type of collection

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#1920]
We're going to use the existing "Collections" feature to support our aggregation of digitial items featured in an exhibition, by making the following small tweaks:

1. Add a new Collection "department" called "Exhibition" (even though it's not really a department, hopefully this won't be confusing to metadata staff)
2. On the Exhibition page itself, the little genre title "Collection" should say "Exhibition" instead.  It should _not_ be a link to the collections list page.  I guess it will not be a link at all?
3. "Exhibition" type collections will NOT show up on collections list page https://digital.sciencehistory.org/collections
4. On individual work page, there will be a new line _under_ "Collections" labelled "Exhibited in" with (one or more!) "Exhibition" type collections it's assigned to. 

@apinkney0696 please review to make sure this matches your understanding and let me know if i'm missing anything!

**Comment by jrochkind** [comment]
(I don't know how this wound up an "epic" in Zenhub, I didn't mean to use that feature which I'm not familiar with -- but don't know how to turn it back!)

**Comment by apinkney0696** [comment]
This all looks good to me and covers everything we discussed earlier. Thanks!
