### ISSUE TITLE
Change Collections to Exhibitions heading in search results

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1932]
Hi! I noticed while searching today that the Collections heading appears over an exhibition option in the search results, see:

<img width="1396" alt="Screen Shot 2022-11-07 at 3 28 31 PM" src="https://user-images.githubusercontent.com/78036563/200413926-c42ec08c-7881-4afd-8d86-e4df7dfaa65f.png">

Would it be too difficult to change that to say "Exhibitions"?

**Comment by jrochkind** [comment]
Good catch, thanks, we missed that one. Yup, will fix.
