### ISSUE TITLE
export of thumbnail urls for collection blog project

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1944]
I would please like a url leading to the thumbnail of the representative image for each of the following records: 
[URL_thumbnail_export_IDs.xlsx](https://github.com/sciencehistory/scihist_digicoll/files/10006638/URL_thumbnail_export_IDs.xlsx)

Let's test it with this record from Akron, Ohio (https://digital.sciencehistory.org/works/1v53jx54b) before doing the whole export. I'll just have to plug it into ArcGIS to test the URL option.

**Comment by eddierubeiz** [comment]
Sounds good - let's just start experimenting with that one work. Its representative asset is [1c18dg34s](https://digital.sciencehistory.org/admin/asset_files/1c18dg34s
), and here are six URLS that will forward you to six presigned (expiring) URLS for thumbnails of increasing size:

- https://digital.sciencehistory.org/downloads/deriv/1c18dg34s/thumb_mini?disposition=inline
- https://digital.sciencehistory.org/downloads/deriv/1c18dg34s/thumb_mini_2X?disposition=inline
- https://digital.sciencehistory.org/downloads/deriv/1c18dg34s/thumb_standard?disposition=inline
- https://digital.sciencehistory.org/downloads/deriv/1c18dg34s/thumb_standard_2X?disposition=inline
- https://digital.sciencehistory.org/downloads/deriv/1c18dg34s/thumb_large?disposition=inline
- https://digital.sciencehistory.org/downloads/deriv/1c18dg34s/thumb_large_2X?disposition=inline

Let's pick one of these sizes before we move to the next step.

**Comment by eddierubeiz** [comment]
Our winner is https://digital.sciencehistory.org/downloads/deriv/1c18dg34s/thumb_large?disposition=inline .

**Comment by eddierubeiz** [comment]
[This spreadsheet](https://github.com/sciencehistory/scihist_digicoll/files/10043910/extra_metdata.xlsx) contains thumbnails for all published works, in the format described above. You will need to filter out the rows you don't need in Excel, but I can certainly help with that.

**Comment by eddierubeiz** [comment]
I did a bit of filtering in Excel; [here's the data you need](https://app.zenhub.com/files/153306763/83548665-845e-4fb9-b7bf-f60558a48619/download).
