### ISSUE TITLE
Reorganize account types

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1948]
This is part of ref #1946

| Who      |  ✅ |  ⛔ |
| ----------- | ----------- | ----------- |
| Admin      | ✅ Everything       |  |
| Editor   | ✅ Create ✅ Edit ✅ Publish        | ⛔ Delete |
| Viewer   | ✅ View ✅ Add to digitization queues        | ⛔ Edit ⛔ Delete |

**Comment by jrochkind** [comment]
Recommend spending some time with access_granted README and this wiki page, for orientation: https://github.com/chaps-io/access-granted/wiki/Role-based-authorization-in-Rails

(I am reviewing it too)
