### ISSUE TITLE
One more Collection Blog Export

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1951]
Last one, I hope! Could I please have an export of the following:

Items from the COLLECTION: Papers of Georg and Max Bredig
Items with the AUTHOR: Bredig, Georg, 1868-1944

Title
Date
Place
ID

Please and thank you!

**Comment by eddierubeiz** [comment]
Hi @apinkney0696 ! I'm attaching [a spreadsheet that I think you should be able to use](https://github.com/sciencehistory/scihist_digicoll/files/10043910/extra_metdata.xlsx). Let's talk in person when you have a second.

**Comment by apinkney0696** [comment]
Both are good ideas and definitely something to think about! I've needed these a few times for random purposes now, so I'm not opposed to making a self-service tool sometime in the new year if there's a good time.
