### ISSUE TITLE
`ffmpeg` can't load `libvorbis` shared library in Github Actions CI tests.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#1978]
Started happening yesterday. Not fun, but needs to be investigated and fixed.

**Comment by jrochkind** [comment]
Hi, I need more info!

"In CI tests" means on github actions?  Can you link to a github action URL demonstrating, presumably for a failed test?

Or do you mean when running the tests locally on your dev machine?  The whole test suite still passes locally for me, I think. If it's just your machine, have you tried reinstalling ffmpeg with homebrew?  Maybe it's related to your OS upgrade. 

The ticket needs more info explaining where you saw this, and exactly what happened (like copy paste error message, whatever).

**Comment by eddierubeiz** [comment]
Yup -- here's the URL you need: https://github.com/sciencehistory/scihist_digicoll/actions/runs/3587564450/jobs/6038052228

**Comment by eddierubeiz** [comment]
```bash 
Running `ffmpeg -y -i /tmp/shrine20221130-3705-db66qh.flac -ac 1 -codec:a aac -b:a 64k /tmp/temp_deriv20221130-3705-e1b0o7.m4a` failed with
         exit status: 127
         stdout: Nothing written
         stderr: ffmpeg: error while loading shared libraries: libvorbis.so.0: cannot open shared object file: No such file or directory
     # ./app/uploaders/asset_uploader.rb:103:in `block in <class:AssetUploader>'
     # ./spec/models/asset/derivatives_spec.rb:45:in `block (4 levels) in <main>'
```
