### ISSUE TITLE
Download file name for ris file.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#198]
We may want to customize the name of the file downloaded when users request an RIS 

See https://github.com/sciencehistory/scihist_digicoll/pull/197 for the files that need to be modified, and 

https://github.com/sciencehistory/chf-sufia/blob/a103c5908af90c9076cb826140527213ba2e645f/app/controllers/curation_concerns/generic_works_controller.rb#L31-L34

for an example of how it was done in Sufia.

**Comment by jrochkind** [comment]
Thanks! Only file that needs to be modified is WorksController where it generates the response.

**Comment by eddierubeiz** [comment]
Get it to use the same recipe as it uses when you download an original file.
