### ISSUE TITLE
adjust full text relevancy ranking (omitNorms default false?)

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2013]
I created our fulltext solr fields with `omitNorms="true" `, but I think that was actually a mistake, I'm not sure what I was thinking. 

Would like to try it without that. 

We don't have any formal way to evaluate relevancy ranking, but i can do different way in staging, and ask people to compare. 

branch: solr_no_omit_norms_fulltext

**Comment by jrochkind** [comment]
So as far as I can tell the effect of omitNorms here is basically that the length of the fulltext document no longer matters. 

Normally 10 matches in a 100 page document might be ranked _below_ 5 matches in a 4 page document. Because standard TF-IDF relevance ranking kind of normalizes per size of document, like 5 matches in a 4 page doc represents _more_ of the doc than 10 matches in a 100 page doc. 

This is standard relevancy ranking, so I guess usually what people want?

But perhaps we don't want it here. Maybe if you enter say "Detroit", you want the doc with 10 matches over 5 matches, even if it is 100 pages vs 5?

**Comment by jrochkind** [comment]
Not for now.

**Comment by jrochkind** [comment]
We're going to re-open this to reconsider now that we have OCR full text too.

**Comment by jrochkind** [comment]
We decided Wed-Thursday Oct 4-5 are good days to demo this in staging and evaluate.

**Comment by jrochkind** [comment]
@apinkney0696 This was on staging last week, but i think maybe we all forgot to look at this last week?  

Do you want to pick more days for us to put it on staging to compare?

**Comment by apinkney0696** [comment]
Yep, totally slipped my mind. Any day this week would be fine.

**Comment by jrochkind** [comment]
We decided the difference was so subtle, let's just go with the standard way -- back to omitNorms=false, the 
 Solr default -- not done yet as of this comment.
