### ISSUE TITLE
Viewer bug (zoomed in on opening)

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2023]
When a user clicks on an asset to open in the viewer, it automatically opens the image slightly zoomed in. If the user exits and opens the viewer again it appears to be normal. This could be a bug related to the newest Open Sea Dragon update.

**Comment by jrochkind** [comment]
Isolated reproduction reported on OpenSeadragon discussion forum, asking for advice:

https://github.com/openseadragon/openseadragon/discussions/2279

**Comment by jrochkind** [comment]
Rolling back OpenSeadragon to 3.0 until we resolve for 4.0. Let's leave this ticket open until we resolve and upgrade though.
