### ISSUE TITLE
Spellcheck in DC

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2042]
Spellcheck options to appear on 0 results pages.

Suggest new spellings from titles and subject headings in the database.

Currently, the page says:

> No entries found
> No results found for your search
> Try modifying your search
> Use fewer keywords to start, then refine your search using the links on the left.

In addition to spelling suggestions, could we also update the text to say:

> No entries found
> No results were found for your search
> Try modifying your search and check your spelling
> Use fewer keywords to start, then refine your search using the links on the left.

**Comment by jrochkind** [comment]
Also, using the Solr spellcheck feature has _some_ risk of harming our Solr performance, I seem to recall some samvera people saying they had issues with it -- and we are having some issues already where for some reason our searchstax solr occasionally times out -- but we'll just have to try to find out!

**Comment by apinkney0696** [comment]
Yes, that was my initial proposal, however, I'm open to it appearing on every search page, especially if that's easier from a technical standpoint. As you said in our meeting, a user might get results, but not the results they were expecting. 

And great, let's go ahead and modify the zero results page text as a simple first step.

**Comment by apinkney0696** [comment]
Okay, did a little digging, and in the top 250 search terms in the past week alone, I found many names searched and at least three examples of misspelled names: 

Eli Lilly instead of Eli Lily;
Betty Washington Greene and Bettye Washington Green instead of Bettye Washington Greene;
and George Bredig instead of Georg. 

I can keep looking through our search term data, but so far this has me convinced that a spelling suggestion would be a helpful feature for our users!

**Comment by jrochkind** [comment]
Nice! I love having data!

I wonder if we might even want to search ONLY on "creator" names (as we have them recorded). If that's our main use case. 

That also shows some of the  challenges of trying to do this kind of spell-suggest. The words "Green" and "Lily" _do_ both appear in our database.  In fact, "Green" appears many _more_ times than "Greene".  

Getting a spell suggest that can notice that you meant "Bettye Washington Greene" when you entered "Bettye Washington Green" -- I'm not sure if the Solr built-in "spell suggest based on your actual index" is going to be capable of that unfortunately. 

We can play around with it -- having those as target examples for "It would be nice if it would fix these" is very helpful. If you can come up with any more examples and provide us a list, that would actually be super helpful. 

If that is the _sort_ of thing we want to do... I actually wonder if we'd be better off manually maintaining a list of "common errors" to suggest, based on reviewing search queries. That's a lot of work though. I'm not totally sure how else we manage to correct "green" to "greene".

**Comment by jrochkind** [comment]
@apinkney0696 

Also “George Bredig” actually has a lot of hits!  In part because I think Solr stemming actualy makes it hit on “georg”?

So if we were only supplying suggests on 0 hits, "George Bredig" wouldn't get any. 

It would actually be super helpful to have a list of known errors we want to correct -- then we could test a possible implementation with them, and see how many it manages to correct!

**Comment by apinkney0696** [comment]
Sure! For now, here are some more misspelled names that would garner zero results:

 "Galileu" for Galileo
"fritz habee" for fritz haber
"Friedich Whler" and "frederich wohler" for Friedrich Wohler
"frankl" for frankel
"farbschuule" for farbschule (I don't think this is a name though)
"eugen e. garfield" for Eugene Garfield
"Erwin Scrodinger" for Erwin Schrodinger

Happy to find more if desired.

Based on your comments, I'm starting to think we should only supply suggestions on 0 hit searches, so the example of "George Bredig" isn't a good one, because that would lead a user to Georg Bredig records. 

If we can't find a simple way to do this, (as with your Greene vs. Green example, it seems super tricky) I think making the text that appears prominently say "check your spelling" somewhere would be a super helpful and simple solution.

**Comment by apinkney0696** [comment]
Closing as we re-did the 0 results page to include text about checking spelling. Text suggestion solutions are complicated, so we will re-open and consider the work if we receive further evidence that users are having a hard time realizing they have a typo.
