### ISSUE TITLE
Investigate and research OCR

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2043]
Here are some things (that I can think of) that we'll need to consider:

- What OCR tool options are available, and which will be best for us
- What are the costs associated with these tools?
- How we may need to update the record interface
- How we may need to update the results page interface
- How will staff workflows change, if at all (e.g., will OCR occur automatically on ingest or will I need to do something after digitization?)
- And I'm sure, lots of technical miscellanies outside of my wheelhouse!

Might be worth making a wiki page to record our findings too.

**Comment by jrochkind** [comment]
https://sciencehistory.atlassian.net/wiki/spaces/HDC/pages/2206203905/OCR+planning+notes

**Comment by apinkney0696** [comment]
Closing as the research phase is complete.
