### ISSUE TITLE
Ensure all audio originals in the digital collections have consistent metadata

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2054]
We have changed our on-ingest file characterization for audio files over the past two years - notably, as part of our move to shrine 2.0, we started calculating audio duration on ingest.

If we make the audio metadata in the collection more consistent, we can:
* simplify the creation of combined audio derivatives
* provide more helpful error messages when a user attempts to create combined audio derivatives from bad audio.

**Comment by jrochkind** [comment]
@eddierubeiz I kind of thought I already did this, but now I realize I'm not sure, so I guess we should check again to be sure!

**Comment by eddierubeiz** [comment]
Yeah - see  https://github.com/sciencehistory/scihist_digicoll/pull/474. I'll double-check regardless as part of my investigations when I come back to this.
