### ISSUE TITLE
Fix interviewee/interviewer names that have punctuation to be bold in OHMS display

### ISSUE THREAD

**Issue by rachellane12** [sciencehistory/scihist_digicoll#2064]
As discussed in our meeting on February 13, 2023, please change the code to bold last names that are more than just one word: people with last names with hyphens or spaces, for example.

All interviewee/interviewer names are always capitalized and followed by a colon. Doug Boyd suggested having a couple characters followed by a colon to solve this issue.

Examples in the DC:
1. [Solnica-Krezel](https://digital.sciencehistory.org/works/r706kyj#tab=ohTranscript)
2. [Saberi](https://digital.sciencehistory.org/works/19wa0af#tab=ohTranscript)

**Comment by jrochkind** [comment]
let's see if we can find the code in open source OHMS viewer in PHP, and copy it's semantics exactly. But if we can't, we can make our own specs. 

OHMS viewer in PHP can be downloaded here: https://www.oralhistoryonline.org/start-using-ohms/

**Comment by jrochkind** [comment]
@eddierubeiz I found the regexp the OHMS viewer uses... 

    '/<p>[[:space:]]*([A-Z-.\' ]+:)(.*)<\/p>/', "<p><span class=\"speaker\">$1</span>$2</p>"

That one is being applied AFTER html has already been applied, so uses `<p>` and `</p>`, ours might be in terms of newlines instead, depending on when it happens. But we can see basically what it does.... any list of all caps with some punctuatio and spaces, followed by a colon....  okay, if that's good enough for OHMS I guess it's good enough for us.

**Comment by eddierubeiz** [comment]
Thanks for the detective work!

**Comment by jrochkind** [comment]
@eddierubeiz says running the test suite produces a warning we should fix.
