### ISSUE TITLE
Edits to Copyright Dropdown menu

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2070]
Decisions from a meeting with Michelle, Patrick, Gabriela, and myself.

From the copyright dropdown menu, please...

REMOVE:
In Copyright- EU Orphan
In Copyright - Non-Commercial Use Permitted
No Copyright - Non-Commercial Use Only
No Copyright - Contractual Restrictions

ADD:
Creative Commons Attribution ([CC BY](https://creativecommons.org/licenses/by/4.0/))

Thank you!

**Comment by eddierubeiz** [comment]
The copyright settings we're getting rid of have no works associated with them, so there's no mapping to be done.

**Comment by eddierubeiz** [comment]
@apinkney0696 : I deployed this to staging.

Take a look also at the icons and copy at https://staging-digital.sciencehistory.org/works/rh3uqew  - or just see below.

![Screenshot 2023-02-15 at 11 29 18 AM](https://user-images.githubusercontent.com/94723/219090701-3620bf40-d303-42dc-918d-1838be72331d.png)

Maybe also check [the diff](https://github.com/sciencehistory/scihist_digicoll/pull/2072/files#diff-793d99e4973e82eec41394ed4f60e59872551e3776d2f04938b35f41d187942a) and confirm that the CC link is correct and that I didn't accidentally remove anything that shouldn't have been.

**Comment by apinkney0696** [comment]
Looks great to me, Eddie! Just what I needed. Everything highlighted in red in the code you linked does seem to describe the four items for removal, and the dropdown menu in staging looks perfect. 

Thank you for the quick turnaround, I really appreciate it!
