### ISSUE TITLE
Require a pull request before merging to the `master` branch?

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2073]
At https://github.com/sciencehistory/scihist_digicoll/settings/branch_protection_rules/5179655
is an unchecked checkbox:

- [ ] **Require a pull request before merging**
When enabled, all commits must be made to a non-protected branch and submitted via a pull request before they can be merged into a branch that matches this rule.

Let's talk about checking this box:
- I cannot remember ever *intending* to commit directly to `master`.
- This morning I found out to my dismay that I am perfectly capable of absentmindedly committing and, yes, pushing to `master` before realizing I forgot to `git checkout -b` and make the changes via a branch and a PR. It's not a big deal as long as this is caught before deployment, but it's embarrassing, a waste of time, and risky.

Are there any drawbacks to checking this box? Let's at least have a conversation about it.

**Comment by jrochkind** [comment]
Sure, we can do it. 

Trying to think of cases where it might be annoying not to be able to commit directly to master....

What if something has gone horribly wrong and we need to revert something?  We'd have to make a PR reverting it, and then merge that PR... but honestly, when something has gone horribly wrong is probably a bad time to be doing "dangerous" things in a hurry anyway. 

I guess seems fine?

**Comment by eddierubeiz** [comment]
OK, I feel like we have consensus. I'm going to go ahead and click the box...

**Comment by eddierubeiz** [comment]
(I did it)
