### ISSUE TITLE
Upgrade Redis

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2074]
Quoting & slightly redacting a recent email from Heroku:
Your Redis database redis-triangular-75789 on scihist-digicoll-production is running a deprecated version (6.0.17) and will not be supported after 30 Jun, 2023.
We urge you to upgrade to version 6.2 as we’re disallowing provisioning of the deprecated version from 30 Apr, 2023. If no action is taken, then we’ll perform forced upgrades after 30 May, 2023.
You can upgrade your Redis database to the latest default version by using heroku redis:upgrade command. You can read more about this procedure in our [Dev Center article](https://devcenter.heroku.com/articles/heroku-redis-version-upgrade).

**Comment by eddierubeiz** [comment]
Based on a quick look at https://devcenter.heroku.com/articles/heroku-redis-version-upgrade the Heroku recipe for this is very similar to updating PostGreSQL.

Staging is already running 6.2.3.

**Comment by jrochkind** [comment]
If already tested on staging anyway, sounds good. Probably an oversight that we're running different versions on prod vs staging anyway.
