### ISSUE TITLE
OCR implementation

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2080]
First: Tesseract vs. AWS Textract? Determine which service best fits our needs.

Preliminary parameters for works in the digital collections that should be OCRed:

Selection One:
Format: Text
Language: English
Department: Library
Date: Post-1860 (Modern Library Materials)

Selection Two:
Format: Text
Language: English
Department: Archives
Date: Post-1900
Genre: Advertisements OR Pamphlets OR Handbooks and Manuals OR Publications

These parameters are meant to select only typewritten items, but there are some handwritten works that get through, and we also will be missing some items that would be good contenders for OCR. What happens if OCR is run on non-typewritten objects? Can we find a way to manually select items for OCR, at least while we are doing our backlog?

**Comment by jrochkind** [comment]
@apinkney0696 can we eliminate more handwritten works -- without eliminating much we want to include -- by adding a constraint "and genre does NOT include `manuscripts`)?

> What happens if OCR is run on non-typewritten objects?

It may work poorly. If it works poorly, we'll just have a bad OCR, including lots of mistakes or nonsense.  Which will mean features we build using OCR will work poorly for this item -- indexing nonsense in a search, or providing nonsense in a visible text version, or in a text layer in a PDF, or a "read this aloud" feature. If we put some visible markings to tell users (eg) "Hey, this item has searchable text  PDF", then the user may be disappointed. 

> Can we find a way to manually select items for OCR, at least while we are doing our backlog?

Here is what I had been considering:

* The "default" setting is according to metadata-based specifications like the ones you are working on above
* But staff can also over-ride default in both direcitons -- say, yes, OCR this even if it doesn't meet metadata specs; or say, no, don't OCR this even if it does
* The overrides should be available both on a "work" level (applying to all pages in the work), as well as the "page" level (over-riding an override set on work level!)

I had been considering that... but it is kind of complicated to implement. Is it also convoluted for staff to understand?

Should we instead abandon the metadata-based spec entirely, and _only_ base OCR on explicitly set by staff values?  Perhaps for the backlog we would generate these values based on the metadata-based spec (which can then be overridden manually), but going forward these would just have to be set by staff on ingest (either on work or page level or both?)
