### ISSUE TITLE
Make a test script for command-line utilities installed on deploy machines (eg heroku)

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2090]
We have a number of unix command line utilities we arrange to have installed on our heroku dynos. 

We don't have any automated testing that this actually worked. 

When we're changing something on heroku; or wanting to check our assumptions; or if we were moving somewhere off heroku -- we just need to test manually that all CLI utilities are installed and working properly. 

We do have some notes for manual testing, here: https://sciencehistory.atlassian.net/wiki/spaces/HDC/pages/2088271873/Derivative+generation+on+Heroku#Diagnostics-for-derivative-generation-software

We should have a runnable script that run on an actual live deployment machine, and checks that all of our utiltiies are installed properly, and gives good diagnostics. 

This could be bash, but also could just be a simple ruby script. We're going to have ruby available on anything we're checking. Might be easier and more maintainable. (But can we do it avoiding any gem dependencies?)

Tools include:
* mediainfo
* pdfunite
* vips
* ffmpeg
* ffprobe
* (soon) tesseract

We might make sure they are installed and run properly without error; check `--version` is as expected. For any optional configuration or plugins, check they are there. Etc.

**Comment by eddierubeiz** [comment]
Three cheers for this idea.
You'll want to draw on this: https://sciencehistory.atlassian.net/wiki/spaces/HDC/pages/2088271873/Derivative+generation+on+Heroku
