### ISSUE TITLE
OCR management features

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2095]
Once #2092 is finished/merged, the functionality will be there to create hOCR and attach it to an Asset model. But this won't be wired up to ever actually get called. 

We need management functionality first. This is one Issue to specify, but may likely be multiple PR's. 

* staff-editable fields on both `Work` and `Asset` models, for "should OCR" (or "OCR desired", or I'm not sure what it should be called). We want to set it on Work, but be able to over-ride it (in either direction) on individual idiosyncratic asset. 
   * On the `Work` model, two possible values: Yes or No. (Default: "no")
   * On the `Asset` model, we actually have three separate values:  Ordinary same as set on work; Over-ride "Yes" for this specific Asset; Over-ride "No" for this specific asset. (Default: "inherit from work")
   * it's possible we want a new "tab" on Work management page for OCR, because there will be more management stuff too (below)
   * But we also need the `Work` level one to be editable on our "batch" edit specifically (I forget if this happens automaticall or what)

* Code to make those selections actually result in the OCR happening. Keep in mind that there are a variety of possible life-cycle orderings in time, all of which should be supported:
  *  At the point a Work is set to OCR, it might already have assets attached, that will need to be OCRd
  * But a new Asset might be attached after a Work has already been set to OCR=yes, and it will also need to be OCR'd
  * After assets have OCR, the Work as a whole or the individual Asset may have their settings changed such that OCR is no longer desired; it should be removed
  * We've talked about implementing this as a regular cron job that checks if things need their state changed -- I'm honestly not sure what other options there might be or what the best way might be, but that's definitely a contender! 
  * Actual OCRing should definitely happen in bg job, using the job created in #2092 

* Additional management functions (perhaps on an "OCR" tab)
  * At Asset level, echo back the actually applied "OCR desired" value, combining both work and asset settings.    
  * Ability to see if hOCR is _actually attached right now_.  
     * At an individual Asset admin page, but maybe also at the Work level as "X out of N" or whatever?
  * Ability to see the TEXT (and/or the complete raw hOCR?) for an existing attached OCR, to get a sense of how accurate it is.  
  * Maybe?: Ability to forcibly _remove_ OCR if it's already attached, or forcibly trigger 'OCR _right now_' for an OCR that would be scheduled at some future point?

**Comment by eddierubeiz** [comment]
I would also like to be able to filter works by "have at least one asset with OCR" or "OCR requested" in the list-of-works admin screen

**Comment by eddierubeiz** [comment]
After #2120 is merged, I'm going to move this ticket to "Review". A couple of the specs have shifted slightly during the development process, but we have all of the basic affordances described above in the UI:

- You can ask for OCR to be created for all images on a work;
- You can ask for OCR via the batch edit tool;
- A rake task creates that OCR for all images that need OCR, and removes OCR for all images that don't;
- On the work admin page, you can see which images have OCR and which don't;
- On the asset admin page, you can look at the OCR for that asset.

Things we decided *not* to do, which could become separate tickets if and when we need them:
- A summary view of *all* the OCR for a work, concatenated.
- The ability to override work OCR settings at the asset level (e.g. request OCR for a single asset, or request no OCR for all assets except one.)
