### ISSUE TITLE
URLs in Citations don't include protocol, arne't real URLs

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#210]
In chf_sufia, when looking at the citaiton under "Cite As", you get a URL like:

    https://staging.digital.sciencehistory.org/works/zk51vh89m.

In scihist_digicoll staging, the URL looks like:

    kithe.sciencehistory.org/works/fb4949523

That's not actually a URL! It needs the https. 

Same in RIS export, so it's an issue in CitableAttributes. In scihist_digicoll:

    UR  - kithe.sciencehistory.org/works/fb4949523

Needs the http://!

You could look at how this was done in chf_sufia (probably hackily) and do it that way, or we could figure out a 'righter' way to do it. 

There should probably be a test for CitableAttributes ensuring it's a full URL with protocol and host and everything.

**Comment by eddierubeiz** [comment]
Done!
