### ISSUE TITLE
Updates to Restricted Oral History Record Pages (Manual Review)

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2100]
@rachellane12 @sarahschneiderSHI 

Restricted oral history interfaces with files available upon request were found to be confusing for users. The following text and design update suggestions are for interviews requiring manual review of file requests. The goal of these updates is to make the available files, the reasoning for restriction, and the request process clearer to users. 

Please view the files located here for page sketches: https://files.sciencehistory.org/navigate/folder/cc189af2-7268-43b5-b4bc-327a67c847ab

Updates to record page:
- [ ] Change “Available upon request” to “Submit a brief form for a staff member to review your request for the following files:  __ PDF Transcript File(s) [insert icon] and ___ Audio Recording File(s) [insert icon].”
- [ ] Move Request Access icon underneath the list of available files.
- [ ] Language in blue box: "If you have any questions about transcripts, recordings, or usage permissions, contact the Center for Oral History at [oralhistory@sciencehistory.org](mailto:oralhistory@sciencehistory.org)."

Updates to Request form:
- [ ] Text under page title to read: "To receive the files for "Oral history interview with XX" via email, please fill out the form below. **After your request is reviewed, you will receive an email response, usually within 3 business days. If permission is granted to access the interview, you will receive the files via email.** A request is needed to access this oral history interview due to privacy restrictions stipulated by the interviewee."
- [ ] Intended Use field caption to read: "So that we can better understand our audience, please tell us how you plan to use this oral history interview."
- [ ] Email address field caption to read: " Your files will be emailed to this address."
- [ ] Move Blue box to bottom of page and emit the first sentence about CC licensing.

**Comment by apinkney0696** [comment]
Thanks for the clarification @rachellane12! Jonathan suggested a little less-intense version: "Please tell us how you intend to use this oral history interview so that we may inform you about any relevant interviewee restrictions." 

I'm fine with either version!

**Comment by rachellane12** [comment]
@apinkney0696 I think I prefer Jonathan's version since it's a little less-intense!

**Comment by jrochkind** [comment]
@rachellane12 y'all are also of course welcome to write your own version or tweaks, now or in the future. Changing wording alone is fairly easy for us.

**Comment by apinkney0696** [comment]
Great! Thanks for weighing in, Rachel, and yes, feel free to suggest additional wording edits at any time! @jrochkind, I think we can go ahead and adjust that sentence to your suggestion for now.
