### ISSUE TITLE
Updates to Restricted Oral History Record Pages (Automatic Release)

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2101]
@rachellane12 @sarahschneiderSHI 

Restricted oral history interfaces with files available upon request were found to be confusing for users. The following text and design update suggestions are for interviews with automatic release files. The goal of these updates are to make the available files, the reasoning for restriction, and the request process clearer to users. 

Please view the files located here for page sketches: https://files.sciencehistory.org/navigate/folder/cc189af2-7268-43b5-b4bc-327a67c847ab

Updates to record page:
- [ ] Change “Request Access” button to say “Get Access.” 
- [ ] Change “Available upon request” to “Submit a brief form to receive immediate access to:  __ PDF transcript files [insert icon] and ___ audio recording files [insert icon].”
- [ ] Language in blue box: "If you have any questions about transcripts, recordings, or usage permissions, contact the Center for Oral History at [oralhistory@sciencehistory.org](mailto:oralhistory@sciencehistory.org)."

Updates to Request form:

- [ ] Change "Request Oral History Access" page title to "Get Oral History Access"
- [ ] Text under page title to read: "To recieve the files for "Oral history interview with XX" via email, please fill out the form below. **You will receive these files immediately after submitting this form.** A request is needed to access this oral history interview due to privacy restrictions stipulated by the interviewee.."
- [ ] Only Name and Email address to be required fields
- [ ] Intended Use field caption to read: "So that we can better understand our audience, please tell us how you plan to use this oral history interview."
- [ ] Email address field caption to read: " Your files will be emailed to this address."
- [ ] Move Blue box to bottom of page and emit the first sentence about CC licensing.

**Comment by eddierubeiz** [comment]
Fantastic work! Thank yous so much. See also ref #1877 .
