### ISSUE TITLE
Pull number of ingested .tifs per year

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2103]
I'd like to request a spreadsheet noting how many .tif image files were ingested into the digital collections for each year of the DCs life, please.

**Comment by jrochkind** [comment]
Documenting how I did it for showing our work:

```ruby
year_counts = Hash.new(0)

irb(main):012:1* Asset.find_each do |asset|
irb(main):013:1*   next unless asset.content_type.start_with?("image/")
irb(main):014:1*   year_counts[asset.created_at.year] += 1
irb(main):015:0> end

include ActionView::Helpers::NumberHelper

year_counts.each_pair.sort.each do |year, count|
  puts "#{year}: #{number_with_delimiter count}"
end
```
## and results

2016: 2,489
2017: 12,664
2018: 5,810
2019: 4,957
2020: 5,025
2021: 14,468
2022: 17,165
2023: 1,099

**Comment by jrochkind** [comment]
not a spreadsheet, but good enough?

**Comment by apinkney0696** [comment]
Totally fine! That's awesome, thanks so much @jrochkind !!
