### ISSUE TITLE
"no results" pages blank in all collections searches (including oral history)

### ISSUE THREAD

**Issue by sarahschneiderSHI** [sciencehistory/scihist_digicoll#2106]
I noticed that, when searching specifically in the oral history collection for something that garners no results, the results page is empty. It would be great to have the results page updated to match what comes up through a "no results" search of the general Digital Collections. (Including the neat image!)

Here is a screenshot of what the oral history page looks like currently when no result is found.
![image (2)](https://user-images.githubusercontent.com/103284115/225021758-cb55bf76-eba1-4609-b014-1c6d276fd473.png)

Thanks,
Sarah

**Comment by eddierubeiz** [comment]
To reproduce:
https://digital.sciencehistory.org/collections/gt54kn818?q=dfg3

**Comment by jrochkind** [comment]
Huh, this may apply to all collection search pages, not just OH? 

Was this an accidental side effect of our no results page customization, do you think, @eddierubeiz ?  We should add `system` specs for no-results page on OH specifically, and generic collections pages.

**Comment by eddierubeiz** [comment]
Yeah - I'll take a look at this and see what I can figure out. Pending @apinkney0696's approval, I'd like to consider treating it as a bug, meaning I might not wait until next week to get started on a fix.

**Comment by apinkney0696** [comment]
Yes, please! I think this is definitely worth prioritizing if you are able to this week.

**Comment by eddierubeiz** [comment]
Sounds good!
