### ISSUE TITLE
cookie banner

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#212]
The one on current website, the color is sometimes same color as background it's over. Find new color? Add border? 

Make 'accept' button full height, even when banner gets higher on narrow screens due to wrapping?

**Comment by eddierubeiz** [comment]
Just thought of this! Glad you did put it in as an issue. Great example of a feature that's easy to forget about.

**Comment by jrochkind** [comment]
Boring work, but another thing you can always work on if you run out of work when I'm not here to discuss more, @eddierubeiz  :)
