### ISSUE TITLE
"Copyright Free" checkbox adjustment

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2125]
When checking the public domain checkbox on the homepage search, this should pull in other classifications that fall within Public Domain (see https://rightsstatements.org/page/1.0/?language=en#collection-nc No Copyright options):

- Public Domain Mark 1.0,
- No Known Copyright,
- No Copyright - United States,
- No Copyright - Other Known Legal Restrictions

**Comment by jrochkind** [comment]
Should we change the name of that checkbox if that's what it's going to search.  

I would suggest that for instance "No Copyright - United States" is _not_ in fact the same thing as Public Domain.  

For instance, Wikimedia Commons will, I believe, take Public Domain items but not "No Known Copyright" items, or "No Copyright - United States" items.  

I am worried we are mis-educating people about what "Public Domain" means, and/or giving people who _do_ know what it means misleading results if we call all of those categories "Public Domain". 

Perhaps "No copyright" or something along those lines?

**Comment by eddierubeiz** [comment]
This involves an indexing change.
