### ISSUE TITLE
Consider allowing the user to override a work's ocr settings for certain assets.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2134]
- A work with `ocr_requested == true` might have one or more assets that we **don't** want OCR for.
- A work with `ocr_requested == false` might have one or more assets that we **do** want OCR for.

See #2095  for a sketch of how this might work.

**Comment by eddierubeiz** [comment]
Agree!

**Comment by apinkney0696** [comment]
We are addressing this in #2311
