### ISSUE TITLE
Remove cookie banner (was: "cookie banner" "decline" button)

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2167]
We want to match main site, which seems to now have a "decline" button. (to match whatever legal/best practices have already been decided we should use for our websites)

* Does "decline" presumably effect google analytics tracking?
* Is "default" (before/without making a choice) to do GA tracking or not?

Interestingly Google docs claim that GA4 only uses "first-party cookies", so is not subject to GPDR and you don't need to let users opt-out at all.  But not our call, we will try to match whatever main site is doing. 

Here is some Google documentation about "consent mode", where you can let users opt-out of Google Analytics. (Again, we need to confirm this is what main site is actually doing, we need to match them!)

https://support.google.com/analytics/answer/9976101?hl=en

https://developers.google.com/tag-platform/devguides/consent

**Comment by apinkney0696** [comment]
From Caitlin:

> I consulted our lawyer and Kevin. Since Digital Collections links to our privacy policy and terms of use policy in the footer, you do not need to include a cookie banner. We explicitly mention DC on those policies, so we're covered. 

So we have the blessing to fully remove the cookie banner!

**Comment by eddierubeiz** [comment]
Reminder: we have some sort of mechanism preventing the cookie banner from displaying in tests. I forget the details, but that can be removed as well.
