### ISSUE TITLE
Cloudfront distribution for restricted derivatives.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2174]
- Create a distribution in Terraform - the restricted derivatives actually live in the originals bucket.
- The distribution should not be public, so we want to use [`trusted_signers`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#trusted_signers)
- Investigate using a [`Aws::CloudFront::UrlSigner`](https://shrinerb.com/docs/storage/s3#signer) to sign the URLS pointing at the new distribution

**Comment by jrochkind** [comment]
Actually effectively a dup of #705, which has a lot more notes about how this ended up hard.
