### ISSUE TITLE
Switch generated transcription/lation text PDFs to use sans-serif font

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2189]
Currently they use a serif font, the open source licensed "LiberationSerif". 

A sans-serif font may be easier to read, look better, and more in line with redesign. Perhaps the sans-serif version of "liberation"?

**Comment by jrochkind** [comment]
Hm, I tried switching to the free font "Liberation Sans", the sans-serif alternative to the "Liberation Serif" we were using. 

Liberation Sans is supposed to be a rough match for Arial, so seems like a good choice for us -- Arial is given as widely available fallback font of choice in our branding guidelines. 

But I'm not sure if it's just me, or if liberation sans doesn't actually look great? But I'm not sure if i'm imagining things, second opinion welcome. 

@eddierubeiz , @apinkney0696 , what do you think, good enough?  

[letter_from_rosa_zxmi3u4_english_translation.pdf](https://github.com/sciencehistory/scihist_digicoll/files/12526880/letter_from_rosa_zxmi3u4_english_translation.pdf)

**Comment by apinkney0696** [comment]
Not bad by any means. Is it an option to be consistent with the rebranding and go with the Adobe Sofia font?

**Comment by jrochkind** [comment]
> Is it an option to be consistent with the rebranding and go with the Adobe Sofia font?

I don't believe we have a license to produce and distribute PDFs that embed the Adobe Sofia font, in order to use it in PDFs we distribute. We have a license only for online use as part of a continuing Adobe Fonts subscription. 

We could look into such a license, but I'm assuming it would be cost-prohibitive. 

This is why we weren't using the actual branded fonts even from previous design either.

**Comment by apinkney0696** [comment]
Got it. Arial isn't an option either I'm assuming?

**Comment by jrochkind** [comment]
Right. We need a font with an open source/open type license that allows us to embed it in a PDF, unless we want to license a font. Arial is a proprietary typeface which Apple and Microsoft license for inclusion in their OSs.

**Comment by apinkney0696** [comment]
Got it, thanks for clarifying. I think the font you have is fine.

**Comment by jrochkind** [comment]
Thanks. And of course, we also need a font that has plenty of diacritics and such. Already we need anything in German, but would like a large complement for future use with other possible languages. 

So the "Liberation" fonts are a good bet, developed for use as general fonts in OpenOffice and some Linux distributions. 

But I may sniff around just a bit to see if there are any alternatives that seem better.
