### ISSUE TITLE
Generate list of all oral history interviews without a bib number

### ISSUE THREAD

**Issue by rachellane12** [sciencehistory/scihist_digicoll#2195]
After looking at the new Digital Collections site, @sarahschneiderSHI and I realized that some oral history interviews are missing bib numbers. We would like to go through and make sure that all oral history interviews in the digital collections have bib numbers, so a complete list of interviews without bib numbers will let us know which ones to fix.

**Comment by eddierubeiz** [comment]
I can take this one - stay tuned please.

**Comment by eddierubeiz** [comment]
Anagnostopoulos : https://digital.sciencehistory.org/admin/works/gl5p69o/edit
Augustine : https://digital.sciencehistory.org/admin/works/5dfxmcu/edit
Bailar, Jr. : https://digital.sciencehistory.org/admin/works/j58sfa7/edit
Baxter : https://digital.sciencehistory.org/admin/works/vr0wu2s/edit
Brown : https://digital.sciencehistory.org/admin/works/k643b2174/edit
Chowdhry : https://digital.sciencehistory.org/admin/works/nt2ydj8/edit
Coates : https://digital.sciencehistory.org/admin/works/qj72p8105/edit
Collins : https://digital.sciencehistory.org/admin/works/v118rf271/edit
Cooper : https://digital.sciencehistory.org/admin/works/bs701nm/edit
Dewar : https://digital.sciencehistory.org/admin/works/hd76s1109/edit
Dixit : https://digital.sciencehistory.org/admin/works/dqn3jcv/edit
Evans : https://digital.sciencehistory.org/admin/works/3b591969h/edit
Flanagan : https://digital.sciencehistory.org/admin/works/siqzmgi/edit
Futrell : https://digital.sciencehistory.org/admin/works/vm40xs61n/edit
Garber : https://digital.sciencehistory.org/admin/works/myoe75z/edit
Hackerman : https://digital.sciencehistory.org/admin/works/tb09j665k/edit
Hackerman : https://digital.sciencehistory.org/admin/works/wd375x17m/edit
Handler : https://digital.sciencehistory.org/admin/works/7disaol/edit
Harrison : https://digital.sciencehistory.org/admin/works/jb39eu1/edit
Hegedus : https://digital.sciencehistory.org/admin/works/9k41zf41s/edit
Holmes : https://digital.sciencehistory.org/admin/works/vhfkc4n/edit
Jackson : https://digital.sciencehistory.org/admin/works/58o0m67/edit
James : https://digital.sciencehistory.org/admin/works/pptbo4m/edit
Kebarle : https://digital.sciencehistory.org/admin/works/f160qwq/edit
Kline : https://digital.sciencehistory.org/admin/works/4q77fs343/edit
Kwolek (1986): https://digital.sciencehistory.org/admin/works/d217qq72t/edit
Los : https://digital.sciencehistory.org/admin/works/tur0d0j/edit
Luskin : https://digital.sciencehistory.org/admin/works/vfryv48/edit
Macfarlane : https://digital.sciencehistory.org/admin/works/dhb9sbc/edit
Malcom : https://digital.sciencehistory.org/admin/works/mrwh24g/edit
March : https://digital.sciencehistory.org/admin/works/qb98mg60w/edit
McKeown : https://digital.sciencehistory.org/admin/works/gq67js311/edit
Phillips : https://digital.sciencehistory.org/admin/works/401vbux/edit
Proenza : https://digital.sciencehistory.org/admin/works/vxhmxhi/edit
Rhett : https://digital.sciencehistory.org/admin/works/3qqfwse/edit
Saberi : https://digital.sciencehistory.org/admin/works/19wa0af/edit
Somorjai : https://digital.sciencehistory.org/admin/works/y02f8m6/edit
Standing : https://digital.sciencehistory.org/admin/works/u2b8mfv/edit
Termeer : https://digital.sciencehistory.org/admin/works/ptm8797/edit
Weissmann : https://digital.sciencehistory.org/admin/works/1z40kt98n/edit
Williams : https://digital.sciencehistory.org/admin/works/9axacta/edit
Woolston : https://digital.sciencehistory.org/admin/works/nsj7bsn/edit
