### ISSUE TITLE
Find broken "related links" to www.sciencehistory.org

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2220]
With the main site redesign/new platform -- I know they intended to keep all the URLs from old site working with redirect. And many/most of them are. 

But when testing things out and clicking around, I find plenty that unfortunatley are broken. 

We could write a script to check them all (checking for 404 HTTP response vs 200 is enough to identify the broken ones I've found), and make a list -- for either manually finding the new URL for the thing we tried to link to main site, or just removing the broken links. 

(Communications may or may not want to know about broken links, since they intended to keep them all working. We could ask them if they'd like our list). 

-----

Note also, need to check for links that do not 404, but now redirect to `https://sciencehistory.org/stories/`. See below, any former links to videos may now do this.

**Comment by jrochkind** [comment]
cc @apinkney0696

**Comment by jrochkind** [comment]
Oops, here's at least one example where checking for HTTP error status code wouldn't suffice. :( 

https://digital.sciencehistory.org/works/fq977v64q

Includes a link to:

(Video) Distilled #5: Porcelain Painting: https://www.sciencehistory.org/distillations/video/distilled-5-porcelain-painting

that redirects to a generic "stories" page at https://sciencehistory.org/stories/

It's not getting to the actual video, which... may not be on the site anymore?  Did they remove all the Distillations Videos?

**Comment by apinkney0696** [comment]
It looks like they did remove all of the videos from the main site, but not the YouTube channel - I started replacing the links to go instead to YouTube. If you were able to make a list of all the broken links I would be happy to go through and edit/remove the rest!

**Comment by jrochkind** [comment]
It is unfortunately difficult to find "broken links" in an automated fashion, when they redirect to a good page, as this one did, instead of reporting "no page found". 

But I guess if we know all videos now redirect to https://sciencehistory.org/stories/, we can flag all links that redirect to that one. 

We'll have to make a tool to go through all our links and check them -- including checking for that condition. We just need to decide when to prioritize this work, we suddenly have a whole bunch of issues coming up.

**Comment by eddierubeiz** [comment]
To start out with, here's a [list of broken links](https://github.com/sciencehistory/scihist_digicoll/files/12001003/404s.txt).

**Comment by eddierubeiz** [comment]
And here's a [list of links that aren't broken but don't forward you all the way to the destination](https://github.com/sciencehistory/scihist_digicoll/files/12012895/Non-404.broken.external.links.txt) .

**Comment by apinkney0696** [comment]
All have been manually updated. Thanks, Eddie!

**Comment by eddierubeiz** [comment]
Hey @apinkney0696 : I ran the latest code against production and there are still some broken links. I'm attaching the list below.

Many of these are duplicates, so let me know if you just want me to make some mass changes via the command line to save time. You could just say "anything that points to A should point to B instead".

[Here's the list](https://github.com/sciencehistory/scihist_digicoll/files/12232432/bad_links_august_1.txt).

**Comment by apinkney0696** [comment]
Just finished addressing this list. Hopefully that was the last of them!

**Comment by eddierubeiz** [comment]
@apinkney0696 , there are still a few left, unfortunately. Feel free to give me a search-and-replace recipe if you want and I can run it automatically.

Incomplete redirect to the "stories" page:
- 	r494vk18s: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	qv33rw655: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	p5547r37h: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	c534fn92g: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	q524jn78d: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	nc580m649: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	ng451h485: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	dz010q04x: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	8s45q8784: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	8w32r560x: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	rj4304528: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	4t64gn17g: https://www.sciencehistory.org/distillations/video/distilled-4-virtual-reality-in-the-19th-century
- 	0p096710b: https://www.sciencehistory.org/distillations/video/distilled-9-lovely-ladies-sell-instruments
- 	qn59q405m: https://www.sciencehistory.org/distillations/video/distilled-9-lovely-ladies-sell-instruments
- 	79407x355: https://www.sciencehistory.org/distillations/video/distilled-13-an-environmental-cowboy-from-the-1970s

Incomplete redirect to the "magazines" page:

- 	m326m2699: https://www.sciencehistory.org/distillations/a-chemical-empire-thriving-on-an-ancient-ocean
- 	ff3656113: https://www.sciencehistory.org/distillations/a-chemical-empire-thriving-on-an-ancient-ocean
- 	3b591858s: https://www.sciencehistory.org/distillations/a-chemical-empire-thriving-on-an-ancient-ocean

**Comment by apinkney0696** [comment]
oh sheesh. Do you know why these didn't show up on your last list?

**Comment by apinkney0696** [comment]
I'll take care of them now.

**Comment by eddierubeiz** [comment]
Sorry, I don't really have an explanation for why they weren't on the first list.

**Comment by apinkney0696** [comment]
No problem! Just wondering for the future. Hopefully all taken care of now!
