### ISSUE TITLE
Replace custom functionality for "COPYRIGHT FREE ONLY", instead use default BL facet feature for same checkbox

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2232]
Our "Copyright Free Only" checkbox (formerly "Public Domain Only") is implemented with custom functionality to add a whole new feature to Blacklight search. 

This gets us a displayed "constraint" that looks like this:

![Screen Shot 2023-06-22 at 3 00 29 PM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/a5e5863a-b10d-4025-97d8-dbd77df8d0b7)

That actually does the **same thing** as the normal facet limit, choosing "Copyright Free" from the "Rights" facet.  But it's implemented with a separate feature. 

In fact, the way it's implemented, you can apply _both_ the custom-feature one and the default one, even though they both do exactly the same thing, you can have both constraints listed on the screen:

![Screen Shot 2023-06-22 at 3 01 47 PM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/87fd2f0a-49ae-4feb-a20e-d4af5d871d1d)

## Why did I implement it this way?

I can't really remember?

* Maybe we _really_ wanted a "cleaner" URL param? With the custom function we get `&filter_copyright_free=1` instead of the really messy default Blacklight `&f%5Brights_facet%5D%5B%5D=Copyright+Free`.  But our URL params (from Blacklight) are so messy anyway, I can't see how this matters. 

* Our _original_ implementation had the search bar (with this checkbox) modifing the _current search_.  It's possible it would not have been so easy to use the normal BL feature with that design? But we moved away from that a while ago, and I don't see us going back. 

## Why remove this?

It's extra code to maintain, and especially it's extra code that we have to figure out how to migrate to Blacklight 8.  Specifically the way we are making the custom "constraint" appear is going to break in Blacklight 8, and it's not totally clear how to migrate it. 

If we get rid of this custom implementation, we don't have to worry about it. 

**We would still have the checkbox**, it would just be implemented to add the typical `&f%5Brights_facet%5D%5B%5D=Copyright+Free` value in, and then we wouldn't need any of the custom implmenetation of custom search function on the Blacklight end.

**Comment by jrochkind** [comment]
@eddierubeiz I realized that when we changed "public domain only" to "copyright free only" -- and changed the URL param -- we did NOT put in a redirect to keep any bookmarked URLs with the old param working?  Maybe we should have? And should do so again here if it changes again?

**Comment by eddierubeiz** [comment]
Supporting the old URL param is fine by me, yes!
