### ISSUE TITLE
Use of m4as in DC for Oral History

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2241]
My understanding is that we need to check the app to make sure it properly supports this file type (downloading, in-app listening, derivative generation, etc.). Including the interviews that had m4a original files that were then converted to WAV and then to FLAC.

We also want to establish ourselves as stakeholders for future OH decisions that have technical impacts, i.e., the production of new file types, audio file conversion workflow adjustments, etc. 

What are our other to-do's here?

**Comment by jrochkind** [comment]
I think you got it!

The particular place I suspect needs attention is creating "derivatives" for downloads -- at least in case of by-request emailed downloads, and that might be the only place where it comes up.  

If an m4a original... do we want to create an mp3 derivative too, or is the m4a original sufficient?  In any cases, assure originals and derivatives are labelled properly. 

> Including the interviews that had m4a original files that were then converted to WAV and then to FLAC.

I think we should talk to OH staff about this workflow -- my initial reaction is that there is no reason for this workflow, it is inflating file sizes for no reason, if not also losing audio information.  I suspect uploading the original m4a's is far preferable (although does requres us to ensure the software handles it appropriately, per this ticket). 

Once we have a decision/understanding on appropriate workflow for m4a originals, we should ensure it's documented in the appropriate place(s), and that relevant staff knows to refer to appropriate documentation, to maximize chances of consistent treatment.

**Comment by jrochkind** [comment]
Oh wait, also -- it may be that m4a is a "container" format that can have diverse contents, some more universally playable and/or suitable for preservation than others, we may want to characterize the nature of the m4a on ingest to include as technical metadata.  If not require only certain kinds of m4a's on ingest?  And/or convert certain kinds?

**Comment by jrochkind** [comment]
Hm, it looks like m4a support may not be as universal as mp3... we may want to provide mp3 derivatives too in cases where we have m4a originals?  Not sure, more research/advice would be good, perhaps @archivistsarah has some background knowledge.

**Comment by jrochkind** [comment]
@sarahschneiderSHI @rachellane12  (cc @eddierubeiz and @apinkney0696 )

It may be a while until we can look at this thoroughly. 

In the meantime, I'd say the ideal, when you have m4a originals, would be uploading the m4a originals to the Digital Collections. 

Our only concern is we haven't thoroughly vetted it to make sure it does this properly. So I'd recommend you just test it as thoroughly as possible, including all functions that a user might use.  Feel free to use staging server if you'd like. 

If you have different OH's with different availability/restriction levels, they would need to be tested independently, as they may behave differently, have different functions, etc. 

Let us know of any issues or problems you find!  If you don't find any, I'd say go ahead with m4a for now. 

When/if Digital Collections can handle m4a -- I see no reason to convert m4a originals to WAV or FLAC for Digital Collections.   Generally, even outside Digital Collections, I'm not sure if there is any reason to convert m4a originals to WAV or FLAC, but perhaps there's something I'm not aware of. I worry such a conversion will increase file sizes, with no increase in audio quality, and also possibly confuse future users or staff about the provenance and nature of these files.

**Comment by rachellane12** [comment]
@jrochkind Thanks for your work on this. I will proceed as you listed above and let you know of any issues or problems!

**Comment by sarahschneiderSHI** [comment]
Noted--thank you for the information!

**Comment by rachellane12** [comment]
I attempted to ingest the original m4a audio files for Malcom, Augustine, Lovejoy, and Proenza (all the interviews converted from m4a --> wav --> flac). The DC identified all the m4a files as video files even though they were from Zoom interviews like Dixit's interview (which is a Zoom interview and is an m4a file and was identified as audio in the DC).

I have created a folder in M/Oral Histories/Updated Audio called `m4a_audio_files_identified_as_video_in_dc` that has all the original m4a files for Malcom, Augustine, Lovejoy, and Proenza that the DC identified as video.

**Comment by rachellane12** [comment]
I did some more digging and discovered that the Dixit audio files under properties --> details --> file --> attribute have the letter "N" while Malcom, Augustine, Lovejoy, and Proenza all have the letter "A." Don't know if that is important but wanted to share!

**Comment by jrochkind** [comment]
@rachellane12 When you say "under properties --> details --> file --> attribute ", are you talking about on the Windows desktop, right-clicking on the file? Or somewhere else you are accessing that information in that way?

Do you know if there was any difference in where the files came from, as far as you know they both came out of zoom in the same way?

**Comment by rachellane12** [comment]
@jrochkind Yes, correct. Right-clicking on the file.

I believe all the PCAST interviews were recorded via our collaborators at Rice University and their Zoom account while Dixit's interview was recorded with the Institute's oral history Zoom account.

**Comment by apinkney0696** [comment]
New workflow was established after COH department was advised by Digital Preservation Archivist. As of now, OH "preservation files" (including m4a originals) are saved on J drive. Made decision to convert M4a files to mp3s prior to ingesting into DC.

**Comment by eddierubeiz** [comment]
Just adding this in here:
https://sciencehistory.atlassian.net/wiki/spaces/HDC/pages/2211348485/Oral+history+audio+files
