### ISSUE TITLE
Generate PDFs which include positioned OCR text

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2250]

**Comment by apinkney0696** [comment]
Here are some ideas for testing, when you're ready. I'm not sure if each one of these objects would actually be an item I would select for OCR, but I am curious to see what's possible. 

Text and images
https://digital.sciencehistory.org/works/py3dc61 
https://digital.sciencehistory.org/works/y4b4fmz
https://digital.sciencehistory.org/works/65is4td
https://digital.sciencehistory.org/works/8g84mm38c


Other Languages
https://digital.sciencehistory.org/works/9vaq8vo Latin, printed
https://digital.sciencehistory.org/works/x78peme German, printed
https://digital.sciencehistory.org/works/hhohjvz German telegram
https://digital.sciencehistory.org/works/5138jg18r French, italic printed script

Standard English printed materials
https://digital.sciencehistory.org/works/c821gk49n
https://digital.sciencehistory.org/works/cc08hf65b
https://digital.sciencehistory.org/works/g158bh28p
https://digital.sciencehistory.org/works/6lty65g
https://digital.sciencehistory.org/works/d791sg93t

**Comment by jrochkind** [comment]
@apinkney0696 This is one of your desired test records:

https://staging-digital.sciencehistory.org/works/py3dc61

It has no "language" metadata field though -- in order to do OCR, we need a language metadata field to tell tesseract what language(s) it is -- and the languages need to have overlap with what we have tesseract configured to handle: Currently: English, German, French, Spanish. 

I am going to look at making admin UI/feedback more clear on this -- and I also just wanted to point it out as another thing to understand about our OCR. 

If you do want to try OCR'ing that work, you just need to edit `language` metadata to add English.
