### ISSUE TITLE
New Featured Topic: Color

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2257]
This popped up a little unexpectedly, and I've been asked for this to align with the beginning of BOLD marketing. Could we prioritize this to be finished by next Friday, 7/28? And could we please replace the Water featured topic on the homepage with this topic? Many thanks!

Please create a new featured topic with the following parameters: 

Title: 

Color

Description:

Wavelengths of light between 400 and 700 nm on the electromagnetic spectrum are known as visible light, or light that can be processed and seen by the human eye. The result? What we know as color! This digital collection features a broad selection of materials related to color. This includes the scientific study of color – colorimetry and color theory – as well as the science and practice of applying color via dyeing or painting. Browse sample books containing rainbows of dyed fabrics, instruments used to study color phenomena, interviews with scientists with firsthand experience in the pigments and dye industries, and more!

List of Subject Terms:

· Absorbance scale (Spectroscopy)
· Absorption spectra
· Autokinesis
· Bleaching
· Chromatographic analysis
· Color (Philosophy)
· Color guides
· Color in marketing
· Color in textile crafts
· Color in visual communication
· Color printing
· Color sensitometry (Photography)
· Color separation
· Color vision
· Color
· Colorfastness (Textiles)
· Colorfastness (Textiles)--Testing
· Colorimetry
· Colorimetry--Instruments
· Coloring matter in food
· Colors
· Colors--Analysis
· Color--Social aspects
· Colors--Standards
· Color--Study and teaching
· Color--Terminology
· Dye industry
· Dyes and dyeing, Domestic
· Dyes and dyeing
· Dyes and dyeing--Acrylic fibers
· Dyes and dyeing--Cellulose
· Dyes and dyeing--Chemistry
· Dyes and dyeing--Cotton
· Dyes and dyeing--Dacron
· Dyes and dyeing--Equipment and supplies
· Dyes and dyeing--Feathers
· Dyes and dyeing--Glass fibers
· Dyes and dyeing--History
· Dyes and dyeing--Hosiery
· Dyes and dyeing--Knit goods
· Dyes and dyeing--Leather
· Dyes and dyeing--Nylon
· Dyes and dyeing--Paper
· Dyes and dyeing--Plastics
· Dyes and dyeing--Rayon
· Dyes and dyeing--Religious aspects
· Dyes and dyeing--Rubber goods
· Dyes and dyeing--Silk
· Dyes and dyeing--Textile fibers
· Dyes and dyeing--Textile fibers, Synthetic
· Dyes and dyeing--Wool
· Electromagnetic waves
· Hair dyes
· Language and color
· Light
· Music and color
· Optical spectroscopy
· Paper chromatography
· Paint industry and trade
· Paint materials
· Photometry
· Pigments industry
· Pigments
· Pigments--Analysis
· Polychromy
· Rainbows
· Spectrum analysis
· Symbolism of colors
· Tie-dyeing
· Tinting

Image: P:\Othmer Library\Digital Collections - Internal Access\Website Updates\Featured Topics\Color COLOR_SELECT.jpg

![COLOR_SELECT](https://github.com/sciencehistory/scihist_digicoll/assets/78036563/24145e7a-cd71-4aa6-952b-5d766ca8c42a)

**Comment by jrochkind** [comment]
@apinkney0696 I'm having trouble getting to P drive from my Mac. Can you give me an egnyte "direct link" to download that file?

If you have the original TIFF crop in addition to JPG, I could use both -- in case I need/want to resize it further, so I can resize the TIFF instead of the lossy JPG. 

Thanks!

**Comment by apinkney0696** [comment]
Thanks! 

The link is here with the new Tif inside: https://files.sciencehistory.org/navigate/folder/5f29fe70-96b0-4651-a7fa-9f26be1cf36b (I just saved it so it may not show up for a couple of minutes)
