### ISSUE TITLE
Enable PDF even for single-page works

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2278]
It was disabled cause I was kind of thinking of the whole point of the PDF as being aggregating multiple pages in one file -- if you only have one file, why not just download a JPG?

But in fact, some people would rather have a PDF for all sorts of reasons -- plus now that we're adding OCR text, it's another reason.

**Comment by jrochkind** [comment]
@jrochkind right now PDF downloads for multi-page works show up in a separate "section"....

![Screen Shot 2023-08-07 at 12 17 03 PM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/e04ee215-5dfd-4a32-8517-151e5666c9ba)


While single-page works lack that section:

![Screen Shot 2023-08-07 at 12 17 25 PM](https://github.com/sciencehistory/scihist_digicoll/assets/149304/d81589b2-c3a3-4616-9b48-3c23772f2d73)


I guess for single-page works, the PDF option should show up in the "Download Selected Image" section that is present?

@eddierubeiz This is another small-ish one you could do if you run out of work -- clearly no worry of that!

**Comment by apinkney0696** [comment]
That makes sense to me.
