### ISSUE TITLE
OCR of parent work should enable OCR of children

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2280]
Currently, the OCR of a parent work only will apply OCR to assets that do not exist as a child work.

**Comment by apinkney0696** [comment]
Great to know. I think this ticket would only really apply to the one-time bulk OCR of works that have already been ingested, not new records, so it's probably not worth it. (Especially because I suppose child records would be picked up in bulk OCR anyway?). I can always bulk-edit children to apply OCR if need be, so I will close this. Thanks!!

**Comment by jrochkind** [comment]
Good reminder that our bulk-edit needs to include child works though!

**Comment by eddierubeiz** [comment]
Note: the initial spec did have us turning on and off OCR at the asset level:
https://github.com/sciencehistory/scihist_digicoll/issues/2095

I did get a good start on this (tests passing, etc.) in:
https://github.com/sciencehistory/scihist_digicoll/pull/2113/files

but we decided to not to pursue it, using instead the simplest thing that could possibly work (OCR is turned on or off at the work level instead):
https://github.com/sciencehistory/scihist_digicoll/pull/2114

**Comment by eddierubeiz** [comment]
No, that PR did in fact allow for works to inherit their parent work's OCR setting.
