### ISSUE TITLE
Change [Missing] text to Undated

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2282]
In the date facet on the left menu of search results, works with "undated" date metadata are found by a link that says "[Missing]". I would like to change this text to say "Undated" instead if it's possible with Blacklight.

**Comment by eddierubeiz** [comment]
Here's a clue:
https://github.com/sciencehistory/scihist_digicoll/issues/408#issuecomment-555558656

**Comment by eddierubeiz** [comment]
Did a bit more research.
In the blacklight controller, adding:

```
    config.default_solr_params = {
      # [...]
      "facet.missing": true,
```
will in fact enable a "missing" facet for `format` and `department` facets.
Sure enough, all of these facets use the label configured in `blacklight.en.yml`.

**Comment by eddierubeiz** [comment]
I feel like explicitly setting `"facet.missing": false` , just as a pretext to add some comments.

**Comment by jrochkind** [comment]
I don't understand why we're messing with changing how Blacklight is configured to generate Solr queries -- we don't need to change any Solr queries, right? Just labels?  I wouldn't add configuration we don't need, the easiest code to maintain is code that isn't there.
