### ISSUE TITLE
Deal with "orphaned" Assets with no parent work

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2292]
While the kithe model allows this, I don't _think_ we intend to have any?

But we currently have 420

   * `Asset.where(parent: nil).count` => 420

They MAY all be really old ones, perhaps an older version of our software had a bug that made it more likely to get "orphaned" like this?

   * `Asset.where(parent: nil).order(created_at: :desc).first.created_at` => `Thu, 29 Nov 2018 15:23:37.000000000 EST -05:00`

but I don't know, some of them have been updated slightly more recently , but that could be for various bulk data fixes. 

   * `Asset.where(parent: nil).order(updated_at: :desc).first.updated_at` => `Tue, 10 Aug 2021 09:37:32.012798000 EDT -04:00`

We want to figure out if any of these are actually used in any way, and if not delete them. 

(These are also putting our count slightly off when people like @apinkney0696 have asked for reports on how many total assets we have, if these are actually leftover "garbage" assets!)

**Comment by eddierubeiz** [comment]
OK - I did a bit of investigating. The following code was helpful:

```ruby
goat = Asset.where(parent: nil).
	map { |a| [a.file.metadata["filename"], a.created_at.strftime('%Y-%m-%d'), a.friendlier_id] }.
	sort_by { |e| e[0] }
```

**Comment by eddierubeiz** [comment]
I'm going to create three separate issues pertaining to this, just to keep the conversation organized.

**Comment by eddierubeiz** [comment]
@apinkney0696  - all 420 orphaned assets are covered in the three issues 2326, 2327 and 2328.

**Comment by apinkney0696** [comment]
Interesting. It's unclear to me why this happened, but I'm relieved that the most recent incident was in 2018. Thanks for separating these out by work. It seems as though everything here has a duplicate file, so the 420 assets with no associated work can all be deleted at your convenience.

**Comment by eddierubeiz** [comment]
Will do!

**Comment by eddierubeiz** [comment]
These are gone in both prod and staging.
