### ISSUE TITLE
Two corrupt TIFFs in the corpus, Assets kz593ep and m1zy3an

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2297]
These Assets:

https://digital.sciencehistory.org/admin/asset_files/kz593ep
https://digital.sciencehistory.org/admin/asset_files/m1zy3an

(Eddie found another one with the same symptoms on Aug 22 2023 -- discussion below applies to both)
Seems to be a corrupt TIFF. If you download it, it can't be viewed.  It has no thumbnails (probably because thumbs couldn't be created, because it's corrupt). 

It passes fixity checks -- I would imagine it was ingested as corrupt somehow in the first place, and nobody ever noticed. Created 2022-Sep-29 16:57:32 EDT

We could also discuss if we need systems in place to catch this earlier, make it harder to go ahead and publish a work not noticing one of the pages failed to properly ingest. 

This one oddly does have it's type detected as "image/tiff", it's not just a garbage file... I'm not really sure what happened.

**Comment by jrochkind** [comment]
Quite possibly a failure of the variety already noted at #1652 (Thanks @apinkney0696 ), which already discusses putting in checks to make it harder to slip though.

**Comment by jrochkind** [comment]
@apinkney0696 just tagging to make sure this is on your radar!

These are a bit annoying for us, as they cause errors if we try to do anything with them, as we work on the new PDF stuff.

**Comment by apinkney0696** [comment]
I'm going to reprocess these today!
