### ISSUE TITLE
Export for final CLIR Report

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2299]
Hi! I have a request for a data export to fulfill the "file manifest" requirement from CLIR with for the final report for the Bredig project. I will need: 

- The filenames of a representative sampling of access files created through your project. (600 files for a 24-month project). Include the file extensions (.jpg, .jpeg, .tiff, .mp3, .mp4, etc.) as part of the filenames. 

- The full URL/URI (including http:// or https://) for the location of the listed files on your main access system. Note this should be the URL/URI for the file itself and not for the metadata record associated with the file.

- If you have generated a checksum to monitor the integrity of the files, enter the checksum value into the column labeled "CHECKSUM".

- Enter the date you last verified the availability of each file on your main access system. _(I'm guessing this will be the same date for all?)_

I will need this by Friday, August 16th at the latest, please. Let me know if this is possible!

**Comment by jrochkind** [comment]
> The filenames of a representative sampling of access files created through your project

So... when you actually download the files, you get a generated filename like `paul_lauterburs_coconut_1fjgp7n_1_dtbu9yv.tiff` -- at least you get that when you use a web browser, or another client that respects the `Content-Disposition` header (which knows if their thing does). 

Do you think _that's_ the filename they want? Or do they want the internal filename, which we also have on record, like `2010.009.013_001.tif`. 

When they don't tell us what they are actually trying to do, it's hard to know what they want. Reading between the lines, I think they are making a lot of assumptions about how our system works that are not accurate. 

Also as far as checksum, I guess we should tell them what digest algorithm we used to generate the checksum, if it's going to mean anything at all, even though they weirdly don't ask for that. We have MD5, SHA1, and SHA512 on record. I think SHA512 is what we use for our fixity checks, so I guess give them that one?

**Comment by eddierubeiz** [comment]
Of course I can take this!

**Comment by apinkney0696** [comment]
Can I get both the generated filename and the internal filename? They also ask about access copy filenames, and I was just going to write something about how derivative copies are created on demand, but I could put in the generated filenames instead. 

I wasn't able to download the file with the explicit directions for this from my email for some reason, so I paraphrased my initial comment. I think it would be helpful for you to have the full set of instructions for more context so I'm going to try again from my work computer tomorrow.

**Comment by jrochkind** [comment]
Yeah, it's a bit more of a pain to generate the generated filename, but anything for our grantors. 

The context would probably be helpful, yes!

I'm not sure what you mean by:

> I wasn't able to download the file with the explicit directions for this from my email for some reason

Perhaps it will be clear with more context!

**Comment by jrochkind** [comment]
> They also ask about access copy filenames, and I was just going to write something about how derivative copies are created on demand, but I could put in the generated filenames instead.

I'm not sure we're talking about the same thing. We generate up to 10 derivatives. Some of them don't really have meaningful filenames. 

The generated filename I am talking about is on the _original_ when you download it. I'm not sure if it gives you anything relevant for derivatives or not. 

I am a little bit annoyed that they seem to be making assumptions about our system that are not valid, which is creating lots of extra work for us.

**Comment by eddierubeiz** [comment]
Yup - thanks Annabel!

**Comment by apinkney0696** [comment]
> I wasn't able to download the file with the explicit directions for this from my email for some reason

I was emailed an excel file with the directions for the file manifest and it kept telling me "download failed" on my Mac. 

I mean it's definitely annoying, but it's just part of it. They make everyone they give money to fill this out.

**Comment by jrochkind** [comment]
Oh wait...

> Enter the date you last verified the availability of each file on your main access system.

That's not asking about fixity checks... I'm not sure what it's asking about?   I'm not sure we actually do anything to "verify the availability of each file on our main access system" normally... I guess we can do so as part of this report?   

If it just means we write a script to make sure a file can be downloaded at the URL we expect and no errors are returned? Not sure if it also wants us to fixity check these files accessed via "our main access system"? This could turn into quite the project.

**Comment by apinkney0696** [comment]
Here's the doc (check out the instructions tab):
[CLIR_Digitization_File_Manifest_Template_2020 (1).xlsx](https://github.com/sciencehistory/scihist_digicoll/files/12291629/CLIR_Digitization_File_Manifest_Template_2020.1.xlsx)

**Comment by eddierubeiz** [comment]
I'm going to argue that:
- in the process of calculating a checksum, we download the entire contents of the file from storage.
- if a file can be downloaded from s3 in this manner, we consider it "available";
- if a file passed its fixity check, the file was _a fortiori_ "available" at the time of the check.

**Comment by eddierubeiz** [comment]
@apinkney0696 here's the report with data from the actual production site:
[CLIR report, August 10 2023.xlsx](https://github.com/sciencehistory/scihist_digicoll/files/12316153/CLIR.report.August.10.2023.xlsx)
