### ISSUE TITLE
Use Ransack consistently for the admin work filter by ocr_requested

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2315]
I'd like to redo PR #2314 using `Ransack`, just to be consistent with the other admin controls on that form.
For whatever reason I couldn't figure out how to do do this. For now, this feature works just fine without using `Ransack`.

Ref #2286

update: solved, merged to master. Haven't deployed yet as of Friday August 25th, but will deploy on Monday.

**Comment by eddierubeiz** [comment]
I don't think this is a good idea. I've looked at https://activerecord-hackery.github.io/ransack/going-further/searching-postgres/ and I think this isn't really what Ransack is meant to do. I'm probably going to leave 2314 as it is.

**Comment by eddierubeiz** [comment]
Figured this out. I was confused by `c.ignore_unknown_conditions` in `config/initializers/ransack.rb.

**Comment by eddierubeiz** [comment]
Note: #2332 still needs to be merged into `master` before this can be moved to Review.

**Comment by jrochkind** [comment]
@eddierubeiz Agreed! 

Ransack has kind of been a pain and I'm thinking more about getting rid of it and doing anything it does "manually" instead.  It's convenience in doing stuff instead of us having to write custom code for every filter may not be worth the complexity and maintainance.

**Comment by eddierubeiz** [comment]
I ended up using Ransack exactly as we do for other filters on that form. Nothing fancy.

**Comment by jrochkind** [comment]
Ah, okay cool, consistency is good!

The trouble you had with it further pushes me to want to remove ransack and just do it all manually!

**Comment by eddierubeiz** [comment]
The trouble I had was caused by
`c.ignore_unknown_conditions` in `config/initializers/ransack.rb`. `ignore_unknown_conditions` means that this filter (as well as at least one other filter that you created) works fine in staging and in production, but does not work in development.

I concur that `ransack` is making our code more complicated than it needs to be, and we could do without it.

**Comment by jrochkind** [comment]
Wait, are they _currently_ not working in development? if so, we should file that and fix it!

Or is it already filed?  I do recall running into some weirdness here, but I was having trouble reproducing it, even in development, I hadn't gotten as far into diagnosing it as you have!
