### ISSUE TITLE
fixity checking

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#232]
Outstanding things:

- [x] Report of fixity checks for an individual asset on asset admin page
- [x] ability to request "fixity check now/soon" for a specific asset
- [x] Fixity check summary "dashboard" 
- [x] Email/slack notify on any fixity check failure
- ~import old fixity check data from chf_sufia?~ (will not do)

**Comment by eddierubeiz** [comment]
Basic idea:
```
Asset.find_each do |asset|
   asset.sha512 == calculated_512(asset)
end
```
Only run checks on items where `asset.stored?==true` because if it’s not finished ingesting, it won’t have a sha512 yet

If asset.sha512 is null, report that.

**Comment by jrochkind** [comment]
Other hints/ideas (some maybe wrong):

The basic way fixity checking was done before involves creating a database record (it was called something weird before, but we could call it... `FixityCheckLog`) that represents a logged fixity check. It has success(boolean), the ID of the Asset checked (we might want to store our UUID actual pk/fk for easy rails relationships, along with the friendlier_id for easy reporting), and the actual/expected checksums. 

One tricky thing is we don't want to keep these log files forever, so after creating a new one, we had some clever SQL to delete ones older than most recent N, unless they were error logs, in which case we do want to keep them forever, or the FIRST log on record, which we also want to keep forever (so we know earliest verified fixity). That tricky "clean up old log records" can be left for last. 

we want to use sha512 checksums here, although chf_sufia may have used md5. md5 is deprecated in general (in the whole world), sha512 is the newness. 

Another tricky thing is how you get the remote file (via shrine) to calculate it's checksum. And ideally doing it without having to read the whole thing into memory, or write the whole thing to disk -- check streaming. 

`asset.file.open(rewindable: false)` should give you an "IO"-like object.

One way to calculate checksum from it... I got this from looking into shrine source and seeing that maybe we can re-use how shrine does it:

I think something like this (some of this I got from looking :

```ruby
io_object = asset.file.open(rewindable: false)
sha_512_calculated = Shrine::Signature::SignatureCalculator.new(:sha512, :hex).call(io_object)
```

* In addition to batch, there should be some kind of "service" class to fixity check (and log to db) an individual asset. Cause we may want a "fixity check this now" button on Asset admin page. Should probably be an ActiveJob for individual fixity check to be scheduled in jobs system.

**Comment by eddierubeiz** [comment]
I've been thinking about this a bit. How would you feel about the notion of adding a boolean column to the FixityCheckLog to denote whether the check log is the earliest/canonical check? That way, our tricky 'clean up old log records' code can be reduced to just `delete from FixityCheckLog where item_id = X and earliest is false and success is true and age < Y.` Let me know if I'm missing something, as always.

**Comment by eddierubeiz** [comment]
Status update: work on this is well underway (see PR https://github.com/sciencehistory/scihist_digicoll/pull/315 ). 315 is only part of the work we need to do to "finish" fixity checking, so I'm not adding a "fixes" note in it.

**Comment by jrochkind** [comment]
@HKativa Do you see any reason we'd want to import fixity check information from chf_sufia?

Since all of our stuff should be continuously fixity healthy, that would basically just mean having the earliest date of fixity verification on record in new app, imported from old app.
