### ISSUE TITLE
Collection list page load is slow

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2346]
Can be 4-5 seconds on back-end on heroku.  

Looking at logs, most of this is taken up by waiting on DB! Specifically:

>  Aug 30 14:54:08 app/web.1 DEBUG: [f9a8a788-d2d8-4a2b-bf46-4dd63c1d2ea1]   Collection Load (4510.6ms)  SELECT "kithe_models".* FROM "kithe_models" WHERE "kithe_models"."type" = $1 AND (published = true) AND NOT (kithe_models.json_attributes @> ('{"department":"Exhibition"}')::jsonb) ORDER BY "kithe_models"."title" ASC  [["type", "Collection"]]

Oh interesting. In order to select all items from kithe_models that are of type Collection, it's scanning through all kithe_model rows I guess?  I still wouldn't expect that to be so slow.  The pg optimizer may be doing something weird, like looking through the jsonb first for every single row, which would be non-ideal. 

We could have an index on kithe_models.type, but you're usually advocated not to have an index on a value with only a few possible values... but in this case at least for the use case of just identifying collections, seems maybe needed?

**Comment by jrochkind** [comment]
Having trouble figuring out what's going on/reproducing.  I can't figure out why this DB fetch is taking 4.5 seconds to return, can't reproduce it trying specific commands in console.

**Comment by jrochkind** [comment]
Here's where the fetch that seems to be slow happens:

https://github.com/sciencehistory/scihist_digicoll/blob/5d007bf46c60919b3eb7ee1bd0e28458f23bd0df/app/controllers/collections_list_controller.rb#L6-L10

Fetching ALL collections (SQL will be from kithe_models where type = `Collection`) is pretty quick 52ms

```
irb(main):075:0> Collection.all.to_a ; nil
DEBUG:   Collection Load (52.1ms)  SELECT "kithe_models".* FROM "kithe_models" WHERE "kithe_models"."type" = $1  [["type", "Collection"]]
```

Adding _additional_ constraints should not slow it down that much, we're just filtering _within_ the very small 95 record result set... but it really does, turns 56ms in 2000ms (in this case):

```
irb(main):078:0> Collection.where("published = true").not_jsonb_contains(department: Collection::DEPARTMENT_EXHIBITION_VALUE).order(:title).includes(:leaf_representative).to_a ; nil
DEBUG:   Collection Load (2065.6ms)  SELECT "kithe_models".* FROM "kithe_models" WHERE "kithe_models"."type" = $1 AND (published = true) AND NOT (kithe_models.json_attributes @> ('{"department":"Exhibition"}')::jsonb) ORDER BY "kithe_models"."title" ASC  [["type", "Collection"]]
```

OK, let's take conditions out to indentify which one it is....

It's the jsonb_contains stuff....

```
irb(main):081:0> Collection.not_jsonb_contains(department: Collection::DEPARTMENT_EXHIBITION_VALUE).to_a ; nil
DEBUG:   Collection Load (2299.3ms)  SELECT "kithe_models".* FROM "kithe_models" WHERE "kithe_models"."type" = $1 AND NOT (kithe_models.json_attributes @> ('{"department":"Exhibition"}')::j

# vs

irb(main):082:0> Collection.where("published = true").order(:title).includes(:leaf_representative).to_a ; nil
DEBUG:   Collection Load (45.5ms)  SELECT "kithe_models".* FROM "kithe_models" WHERE "kithe_models"."type" = $1 AND (published = true) ORDER BY "kithe_models"."title" ASC  [["type", "Collection"]]
```

The SQL for the jsonb query here is:

```
irb(main):083:0> Collection.not_jsonb_contains(department: Collection::DEPARTMENT_EXHIBITION_VALUE).to_sql
=> "SELECT \"kithe_models\".* FROM \"kithe_models\" WHERE \"kithe_models\".\"type\" = 'Collection' AND NOT (kithe_models.json_attributes @> ('{\"department\":\"Exhibition\"}')::jsonb)"
```

OK, something is going wrong with the pg query planner. It really ought not to take a while to filter even on this jsonb condition _within_ the result set of 95 rows... but if pg is mistakenly first filtering on the pg, yeah, I can see how that might be a problem. 

OK, we'll just do the filter in-memory instead?

**Comment by jrochkind** [comment]
The optional department filter like `.where("json_attributes ->> 'department' = ?", "Archives")` does **NOT** actually cause a problem. It's just that `not_jsonb_contains(department: Collection::DEPARTMENT_EXHIBITION_VALUE)` that does!

I think pg doesn't really like that jsonb SQL query that has a `NOT ` in it, `AND NOT (kithe_models.json_attributes @> ('{\"department\":\"Exhibition\"}')::jsonb)"`. 

I added that `not_jsonb_contains` feature to attr_json by user request, but maybe it results in unfortunate queries. 

What if we just change it to a positive query for all the possible values except exhibition? 

    jsonb_contains(department: (Collection::DEPARTMENTS - Collection::DEPARTMENT_EXHIBITION_VALUE)).

We'll try it.

**Comment by eddierubeiz** [comment]
I wonder if a subquery or even a second call to the database might be helpful here. Curious to see what the answer is.

**Comment by jrochkind** [comment]
If I couldn't figure out a simple way, just filtering in-memory after fetching them all would be fine -- we're talking currently 95 total collections, even if it was 500, fetching them all in to exclude Exhibitions in memory would be fine. 

BUT, this works, as far as generating SQL that does the right thing. 

    where("json_attributes ->> 'department' IN (?)", Collection::DEPARTMENTS.without(Collection::DEPARTMENT_EXHIBITION_VALUE)).

Have to deploy to staging with real data to see if it fixes the performance problem!

**Comment by jrochkind** [comment]
That fixed it. From 2500-4500ms with most of that in DB,  to 171ms, with 80ms in db. 

```
Aug 30 15:36:59 app/web.1 INFO: [5cdbf0dd-4692-40f5-9287-b4a401d7e964] method=GET path=/collections format=html controller=CollectionsListController action=index status=200 allocations=64444 duration=171.17 view=86.23 db=80.47 ua=Chrome-116/Mac-10.15 ip=69.243.27.93
```

**Comment by eddierubeiz** [comment]
Awesome.

**Comment by jrochkind** [comment]
There's an index we can make on the jsonb column that hypothetically should be used for nearly any jsonb contains query on it...

We haven't bothered, cause our DB was so small (100K rows is still pretty small for pg). 

But I wonder if that would have fixed this issue... or if the `NOT` in there would still have defeated it. 

It might be time to look into creating that index though. 

https://www.postgresql.org/docs/9.5/datatype-json.html#JSON-INDEXING
