### ISSUE TITLE
Two quick changes to recent items feature.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#237]
Adjust the following:
1) Get rid of $collage_style in the css and hardcode it so $collage_style is always true
2) Move the helper class into our presenters directory and call it recent_items.rb

_Originally posted by @eddierubeiz in https://github.com/sciencehistory/scihist_digicoll/pull/236#issuecomment-512447149_

**Comment by jrochkind** [comment]
oh did we merge without doing these things? I thought we were going to do them before merge? But ok!

**Comment by eddierubeiz** [comment]
Yeah so did I! Then you merged the PR and I thought fine, I'll do it next week :)

**Comment by eddierubeiz** [comment]
#1 is fixed in https://github.com/sciencehistory/scihist_digicoll/pull/238. Still need to do the refactor.
