### ISSUE TITLE
On admin page for Oral Histories, "OCR" and "Oral History" tabs are merged together

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2380]
"OCR" content appears beneath "Oral Histories" tab content instead of appearing on a separate tab, and switching between OCR and Oral Histories tabs doesn't do anything. 

Probably a mis-matched or un-closed HTML tag somewhere, maybe on Oral Histories tab?

**Comment by eddierubeiz** [comment]
Thanks for flagging this. Happy to fix it.
