### ISSUE TITLE
add local_env.yml key `s3_bucket_on_demand_derivatives`

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#240]
With values `scihi-kithe-stage-ondemand-derivatives` or `scihi-kithe-prod-ondemand-derivatives`. 

Necessary for #239

**Comment by sanfordd** [comment]
A key has been added with the staging variable value added. The bucket has a 20 day cycle to clean out old files. We can shorten it if it becomes an issue.
