### ISSUE TITLE
PDF creation fails when one or more assets are missing `graphiconly_pdf` derivative.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2413]
Start here:
https://digital.sciencehistory.org/works/6lkg923

and request full-work PDF.
The last asset in the work has OCR suppressed, and is missing its graphiconly_pdf deriv.

```
StandardError: AssetPdfCombiner: Can't create combined PDF for asset 'eft6bg1' with missing :graphiconly_pdf derivative
```

[Error](https://app.honeybadger.io/projects/58989/faults/99787845)

**Comment by jrochkind** [comment]
`eft6bg11 is a TIFF, and is a really large TIFF.  Maybe the process failed because it was so large. 

But let's look in production for image assets missing a graphiconly_pdf derivative; what is the extent of the problem?

```ruby
irb(main):017* Asset.find_each do |asset|
irb(main):018*   if asset.content_type.start_with?("image/") && asset.file_data["derivatives"]["graphiconly_pdf"].blank?
irb(main):019*     missing << asset
irb(main):020*   end
irb(main):021> end
```

Actually 226 assets....  Include jpegs, tiffs, and pngs (png?)!

=> {"image/jpeg"=>201, "image/tiff"=>17, "image/png"=>8}

OK, some of these are collection thumbs, oral history portraits etc. Let's focus on the TIFFs.  Ooops, some of the TIFFs are collection thumbs too!

Only ONE TIFF that is missing graphiconly_pdf and is not a CollectionThumbAsset, and of course it is `eft6bg1`. Great!

**Comment by jrochkind** [comment]
Can we just create it inline in the console?

```ruby
asset_eft6bg1.create_derivatives(only: :graphiconly_pdf)
```

That *is* giving us R14 errors for sure, looking at logs. Maybe ti'll complete anyway, let's wait and see, otherwise we'll manually start up a larger dyno console to run it.

**Comment by jrochkind** [comment]
Oh no, it definitely got an R15 and was killed by heroku!

OK, too big, uses too much RAM creating graphiconly_pdf, we know why it was missing one!

We will open up a console on expensive performance-l dyno -- expense shoudln't be too much for the under an hour we should have it open!  `performance-l` has 14G of RAM, so we should have enough!

    heroku run --size=performance-l console

```ruby
asset = Asset.find_by_friendlier_id("eft6bg1")
asset.create_derivatives(only: :graphiconly_pdf)
```

Completed! Didn't even take too long when it wasn't swapping with R14's.  

Seems to show up in console, but I'm confused why it's not showing up in https://digital.sciencehistory.org/admin/asset_files/eft6bg1

OH, cause I accidentally did it on staging not production! OK, back to doing it on production. 

Took 73 seconds. Derivative on production now.

**Comment by jrochkind** [comment]
I succeesfully created the PDF for https://digital.sciencehistory.org/works/6lkg923

It's cool to see our "preserve actual size of pages" functionality working for this item that has that one image that's all the pages together flipped out -- that "page" of PDF is the right size, proportional to the individual pages!  It makes for an odd PDF, but it is "right".
