### ISSUE TITLE
confirm resque pool restart is graceful

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#242]
Should be waiting some amount of time for currently in progress jobs to complete, before just killing them. 

Cap deploy does a restart with a `chf:resquepoolrestart` cap task, which ends up running: `sudo /usr/sbin/service resque-pool restart`

1. Does that do a "graceful" restart? Which would be something like: stop accepting new jobs, but allow in-progress jobs some amount of time to complete before giving up on them and killing them hard. 
2. Let's confirm how long it will wait on a job to finish before giving up and hard-killing it, and how to configure that to a different value. (document in this ticket). 

I just saw it interupting a "create a large PDF file" job, in less than 2 seconds. I'm not sure it's waiting at all for it to complete, although it may be waiting some time less than 2 seconds (which could even be fine -- we just want to know what's going on, and how to adjust it).

**Comment by sanfordd** [comment]
1. We're definitely not doing the best practice graceful restart (i.e. a `QUIT` signal). I'm going to try adjusting that.

**Comment by sanfordd** [comment]
Manually calling the proper kill signal (QUIT) has things behave correctly. The error is in the systemd setup and will be fixed there.

**Comment by jrochkind** [comment]
Yes, probably. 

On the one hand, some of our tasks could take quite a while. 

On the other, they all SHOULD be idempotent, and okay to run again if interupted (although I'm not sure if the jobs queue will know they have been killed and should run again). 

AND we can't have our system restarts hanging forever on a job that takes 20 minutes to complete or something. 

Why don't you pick a timeout time that seems to you the right time for the mechanics of a restart, not so long that it's gonna make our operations terrible waiting for things to restart?

**Comment by jrochkind** [comment]
And good thought on the timeout @sanfordd , thanks!

**Comment by sanfordd** [comment]
Documenting here, I've got a working solution setup. It's been tested on the new application. We now have a proper shutdown that respects running workers and will wait 300 seconds to forcibly terminate them. The time was based off the length of time to make fairly large PDF files (Ramelli and the Museum Wormianum) and some rough upload estimates. Ramelli currently takes about 215 seconds to process and some extension was added assuming multiple concurrent tasks. 

Multiple test deploys were run, the workers do properly have time to finish their tasks before stopping. However in the case of making an aggregate download , this can still lead to an error. The worker finishes making the aggregated file and then is terminated right away. This causes the same dirty exit error (https://app.honeybadger.io/projects/58989/faults/52384541/bba92c92-b87e-11e9-8013-843e151d54d6#notice-summary) where the user will see the software failure page on their pop-up. However if they do attempt to download the file again, it will serve quickly from the cache. 

Running a deploy during ingest also caused a pile of errors which prevented all the derivative files from generating properly, It looks like the workers were removed before all the tasks were finished. I'll be doing more test resque-pool stop and starts to be sure of the case.

There is currently one other very minor issue on the back end of things, if resque-pool is stopped, cannot complete all the jobs and forcibly terminates workers, the forcibly killed workers appear in the worker queue/redis list of workers even though they have been removed from the processes. They are not there, and restarting resque removes them from appearing but it is a potential point of confusion if they appear to be there while actually being removed. This doesn't seem to cause any problems, so falls below the first two issues and is not in my mind a stopping issue.

**Comment by sanfordd** [comment]
I've done further testing and manually (i.e. `kill -s 3 PID`) stopping resque-pool and using the systemd command (`systemctl restart resque-pool`) both exhibit proper behavior. The characterization and derivation generation may stop as workers are removed gracefully from the pool, but upon a restart of resque-pool the remaining tasks are assigned to new workers and finished with no errors.

Capistrano's deploy on the other hand invariably results in errors and unfinished tasks are not given to the restarted workers.

**Comment by jrochkind** [comment]
@sanfordd 

Capistrano is doing a `execute :sudo, "/usr/sbin/service resque-pool restart"`. https://github.com/sciencehistory/scihist_digicoll/blob/5b5a4066c13cb8f0bc2c6e015bd4c7556a542afc/config/deploy.rb#L143

It sounds like I should change it to `systemctl restart resque-pool`, and since you verified `systemctl restart resque-pool` exhibited proper behavior, after that change capistrano deploy should also exhibit proper behavior... or at least that's the first step, and if not we have more analysis to do. 

Should I go ahead and make that change?

**Comment by sanfordd** [comment]
@jrochkind The service command also _should_ use systemd's systemctl command, just serving as a wrapper. I did a quick edit of the cap code to use the systemctl command on capistrano and the same behavior was exhibited when it's called directly. 

I was able to force a systemctl command to generate an error, though the end behavior was a bit different than cap deploy. I'm going to do more digging into this before any changes.

**Comment by jrochkind** [comment]
OK, so this is a mystery. The cap should be doing exactly the same thing that you say exhibited proper behavior, and yet it does not exhibit proper behavior. 

I can not explain this. 

I may change the Cap command to be `systemctl restart resque-pool` anyway, just for consistency, and so nobody needs to ask this question again, if that is the preferred command?

**Comment by sanfordd** [comment]
I've done more work and found that at least part of it is a timing issue. 
A `kill -s 3` can be sent during any time and I've yet to generate an error, jobs that are as yet unfinished are they added back to the workers when they start up again 
The `systemctl restart`command can be sent during asset promotion safely, during the create derivatives task it generates failed jobs. However jobs that did not fail but were simply not run yet do properly get sent to workers when they are restarted.
A cap deploy has the same issue the `systemctl restart` does, I thought there was an additional problem but that may just be me having difficulty of timing a cap deploy to hit the restart as precisely as using the other two. 

This puts it back an issue with systemctl stop not behaving as a command line `kill`does for some reason.

**Comment by jrochkind** [comment]
That makes it sound to me like `kill -s 3` is doing a "graceful" restart, but `systemctl restart` is not yet.

**Comment by sanfordd** [comment]
According to the resque-pool.stdout.log both show
```
resque-pool-manager QUIT: graceful shutdown, waiting for children
resque-pool-manager Sending QUIT to all workers
```

Both appear to be sending the same graceful shutdown signal when run.

**Comment by sanfordd** [comment]
This has taken a while but here's what I have finally so we can progress. 
I'm not totally sure why `systemctl restart` (which calls `systemctl stop`) doesn't do a proper graceful shutdown. Most of the workers seem fine but we can reliably get an error with some of them doing derivative generation during that time. It's something to investigate, but the real goal is for cap deploys to _not_ cause any problems.

In that spirit, I can add an ExecReload= option to our resque-pool systemd config file.
This will send a **SIGQUIT** signal and wait for the the master pool process to show it is shut down.
This shutdown (or any shutdown that isn't `systemctl stop`) will trigger the restart condition for systemd which will start up a new resque-pool service. 

There are 2 potential issues
1. A minor one, but technically it's a restart and not a reload. This isn't a problem but we want to be sure this is documented in capistrano and systemd so we know that.
2. A long running worker will delay any deploys until it finishes. A very long running worker (>5 minutes) will cause it to hit a timeout and error out on the deploy. I don't think we have those but it may be an issue.
We _could_ add a flag like we do for solr that uses the more aggressive systemctl stop/start commands to bypass long running workers but that introduces the chance for errors. If we have a hung job, we could also handle it manually and avoid allowing any cap deploy to cause worker errors. Thoughts?

**Comment by jrochkind** [comment]
OK, if i understand right, you hacked it to be doing what it should have been doing already according to it's docs?

Ideally, we'd file an issue with resque/resque_pool that it wasn't doing what it said it was doing. And/or actually debug it in ruby to figure out why. But I'm not sure how much attention resque/resque_pool get, I feel like most people have moved to sidekiq. 

1. I'm not concerned, I don't understand the difference between a 'restart' and a 'reload'; all the matters is what happens. 

I'm concerned about what happens though. I think 5 minutes is too long to wait, we don't want our cap deploy to be stopped for 5 minutes.  

Those PDF/ZIP jobs can handle on their own being killed in the middle, if a deploy happens in the middle -- they'll recover on their own.  It's true other jobs might not. 

Still, I think what we want is it waiting only 10-15 seconds, then killing any jobs that are still running. 

But if I understand your 2 right... if any jobs DO go beyond your limit (currently 5) minutes, it'll error out the deploy? That seems not right. Especially becuase this will leave no workers accepting new jobs until manual intervention is taken, which is not optimal. 

We don't want long jobs erroring out the deploy; we want long jobs just hard-killed. (Which I suspect is what resque/resque_pool is _supposed_ to be doing already!). 

How hard is it to get it to hard-kill jobs if they are still running after timeout? Maybe it sends a different signal for hard shutdown after the timeout, instead of erroring out and cancelling deploy?

Alternately, we could give up and say we just need to migrate to sidekiq. I suspect sidekiq's [documented graceful shutdown behavior](https://github.com/mperham/sidekiq/wiki/Signals#term) actually works as documented.

**Comment by jrochkind** [comment]
(Note sidekiq says that if it kills any workers for taking too long to finish -- it'll push their jobs back on the queue to be taken by the new workers! I don't think resque even has that feature, but that makes it even less worrisome to be killing long-to-shut-down workers).

**Comment by sanfordd** [comment]
To be clear, it does not wait 5 minutes. It waits up to 5 minutes, should there be a 5 minute long resque worker running. If there are no long workers running, it waits a few seconds (currently 5, easy to reduce that) and checks that the workers are closed.

**Comment by jrochkind** [comment]
OK, I am indeed confused. 

What we WANT to happen is there is some timeout X (whether 15 or 300 seconds), and if workers aren’t finished by then, they are hard-killed, and a new pool is started. And capistrano continues with the deploy. 

It's not clear to me which parts of those are happening or not, or how hard it would be to get them to happen. If they are happening, great!

That's what I thought resque-pool graceful restart was supposed to do. That is optimal behavior.

**Comment by sanfordd** [comment]
We'll discuss this more at the technical meeting, but this is based on referring to two documents
https://github.com/nevans/resque-pool#Signals
https://github.com/resque/resque#Signals

I'm basing this on the following conditions and desires, laid out to be specific about our needs.
1. Deploys should, when possible, avoid causing problems for running jobs. Users should not notice them.
2. Deploys also need to not be delayed by long jobs, after some number of seconds it is acceptable to terminate any jobs and deal with the results of the jobs failure.

If we sent a SIGQUIT we can insure a graceful shutdown and restart but by default it does not apply a timeout. Extremely long jobs such as pdf generation can cause a deploy to be delayed by up to 3-4 minutes. This also means that the other workers are missing during that time. Users will experience a delay in new ingested objects being ready or other on-demand derivatives will have an added delay.

We can cause systemd to treat that as a timeout error and stop/start the resque-pool service, but this results in capistrano failing to deploy due to a timeout error. It can be redployed but that requires that the deployer make multiple attempts.

In theory the fix is to sent a SIGQUIT followed by, X seconds later, a SIGTERM. As per the resque-pool documentation, SIGTERM is the only way to tell the pool manager to quint and sent a SIGINT shutdown signal for a non-graceful shutdown. However attempting to do so when a SIGQUIT has already been sent seems to result in the SIGQUIT being processed first so the shutdown of the lingering active worker is delayed. The SIGINT signal does not bypass other signals is the likely cause of this. SIGKILL would bypass it, but it needs to be targeted at the individual worker(s) and not the pool manager, otherwise the manager is killed and the now orphaned workers continue on. 

Sending a SIGKILL to a process that did end, such as a properly exited pool, generates an error and will likely cause another deploy error. Adding a SIGKILL to the end sent to the pool manager and all workers seems likely to generate those, in addition to simply removing the need or use of resque-pool. Tracking the workers is what resque-pool should solve.

Looking at the resque docs, not resque-pool, the SIGUSR2 signal tells workers to stop accepting new jobs. This doesn't terminate anything, but prevents new jobs from being assigned to workers. We can send a SIGUSR2 to resque-pool, which will be passed along to each worker. They will not accept any new jobs. After some number of seconds, we can then send a SIGTERM which will forcibly shutdown the workers, not waiting on the QUIT to process, and then kill the pool manager so it can restart.

The main downside to this is that, at the moment, I don't have any elegant way to check if the workers are not busy when this is done so it will add a delay of whatever we decide is a reasonable number of seconds to each deploy. Unless we want to use some code in capistrano to easily check that.

**Comment by sanfordd** [comment]
As per discussion at team meeting, following the suggestion of @jrochkind we are closing this right now due to current behavior matching existing application. We can focus on updating this to a better version later.

**Comment by jrochkind** [comment]
resque _does_ seem to have _some_ functionality to "try to gracefully kill the workers, if they don't die in X seconds, hard-kill them."

But it's poorly documented, and unclear how it interacts with resque_pool. :(

A lot of the confusion here is resque_pool/resque not working well/well-documented together. 

https://github.com/resque/resque/blob/1d85f7c705ee8a609531c29035f8cf7cc6d67b19/lib/resque/worker.rb#L530-L542
