### ISSUE TITLE
Consider removing `Missing required TIFF ExifIFD tag 0xa001 ColorSpace` ingest check

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2420]
I haven't done any research into this particular check, but it looks like we should consider removing it.

I'm not exactly clear when we deployed https://github.com/sciencehistory/scihist_digicoll/pull/2395, but it appears some or all files ingested since the deploy are being [flagged on ingest as corrupt](https://digital.sciencehistory.org/admin/asset_files?promotion_failed=true).

Removing the check in staging allows you to ingest at least one file that doesn't appear corrupt (at any rate, there's nothing wrong with the derivatives.)

Contrast, for example:
	https://digital.sciencehistory.org/admin/asset_files/b660iq5 
	https://staging-digital.sciencehistory.org/admin/asset_files/3wpuika

**Comment by jrochkind** [comment]
Actually I'll work on this now!

**Comment by eddierubeiz** [comment]
For future reference:
```
Work.find_by_friendlier_id(friendlier_id).members.each do |a|
  a.file_metadata["promotion_validation_errors"] = {}
  a.save!
  a.promote
end
```

What I did in practice is more roundabout (see the PR for notes on that) but in retrospect the above would have worked fine.

**Comment by jrochkind** [comment]
you _might_ not even need the `promote`, but it shouldn't hurt, probably.

**Comment by eddierubeiz** [comment]
It looks like I forgot to process [this work](https://digital.sciencehistory.org/admin/works/kpkfh2c) (it's not on the list above.)
Following the recipe above, I ran the following in production:
```
pinkham = Work.find_by_friendlier_id('kpkfh2c')
pinkham.members.each do |a|
   a.file_metadata["promotion_validation_errors"] = {}
   a.save!
   a.promote
end
```
