### ISSUE TITLE
Clean up and/or document our "customer managed" IAM policies.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2424]
It appears we have some unused and/or underdocumented IAM policies which it would be nice to tidy up.

Start [here](https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/policies)
Filter by ` Customer managed` type in the `Filter by Type` menu.
Pay attention to the `Description` column and the `Used as` column.
- Items with `None` in the `Used As` column are suspect.
- Items with `test` in the title are suspect.
- Items with no description  (e.g. the four `s3crr` policies) should be edited to make them easier to understand.

**Comment by jrochkind** [comment]
Eddie already cleaned this up hooray
