### ISSUE TITLE
Find published works with 0 public assets

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2433]
There are a handful of items (I'm not sure how many) in the Booth collection, and perhaps in the DC in general, that may have 0 published assets on a published metadata record. If we can identify these, then I can bulk edit to publish the assets or leave for you to publish if it's easy to do on your end.

Please only look for items that have 100% unpublished assets and are not Oral Histories - there are a couple of records in the DC that are only partially public for copyright reasons. We fully digitized and included all assets from these works because their copyright expiration is within the next couple of years and they can be made fully public at that point.

**Comment by eddierubeiz** [comment]
- https://digital.sciencehistory.org/admin/works/i1fumf5 (Letter from Mary A. Post to James Curtis Booth, December 17, 1874)
 - https://digital.sciencehistory.org/admin/works/bakyr0u (Letter from Mary A. Post to James Curtis Booth, June 22, 1879)
 - https://digital.sciencehistory.org/admin/works/byjqznl (Letter from James Curtis Booth to Mr. J. R. Savage)
 - https://digital.sciencehistory.org/admin/works/y324fqg (Letter from Frederick Sylvester & Brother to James Curtis Booth, October 28, 1880)
 - https://digital.sciencehistory.org/admin/works/ljed9mk (Letter from F. C. Yarnall to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/zdgfasg (Letter from Samuel W. Levis to James Curtis Booth, April 1883)
 - https://digital.sciencehistory.org/admin/works/us1tcd1 (Letter from Sanderson Smith to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/7fmggmu (Letter from Marcus Benjamin to Margaret M. Booth, March 28, 1888)
 - https://digital.sciencehistory.org/admin/works/pq82gi2 (Letter from Emily Winsor to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/truandq (Letter from M. Alsberg to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/s1hmlbi (Letter from Rev. Bishop Morris to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/a1sdtup (Letter from Dr. Charles M. Wetherill to James Curtis Booth, December 13, 1863)
 - https://digital.sciencehistory.org/admin/works/rv4gi63 (Letter from Booth, Garrett, & Blair, Analytical and Consulting Chemists, to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/k0lxixk (Letter from W.C. Spruance to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/62dyp95 (Letter from Henry Carrington Bolton to James Curtis Booth, June 4, 1883)
 - https://digital.sciencehistory.org/admin/works/kjzq5sx (Letter from Louis Blodgett to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/3x36keu (Letter from Joseph Henry to James Curtis Booth, December 28, 1875)
 - https://digital.sciencehistory.org/admin/works/n8rgw0r (Letter from Henry Carrington Bolton to James Curtis Booth, March 8, 1882)
 - https://digital.sciencehistory.org/admin/works/t8jqp52 (Letter from Edward L. Lycett to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/65kl3ha (Letter from Frederick Sylvester & Brother to James Curtis Booth, July 26, 1880)
 - https://digital.sciencehistory.org/admin/works/sfk3235 (Letter from Patterson Du Bois to Margaret M. Booth, October 4, 1888)
 - https://digital.sciencehistory.org/admin/works/njnlbz1 (Letter from C.M. Potter to James Curtis Booth)

**Comment by eddierubeiz** [comment]
We can publish these in production on Monday.

**Comment by apinkney0696** [comment]
Oh, it's not many at all! It took me 2 minutes to update so it's all taken care of. Thank you!

**Comment by eddierubeiz** [comment]
😎

**Comment by eddierubeiz** [comment]
Apparently the code I wrote somehow missed [ssx4mym](https://digital.sciencehistory.org/works/ssx4mym) . Could there be others?

**Comment by jrochkind** [comment]
@eddierubeiz I never reviewed the code you wrote, can you direct me to it, I'll see if I see how it could have missed some?

Or now that we have an example it missed, we can debug why that particular example missed it?

i guess we re-open this ticket, put it back in in-progress!

**Comment by eddierubeiz** [comment]
Oh, it might be a simpler problem than that. It looks like I might not have copied the whole list into the ticket.

**Comment by eddierubeiz** [comment]
Yeah, I'm not sure exactly what I posted on Friday but that's not the complete list.
In particular there's an item *outside* the Booth collection that's similarly afflicted:
 - https://digital.sciencehistory.org/admin/works/f4752g98r (Beckman Total Hydrocarbon Analyzer)

**Comment by eddierubeiz** [comment]
I'm going to publish the assets for the following:
 - https://digital.sciencehistory.org/admin/works/if23wa7 (Letter from the Society of Alumni, University of Pennsylvania to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/tnhai4l (Letter from Henry Carrington Bolton to James Curtis Booth, January 30, 1882)
 - https://digital.sciencehistory.org/admin/works/zg3mqde (Letter from George H. Cook to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/cfds5lq (Letter from L. Sadtler to James Curtis Booth, March 17, 1887)
 - https://digital.sciencehistory.org/admin/works/88u2es8 (Letter from Patterson Du Bois to Margaret M. Booth, October 11, 1888)
 - https://digital.sciencehistory.org/admin/works/exp6fjh (Letter from James Curtis Booth to John Jay Knox )
 - https://digital.sciencehistory.org/admin/works/qkfs9bd (Letter from D. R. King to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/9h4cd3p (Letter from John Jay Knox to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/45fy7au (Letter from Thomas H. Garrett to Margaret M. Booth)
 - https://digital.sciencehistory.org/admin/works/omkjea4 (Letter from Ira Remsen to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/ljxamoy (Letter from George Blight to Margaret M. Booth)
 - https://digital.sciencehistory.org/admin/works/wijuf2w (Letter from the Managers of the Fair for the Church of the Redeemer to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/6nhcynv (Letter from Joseph Lesley to James Curtis Booth, August 23, 1883)
 - https://digital.sciencehistory.org/admin/works/m4u1n1j (Letter from Rev. Washington B. Erben to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/90aebrt (Letter from C. W. Johnson to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/hf570p0 (Letter from Daniel D.L. Farson to Margaret M. Booth, July 8, 1888)
 - https://digital.sciencehistory.org/admin/works/5myaqgq (Letter from Joseph Lesley to James Curtis Booth, December 10, 1881)
 - https://digital.sciencehistory.org/admin/works/gres02i (Letter from Edwin Montell to James Curtis Booth, December 15, 1866)
 - https://digital.sciencehistory.org/admin/works/duqlk9e (Letter from Professor Roemer to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/eol36ex (Letter from [Sandreth?] to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/1ercfb2 (Letter from Maria L. Bolton to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/p80xxp9 (Letter from Marcus Benjamin to James Curtis Booth, June 16, 1886)
 - https://digital.sciencehistory.org/admin/works/mqux06j (Letter from John Struthers to James Curtis Booth, November 27, 1879)
 - https://digital.sciencehistory.org/admin/works/wegcetb (Letter from Samuel Durborow to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/bkd1vmh (Letter from John Wien Forney to James Curtis Booth, June 18, 1863)
 - https://digital.sciencehistory.org/admin/works/s9lze3z (Letter from Dr. William Curran to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/pkziwcl (Letter from Henry Carrington Bolton to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/f7ehf15 (Letter from W. W. Montgomery to James Curtis Booth, February 17, 1882)
 - https://digital.sciencehistory.org/admin/works/zxkzmbb (Letter from James Curtis Booth to Joseph B. Townsend)
 - https://digital.sciencehistory.org/admin/works/t80zmib (Letter from George F. Wilson to James Curtis Booth, January 10, 1860)
 - https://digital.sciencehistory.org/admin/works/h2646uz (Letter from Edward J. Nolan to Margaret M. Booth)
 - https://digital.sciencehistory.org/admin/works/we7kwvm (Letter from S.B. Brown to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/wv12xyo (Letter from Frederick Sylvester & Brother to James Curtis Booth, September 1, 1880)
 - https://digital.sciencehistory.org/admin/works/oy8qthc (Letter from Thomas H. Garrett to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/ki6zvt1 (Letter from Edwin Montell to James Curtis Booth, December 6, 1866)
 - https://digital.sciencehistory.org/admin/works/h7j2htv (Letter from James Curtis Booth to J. L. Stadelman)
 - https://digital.sciencehistory.org/admin/works/bc4sq1u (Letter from David J. Hill to Margaret M. Booth)
 - https://digital.sciencehistory.org/admin/works/vt1p88d (Letter from L. Poulson Dobson to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/isovra0 (Letter from Thomas W. Yardley to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/4s7w0ee (Letter from G. W. Hunter to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/qw628gp (Letter from James Curtis Booth to Mr. S. M. Howell)
 - https://digital.sciencehistory.org/admin/works/kgeiql7 (Letter from J.W.M. Cardeza to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/24r6v6y (Letter from Daniel D.L. Farson to Margaret M. Booth, May 9, 1888)
 - https://digital.sciencehistory.org/admin/works/zrsqqca (Letter from Samuel W. Levis to James Curtis Booth, May 4, 1883)
 - https://digital.sciencehistory.org/admin/works/7hofwad (Letter from Nanette Bolton to James Curtis Booth, January 28, 1882)
 - https://digital.sciencehistory.org/admin/works/1uerldi (Letter from V. R. Allen to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/pastnl8 (Letter from Fred W. Booth to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/4demxx0 (Letter from W. W. Montgomery to James Curtis Booth, January 4, 1886)
 - https://digital.sciencehistory.org/admin/works/7pkc555 (Letter from Daniel D.L. Farson to Margaret M. Booth, May 15, 1888)
 - https://digital.sciencehistory.org/admin/works/hfmst72 (Letter from John Jordan Jr. to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/2f94ipb (Letter from Edwin Lonsdale to Margaret M. Booth)
 - https://digital.sciencehistory.org/admin/works/9wi6n0j (Letter from J. Churchman to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/bjjkf16 (Letter from James Curtis Booth to an unidentified recipient)
 - https://digital.sciencehistory.org/admin/works/q4z7qne (Letter from Professor B. Puryear to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/mxrijou (Letter from L. Knowles to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/ha7m2b5 (Letter from James Curtis Booth to John Struthers, November 1, 1879)
 - https://digital.sciencehistory.org/admin/works/lr7dwhl (Letter from John H. Peck to Margaret M. Booth)
 - https://digital.sciencehistory.org/admin/works/kdk1n9x (Letter from Frederick Sylvester & Brother to James Curtis Booth, August 19, 1880)
 - https://digital.sciencehistory.org/admin/works/idcexhf (Letter from Joseph E. Hoven to James Curtis Booth, June 29, 1867)
 - https://digital.sciencehistory.org/admin/works/pbhvlmd (Letter from Frederick Sylvester & Brother to James Curtis Booth, August 13, 1880)
 - https://digital.sciencehistory.org/admin/works/dw7atl3 (Letter from A. E. Outerbridge to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/jdlxt0l (Letter from John J. Allen to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/d1uo74o (Letter from L. Sadtler to James Curtis Booth, February 25, 1884)
 - https://digital.sciencehistory.org/admin/works/wb8d9xu (Letter from Marcus Benjamin to James Curtis Booth, June 20, 1886)
 - https://digital.sciencehistory.org/admin/works/1ezhag7 (Letter from Marcia B. Booth to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/mer100s (Letter from Charles Willing Hare to James Curtis Booth)
 - https://digital.sciencehistory.org/admin/works/7jaw5fm (Letter from Henry Carrington Bolton to James Curtis Booth, May 22, 1883)
 - https://digital.sciencehistory.org/admin/works/s7yaems (Note from Campbell Morfit to Margaret M. Booth)
 - https://digital.sciencehistory.org/admin/works/i9g2u3c (Letter from Hugh Miller Thompson to James Curtis Booth)
Done!
