### ISSUE TITLE
Update to Python from 3.11. 4 to 3.11.6

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2436]
Just noted the following warning during a deploy to Heroku:

```
remote: -----> No Python version was specified. Using the same version as the last build: python-3.11.4
remote:        To use a different version, see: https://devcenter.heroku.com/articles/python-runtimes
remote:  !
remote:  !     A Python security update is available! Upgrade as soon as possible to: python-3.11.6
remote:  !     See: https://devcenter.heroku.com/articles/python-runtimes
```

**Comment by jrochkind** [comment]
let's ask Heroku a feature request for specifing a range of python, to get the latest patch when it comes out automatically

**Comment by eddierubeiz** [comment]
I finally put in that feature request and it's at https://help.heroku.com/tickets/1337432 . Will report back if and when they respond. In the meantime, moving this to "review".
