### ISSUE TITLE
[scihist_digicoll/production] ActiveEncodeStatus::EncodeFailedError: Asset: , Demuxer: [Failed to read data: Error caching file]

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2461]
Some failure in updating status of creating video derivatives using AWS MediaConverter. 

## Backtrace

    line 39 of [PROJECT_ROOT]/app/models/active_encode_status.rb: refresh_from_aws
    line 4 of [PROJECT_ROOT]/app/jobs/refresh_active_encode_status_job.rb: perform
    line 104 of [PROJECT_ROOT]/bin/bundle: load

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/58989/faults/93063272)

**Comment by jrochkind** [comment]
Retried the job, immediatley failed again.

**Comment by jrochkind** [comment]
jrochkind  12:51 PM
@Sarah Newhouse
 Hey sarah, investigating something odd in our logs, can you confirm that at around 10:30am this morning, you ingested a video but then deleted it a couple minutes after ingesting it?

Sarah Newhouse  12:52 PM
yes, confirmed


jrochkind  12:52 PM
OK thanks!
It caused a weird edge case warning/error in our app, but no big deal really!

**Comment by jrochkind** [comment]
OK, the error keeps being reported, I think becuase the `ActiveEncodeStatus` is still in the db, so regular job keeps trying to update status!

I'm just going to delete it. 

```
rb(main):001> ActiveEncodeStatus.find(104).destroy
=>
#<ActiveEncodeStatus:0x00007eff4f90ef20
 id: 104,
 active_encode_id: "1701876794045-5zcvtr",
 asset_id: "1333a46e-27d2-485c-a1d1-4827ae1dbbc0",
 state: "failed",
 encode_error: "Demuxer: [Failed to read data: Error caching file]",
 percent_complete: 50,
 hls_master_playlist_s3_url: nil,
 created_at: Wed, 06 Dec 2023 10:33:14.285438000 EST -05:00,
 updated_at: Wed, 06 Dec 2023 12:44:15.995566000 EST -05:00>
irb(main):002>
```

104

**Comment by eddierubeiz** [comment]
```
ActiveEncodeStatus.where(state: "failed")
=>
[#<ActiveEncodeStatus:0x00007f8660e5d998
  id: 126,
  active_encode_id: "1706286174379-qifkqh",
  asset_id: "718e0267-4bcf-4598-b1f9-4e584d00ff7a",
  state: "failed",
  encode_error: "Demuxer: [Failed to read data: Error caching file]",
  percent_complete: 50,
  hls_master_playlist_s3_url: nil,
  created_at: Fri, 26 Jan 2024 11:22:54.522336000 EST -05:00,
  updated_at: Fri, 26 Jan 2024 12:56:32.992433000 EST -05:00>]
  ```

**Comment by eddierubeiz** [comment]
Yup - `ActiveEncodeStatus.find(126).destroy` solved the problem.
