### ISSUE TITLE
Dates before 1000 -- display without leading zeros.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#248]
See e.g. https://kithe.sciencehistory.org/works/k35694749

**Comment by jrochkind** [comment]
Are we sure that is "correct" or less confusing to actual users?

I had noticed the discrepency, but wasn't sure whether it was an actual problem.

**Comment by HKativa** [comment]
I think we should stay consistent with how these dates are currently structured, per our metadata guidelines, which are based on W3C International Standards.

**Comment by eddierubeiz** [comment]
Just a note: this is only about how the dates are displayed, not how they're stored. Happy to remove leading zeros if you think it would make more sense to users.

**Comment by jrochkind** [comment]
Yep. It's possible that in chf_sufia the dates didn't have leading zeroes in the db either, in contradiction of the W3C date standards. 

The new app fixes this. They will definitely be stored in a standard way, including leading zeroes, in the db and in our data. 

The question is if the display should be fixed. (I'm not actually sure what users would find less confusing or prefer myself).

**Comment by HKativa** [comment]
Let's fix the display to eliminate the leading zeroes.
