### ISSUE TITLE
Automatically sort CHM and Dist. collections chronologically

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#2494]
Due to some donor promotion that's going to happen with these collections, it would be ideal for the Distillations and Chemical Heritage collections chronologically sorted by default, from oldest to newest. 

https://digital.sciencehistory.org/collections/g6go8ar?sort=oldest_date
https://digital.sciencehistory.org/collections/avyv728?sort=oldest_date

The date fields are a little funny for this collection because only the year and season are included in the publication information. This means they appear slightly out of order, even when the "SORT BY OLDEST DATE" setting is applied. I wonder if the technical configuration of these collections should be automatically sorting the titles alphabetically instead. This would accurately put them in chronological order.  

This setting could apply to other collections as well, but I'm not sure which ones at this point. I recommend applying this change to only these two collections for now so that the donor work can move forward swiftly, and then circling back upon my replacement to establish a more thought-out application of this setting to the DC more broadly.

**Comment by jrochkind** [comment]
We have to figure out how to have code figure out _which_ collections to change the sort on, since there's nothing distinguishing these. 

Or I guess we could just hard-code some ID's in, but we don't love that. But if there's a deadline? When you say "due to some donor promotion", is there a particular tight deadline for this request?

We could also just change all collections, or all Library collections, to sort this way. The idea of "recently added" sort was you might be a regular visitor and want to see the new stuff, but that's never really been validated with users, we don't know if it's useful, we could just change all collections to default to publication year oldest first.

**Comment by jrochkind** [comment]
Once @apinkney0696 is sadly no longer working here, who would we check in with about this donor promotion timeline/priority, and also check in with on UX feedback?

I would tag Gabriella, but I cna't find her github account, we should probably add her to the project so it auto-completes if nothing else!

**Comment by jrochkind** [comment]
> This means they appear slightly out of order, even when the "SORT BY OLDEST DATE" setting is applied. I wonder if the technical configuration of these collections should be automatically sorting the titles alphabetically instead. This would accurately put them in chronological order.

I am loathe to add a new "sort by title" feature, because the use cases for it seem so minimal. 

Perhaps we could make sort by publication date sort secondarily by title when publication date is identical, although I don't love it either, maybe it's not too bad.

**Comment by jrochkind** [comment]
ONE way to handle this is we coudl add metadata to the Collection that actually specifies the sort order for that specificc collection -- publication date, order of addition, etc. 

We also discussed at the meeting today that we do NOT believe this is urgent, and we're going to leave it on teh backlog for future prioritization -- check back in a month or two.

**Comment by eddierubeiz** [comment]
OK - I'm going to do something simple here - just add a collection_sort_order key in the attr_json metadata. If the key is set, use the value to look up the sort key for this collection. If the key is not set, behave as usual.

**Comment by jrochkind** [comment]
@eddierubeiz Yep, that's what I was thinking! Please make it a select menu, not free entry!

The possibly somewhat tricky part will be getting the Blacklight config set on a per-collection basis like that, not sure what we have set up for that -- it should be very simple once we figure out the "magic" way to do it, so let me know if you are banging your head against it!

**Comment by eddierubeiz** [comment]
Consensus on the spec (see more notes at https://315chestnut.slack.com/archives/G58RGLLE8/p1707939588992229 ):

- Add the title field in solr;
- Don’t add any additional visible sort choices;
- Just re-define the [sort order for the above collections]  to under the hood be `[publication] date, title`.

**Comment by eddierubeiz** [comment]
[Distillations](https://digital.sciencehistory.org/collections/avyv728) is now sorted correctly.
