### ISSUE TITLE
Emails we are sending via AWS SES may not be fully authorized with SPF/DKIM, and should be

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#2497]
Emails we send via our AWS SES show up in gmail as "via amazones.com" For instance, Oral Histories delivery emails. 

While this isn't a huge problem as long as they get delivered, it is a bit sloppy, and indicates everything may not be set up correctly to maximize deliverability. Clicking on the "via" in gmail gives you this support document:

https://support.google.com/mail/answer/1311182?hl=en#zippy=%2Ci-see-an-email-address-next-to-the-senders-name

Which suggests our emails are not properly fully authenticated:

> * If you send messages with a bulk mailing vendor or third party affiliates, [prevent your emails from being blocked by Gmail](https://support.google.com/mail/answer/81126). 
> * Publish an SPF record that includes the IPs of the vendor or affiliates which send your messages.
> * Sign your messages with a DKIM signature that is associated with your domain.
> * Make sure the domain in the "From:" address matches the domain you're using to authenticate your emails.

We think we had this set up properly at one point, perhaps it stopped being set up properly? Perhaps there is a check we could set up to alert us if it breaks?

**Comment by jrochkind** [comment]
@CHF-IT-Staff

**Comment by jrochkind** [comment]
Please add to ticket headers from a sample email

**Comment by eddierubeiz** [comment]
Headers as of today (redacted):

```
Delivered-To: eddierubeiz@gmail.com
Received: by 2002:ab3:7ad1:0:b0:258:56cd:dae4 with SMTP id [REDACTED];
        Thu, 29 Feb 2024 10:07:32 -0800 (PST)
X-Google-Smtp-Source: [REDACTED]
X-Received: by [REDACTED] with SMTP id [REDACTED];
        Thu, 29 Feb 2024 10:07:31 -0800 (PST)
ARC-Seal: i=1; a=rsa-sha256; t=1709230051; cv=none;
        d=google.com; s=arc-20160816;
        b=[REDACTED]==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=feedback-id:content-transfer-encoding:mime-version:subject
         :message-id:to:from:date:dkim-signature;
        bh=[REDACTED];
        fh[REDACTED];
        dara=google.com
ARC-Authentication-Results: i=1; mx.google.com;
       dkim=pass header.i=@amazonses.com header.s=[REDACTED];
       spf=pass (google.com: domain of [REDACTED]@amazonses.com designates 54.240.48.97 as permitted sender) smtp.mailfrom=[REDACTED]@amazonses.com;
       dmarc=fail (p=NONE sp=NONE dis=NONE) header.from=sciencehistory.org
Return-Path: <[REDACTED]@amazonses.com>
Received: from a48-97.smtp-out.amazonses.com (a48-97.smtp-out.amazonses.com. [54.240.48.97])
        by mx.google.com with ESMTPS id l2-20020a05620a28c200b0078727348af7si2090924qkp.470.2024.02.29.10.07.31
        for <eddierubeiz@gmail.com>
        (version=TLS1_2 cipher=ECDHE-ECDSA-AES128-GCM-SHA256 bits=128/128);
        Thu, 29 Feb 2024 10:07:31 -0800 (PST)
Received-SPF: pass (google.com: domain of [REDACTED]@amazonses.com designates 54.240.48.97 as permitted sender) client-ip=54.240.48.97;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@amazonses.com header.s=[REDACTED] header.b=SmCbQySf;
       spf=pass (google.com: domain of [REDACTED]@amazonses.com designates 54.240.48.97 as permitted sender) smtp.mailfrom=[REDACTED]@amazonses.com;
       dmarc=fail (p=NONE sp=NONE dis=NONE) header.from=sciencehistory.org
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/simple; s=[REDACTED]; d=amazonses.com; t=1709230051; h=Date:From:To:Message-ID:Subject:Mime-Version:Content-Type:Content-Transfer-Encoding:Feedback-ID; bh=[REDACTED]; b=[REDACTED]
Date: Thu, 29 Feb 2024 18:07:31 +0000
From: no-reply@sciencehistory.org
To: eddierubeiz@gmail.com
Message-ID: <[REDACTED]@email.amazonses.com>
Subject: Test message from Eddie. Please ignore.
Mime-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit
Feedback-ID: 1.us-east-1.[REDACTED]:AmazonSES
X-SES-Outgoing: 2024.02.29-54.240.48.97
```

**Comment by eddierubeiz** [comment]
The `via amazonses.com` is gone. Chuck generated and added the 2 DKIM DNS records for AWS, and this was apparently all this took.
I'll look into updating our Terraform settings, if it's needed. Leave this ticket "in progress" until that's taken care of.
I also want to make a note on the wiki on our SES page that states we 're now using DKIM and points to the relevant admin pages in AWS.
