### ISSUE TITLE
No automatic refresh after file ingest

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#251]
When ingesting files, page does not automatically refresh to indicate ingest is complete, as in current app.  Screenshot follows of what page looks like before reloading:

![image](https://user-images.githubusercontent.com/30178818/61651995-0a015c80-ac85-11e9-9e6c-8f97e16a59cd.png)

One must reload page to determine whether ingest is successful.

**Comment by jrochkind** [comment]
Are you sure the current app refreshes the page to indicate ingest is complete?

Can you provide me a screenshot or description of the relevant page in current app that you experience as refreshing to indicate ingest is complete?

Either way, this represents something you find more confusing in the new app than the current app, which is something we can hopefully address. It's somewhat difficult to figure out how to address it technically. Looking at the old app for what it does would be useful as a model for me -- but I wasn't aware the old app did this at all and don't understand at present where it does!

**Comment by jrochkind** [comment]
Closing, not going to do this for now -- we hope just explaining the UI to people will suffice. Can reopen later!
