### ISSUE TITLE
Remove the "three month summary" filter on the OH page, and add pagination.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2511]
If a request is pending for more than 3 months (which is the case for at least one request at the moment, due to requester not answering our follow-up questions), there is currently no way to approve or deny the request.

Also, and more generally,  the "new filter by status" menu is confusing when combined with the 3-month time limit.

I have @sarahschneiderSHI's approval to do this.

**Comment by jrochkind** [comment]
let's add pagination to teh top of the results too, as a standard practice!
