### ISSUE TITLE
`can't find executable rspec` error, even after setting BUNDLE_WITHOUT="" and waiting.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2519]
IMPORTANT NOTE: 5 days later, on Tuesday Jan. 30th, I can't reproduce the problem.
Could I have set `BUNDLE_WITHOUT="" ` on staging instead of production? Not impossible, since I was dealing with a lot of stuff on Friday.

Original notes re: this problem:
Just adding this for later investigation. I'm following the instructions athttps://github.com/sciencehistory/scihist_digicoll/tree/master/system_env_spec .
`heroku config:set BUNDLE_WITHOUT="" --app scihist-digicoll-production`

[wait half an hour or so]

Make sure the var is set:
```
$ heroku config --app scihist-digicoll-production | grep WITHOUT
BUNDLE_WITHOUT:
```

We still get:
```
$ heroku run "rspec system_env_spec" --app scihist-digicoll-production
Running rspec system_env_spec on ⬢ scihist-digicoll-production... up, run.6590 (Standard-1X)
/app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/rubygems_integration.rb:308:in `block in replace_bin_path': can't find executable rspec for gem rspec-core. rspec-core is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
	from /app/vendor/ruby-3.2.2/lib/ruby/3.2.0/bundler/rubygems_integration.rb:347:in `block in replace_bin_path'
	from /app/bin/rspec:29:in `<main>'
```

**Comment by jrochkind** [comment]
I think you LATER wrote:

> I ran all the "is present" tests in https://github.com/sciencehistory/scihist_digicoll/blob/master/system_env_spec/system_env_spec.rb and the only utility we're missing is exiftool.

https://github.com/sciencehistory/scihist_digicoll/issues/2518#issuecomment-1912280897

How'd you manage to do that without this working?

**Comment by eddierubeiz** [comment]
Oh, I just ran the commands from a bash shell.

**Comment by jrochkind** [comment]
> Oh, I just ran the commands from a bash shell.

I'm still confused how THAT could work if the BUNDLE_WITHOUT didn't!  

When we get to this, lets pair on it initially.

**Comment by eddierubeiz** [comment]
I want to test this one more time...

**Comment by eddierubeiz** [comment]
As of today I can't reproduce this in production.

**Comment by jrochkind** [comment]
OK, here's one confusing thing -- if you want to get rspec and other development- or test-only gems installed, you have to:

1) Set BUNDLE_WITHOUT=""
2) and _then_ re-deploy!  The gems get installed on deploy, so you have to first change the config so when gem install happens it WILL install them, but then trigger a deploy (not just restart!) to actually do the install. 

I'm wondering if the confusing nature of this process just led to confusion?

We could just move rspec to be always installed on every deploy, so it's useable for that system check, if we wanted. I guess the cost is just a slightly bigger deploy. We'd want ot make sure it wasn't automatically loaded in production with a `require:false` in the gemfile, I guess.

**Comment by eddierubeiz** [comment]
In that case let's just make this issue about updating the documentation. We only really need `system_env_spec` once in a while, but when we need it, we really need it. Anything that can reduce the amount of confusion is good.

**Comment by eddierubeiz** [comment]
OK, docs updated.
