### ISSUE TITLE
Onboarding Jahna Auerbach as new DC librarian

### ISSUE THREAD

**Issue by Gabz73** [sciencehistory/scihist_digicoll#2527]
Please create an account for Jahna Auerbach in the DC that gives her the same privileges that Annabel had.  Her start date is 2/20/2024. 

Since she doesn't have an active SHI email account yet, please let me know what her credentials are and I will share them with her.
You asked to be reminded to create a checklist of things that need to be set up for new staff in the DC Wiki.

Things Gabriela will do:
I will make sure her email gets added to the digital@sciencehistory, so no need to do that.  
Once she starts, I will have her share her GitHub user name with you so that she can be added to our organization.

**Comment by jrochkind** [comment]
> Since she doesn't have an active SHI email account yet, please let me know what her credentials are and I will share them with her.

So, as a matter of policy we don't share passwords over email or other channels. 

Also, we have been registering everyone in DC with their @sciencehistory.org account, which i think may also be a matter of policy, to use the business account for business purposes?  Every other account in there is registered with the @sciencehistory.org account. 

So I'd propose waiting until Jahna is onboarded to do this, as part of onboarding? 

It should not take us long, we can definitely prioritize it to get her on board quickly, once she has an email address!

**Comment by Gabz73** [comment]
OK, that makes a lot of sense.  I will let you know once I am told that her @sciencehistory email has been created.  Do you want to just close this ticket and I'll put in a new one then, or should I use this one when the time comes?


Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

________________________________

**Comment by jrochkind** [comment]
We can leave it open reminding us it will have to be done, no problem! Or whatever works best for you!

**Comment by Gabz73** [comment]
Sounds good!


Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

________________________________

**Comment by Gabz73** [comment]
Hi! Jahna's email will be jauerbach@sciencehistory.org.  Please create a DC account for her. In terms of sharing her initial password, perhaps it could be shared at the Wednesday meeting?  Or Eddie could write it down and leave it in her office?

**Comment by jrochkind** [comment]
Once we have confirmed an account is created, the best thing to do with password is actually for her to go to login page and click "forgot my password", and then it'll email a password reset link and she can set it to whatever she likes!

(I am not sure if the passowrd reset links can get caught in sendio or not, possibly they are exempt but otherwise something else to look out for)

**Comment by Gabz73** [comment]
Got it!


__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

**Comment by eddierubeiz** [comment]
Reactivated her account in the Digital Collections.

**Comment by eddierubeiz** [comment]
Sent Jahna a prompt to sign up for a Github account.

**Comment by Gabz73** [comment]
Jahna is in GitHub now, and has her DC credentials.  So I think we can close this?

**Comment by eddierubeiz** [comment]
Not quite, but almost.

**Comment by eddierubeiz** [comment]
I just need Jahna's username on GitHub, after which I can add her to our team. Following up with her now via Slack...

**Comment by Gabz73** [comment]
Her user name is jauerbach26

**Comment by eddierubeiz** [comment]
Hmm... @CHF-IT-Staff - do you have access to add her to [the team](https://github.com/orgs/sciencehistory/teams/collaborator-team)?

**Comment by CHF-IT-Staff** [comment]
I just sent the invitation to Jahna. (I also added Eddie to the Collaborator Team)

**Comment by eddierubeiz** [comment]
Great - I think we're all set. I'll move this ticket to review.

**Comment by eddierubeiz** [comment]
Jahna does have an account! (reopened the ticket temporarily in response to https://github.com/sciencehistory/scihist_digicoll/issues/2492#issuecomment-2302710280 but closing it again. )
