### ISSUE TITLE
Email address lookup needs to be case insensitive on the OH sign in page

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2543]
On the oral_history_session/new page:
Safari changed the user's email address by capitalizing the first letter, upon which the user was told there was no record of a user with that email.

Please make the match case-insensitive.

**Comment by jrochkind** [comment]
REalize this also means we would create duplicate records for varying cases, which I guess we shoudln't. I guess we need to normalize on insert as well as lookup. Perhaps in the DB? Need to do a bit of research on best practices here.
