### ISSUE TITLE
"play" arrow overlay on video work thumbnails

### ISSUE THREAD

**Issue by archivistsarah** [sciencehistory/scihist_digicoll#2550]
I'd like to add a "play" button arrow overlay to any thumbnails of video works. No change to behavior -- clicking on the thumbnail would still send users to the work page where they can play the video.  

The priority for this is thumbnails that appear in the "recently added" section of the DC homepage, where there's no indication that these low-res kind of uninteresting-looking image are in fact videos (we have a lot of white guys at poorly-lit podiums) and to me, they  look out of line with our usual crisp, high-res photographs. I'd like something to indicate why these are visually different. 

Users may also expect that clicking on one will just take them to a larger version of the thumbnail image, and so be _slightly_ more inclined to click if they can tell clicking will take them to a video. 

It's also another way to advertise on the front page that we have video in the digital collections.

![video thumbnails in DC recently added](https://github.com/sciencehistory/scihist_digicoll/assets/25084902/6f27c139-7e25-4c1b-bff2-eb9fb9e52d2e)

If it's easy to just apply this to all video work thumbnails wherever they appear (search results, collection pages) then that's great. Although those are a slightly lower priority since they at least have the genre "video recording" appearing above the work title. But a graphic representation of that for folks just skimming the images would be helpful, although I'm open to arguments that obscuring the thumbnail image may actually decrease accessibility. 

I don't think this is at all a priority, but hopefully a small project that can get shuffled into your work sometime in the next year.

**Comment by archivistsarah** [comment]
Oh, that's a good point -- it is an extra click to then play the file. 

Yes, a camera icon is fine with me. Just want to distinguish the thumbnails from the static images.

**Comment by eddierubeiz** [comment]
This still needs work, and especially:
- The icon doesn't look so great to begin with
- We might want to make some or all of the icon's background transparent
- There's still some repetition in the code (both HTML and CSS)
- The positioning isn't quite correct
- Not sure we should be using inline SVG

Current screenshots:
![Screenshot 2024-07-09 at 2 28 35 PM](https://github.com/sciencehistory/scihist_digicoll/assets/94723/0d30767b-d5c7-4b68-96d0-94f98c983de1)
![Screenshot 2024-07-09 at 2 28 04 PM](https://github.com/sciencehistory/scihist_digicoll/assets/94723/b6b700a1-29c7-44de-991c-6bbba7c613ce)
