### ISSUE TITLE
Consider not adding a sign-in link in e-mails that deny an OH request.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2558]
Paraphrasing slightly for clarity:

Dave and @sarahschneiderSHI  prefer that there not be a link in [emails that deny an OH request]:
- if someone only requested one oral history and they were denied access, they won't need a link
- if they requested multiple interviews they would already have the sign-in link in other e-mails).

![image_720](https://github.com/sciencehistory/scihist_digicoll/assets/94723/937f064f-3c52-4c93-a54f-99216d37ad3e)

Remove the following copy in these emails:
"You can view the status of your oral history requests [...] Access Science History Institute Requests"

It's fine to leave the title of the OH linked to the OH page.

**Comment by sarahschneiderSHI** [comment]
Thank you for sharing that explanation. It is fine to keep it in the "deny" e-mails then in case it helps someone access their other requests.

**Comment by eddierubeiz** [comment]
On rereading this thread I think it's fine to close this ticket. We can reopen it later if we change our mind.
