### ISSUE TITLE
HoneyBadger needs to report staging deploys to Slack.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2573]
Here’s the integration that is supposed to be posting heroku deploys to Slack:
https://app.honeybadger.io/projects/58989/channels/2179775/edit

Searching `#digital-technical` for the phrase `deployed scihist_digicoll to staging` reveals that HB has not reported staging deploys to Slack since November 2023.

Let's fix this.

**Comment by jrochkind** [comment]
https://docs.honeybadger.io/lib/ruby/getting-started/tracking-deployments/#heroku-deployment-tracking

**Comment by jrochkind** [comment]
OK, we track deploys to honeybadger with a heroku webhook. 

I believe the staging webhook is set to a honeybadger URL with an out of date API key. Probably from some past API key rotation. 

Will try re-setting with current staging API key.

**Comment by jrochkind** [comment]
fixed
