### ISSUE TITLE
FAST autocomplete yields “no results

### ISSUE THREAD

**Issue by JAuerbach26** [sciencehistory/scihist_digicoll#2589]
When creating or editing a work in the digital collection, the sections that are linked to FAST are not populating results.

When typing in "Annapolis, Maryland" in the place fields no results are populating.
When typing "Massie, Samuel" in the creator field no results are populating.
When I typed "scientists" in the subject heading field no results are populating. 

When I typed "English" into the language field English did populate.

**Comment by jrochkind** [comment]
We use the free OCLC "assignFast" (aka search-fast) API to power this. 

https://www.oclc.org/developer/api/oclc-apis/fast-api/assign-fast.en.html

The API is currently always returning zero results for our queries -- it's not returning an error, it's returning a succesful response with zero results. 

For the example URl in the OCLC documentation itself, it does the same thing!

http://fast.oclc.org/searchfast/fastsuggest?&query=hog&queryIndex=suggestall&queryReturn=suggestall%2Cidroot%2Cauth%2Ctag%2Ctype%2Craw%2Cbreaker%2Cindicator&suggest=autoSubject&rows=3&callback=testcall


```json
testcall({
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"suggestall:hog",
      "json.wrf":"testcall",
      "fl":"suggestall,idroot,auth,tag,type,raw,breaker,indicator",
      "rows":"3"}},
  "response":{"numFound":0,"start":0,"docs":[]
  }})
```

Note the empty array after `docs: []` -- that is expected to have results. 

If I remove the parameter `&queryReturn=suggestall%2Cidroot%2Cauth%2Ctag%2Ctype%2Craw%2Cbreaker%2Cindicator`, then I _do_ get results -- but that paramter used to be necessary, and now causes zero results?

The URL our app is using is constructed by the "questioning authority" gem (aka `qa`) at https://github.com/samvera/questioning_authority

So if the URL it needs to send to OCLC API has changed... we need to fix it in QA and/or customize QA locally. 

Probably  first we should attempt to find someone at OCLC to report this to and figure out what's going on.  

If it's a really urgent matter, we could simulateneously try reverse engineering the new way the OCCL API performs and writing custom local code. ping @Gabz73 to help determine how urgent this is.

**Comment by jrochkind** [comment]
Here's an example URL our app (via qa) sends to OCLC for query `can`:

http://fast.oclc.org/searchfast/fastsuggest?&query=can&queryIndex=suggestall&queryReturn=suggestall%2Cidroot%2Cauth%2Ctype&suggest=autoSubject&rows=20

You can see it's zero result response In this case we have to remove not just the `queryReturn` but some of the other parameters.

**Comment by jrochkind** [comment]
@JAuerbach26 do you know when this stopped working, or when the last time we are sure it was working was?

Janha says: It was working on Friday

**Comment by jrochkind** [comment]
This seems to be working again -- we changed nothing.  The OCLC service had some kind of unexpected problem, which has resolved. 

I did get replies from OCLC. 


Rebecca Dean deanr at oclc.org

> Greetings, Jonathan,
>
> Thank you for reporting the issues with the FAST API; a ticket for our development staff has been opened to start an investigation—this is the first report of this issue.  Staff will be in contact with you as we work to resolve this issue. 
>
> Thank you again for contacting us,
>
> --Becky Dean


> Hi, Jonathan,
>
> Our staff has started an investigation into the issue you reported yesterday, and we are asking if you could please reattempt the scenarios you reported.  We believe this may have been a timing issue.
>
> Many thanks for your assistance, and please respond when you are able.
>
> Regards,
> --Becky Dean

**Comment by jrochkind** [comment]
And rebecca writes:

> Hi, Jonathan,
>
> This will happen periodically—once a month.
>
> At present, a predicable date/time has not be set; so I would suggest that if you encounter issues, you can certainly contact us (using the form you submitted this time) and we will investigate and get back to you.  Another option would be to wait a few hours, then retest.  I can appreciate that neither are ideal, but I hope you are able to accept this as a reasonable path forward.
>
> Please contact me with any additional concerns you may have,
>
> --Becky Dean
