### ISSUE TITLE
Track how many people use "search inside the text" feature

### ISSUE THREAD

**Issue by Gabz73** [sciencehistory/scihist_digicoll#2606]
I would like us to be able to track how many users use the "search inside the text" feature from the work's page, from the image viewer.I would also like to know what term they are searching.

 I don't know if this is something we can achieve via Google Analytics, so that I could then capture it as part of the monthly stats?  If it isn't achievable via GA, I would like a way that I could easily access the monthly #s without having to bother the tech team.

**Comment by eddierubeiz** [comment]
We decided this morning not to report the search phrase to GA (this feature is in PR #2715, which is closed for now) until we have a chance to test it in staging. Instead, let's report just the *fact* that someone searched inside the work.
