### ISSUE TITLE
Add all items on page to Cart

### ISSUE THREAD

**Issue by Gabz73** [sciencehistory/scihist_digicoll#2615]
1. From the default view on the works page, allow users to "select all items on page" to add to the Cart: this would be beneficial when a user wanted to add all their recently created or recently added works to the cart for metadata batch work, or metadata review

2.  when a user runs a search on the works page, allow them to "select all items on page" to add to Cart.  (Jonathan asked if what we really want is "add search results to cart."  I would like the user to be able to deselect items if needed, so if "add search results to cart" would eliminate the ability to de-select individual items, then the answer to "do we want 'add search results to cart'?" is "no").

**Comment by jrochkind** [comment]
I am not sure how "select all items on page" lets people deselect items in a way "select all items in search" does not, I think I'm not thinking of the same UI as you!

When we get to this, we'll just have to be careful to understand the use case and start with paper mockups to make sure we're all on the same page of what's going on. This one to me seems to have a high risk of developers going off and doing something that isn't what you meant, if we're not careful!

**Comment by Gabz73** [comment]
Use case for "select all items on page" (vs select all items in search): every week I review the records Jahna has created since the previous week.  I go to the "Works" section of the dashboard and sort the page by "Created."  Of the 25 items on the page, 24 were created in the last week.

I would like to be able to add all the items on the page to my cart, and then deselect the one item that I don't want.  (I could remove it from the cart, but once I go to the cart, it is not easy to see which one I want to remove because "date created" is not displayed.

**Comment by eddierubeiz** [comment]
One thing to keep in mind is that sorting and deleting rows and columns is (by nature) easy to do in a spreadsheet, and (also by nature) clunky in the digital collections.

So the general pattern I imagine is for the user to use fairly broad strokes to add a bunch of stuff (possibly including hundreds of unwanted rows, and dozens of unwanted columns), and export the whole thing into Excel, where it's only a matter of seconds to get rid of the extra junk.

**Comment by jrochkind** [comment]
I'm not sure if we had been thinking of this feature in combination with the export as CSV feature... for the use cases we're talking about, would what you're thinking about, @eddierubeiz , then require the ability to "import" the CSV back to the cart after you've "gotten rid of extra junk" in Excel, so you can bulk edit it again?
