### ISSUE TITLE
add finding aid links to all archives department works without one

### ISSUE THREAD

**Issue by archivistsarah** [sciencehistory/scihist_digicoll#2627]
### TODO
- [x] Remove now-obsolete finding aids using the rake task at https://github.com/sciencehistory/scihist_digicoll/pull/2726 . The command is `bundle exec rake scihist:data_fixes:remove_extra_finding_aids` .

### Description
Currently, our metadata creation practice is that all works/items belonging to the archives department contain a publicly accessible link from the work in the digital collections to the public finding aid in ArchivesSpace for the collection the work belongs to.

But because we launched the Digital Collections well before the ArchivesSpace public user interface was in use, only archives DC works created _after_ the ASpace PUI was in use contain that link. Approximately 5000 archives works created before the ASpace PUI launch are missing this link and archives staff would like for it to be retroactively added to their metadata. 

Links to finding aids are added to metadata using the Related Link fields:
Category = Finding aid
URL = [something that looks like] https://archives.sciencehistory.org/repositories/3/resources/236

It appears on the front end of the Digital Collections as a visually distinct button ("collection guide") in the Institutional Location section:
![institutional location fields DC work](https://github.com/sciencehistory/scihist_digicoll/assets/25084902/fdf62920-63c3-4bee-bac5-cb729779985b)

Other info:
All archival collection-level works in the DC _should_ already contain a link to their finding aid in the collection's related link field. Is it possible to have works belonging to these collections automatically inherit this link? As a one-time batch update?

All archival works in the DC _should_ be from a fully processed archival collection that _should_ have a public finding aid in the ArchivesSpace PUI. It is possible, however, that archival items were digitized from collections that do not yet have public records in ArchivesSpace (this shouldn't be happening, but just trying to cover my bases here).

I can generate a CSV containing the accession number (in the DC metadata this is stored in External ID: Accession No.), title, and public URL for each archives collection with a public finding aid and/or only the collections that have digitized content in the DC. 

Also, ASpace has an API and OAI-PMH functionality that are options if we need them for this or other projects.

**Comment by jrochkind** [comment]
Let's talk about if we want to just display link from Collection a Work is part of (possibly changing workflow going forward?), or if we do want to continue adding this duplicate link to every Work, and bulk do that. 

Initially at next weekly meeting?

**Comment by archivistsarah** [comment]
Sure, I can pop into the weekly meeting.

**Comment by jrochkind** [comment]
We decided to display the Finding Aid link from linked Collection, so it does not need to be entered in individual Work. 

We're also going to run a report of any Works in Archive that are not linked to a public collection with a finding aid link.

**Comment by eddierubeiz** [comment]
@archivistsarah  - in Staging, at least, the only `Archives` department collections in the d.c. that do *not* currently have external URL links to Aspace except for these three:
- Houdry: https://digital.sciencehistory.org/collections/dr26xx95r
- SHI 16mm films: https://digital.sciencehistory.org/collections/7gfmcek
- CHEM 16mm films: https://digital.sciencehistory.org/collections/jpwtxyp
I suspect this is just fine :)

**Comment by eddierubeiz** [comment]
Oh, looks like Houdry is here: https://archives.sciencehistory.org/repositories/3/resources/63

**Comment by jrochkind** [comment]
@eddierubeiz Can you also check for Archival Works that are not assigned to an Archives department collection though?

The way I would do this is first complete the main work, then basically you want to look for an Archives department Work that does not have a finding aid to display under the new logic. This could be because it doesn't have a (public) Collection assigned as well as if the Collection does not have a finding aid link.

**Comment by archivistsarah** [comment]
@eddierubeiz correct -- those two (SHI 16mm and CHEMStudy) do not have finding aids. If this is a roadblock I can spend some time them this week?

**Comment by eddierubeiz** [comment]
No problem at all @archivistsarah .

**Comment by eddierubeiz** [comment]
Hi @archivistsarah .
FYI, here's a list of works for which:
- there's no finding aid metadata attached to the work itself;
- there's ALSO no way to look up a finding aid via the collection the work is in.

[Archival works in the digital collection with no finding aid.xlsx](https://github.com/user-attachments/files/16366645/Archival.works.in.the.digital.collection.with.no.finding.aid.xlsx)

It's not much, roughly 200 items. Happy to discuss results with you.

**Comment by eddierubeiz** [comment]
Recipe for the above:

```
csv_string = CSV.generate do |csv|
	Work.where("json_attributes -> 'department' ?  'Archives'").each do |w|
		work_related_link = w.related_link.select { |rl| rl.category == "finding_aid" }.map(&:url).flatten.first
		coll_related_link =  w.contained_by.where(published: true).map { |col| col.related_link.select { |rl| rl.category == "finding_aid" }.map(&:url) }.flatten&.first
        csv << [w.friendlier_id, w.parent&.friendlier_id, w.title.truncate(50), w.published?, w.contained_by&.first&.title&.truncate(20), w.physical_container&.box] if work_related_link.nil? && coll_related_link.nil?
	end
end
puts csv_string;0
```

**Comment by eddierubeiz** [comment]
Just for future reference, I pasted the above code into a ruby file, then ran:
cat export.rb | heroku run console --no-tty > prod_out.csv
Then I imported the csv into Google Spreadsheet, then pasted the resulting table into Excel, then uploaded that to GitHub.

**Comment by jrochkind** [comment]
> If this is a roadblock I can spend some time them this week?

Not any kind of roadblock for us, we're just making a report of every Archives work that _wont'_ have a link to Finding Aid after this new thing, so you can make sure none of them are mistakes or problems, whether they are or not is up to you!

**Comment by eddierubeiz** [comment]
Yeah, there's no roadblock at all - rather, we're working on parallel tracks.
* One track is making sure works with no link to a finding aid can display a link to to their collection's finding aid.
* The other track is focusing on works that aren't in a collection and ALSO don't have a finding aid.

**Comment by eddierubeiz** [comment]
Metadata guidelines:
The finding aid link will be stored in as few places as possible.
- Works that **are not** currently part of a DC collection, at Sarah's discretion,
  - will **either** have a collection created for them (with its own link to a f. a.)
  - **or** have f. a. link attached directly to the work;
- Works that **are** part of a D.C. collection
  - Child works
    - will inherit f. a. link from their parent work, or its collection;
  - Regular works
    - will get their  f. a. link from the collection.

**Comment by eddierubeiz** [comment]
1. @archivistsarah is going to make changes to the metadata per the above guidelines.
2. In parallel, Eddie has the green light to modify the code so that works also take collections, parent works, and the collections _of_ parent works into consideration when looking for a finding aid to display in the work metadata.

**Comment by jrochkind** [comment]
Just I hope @archivistsarah isn't planning on manually editing hundreds of works to, say, remove currently existing links. We can do that batch for her, right?

**Comment by eddierubeiz** [comment]
There's some piecemeal work, and Sarah can and will request any batch changes from me. It should be very manageable.

**Comment by archivistsarah** [comment]
> Just I hope @archivistsarah isn't planning on manually editing hundreds of works to, say, remove currently existing links. We can do that batch for her, right?

Definitely not planning on it! I'll let Eddie know if/when that needs to happen.

I'm going to give Jahna a list of the new collections that need to be created and the parent/standalone works (without finding aid links currently) that should belong to them. She'll create the collections and add the works as this is a bit more in her responsibilities than mine.

**Comment by eddierubeiz** [comment]
When Sarah and Jahna are done with the first round of modifications, we can check their work with:
```
Work.where("json_attributes -> 'department' ?  'Archives'").each do |w|
	arr = WorkShowInfoComponent.new(work: w).links_to_finding_aids.to_a
	pp  [w.friendlier_id, w.parent&.friendlier_id, w.title.truncate(50), w.published?, w.contained_by&.first&.title&.truncate(20), w.physical_container&.box] if arr.empty?
end;0
```

**Comment by eddierubeiz** [comment]
```
# cat remove_extra_metadata.rb | heroku run console  --no-tty
Work.where("json_attributes -> 'department' ?  'Archives'").each do |work|

	current_related_links = work.related_link

	next unless current_related_links.present?
	next unless current_related_links.map { |rl| rl.category }.include? 'finding_aid'

	 models = [
        work.parent, work.contained_by, work.parent&.contained_by
      ].flatten.compact

	other_sources_of_finding_aid_url =  models.map do |mod|
		mod.related_link.select { |rl| rl.category == "finding_aid" }.map &:url
	end.flatten.uniq

	new_related_links = current_related_links.reject do |rl|
		rl.category == "finding_aid" &&
		other_sources_of_finding_aid_url.include?(rl.url)
	end

	if Set.new(current_related_links) != Set.new(new_related_links)

		if new_related_links.empty?
			new_related_links = nil 
		end

		work.update!(related_link: new_related_links)

		puts "#{ work.friendlier_id.ljust(10) } before: #{current_related_links}"
		puts "#{ work.friendlier_id.ljust(10) } after:  #{new_related_links}"
		puts ""
	end

end.to_a; 0
```

**Comment by eddierubeiz** [comment]
The above code removes the now-obsolete finding-aid links from items.

I ran it in staging and got the following list of removed finding aids:
[finding_aids_removed.txt](https://github.com/user-attachments/files/16616499/finding_aids_removed.txt)

The end user sees no difference _(compare e.g. https://staging-digital.sciencehistory.org/works/zugqcua and https://digital.sciencehistory.org/works/zugqcua )_

but the underlying metadata is now cleaner:
_compare e.g. https://staging-digital.sciencehistory.org/admin/works/zugqcua and https://digital.sciencehistory.org/admin/works/zugqcua_ .

We can run this in production next week.

**Comment by eddierubeiz** [comment]
(After we run this last step, fine to move this issue to "review".)

**Comment by jrochkind** [comment]
@eddierubeiz Finding Aid links are shown in only one place and not indexed, which simplifies the reliability and performance issues somewhat compared to collection ID.
