### ISSUE TITLE
Report of textual works without OCR

### ISSUE THREAD

**Issue by Gabz73** [sciencehistory/scihist_digicoll#2652]
Can I have a report of works for which
Language = French or German or Spanish 
Department = Library or Archives or Museum
Format = text
OCR enabled = NO

Report should show:
work ID (what do we call this - I mean the "of8lva6" in "https://digital.sciencehistory.org/works/of8lva6")
title
date/s
desc
genre/s

**Comment by eddierubeiz** [comment]
(We call that the `friendlier_id`).

**Comment by Gabz73** [comment]
Awww!


__________________________________

Gabriela Zoller   (she, her, hers)
Director of Library Services
Othmer Library of Chemical History
t. +1.215.873.8289

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
We tell the stories behind the science.
sciencehistory.org<https://www.sciencehistory.org>

**Comment by eddierubeiz** [comment]
Just for historical interest:
https://github.com/sciencehistory/scihist_digicoll/issues/2080

**Comment by eddierubeiz** [comment]
```
scope = Work.
        where("json_attributes -> 'department' ?| array[:depts  ]", depts:   ['Archives', 'Museum', 'Library'] ).
        where("json_attributes -> 'language'   ?| array[:langs  ]", langs:   ['English', 'French', 'Spanish', 'German'] ).
        where("json_attributes -> 'format'     ?| array[:formats]", formats: ['text'] ).
        where("(json_attributes -> 'ocr_requested')::boolean = false" )

report = WorkCartSerializer.new(scope, columns: [:title, :url, :date, :description, :genre]).to_a

puts CSV.generate { |csv| report.each { |line| csv << line }}
```

**Comment by eddierubeiz** [comment]
With that code in a file named `export.rb`,
```
cat export.rb | heroku run console --app=scihist-digicoll-production --no-tty > prod_out.csv
```

**Comment by eddierubeiz** [comment]
Here's the resulting file. Happy to adjust, of course.
[June_12th_report.xlsx.gz](https://github.com/user-attachments/files/15809593/June_12th_report.xlsx.gz)

**Comment by eddierubeiz** [comment]
Here it is. Let me know if you need anything adjusted.
[june_12_report.xlsx](https://github.com/user-attachments/files/15809621/june_12_report.xlsx)

**Comment by eddierubeiz** [comment]
I created OCR for these in production today.
