### ISSUE TITLE
date-range Facet limit histogram is weird

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#270]
1. Start [here](https://kithe.sciencehistory.org/catalog?utf8=%E2%9C%93&search_field=all_fields)
3. Click `Date` in the faceting apparatus on the left
4. Type `1973` into the lower bound for dates
5. Click the `apply` button to limit dates.
6. The HTML is broken. Looks like malformed HTML.

**Comment by jrochkind** [comment]
oh man I ran into something similar that eventually went away, and I was never able to fix it. 

Something is weird with the code that is using JS canvas to plot that graph, and deciding how wide the graph should be. 

I am not sure why it doesn't occur on chf_sufia, but Blacklight's own CSS changed. It is hard to reproduce. I'm not sure if it is reproducible on stock latest Blacklight and blacklight_range_limit. 

This may be a hard one to fix. blacklight_range_limit is some hacky stuff.

**Comment by jrochkind** [comment]
hmm, 1973 isn't a magic number though, seems to be happening with nearly anything. This is indeed bad. gah.

**Comment by eddierubeiz** [comment]
Yeah, this is generalized. I came across it working on my featured topics page.

**Comment by jrochkind** [comment]
Note could not be reproduced on Windows Chrome on 5th floor conference room. 

i also noticed that clicking on the "Date" heading to collapse and then again to expand the date limit area -- gets it to be sized correctly again.

**Comment by HKativa** [comment]
Note: I did reproduce this bug on Windows Chrome on my office computer while testing Kithe on 10/30/2019.

![Date_histogram_error.jpg](https://images.zenhubusercontent.com/5d8e1dc48e31e4000184141b/f442894d-e64a-4084-8aed-d7b5d8f436d7)

**Comment by jrochkind** [comment]
Filed with blacklight_range_limit at https://github.com/projectblacklight/blacklight_range_limit/issues/111

**Comment by HKativa** [comment]
Note in case this isn't a known issue: this error occurs when using the "limit dates" feature on the homepage as well. 

![Date_homepage_search.jpg](https://images.zenhubusercontent.com/5d8e1dc48e31e4000184141b/d1f53196-57be-4b29-955f-3a1aa9ecf982)

Select "go" and you get:

![Date_histogram_error_homepage.jpg](https://images.zenhubusercontent.com/5d8e1dc48e31e4000184141b/0c85d774-b89e-45ff-97ea-853ada9ed6cd)

**Comment by jrochkind** [comment]
Yep, it's going to happen on any page that is displaying a pre-chosen date limit. At least it can potentially happen on any such page; we know that it is a somewhat intermittent/unpredictable problem.

**Comment by jrochkind** [comment]
I'm currently not able to reproduce it, it no longer happens for me. Which makes it hard to tell if a change I've made fixes it or not, when I can no longer make it happen without the change. 

@eddierubeiz @HKativa are you currently seeing it on your own machines?

**Comment by eddierubeiz** [comment]
I CANNOT reproduce it! It works for me in Safari and Chrome. As far as my browser is concerned... either you fixed it or it fixed itself.

**Comment by sanfordd** [comment]
Cannot reproduce on Chromium or Firefox looks fine for me.

**Comment by jrochkind** [comment]
It's just hard to reproduce, becuase it's basically a "race condition" that occurs depending on unpredictable timing of browser/network events. That we can't see it now doesn't mean it won't come back, but it does make it hard to work on, since it's hard to be sure if a code change fixed it when you can't reproduce it.
