### ISSUE TITLE
Convert specified handful of child works to regular works

### ISSUE THREAD

**Issue by JAuerbach26** [sciencehistory/scihist_digicoll#2701]
please make the child works of https://digital.sciencehistory.org/works/8049g6270 regular works. Thank you!

**Comment by eddierubeiz** [comment]
Done in staging:


Parent:
	https://staging-digital.sciencehistory.org/admin/works/8049g6270

Children
	https://staging-digital.sciencehistory.org/admin/works/ulls51a
	https://staging-digital.sciencehistory.org/admin/works/ustpyq7
	https://staging-digital.sciencehistory.org/admin/works/jl95ae2
	https://staging-digital.sciencehistory.org/admin/works/snabdxf

Can you confirm this is what you want?
Thanks!

**Comment by eddierubeiz** [comment]
Recipe is:
```
['ulls51a', 'ustpyq7', 'jl95ae2', 'snabdxf'].each { |ch| pp Work.find_by_friendlier_id(ch).update!(parent: nil)  }
```

**Comment by JAuerbach26** [comment]
Looks great, thank you Eddie!

**Comment by eddierubeiz** [comment]
Yup, done in production!
