### ISSUE TITLE
Digital Collections SSL certificates: switch to LetsEncrypt

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2742]
The production digital collections SSL cert expires on 9/26/2024.
Let's switch it and the staging cert. to LetsEncrypt this time so they renew automatically.

**Comment by eddierubeiz** [comment]
Staging: https://dashboard.heroku.com/apps/scihist-digicoll-production/settings
Production: https://dashboard.heroku.com/apps/scihist-digicoll-staging/settings

**Comment by jrochkind** [comment]
Heroku docs: https://devcenter.heroku.com/articles/automated-certificate-management
