### ISSUE TITLE
Fix newspaper OCR for an issue of the Carlsbad Current Argus

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#2745]
Our OCR software ran out of memory attempting to run OCR on [this newspaper](https://digital.sciencehistory.org/admin/works/b1q5s7w#tab=nav-ocr).

See https://app.honeybadger.io/projects/58989/faults/82650187#notice-context for the HB error.

**Comment by jrochkind** [comment]
Thanks! I think our procecure is run ocr manually on a developer mac, and upload it manually?  This is prob documented in wiki somewhere?  We should link wiki with docs here -- or make wiki with docs!
