### ISSUE TITLE
Template refactor: move duplicate pagination to a partial.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#276]
The collection show pagination (https://github.com/sciencehistory/scihist_digicoll/pull/275 ) is identical to the featured topic pagination ( https://github.com/sciencehistory/scihist_digicoll/pull/269 ) .

Once these two PRs are merged, just move the duplicate template fragment out into a partial view template.

**Comment by jrochkind** [comment]
I believe it also applies to the _search result_ pagination too, right? So three places?

**Comment by eddierubeiz** [comment]
Also, per Jonathan's suggestion, the templates are very similar and we want them to stay that way.
Add a comment in the template encouraging developers to minimize repetition in the future.
