### ISSUE TITLE
Sort  not working on Works page in Admin

### ISSUE THREAD

**Issue by Gabz73** [sciencehistory/scihist_digicoll#2762]
The "Created" and "Last Modified" sorts on the Works page in the Admin dashboard )https://digital.sciencehistory.org/admin/works) are not working: when you click on the header, the sort doesn't change.

**Comment by eddierubeiz** [comment]
I very likely broke this - stay tuned.

**Comment by jrochkind** [comment]
I guess add a test that would fail on the broken code and pass on the fix, please, @eddierubeiz !

**Comment by eddierubeiz** [comment]
Yeah. I'm considering it high priority.
