### ISSUE TITLE
consider bulk creation of derivatives/dzi

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#291]
When we do our first import into new app production, we'll need to create derivatives and DZI files for everything. 

This takes a while. For DZI, initial estimate is ~131 hours -- but that's before allowing for further slowdown due to exhausting burst allowance on our EC2. (Not sure current estimate for non-dzi derivatives). 

Is this a problem? Having to wait that long might be a problem (inconvenient). Exhausting burst credits might be a problem (makes deployment environment behave atypically until burst credits build up again). 

Might we ever need to do this after initial import? Probably not typically -- we keep backups of our derivatives to avoid it -- but potentially in case of some kind of castrostophic failure, or if we discover existing derivatives had been created improperly. So any techniques to speed it up could be useful in the future. 

At present derivatives creation routines do not apply any concurrency, they just create one derivative at a time, one after the other. 

### Create one temporary EC2 for bulk derivative creation

It could potentially be a much higher capacity EC2 (without 'burst', if possible?). 

It would need the Rails app deployed to it, which should be possible to get capistrano to do, possibly just by giving it a capistrano `:app` role and including it in auto-discover. 

We would execute derivative creations on that server. 

This would have some temporary cost associated. 

This would not require any app code changes. 

Because of MRI "GIL", one deriv creation process would still only use one core. :(

### Let deriv creation work in separate 'batches' instead of one process for entire run

Still without making our deriv creation code use concurrency, we could instead figure out a way to have deriv creation commands create only a portion of derivatives. Either by only creating some types of derivatives, or splitting our entire assets into portions and having a command that only creates derivs for the 1/N xth batch. 

Multiple deriv creation 'batch' commands could then run on the same server to use multiple cores, or be split to multiple temporary servers. If on same existing server, still 'using all burst' issues. 

Some temporary cost (if extra servers), some minor app code changes, some confusion in orchestrating the batches. 

Would have more flexibility on scaling up, not limited by the maximum EC2 server size that exists, as many servers as we want. 

### Add thread-based concurrency to deriv-creation logic

We could add multi-threading to derivative creation routines. 

This should speed things up some, despite the MRI "GIL", because while threads are busy downloading/uploading bytes, other threads can do work. 

Could be run on existing server, or in new server.  If existing server, still 'burst all used up' worries. Still only actually uses one core, unless combined with separate processes for separate batches as above. 

### Have deriv-creation use the ActiveJob/resque pool

The deriv-creation process would enqueue jobs for each Asset, for bg ActiveJob/resque workers to handle. 

We can now scale simply by scaling jobs servers. Multiple cores on a server could be used, so long as sufficient worker processes are running. 

This is probably the way to scale horizontally with least "reinventing the wheel". 

The trick is that the bulk creation will fill up the jobs queue, meaning other app work won't happen until the queue is clear. **Unless** we get different workers on different servers handling different resque queues. 

*  Need to figure out how to do this, and get workers on the 'ordinary' jobs server(s) handling all queues except our special, say, "bulk_batch" queue.  And workers on special bulk-batch jobs servers handling only that special bulk_batch queue. 
* Need to make sure our batch jobs to enqueue all this work enqueues to the special `bulk_batch` queue. 

### other ideas?

?

**Comment by sanfordd** [comment]
@jrochkind Does one derive process use one core mean that we can't use other derivative processes on other cores?

Another idea besides spinning up a new box is just resizing the existing jobs box. It entails a minute or so of downtime while it switches sizes but makes it fairly easy to upsize or downsize without needing any new code deployment.

**Comment by jrochkind** [comment]
> Does one derive process use one core mean that we can't use other derivative processes on other cores?

Right now our 'batch derivative process' processes derivatives for all works, and since MRI has the GIL, will only use one core at a time. 

If we rewrote our app code to make it possible to run a derivative creation to "create derivatives for 25% of Assets", we could run four of them, and they could collectively use four cores. That's the second option about "Let deriv creation work in separate 'batches' instead of one process for entire run".  Does that explain it? If not let's take it to slack/voice. 

> Another idea besides spinning up a new box is just resizing the existing jobs box. 

True, but it would still mean that with a jobs queue full of 15000+ jobs for derivatives creation, no other app background jobs could happen until that jobs queue is worked through. That might be okay for a special one-time import where we basically figure the app will be unavailable until the import completes, but is not a flexible/general solution.

**Comment by sanfordd** [comment]
That makes sense for the derivatives.

As a quick comparison in terms of an extreme cost 
we could throw a c5.24xlarge machine (96 cores, 192 GB RAM) for ~ 4.00 an hour
For the same cost we can throw 44-45 basic m4 or m5 instances (no burst credits) for about 88 cores worth of setup and 350GB of RAM. Even ignoring code setup, since we have 40+ machines we can use them at 50% of their 2 cores without rewriting anything.

Horizontal might be the best way to go since we can get a lot of the benefits of a larger server without needing to change the code too much.

**Comment by jrochkind** [comment]
Did speed up DZI creation a bit in #384. 

Not planning on doing anything else just now, but we'll leave it open for future work.

**Comment by jrochkind** [comment]
Close this as no longer  exactly applicable; we could have problem sin this area, but we would solve it in different ways, and it's just not a priority. 

Also option 1 is accomplished; or would be accomplished somewhat differently on heroku.
