### ISSUE TITLE
Scaling Assessment

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#292]
Scale out the infrastructure for testing prior to launch.

Sizing constraints
- [x] Web Traffic
- [x] Background Jobs
- [x] Solr
- [x] Database backend

S3 backed data is already distributed, we don't have any current concerns about its scaling.

**Web traffic characteristics**
We do not have a small number of highly viewed pages. Our most viewed page (homepage) accounts for only slightly over 6% of our annual traffic. This is good insofar as it shows that our users are finding a wide range of content. It does mean that caching will have a fairly minor overall impact on site performance given the range of pages people may visit. 

Current assessments:
High of 8 concurrent users (based off Google Analytics, using following formula Concurrent Visitors=Peak Hourly visitors x Peak Hourly Average Time Spent on Site/ 3600)

We have bots and internal users, so I'm going to estimate that up to 14 concurrent "users" including staff and automated systems (3 staff, 3 bots) as a good high to shoot for. The staff number is based on known staff users, while the bot is based on a very rough guess from logs.

As per (https://www.phusionpassenger.com/library/config/standalone/optimization/#tuning-the-application-process-and-thread-count) some of this depends on if we have blocking I/O in our setup for the optimal number of processes. 

Lacking a good measure of our current IO blocking, I have used the simpler measure of running a basic load test of our front page with wrk, recommended by passenger for testing, with a 4 thread/50 connection setup `wrk -t4 -c50 -d200s` to see how it performs under load. The sweet spot seems to be between 8 and 10 passenger pool size. Scaling up past that seems to at most stay neutral or offer slightly worse performance under the load. This has a number of issues when adjusting to normal browsing patterns of course but seems to indicate a larger pool isn't helping unless we increase our CPU.

**Background job characteristics**
We can broadly divide our jobs into public facing jobs (on-demand derivative creation) and staff facing jobs (ingests: asset promotion, derivative creation).
We want all of them to be as fast as possible, but the first category are the more time sensitive. Staff users know creation takes some time and are easier to communicate any delays to.  
@jrochkind referencing ticket #291 one thing we might consider is putting the on-demand derivative creation tasks their own queue. Since our on-demand derivative creation is the most RAM intensive task when done to large works (Ramelli) we could help control sizing by making a pool of workers just for on-demand derivative creation. It also lets us avoid any slowdown of ingests and on-demand tasks competing with differing priorities.

Avoiding my intentional breaks, a quick "bad case" of both _Museum Wormianum_ and _Le diverse et artificiose machine del capitano Agostino Ramelli_ as our two current largest sets having pdfs generated showed the following use:
6.75 GB of RAM
approximately 30-40% CPU usage, spikes higher due to IO waiting.

Our Ingest jobs on the other hand are fairly stable. They show a rather flat use of RAM (basline is about .7 GB, max is about 1.4 GB) but spike up to use the whole CPU. I threw a moderate set of images (~20) and audio files (~8) with no real variation or IO issues. The number of jobs will determine how long the CPU is running but it doesn't seem like adjusting the number of files in works has a major impact on RAM.

I spoke with @yonyitz about the types of ingests done and got a rough description that ingests tend to be 1 off files, batch uploads (~10 at a time), or books with hundreds of images.

I did a 9 file speed test on processing
3 workers: 5m, 36s +-1s
5 workers: 4m, 8s +-1s
8 workers: 3m, 30s +-1s
16 workers: 3m, 28s +-1s

The DZI generation tended to be job that took the most time. As expected generally speaking we get some performance improvements up to the limit of files being processed. Additional workers pas that point add minimal value.

We can't add hundreds of workers, but if we see regular 10 file ingests a set of 10 workers is likely to offer the largest speed boost. 

For the on-demand derivatives in the last year or so we've seen a little over 1000 on-demand derived images total, mostly pdfs. Accounting for about 11.5% percent of our events. Since it's from GA tracking blockers or other options may be throwing some of those numbers out of balance. It nevertheless shows a notable minority of our users want these files.

A single worker on them would potentially cause delays since all users would need to wait for the first worker to finish. A 2 or 3 worker count would handle almost all of our prior use, we only had 2 spikes above ~10 a day. 

Offhand then I'm leaning towards recommending a 2 queue system, one for ingests with 10 workers, and an on-demand queue with 2 or 3 workers.

Resque-pool helps manage the memory use, so I don't see a major change in used RAM when the workers aren't busy. Since the main RAM hogs are the on-demand jobs, limiting them is the key step.

**Comment by jrochkind** [comment]
>  if we see regular 10 file ingests

We regularly see DOZENS of file simultaneous ingests -- multiple pages for a work with many pages. We can not have as many workers as we regularly see simultaneous ingests. The more workers we have, the faster they will go.

**Comment by jrochkind** [comment]
I am not sure how to operationalize separate queues/"an on-demand queue" with resque, there may be several ways. Not sure if you're thinking something in particular. I understand the goal -- i think? Is it keeping on-demand-derivs from interfering with ingests, or vice versa?  It is not clear how to me how to accomplish it with resque in either case, but we could look into it. 

Are you suggesting there could be 12-13 workers running on the host, with 2 or 3 of them just waiting around for on-demand-deriv work?  Would that mean the host would have to have the resources to handle all 13 at once in case that happened?

**Comment by sanfordd** [comment]
Correct. We can handle a _lot_ of workers handling ingests since they tend to be fairly RAM light and just are limited by waiting for CPU time. The on-demand jobs are much more RAM intensive and likely to cause a crash. When they're not being called for a job their RAM usage is fairly minimal, so having a few "wasted" workers isn't a problem.
I remembered this section (https://github.com/nevans/resque-pool#yaml-file-config) of the resque-pool documents from my earlier review of resque-pool.

**Comment by sanfordd** [comment]
Adding some values, I used a 55 item work as a speed test. 
10 workers:
7m, 32s
25 workers:
7m, 48s (a honeybagder error about S3 access may be behind this regression)
50 workers:
7m, 28s

Unless we want to scale the box up from it's current 2 core 8 GB RAM, we're probably hitting a limit in terms of CPU productivity for ingests somewhere around 10 workers.

**Comment by sanfordd** [comment]
On the web server side I've wrapped up some light testing.  All testing was done via wrk based on comments in the Passenger documents (https://www.phusionpassenger.com/library/config/standalone/optimization/) since we're using single threaded passenger the older t2 instances (with their higher clockspeed) outperforms the newer t3/3a instance types. I tested on the front page extensively, and did a smaller test on one of the multi-image works.
 
For equivalent instance sizes we see a rough 3-5% percent increase in average latency (measured from front page access and a 17-19% increase on the sample work page. Newer instances tend to be 10-15% cheaper. The t3a instances due to an even lower clock speed are definitely unsuitable for the single threaded passenger setup. 

Based on that I'm going to recommend we keep with the t2 instances for webservers. The smallest we looked at was a a little light during a deploy, sticking with a t2.medium is probably the smallest we can go with our expected traffic levels.

**Comment by sanfordd** [comment]
Adding another note here, keeping the on-demand queue distinct from the ingest queue also has the benefit of avoiding interruptions. While any one ingest job is fast, if I throw a book in just before someone starts a on-demand file it can get delayed.

**Comment by sanfordd** [comment]
Currently we don't have a good benchmarking tool for Solr with queries prepared but an analysis of production's Solr instance shows that we're using fairly minimal RAM and we've only had a single 5 minute period where CPU use spiked past 50%.
I ran a quick set of timed direct curl requests inside AWS from a test server to two Solr instances (t2 and t3a) and both seemed to offer intermittently better performance than the other. Real world results should be roughly similar.   

For postgres (and redis) we have similar behavior, a few spikes at higher CPU usage but it normally hovers under 5% usage. Current RAM usage is small, I think we could downside to a t3a instance as well here with no real impact on performance.

**Comment by jrochkind** [comment]
@sanfordd 

> Based on that I'm going to recommend we keep with the t2 instances for webservers. The smallest I tested (t2.small) at was a a little light during a deploy, sticking with a t2.medium is probably the smallest we can go with our expected traffic levels.

How many Passenger workers is this with? (It sounds like you tested different machines with that same number of workers?)

**Comment by sanfordd** [comment]
@jrochkind This was with 10 workers using t2.medium, t3.medium, t3a.medium, t3a.small, and t3.small.

**Comment by sanfordd** [comment]
I'm putting a final copy of the information here in a cleaned up and simple format for later reference.
**Web**
Using a t2.medium server, while we could have a larger passenger pool, for our app testing with wrk seems to indicate that pool sizes beyond 8-10 do not offer performance enhancement. If we do want that we should look at a server with more CPU.

t2 servers are faster in terms of max clock speed/single thread execution, which is what we use for the web side. Newer t3 instances lose some speed which is meaningful for website loading.

**Background Jobs**
We decided to use 10 workers in a general queue and 2 workers in an on-demand queue. The general workers is based off some small upload testing, and the on-demand workers are based on a worst case scenario of the two largest on-demand pdf jobs running at the same time. Allowing 3 to run could cause issues. With the two worst case on-demand jobs we have the space to run 10 workers at the same time for other jobs. A t2/t3.large fits our needs at the moment, small millisecond changes in background jobs are not likely to be an issue if we do switch to a t3.

**Solr**
Solr uses minimal RAM at our scale and we can safely downside to a smaller t3a (t3a.small) instance and see no performance loss based on direct curl requests used to simulate calls to it.

**Databases**
Like Solr our database use is very light and we should have no performance issues when dropping to a smaller t3a instance, a t3a.small.
