### ISSUE TITLE
routine to copy selected items from staging to a dev instance

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#298]
There should be a way to copy specific named things (say, ramelli) from staging to a dev instance. 

I'm thinking a capistrano task which ssh's to staging server, and does a postgres "COPY" to file of the particular tables->rows  of interests, then loads them in the local developer db. 

For derivatives, we could just recreate the derivs on dev (slow, but requires no coding for the tool), OR we could copy the derivative pg rows too, AND issue S3 copy directives to copy the derivatives from staging S3 to the proper location for dev s3. 

I'm leaning toward the latter, although it's more complicated to implement (cap script has to figure out the staging S3 locations, and have AWS permissions to read them all).

**Comment by eddierubeiz** [comment]
We could certainly use this. Besides fixing slow-loading large items, this would be helpful in the common case where *something* about a particular item is pathological, but you can't figure out what. If you can quickly pull the item and all its components down into dev, you're often well on your way to solving the problem.

**Comment by jrochkind** [comment]
For the moment, my in-progress code tries to copy it over with UUID pk and friendlier_id’s intact and equivalent — so if you have anything already in yoru db with those pk/friendlier_ids, you gotta move em out of the way first.

Does that seem like the right thing to do, @eddierubeiz ? I _think_ so.

**Comment by jrochkind** [comment]
Copying the files and copying and/or creating derivatives is the hard/expensive/time-consuming part. 

Another option would be.... pointing to the actual staging S3 buckets for files, even in dev. 

I'd still want it to be read-only access -- which our dev S3 key should already be limited to. 

So you'd end up wanting to switch back and forth -- you wouldn't want to be pointing only at staging buckets with read-only access, cause sometimes you need to actually do ingests in dev too. 

But it could be helpful. It could even make it feasible to sync the _entire_ staging db, actually, and point to the actual files on staging, to test something that could be tested with read-only access to files. 

A bit of a different approach. Thoughts @eddierubeiz ?

**Comment by sanfordd** [comment]
Read only access (specifically GET and LIST) are the only things you currently can do with a dev key on staging against S3.

**Comment by eddierubeiz** [comment]
Hm. I understand that if you need to debug problems relating to adding or removing files in s3, you can always switch back to using your own dev bucket. And I see that your current use case doesn't involve any ingests or deletes.
However, I think it might be worth the extra time (both your current development time *and* the time of the developer who requests a full copy of all an item's files to a dev bucket) to get dev and staging fully independent from each other. Of the two options, the one that allows us to maintain that separation may well save us more development hours in the long run.
