### ISSUE TITLE
separate ActiveJob worker queues, to keep large on-demand derivatives in their own queue

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#302]
@sanfordd says in #292 

> keeping the on-demand queue distinct from the ingest queue also has the benefit of avoiding interruptions. While any one ingest job is fast, if I throw a book in just before someone starts a on-demand file it can get delayed.

Would actually keep large ingests from interfering with on-demand derivatives, as well as many on-demand derivative requests from interfering with ingests. 

"Ingests" an "on-demand derivatives" are the main categories of our BG jobs here, but making a separate queue for on-demand-derivatives, it'd really be "on-demand-derivatives" and "everything else". 

Requires having the separate groups of workers processing the separate queues, as well as making sure jobs get assigned to correct queues when enqueued.

**Comment by sanfordd** [comment]
Adding here, from #292 that we don't want more than 2 on-demand workers, to avoid potential crashes from pdf generation.

**Comment by sanfordd** [comment]
Breaking out the workers into distinct queues is fairly simple (https://github.com/nevans/resque-pool#yaml-file-config)

We'll need to tell our existing tasks what queues to use though once we go from a single pool
"*": 10
to breaking the pools apart into groups like
staff: 10
public: 2

I'm not sure if our tasks or logic support it, but if we can distinguish pdf on-demand requests easily from others we could further divide pools. PDF generation is the only one that's highly RAM intensive on large works, ZIP creation is fairly light and doesn't need to be quite as limited. If they're harder to distinguish then just staff/public seems like a fine divide for now until we have more public facing worker tasks.

**Comment by jrochkind** [comment]
Ideally it would be nice to say some set of workers handle queue X, and other set of workers handle "all queues EXCEPT for X". 

Sadly, I don't believe that is possibe in resque/resque-pool. I thought I saw an unmerged PR to resque-pool that would have provided it, but now I can't find it. 

We can look back at how we handled this in chf_sufia. 

I am not certain if it's easy to separate out PDF from ZIP, I think they are currently both the same ActiveJob, they'd probably have to be split into separate ones to put em in separate queues. 

Rather than "staff" and "public", I'd probably just leave it "default" and "public-on-demand-derivs" or something. There are all sorts of things that can end up in bg jobs, including things that may not be strictly divided into staff or public; right now, I *think* everything is in the single default queue. The redis admin can show us what queues any actually existed jobs have been put in currently.

**Comment by sanfordd** [comment]
Keeping the PDF/ZIP on one ActiveJob and queue is fine then. We don't get enough traffic on that task to really be worried about running out of workers.

A default queue is fine by me, but I think our current one "*" actually means that the workers will get tasks from all queues (https://github.com/resque/resque#running-all-queues) rather than only a default. That means in theory someone could make a pile of pdf requests and the extras would roll into those workers.

Right now our admin page shows
- default
- scihist_digicoll_production_mailers
- scihist_digicoll_production_scihist_digicoll_production_mailers

If we want to be sure that public-on-demand-derivs tasks can't use other workers, we might want to specify workers on default (and/or the others) and not use the * for worker assignment as I understand the documentation. 

Alternately we could put most workers _on_ default and a few on the wildcard
default:10
"*":2

Allowing pdf/zip to be caught by the * workers, as well as any other odd queues we might get.

**Comment by jrochkind** [comment]
@sanfordd whatever we call them, we're going to start with a queue for public on demand derivs, and a queue for 'everything else'. 

And, I think what we're planning, is we're going to have separate workers working each of those two queue. 

Can you tell me how many workers you think I should have working on each queue, for the resources available?  Is this something you've figured out already? Is it `2` and `10` as per examples in your above comment? 

Thanks!

**Comment by sanfordd** [comment]
@jrochkind The 2 and 10 workers (for on-demand and everything else) is the best we can. 2 workers for on-demand is comes from a test where 3 workers all picking the most intensive on-demand task were able to crash the server.

10 workers for everything else matches our current setup and was the best performance we got from the testing done in #292 

However setting the everything queue to 10 workers is, as I understand the documentation, not going to solve our problem. Extra on-demand tasks above the 2 workers would be picked up by the 10 workers which access all pools.

We would want the 10 workers to limit themselves to the `default`, `scihist_digicoll_production_mailers`, `scihist_digicoll_production_scihist_digicoll_production_mailers`, and `failed` queues so we do not have them take on on-demand tasks.

**Comment by jrochkind** [comment]
I think we're confusing each other. I am not talking about an "everything queue" that will pick up extra on-demand tasks. 

I think what we were planning is one set of workers that work only on-demand-derivatives, and another set of workers that work only "everything else" -- note the "else", that work tasks that are NOT on-demand-derivatives. 

Implementation details of how we do that are another story, first just getting the desired counts. But where do you get the existence of a `scihist_digicoll_production_scihist_digicoll_production_mailers` queue from? I hadn't noticed that one. 

Let's work it out on a voice call.

**Comment by jrochkind** [comment]
Ok, notes from me and @sanfordd talking:

* We want *2* workers working on on demand derivatives and *10* working on "everything else". @sanfordd has done some investigation revealing the server can handle this. (It is important the 'everything else' workers will *never* work on an on-demand-derivative, or it would be too much)
* While we could have the *2* workers that only work on on-demand derivatives *also* working on ingest/other if there is no on-demand-deriv work.... dan's previous investigations suggest there will be no advantage to this, more than 10 workers working on ingest are already maxed out CPU and competing with each other and don't help

Also, as far as on-demand derivs, it is *PDFs* specifically that take an inordinate amount of RAM, and why we need to make sure no more than 2 workers are working on them at once. We can in the future investigate if there's a more RAM-efficient way to produce these PDFs. 

Also, if the workers DO exceed RAM usage, the linux "OOM killer" (out-of-memory) will kill them -- this doens't show up clearly in our app logs and errors, and can be a bit confusing to diagnose/understand when it happens. We may want to investigate if we can have NetData alert us to any OOMs from system logs.

**Comment by jrochkind** [comment]
Resque queue list specification is unfortunately somewhat limited. I have inquired about possibly enhancing resque at https://github.com/resque/resque/issues/1700

(Sidekiq's options are a bit different: https://github.com/mperham/sidekiq/wiki/Advanced-Options)

In the meantime, we'll make do with what we got. One danger is some third party thing (samvera etc) will start using a queue name we're not expecting, which no workers are set to work. Kind of like the ActionMailer queue gotcha. But I think that's just part of the deal here; in that case, if we looked at resque admin, it would be fairly clear that there was a queue whose work wasn't being worked.

**Comment by jrochkind** [comment]
@sanfordd @eddierubeiz 

Okay, those mailer-related queues are a MYSTERY. The Resque Admin overview lists mailer related queues. On production, `scihist_digicoll_production_mailers`. On staging, that one as well as additionally `scihist_digicoll_production_scihist_digicoll_production_mailers`. 

I can't figure out where these queues are coming from!

* We have only two mailers I can find/think of: 1) The `Devise::Mailer` that comes with Devise and is used for password reset emails. 2) The `FixityFailureMailer` we use for sending fixity check failure emails. 
* NEITHER of them is being set to send emails in the background -- so neither of them should be using mailer-specific ActiveJob queue. 
* Even if they WERE, they should be using a queue called simply `mailers`, not the longer ones above. This is the default queue for mailers in Rails, and to the best of my ability to check, this is still the queue these mailers are configured to use IF sending emails via ActiveJob queue -- which they aren't doing anyway!

So it's a mystery where these queues that Resque admin dashboard is showing us come from. They are obviously being constructed by "application_name" + "Rails environment" + "mailers" -- or in the staging version, accidentally duplicating that. But I have no idea what would be doing that. 

Resque seems to remember a queue used once... forever. So its possible some previous version of the software, or even *other* software *using this same redis instance* (is this a copy of a redis instance used with chf_sufia with all data intact?) used these queue names. 

For now, I think I may assume these are *not* used queue names. And not configure the workers to work those queue names. We'll have to keep an eye on things and make sure there isn't work piling up in those queues that isn't being worked by workers. I can't think of anything but that approach.

**Comment by sanfordd** [comment]
I think that's a safe plan. 
All of our redis instances have only been used on scihist_digicoll, but they have remained constant in staging so it could be a lingering queue from some prior point in development. I can try restarting redis on staging to see if that clears things up.

**Comment by jrochkind** [comment]
Aha. It looks like maybe it's putting app name+enviornment in front of ALL queues that aren't `default`! Perhaps some other rails feature. 

Because I tried to configure for `on_demand_derivatives`, but actually got `scihist_digicoll_production_on_demand_derivatives`. So that explains `_mailers` too (if not the duplicated one). 

Meanwhile, however, my attempt to change  what queues workers are working on by editing `./config/resque_pool.yml` did NOT work. It still has 10 workers working on `*`, even though I changed the resque_pool.yml -- aha, forgot to commit my change. 

Will keep testing, and veirfy what happens when you have queues nobody is working on. :)

**Comment by jrochkind** [comment]
Aha. 

https://guides.rubyonrails.org/active_job_basics.html#queues

https://github.com/sciencehistory/scihist_digicoll/blob/9a734a1a45bcd0a488f2d5813838feb0722864bc/config/environments/production.rb#L65

Not sure why the queue_name_prefix isn't applying to `default`. That inconsistency is kinda confusing, and may encourage me to set the queue_name_prefix to empty string instead.

**Comment by jrochkind** [comment]
Issue where queue_name_prefix does not apply to default was reported to Rails and reported fixed in https://github.com/rails/rails/pull/34376

Looks like that fix made it into Rails 6.0.0, but not 5.2.x that we are using. So that explains that one. 

https://github.com/rails/rails/pull/34376/commits/b517347be1e229554093b061bd3fd7dbf9017f6a

I will go ahead and remove the default_queue_prefix for now.
