### ISSUE TITLE
Create production environment

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#305]
- [x] Create production S3 buckets
- [x] Assign replication
- [x] Remove staging replication tests
- [x] Build AWS servers
- [x] Sync Data

**Comment by sanfordd** [comment]
Ansible has a known occassional issue with the S3 bucket creation (https://github.com/ansible/ansible/issues/42532) this isn't a normal problem since once made they don't need to be remade but it is something to recall if we need to recreate the environment. Came up on my first build attempt but then they built fine on the second attempt.

**Comment by sanfordd** [comment]
We've done everything except move the data over. @eddierubeiz you can close this out when you've gotten the data pulled over.

**Comment by eddierubeiz** [comment]
Will do!
