### ISSUE TITLE
Claim production derivatives S3 host in google

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#312]
We have our sitemaps on a different host than the main app -- currently on derivatives S3 bucket.

We also include images in our sitemap that are located in derivatives bucket, and are currently linking
directly to them.

So, to get Google to use the sitemap and index those images, we need to 'claim' the production
derivatives host in Google web admin tools. See:

https://support.google.com/webmasters/answer/34592?visit_id=1-636531068483226339-3826640717&rd=1

We can do this once we have production buckets. Will need to claim the host in the URLs we actually link to, the right form of an S3 link, not sure. 

Related to #309 #311

**Comment by eddierubeiz** [comment]
Requested read-only access to the Google search console from Clare Hirai as a first step.

**Comment by eddierubeiz** [comment]
Quick update:
Claire is going to add `https://scihist-digicoll-production-derivatives.s3.amazonaws.com/` to the Google Search console and we are going to use the URL prefix method of verification, which entails us uploading a file provided by Google to a URL into that bucket (see https://support.google.com/webmasters/answer/9008080  under "HTML file upload"). Details to follow.

**Comment by eddierubeiz** [comment]
OK -- we're gaining on this. Clare got back to me, and now:
* We have verified the above URL prefix with the Google Search Console.
* https://scihist-digicoll-production-derivatives.s3.amazonaws.com/__sitemaps/sitemap.xml.gz

**Comment by eddierubeiz** [comment]
However, the actual URLs in the sitemap are still old style URLS starting in https://kithe.sciencehistory.org . I suspect this is just the `local_env.yml` needs to be switched via Ansible; will check with @sanfordd when he's back from his lunch break.

**Comment by jrochkind** [comment]
I don't see any `kithe` URLs in local_env.yml on kithe production jobs server. 

Can you explain more what you mean by "the actual URLs in teh sitemap are still old style URLs starting in..."? What actual URLs in what sitemap, how are you seeing them where? 

Oh you know what, we may just need to GENERATE a sitemap on new server, with new config. Log into jobs server, and in app directory run `bundle exec rake sitemap:create`. Should take maybe 10 minutes.

**Comment by eddierubeiz** [comment]
Running the rake task now...

**Comment by eddierubeiz** [comment]
Generated. It is now correct.

**Comment by eddierubeiz** [comment]
OK -- looks like Google has everything it needs to index the derivatives on s3. I'll check the search console again tomorrow to make sure I actually see it's been indexed; after that I'll consider this task done.

**Comment by eddierubeiz** [comment]
I just checked at https://search.google.com/search-console/index?resource_id=https://scihist-digicoll-production-derivatives.s3.amazonaws.com/ (under `Index` > `Coverage` ). There is still no evidence of us having been indexed; there's still a note reading "Processing data; please check again in a day or so."
Sent a note to Clare requesting advice.

**Comment by jrochkind** [comment]
It's possible we just need to keep waiting, at some point you've done all you can and Google will do what Google will do.

**Comment by eddierubeiz** [comment]
Yeah. I think I've reached that point. I'm setting this bug to "Review", as I won't be doing any more work on this.
