### ISSUE TITLE
S3 errors on kithe staging when trying to make on-demand derivatives

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#326]
Aws::S3::Errors::AccessDenied

## Backtrace

    line 72 of [PROJECT_ROOT]/app/models/on_demand_derivative.rb: put_file
    line 107 of [PROJECT_ROOT]/app/services/on_demand_derivative_creator.rb: attach_derivative!
    line 4 of [PROJECT_ROOT]/app/jobs/on_demand_derivative_creator_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/58989/faults/54234460)

----

see also: Aws::S3::Errors::Forbidden at https://app.honeybadger.io/projects/58989/faults/54234432

[PROJECT_ROOT]/app/models/on_demand_derivative.rb:59 :in `file_exists?`

**Comment by jrochkind** [comment]
@sanfordd saw notes in Slack that maybe you've fixed this already?  If so, just go ahead and close this issue, thanks!

**Comment by sanfordd** [comment]
@jrochkind Will do. I resolved it in Honeybadger but apparently it doesn't automatically close it here.

**Comment by jrochkind** [comment]
Cool, glad to hear there are re-usable IAM roles involved, so once fixed, the fix should stay put!
