### ISSUE TITLE
Alphabetically sort values on display (for subject and/or other fields)

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#330]
Could we consider adding drag-and-drop reordering to the subject fields, or possibly all the multiple-value fields?

By way of justification, the following scenario: a curator enters four subjects to describe a work. The order is meaningful: the most important subject needs to be first, and so on. Once these are entered, if the curator changes his/her mind re: the relative importance of the subjects, s/he needs to cut and paste, rather than simply drag-and-drop.

**Comment by jrochkind** [comment]
This feature was not present in chf_sufia. You can re-order, with difficulty, by copying and pasting text to different fields. So at a minimum it's a new feature and not necessary for release. 

Past feedback from stakeholders was that they were uninterested in the order of subjects mattering at all, and actually suggested even having subjects _alphabetized_ on display. Is there reason to think this has changed?

**Comment by eddierubeiz** [comment]
Yeah, looks like there was a misunderstanding! We do *not* care about the order subjects are displayed in, so there's no need for re-ordering in the metadata entry form. Correct me if I'm wrong! :)

**Comment by HKativa** [comment]
Just confirming @jrochkind is correct - during the initial development phase of the app, Digital Collections Committee discussed ordering of these values on front-end and decided on alphabetical ordering of subject headings so as not to suggest a meaningful ordering when there wasn't one. Discussion with curators (myself included) confirmed that order is not meaningful, based on how curators enter subject headings.

**Comment by jrochkind** [comment]
Ok, please either close this ticket and re-open one for "alphabetically sort values on display" (for subject and/or other fields), or change/name description of this one. Thanks!

**Comment by HKativa** [comment]
Edited existing ticket to reflect updated understanding of issue, which is that values of fields with multiple entries should be sorted to display alphabetically on front end, which currently is not the case in the new app.

**Comment by jrochkind** [comment]
@HKativa  Do we want to sort _all_ multi-valued fields on display?

Here's the list of multi-valued fields handled in our 'standard' way:

* creators
* places (manufacture, publishing, etc)
* format (image/text/sound etc)
* genre
* medium
* extent 
* language
* subject
* rights holder
* Digitization Funder
* Department
* Exhibition
* Project
* Series arrangement

It's no problem to have them all sorted. "extent",  "medium", and "series arrangement" might be kind of odd ones, although I don't know that it will hurt -- actually, sorting "extent" and "series arrangement" might hurt?

It is no problem to have them all sorted, or to sort only some but not all, just want to check in before I do it. 

I am not certain exactly what chf_sufia sorts and what it doesn't; I can try to figure it out; I'm also not sure if chf_sufia always sorts the _right_ things, so it might be easier just to decide what the right things are.

**Comment by HKativa** [comment]
@jrochkind here is the list of multi-value fields that should be sorted alphabetically for public display:

- format (image/text/sound etc)
- genre
- medium
- language
- subject
- Exhibition
- Project

Here is the list of fields that **should not** be sorted alphabetically for public display:
- extent 
- rights-holder 
- digitization funder
- department (by definition, a work cannot be part of multiple departments)
- series arrangement (order in which values are entered is meaningful)

"Creator" and "Place" raise an interesting question - if these were alphabetized, are we alphabetizing according to the value of the field or the qualifier that precedes the value? For instance, taking work tb09j6649 as an example, which comes first, "Artist: Basan, Pierre Francois" or "After: Teniers II, David?" Not sure it matters, but I'm curious about the mechanics.
