### ISSUE TITLE
Rights field missing on the staff view of complete work metadata

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#331]
For instance:
https://kithe.sciencehistory.org/admin/works/gsu1aw
should list the rights field (value is "in copyright").

**Comment by jrochkind** [comment]
URL typo copy/paste error? I get a 404 on https://kithe.sciencehistory.org/admin/works/gsu1aw

**Comment by jrochkind** [comment]
OK, this is reproducible with any work though. Eg https://kithe.sciencehistory.org/admin/works/9g54xj51s

I'll fix it shortly.

**Comment by eddierubeiz** [comment]
Cool, sorry re: typo!

**Comment by jrochkind** [comment]
Huh, weird, I see the code that's supposed to be doing it in the view... why isn't it working?
