### ISSUE TITLE
Re-architect to not try to fetch all derivative objects for display

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#333]
Our derivatives are each represented by a separate row in a derivatives table. 

Currently, when displaying a work, we generally try to fetch the derivative records for each asset to be displayed (and we display all public assets).  This lets us do things like:

1. Generate a URL directly to S3 (we need the derivative metadata to know it's exact S3 path)

2. Look at the file size of a derivative to include in download menu. 

3. Check if a given derivative exists before trying to link to it or use it in a `src`, and doing something else if it does not. 

However, this is causing performance problems for many-membered works. For instance, ramelli (694 member items) can take 10 seconds to display on kithe staging.  And 2.7s to fetch the JSON response with metadata about each member, that feeds the viewer (`viewer_images_info` action). 

* (An order of manitude smaller on my MacBook dev box, haven't figured out if my macbook really is that much faster CPU than EC2, or if something else weird is going on). 

It is difficult to figure out exactly what is causing this to be so slow. It is *not* the actual SQL fetch, that is pretty quick. But it does not necessarily seem to be any one thing. Perhaps a  combination of Rails instantiating the objects for all those derivatives; shrine turning the JSON file attachment info into Shrine objects; and generating direct-to-S3 URLS for all those derivatives (the AWS S3 ruby sdk for generating S3 URLs seems to have quite bad performance, when you are trying to do it for thousands). 
  * But really, we just aren't sure. Keep in mind that for 700 members (ramelli), fetching _all_ derivatives for each one means fetching 7000+ objects (10+ derivatives for each one). And we generate direct-to-S3 URLs for all thumbnails, with a 1x and 2x in a srcset, so that's at least 1400 S3 URLs. 

It is _possible_ we could figure out the performance bottleneck in current approach, and fix it. But I haven't been able to do so, so far. 

But my preliminary investigations suggest that _not_ fetching all derivatives will fix the problem, and is do-able. This will mean:

* Instead of direct to S3 URLs for thumb `src`, the thumb `img src` will be to an action in our app, that will _redirect_ to an S3 URL. This does mean a lot more HTTP requests will be made to our app (we may want to benchmark our app again under load after complete, note @sanfordd), but there won't be those really slow HTTP responses. AND, this seems to be the default way that ActiveStorage works too, using URLs that point to app resulting in redirects. 

* We won't be able to include download file size in our download menu UI, as we won't know it. 

* We won't be able to write logic for display of thumbs or other derivatives based on whether the derivative actually exists -- we won't know it. We'll just include a URL that will result in a 404 if it does not exist. Including for download menu. 

This is some extensive refactor, but I think it makes sense as the best way to deal with 10s+ page response times for ramelli, which are unacceptable. While we could also change our UI to _not_ display all images for a 700 image thing on one page -- the viewer_images_info at ~3s is also too long. And refactoring all of that seems more work with more unanticipated consequences than refactoring to not fetch derivatives. 

After refactor, our view code will seldom/never use `derivative_for` or the `with_representative_derivatives` scope -- it will avoid dealing with derivative model objects. 

I will try to do this small piece by small piece, perhaps with a rough draft that is messy code but can be tested on our deploy servers. 

Also note that we are not using shrine's "derivatives" implementation, but invented our own in kithe, that has each derivative in it's own db row. The original shrine "versions" implementation in shrine 2.0 was not satisfactory for our backgrounding and concurrency-safety needs. However shrine 3.0 has a new derivatives implementation that may work for us, and still puts all info in the original asset db row, so might wind up with better performance. We may want to investigate in the future, although it may require some extensive refactoring. 

Related to #296

**Comment by sanfordd** [comment]
Noted on setting up some new load tests once we're done.

**Comment by jrochkind** [comment]
For comparison, at one point I swear we had ramelli at ~4s on chf_sufia, but it's currently taking 10-20s, there's been a perf regression of some kind. if we weren't migrating to a new app, I'd be diagnosing that on chf_sufia. 

4s is still far too long, but at least a benchmark for not making it worse.

**Comment by jrochkind** [comment]
If we end up switching from putting S3 URLs directly in the HTML, to instead putting a URL back to our app in HTML -- that will redirect to S3....

a load test of the web app isn't actually accurate if it's not requesting some of the `<img src>`s contained, since a real browser would be doing that. 

(We do use lazy loading, so it doesn't request ALL of the thumbs, only those that are actually in the browser viewport, as the user scrolls. But it's still gonna be some requests). 

They should be very quick request/responses to generate the redirects, but still something to keep in mind.
