### ISSUE TITLE
Deleting works does not remove DZI tiles

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#341]
When deleting a work as an admin, the DZI tile derivatives are not removed. The original file and all other derivatives seem to clear away just fine.

**Comment by jrochkind** [comment]
Haven't managed to reproduce in dev. 

Might be an issue with the slightly different storage layout we use in dev vs prod. Will have to keep investigating.

**Comment by jrochkind** [comment]
Did reproduce with a production-like storage setting in my dev copy. Hmm.
