### ISSUE TITLE
File extension missing from certain assets on original download.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#349]
- Visit either of these two assets:
    - https://staging.kithe.sciencehistory.org/admin/asset_files/d791sg519
    - https://staging.kithe.sciencehistory.org/admin/asset_files/9593tv46x
- Click "Download Original"
Expected behavior: file is saved with a ".tif" or ".tiff" extension
Actual behavior: file name is the (very long) title of the asset.

On my laptop this means the downloaded file is not recognized as an image.

**Comment by eddierubeiz** [comment]
Not sure if this is generalized; found out about it in the middle of doing something unrelated; further research needed.

**Comment by jrochkind** [comment]
Ah, the download link on the ADMIN page hasn't been touched in a while, so that probably explains it. I'll take a look.

**Comment by jrochkind** [comment]
Ah, the download link on the ADMIN page. Hasn't been touched in a while, was one of the first things written when the app hardly exists, not surprised it's buggy, although I'm surprised and curious about the _nature_ of the bug, I'm going to take a look. 

Good job finding.

**Comment by jrochkind** [comment]
Ah, right, it's doing just:

    @asset.file.url(response_content_disposition: ContentDisposition.format(disposition: :attachment, filename: @asset.title))

Yep, that is setting the content-disposition filename to the title!

We could go through the DownloadsController like ordinary. 

Or should the admin download do something special that gives you the _direct_ download from S3 without even going through downloads controller? Should it even give you the filename as actually stored in S3, which is going to be something weird like `09983434.tiff`? Probably not.

**Comment by jrochkind** [comment]
For now, use same logic as on public UI for download names from staff UI.
