### ISSUE TITLE
[scihist_digicoll-EXPERIMENTAL/production] ActionView::Template::Error: undefined method `solr_document_url' for #<#<Class:0x000055cb9caf89b8>:0x000055cb98cee4d8>

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#350]
## Backtrace

    line 24 of [PROJECT_ROOT]/app/controllers/application_controller.rb: block in batch_kithe_indexable
    line 23 of [PROJECT_ROOT]/app/controllers/application_controller.rb: batch_kithe_indexable

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/58989/faults/54727072)

**Comment by jrochkind** [comment]
I don't understand where this is coming from or the backtrace, but we should look into it.

**Comment by eddierubeiz** [comment]
The corresponding error on Staging
https://app.honeybadger.io/projects/58989/faults/51385653
has some interesting history about it at the very bottom of the page.

**Comment by jrochkind** [comment]
@eddierubeiz I'm not following what you mean, what interesting history?

**Comment by jrochkind** [comment]
Ah, I just noticed the URL being accessed is `"format" => "rss"` -- this is related to #190. Blacklight has some built-in support for atom/rss/xml representation delivery, that is not working in our app which does things differently.

**Comment by jrochkind** [comment]
I think this is closed with #190?
