### ISSUE TITLE
disk space usage on kithe-database1-staging

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#356]
netdata on kithe-database1-stagingAPP 8:25 PM (Sep 15)
kithe-database1-staging needs attention, disk_space._ (/), disk space usage = 90%
disk space usage = 90%
current disk space usage
disk_space._
/
by kithe-database1-staging | Yesterday at 8:24 PM

**Comment by sanfordd** [comment]
It was an issue with the monitoring logging for our sizing tests being a little too detailed and filling up the server. I reverted it back to standard logging and removed the extra files. Usage is back in line with expected amounts.
