### ISSUE TITLE
Bug: auto-complete only works on first entry in field

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#359]
Bug related to issue #323: on the edit work form, auto-complete only works for the first entry in the field. I encountered this bug in both the creator and subject fields while editing metadata for work thru9n2. Similarly, if you edit metadata on an existing work (I used work krwaibj to test this), auto-complete does not work when selecting "add another creator" or "add another subject."

**Comment by jrochkind** [comment]
The Javascript code looks for relevant text input boxes on the page to attach autocomplete functionality to it, so when a new element is added to the page in response to clicking "Add another", the functionality doesn't get attached. 

The way the JS code is structured (and the way the jquery-autocomplete plugin we're using works), it's unclear immediately how to fix this, but I'm going to play around with the code a bit.
