### ISSUE TITLE
Why is it still trying to run vips dzi on an mp3?

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#366]
[scihist_digicoll-EXPERIMENTAL/production] TTY::Command::ExitError: Running `vips dzsave /tmp/shrine20190916-25430-1ux66jd.mp3 /tmp/dzi_2j62s610h_20190916-25430-1rm6t6b/024c3019-c7e7-4af9-9932-c872b57b367e/md5_dace6e2e36a3ed998a9930bfb3878652 --suffix .jpg\[Q\=85\]` failed with  exit status: 1  stdout: Nothing written  stderr: VipsForeignLoad: "/tmp/shrine20190916-25430-1ux66jd.mp3" is not a known file format

## Backtrace

    line 107 of [PROJECT_ROOT]/app/models/dzi_files.rb: block (2 levels) in create_and_yield
    line 103 of [PROJECT_ROOT]/app/models/dzi_files.rb: block in create_and_yield
    line 102 of [PROJECT_ROOT]/app/models/dzi_files.rb: create_and_yield

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/58989/faults/54940613)

**Comment by eddierubeiz** [comment]
This error occurred in a call to `rake scihist:lazy_create_dzi` and halted the entire dzi creation rake task.

The fact that the error isn't caught but causes the rake task to halt might be a feature and not a bug, but it's definitely worth noting.

**Comment by jrochkind** [comment]
Closed by #375
