### ISSUE TITLE
DZI tile creation rake task is not checking content type correctly.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#373]
Tile creation is attempting to create tiles from mp3s.
Details at https://app.honeybadger.io/projects/58989/faults/54940613

Errors in calls to vips during tile creation are not caught; instead, the entire `rake scihist:lazy_create_dzi` task fails. This might be a feature and not a bug, but it's definitely worth noting.

**Comment by eddierubeiz** [comment]
Duplicate of #366

**Comment by jrochkind** [comment]
Closed by #375
