### ISSUE TITLE
Item count in Solr searches is off in certain cases.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#374]
If you run a solr search on an empty database, the item count is 1 even though there are (predictably) no search results. It may also be worth checking other solr searches against either db searches or Sufia solr searches.

**Comment by jrochkind** [comment]
I wonder if this is just a solr index being out of date, that could be fixed by deleting and reindexing solr.

**Comment by eddierubeiz** [comment]
Updating this with a couple more findings:
1) After a fresh import, if you log out of https://digital.sciencehistory.org and compare SOLR counts for https://digital.sciencehistory.org/catalog and https://kithe.sciencehistory.org/catalog, the count for kithe is still 1 more than Sufia.

**Comment by eddierubeiz** [comment]
If we do decide to do any work on this, see Jonathan's suggestion above: drop SOLR index completely and reindex. If the problem goes away, close this ticket.

**Comment by eddierubeiz** [comment]
The search counts in several cases are off by exactly one, and I agree this is a problem with solr on the new thing.

If you log out of both sites and compare 
https://kithe.sciencehistory.org/catalog and https://digital.sciencehistory.org/catalog,
and compare facets such as `rights` and `department` (where a) an item has to belong to a bin and b) it can't belong to more than one bin, and c) there is a finite number of bins), you'll find there is *one* item in Kithe solr with no rights or department.

I ran 
```
root@scihist_digicoll-jobs1-staging:/opt/import/scihist_digicoll# bin/rake scihist:solr:delete_orphans
Deleted 3 Solr objects
```
and this did not help.
I am tempted to try `scihist:solr:delete_all` and `scihist:solr:reindex`, but I'm resisting that temptation.

**Comment by sanfordd** [comment]
I honestly think a full removal and reindex is a good thing to attempt in this case. Even given that we are talking about production the speed for it is now fast enough it's reasonable to do.

**Comment by eddierubeiz** [comment]
More data:
```
Work.where("published = true").group("json_attributes ->> 'department'").distinct.count
=> {"Archives"=>5278, "Center for Oral History"=>225, "Library"=>1211, "Museum"=>476}
```
which is correct as indexed by Sufia, but not as indexed by New Thing.

**Comment by eddierubeiz** [comment]
This fixed it:

````
# PRODUCTION_OKAY=true ./bin/rake scihist:solr:delete_all
# bin/rake scihist:solr:reindex
````

Thanks for the tip, @jrochkind !
