### ISSUE TITLE
Env[app_url_base] wrong on staging

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#388]
#{ScihistDigicoll::Env.lookup!(:app_url_base)}

It's currently returning `https://kithe.sciencehistory.org`

**Comment by jrochkind** [comment]
That should just come from `config/local_env.yml`

ssh'ing to `kithe-jobs1-staging`, look at `config/local_env.yml`, indeed it's got:

    app_url_base: https://kithe.sciencehistory.org

So local_env.yml needs corrected value for `app_url_base` on staging servers. Assigning to @sanfordd

**Comment by sanfordd** [comment]
Fixed.
