### ISSUE TITLE
Archive Fedora RDF for posterity

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#393]
I want to propose running the Fedora export tool `java -jar fcrepo-import-export/target/fcrepo-import-export-0.3.0-SNAPSHOT.jar --mode export` to extract just the RDF, not the binaries, and archive the resulting file for posterity.

The process is described in:
https://wiki.duraspace.org/display/FEDORA4x/Import+and+Export+Tools .

@sanfordd  -- let me know if we're already doing this on a routine basis, or if this is overkill based on our current pre-export Fedora backup plans.

**Comment by sanfordd** [comment]
We are not doing this right now. Currently we're using a dump of the postgres database and a copy of the data on the disk to back fedora up. How long of posterity are we thinking of holding this data for?

**Comment by eddierubeiz** [comment]
Couple two three years?

**Comment by eddierubeiz** [comment]
As a tar.gz of course, on some drive somewhere.

**Comment by sanfordd** [comment]
It's not the worst idea. We'll want to test both the export and import onto a new machine to make sure this is a valid method of storing it. We do have, in theory, the on-site (and offsite) tape backups using our current method for up to 5 years.

**Comment by eddierubeiz** [comment]
Hm.... let's talk about this in person. I would probably argue that we don't need to try importing it into a new machine for it to be helpful as a backup; just having the XML on hand to use just in case is probably fine.

**Comment by eddierubeiz** [comment]
Per our discussion on the tech Slack channel this week, I will spend some time writing up some documentation (a README file) once the export file is in its final location.

Its purpose would be to make sure the RDF metadata is useful to someone unfamiliar with Fedora, allowing the extraction of particular RDF properties for a given item or set of items.

After that, we can close this ticket.

**Comment by eddierubeiz** [comment]
I've written a pretty complete description of the Fedora data and archived it along with the files. I may make more edits later on (to make it more readable) but I have captured the most important information, along with some useful recipes for accessing the data.

The file is at:

https://chf-hydra-backup.s3-us-west-2.amazonaws.com/sufia_legacy_data/README.txt
