### ISSUE TITLE
Email from kithe jobs server?

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#394]
Hey Dan! We had discussed this briefly last week, but would it be possible to rig up the Kithe jobs server to send mail?

Currently, on `scihist_digicoll-jobs1-staging`, if you run:
```
$ cd /opt/scihist_digicoll/current/ && bin/rails runner "ActionMailer::Base.mail(from: 'no-reply@sciencehistory.org', to: 'digital-tech@sciencehistory.org', subject: 'Test message', content_type: 'text/html', body: 'Test message').deliver_now"
```
you get the error `sh: 1: /usr/sbin/sendmail: not found`

Fixity failures are being reported via Honeybadger, but it would be nice to have this in addition (see https://github.com/sciencehistory/scihist_digicoll/pull/387/files ).

Thanks for looking into it!

**Comment by jrochkind** [comment]
@sanfordd you said in slack you had done something about this, but I'm confused cause I thought our brainstormed solution involved a single SMTP server and would Rails app config switched to use it. Please outline on this ticket what your plan is and where it's at, thanks!

**Comment by sanfordd** [comment]
Documenting this here,

What we'll be doing is opening the email server to the jobs server(s) so we can pass along SMTP requests as per @jrochkind's recommendation in Slack.

This requires that our email server be open in a very limited manner, we don't want to start being a source of spam. We'll be limiting access with both the firewall rules and postfix itself will limit access to allowed servers.

**Comment by sanfordd** [comment]
We've got what should be an open setup now. 
The local_env file has a variable `email_sever` which points to the right location. We're using the AWS public DNS, which EC2 instances will properly resolve to the private IP address of the server in question. 
Since it uses the elastic IP we can easily move to new servers without any need to push out local_env changes with each new email server build.

**Comment by jrochkind** [comment]
`email_server` is SMTP server data?  Can you give an example of the value, is it just a host, host and port, etc? 

The next step will be making the app _use_ that config, if it is set.

**Comment by sanfordd** [comment]
It's currently just a host,
`ec2-[Public-IP-Address-here].compute-1.amazonaws.com`
Where [Public-IP-Address-here] is the public IP with dashes instead of dots, i.e. 1-2-3-4
Pinging or using that causes EC2 instances to _not_ use the public address, but resolve the internal IP address (172.XX.YY.ZZ)
No port, though that's easy to add if needed.

**Comment by jrochkind** [comment]
We are just assuming the standard SMTP port? And there is no username/password auth. OK!

**Comment by sanfordd** [comment]
Correct, right now it's standard SMTP port. We're relying on the internal firewall and only listening on the internal IP addresses to restrict access. If it looks like that's not enough we can add a authentication layer on top of that.

**Comment by jrochkind** [comment]
If we're just going to put a hostname in there, I wonder if we want to call it something with `host` in the name?  I wonder if `smtp_host` would be a clearer and less ambiguous variable name, in that that "email" can be ambiguous, and it's just a hostname. It is easy to get confused about what these variables mean, or have different assumptions being made on the providing and consuming end. Thoughts?

**Comment by sanfordd** [comment]
That's fine by me, I don't have any strong feelings on the variable name.

**Comment by sanfordd** [comment]
It's been updated to `smtp_host` and the change should be in staging shortly.

**Comment by eddierubeiz** [comment]
OK! For this to work, the config needs to be a variation on:

```
    config.action_mailer.raise_delivery_errors = true
    config.action_mailer.delivery_method = :smtp
    config.action_mailer.smtp_settings = {
      address: '[value of email_server (see above) ]',
      domain: 'sciencehistory.org',
      ssl: false,
      enable_starttls_auto: false
    }
```

Just need to include a variation on the above in application.rb and we should be good to go. Stay tuned.
