### ISSUE TITLE
Account for 4 remaining items in Kithe production with no attached files

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#399]
**File 1: "Sample-upload"**
**In Sufia:**
https://digital.sciencehistory.org/works/v405sb22w
https://digital.sciencehistory.org/concern/parent/v405sb22w/file_sets/bn999759h
**In Kithe:**
https://kithe.sciencehistory.org/works/v405sb22w
https://kithe.sciencehistory.org/admin/asset_files/bn999759h
**Diagnosis:** FileSet object existed in chf_sufia without file/bytestream attached
**Caught by audit:** yes (after bugfix #398)
**Recommendation:** delete in both Sufia and Kithe.

**File 2: "jrochkind test work"**
**In Sufia:**
https://digital.sciencehistory.org/works/td96k3395
https://digital.sciencehistory.org/concern/parent/td96k3395/file_sets/bz60cw92w
**In Kithe:**
https://kithe.sciencehistory.org/works/td96k3395
https://kithe.sciencehistory.org/admin/asset_files/bz60cw92w
**Diagnosis:** FileSet object existed in chf_sufia without file/bytestream attached
**Caught by audit:** yes (after bugfix #398)
**Recommendation:** delete in both Sufia and Kithe.

**File 3: "Modern Painter's Cyclopedia"**
**In Sufia:**
https://digital.sciencehistory.org/works/db78td198
https://digital.sciencehistory.org/concern/parent/db78td198/file_sets/hh63sx05h
**In Kithe:**
https://kithe.sciencehistory.org/works/db78td198
https://kithe.sciencehistory.org/admin/asset_files/hh63sx05h
**Diagnosis**: Due to ingest error on chf_sufia, FileSet on chf_sufia existed without attached file/bytestream. This has been fixed in chf_sufia, so fileset with that ID now does have an attached file/bytestream. 
**Caught by audit:** yes (after bugfix #398 )
**Recommendation:** do nothing in Sufia (this was already resolved by Nicole 2 weeks ago.
Do nothing in Kithe; this should fix itself next time we export and import.

**File 4: "Letter from Fred Sanger to David Brock"**
**In Sufia:**
(GenericWork no longer present)
(FileSet no longer present)
**In Kithe:**
(Work no longer present)
https://kithe.sciencehistory.org/admin/asset_files/np1939453
**Diagnosis:** Export happened. Then file was deleted in chf_sufia, so when we ran import, it couldn't find the file to import. Because the file can't be exported (as it no longer exists in Sufia) there is no export file. Because we then did a subsequent export, audits based on _that_ export file didn't catch, cause no longer cared about this file. 
**Caught by audit:** no (even after bugfix) -- but we think this was caught by the original audit after initial import, it's just not caught by subsequent audits with updated imports
**Recommendation 1:** Delete the asset in Kithe.
**Recommendation 2:** No more deletes in Sufia production until launch.

**Comment by jrochkind** [comment]
* Deleted File 1 bn999759h in chf_sufia and kithe.sciencehistory.org

**Comment by eddierubeiz** [comment]
Deleted file2

**Comment by jrochkind** [comment]
Deleted file 4 np1939453 in production
