### ISSUE TITLE
S3 Storage Design

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#4]
Generate a selection of S3 buckets for the application to use as well as the correct lifecycle rules. See the wiki for current planning.

**Comment by sanfordd** [comment]
Done adding, make sure documentation is clean.

**Comment by jrochkind** [comment]
should we close this @sanfordd?

Can you add links to any docs you have on ansible, as well as the relevant bitbucket ansible file(s) that control S3 creation?  I know you gave them to before, but I lost em! :)

**Comment by sanfordd** [comment]
For documentation on the command(s) and limits see the README document at: https://bitbucket.org/ChemicalHeritageFoundation/ansible-inventory
The playbook is: https://bitbucket.org/ChemicalHeritageFoundation/ansible-inventory/src/master/create_kithe_s3.yml
The actual role can be found here: https://bitbucket.org/ChemicalHeritageFoundation/ansible-inventory/src/master/roles/s3/
