### ISSUE TITLE
Make admin notes multiple

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#414]
See https://kithe.sciencehistory.org/admin/works/4f16c291q for an example of a work with 3 admin notes.

- [x] data model
- [x] UI
- [x] export/import and audit https://github.com/sciencehistory/scihist_digicoll/pull/417
- [x] fedora check https://github.com/sciencehistory/scihist_digicoll/pull/390
- [x] migrate old notes to new format https://github.com/sciencehistory/scihist_digicoll/pull/419

**Comment by jrochkind** [comment]
@eddierubeiz ready for you, actually how about make a separate PR but also link to this issue, so you can review and merge #415 on it's own.

**Comment by jrochkind** [comment]
@eddierubeiz Hmm, in my code I didn't actually translate all existing data in db. Although the Rails code can _read_ it in either old or new form and the app works, it's sloppy to leave it in mixed form -- as I saw when it required a special check in your fedora check code, which I don't like, just more opportunity for error. 

I was thinking it would be taken care of on next import... but if your export/import code doesn't take care of it, then I should figure out how to migrate em all, I don't want to leave the data in inconsistent mixed form once we go live. 

And I'm thinking th eexport/import may not take care of it after all. 

Thoughts?

**Comment by jrochkind** [comment]
OK, here's the formula I think I just used on staging to make em all arrays...

```ruby
Work.where("jsonb_typeof(json_attributes -> 'admin_note') = 'string'").count
# => non-zero

Kithe.indexable_settings.disable_callbacks = true
Work.transaction do
  Work.where("jsonb_typeof(json_attributes -> 'admin_note') = 'string'").find_each do |work|
     work.json_attributes_will_change! # Rails doens’t realize it’s changed otherwise, since it kind of hasn’t to Rails
     work.save! # should save in new array form now
  end
end

Work.where("jsonb_typeof(json_attributes -> 'admin_note') = 'string'").count
# => 0
```

**Comment by eddierubeiz** [comment]
Awesome. I'm in the middle of running a check in prod but will run the above code shortly. Thanks!

**Comment by jrochkind** [comment]
@eddierubeiz If we think we really want to do it, I should prob just add it as a migration that does it. 

I'm a bit worried... what if it corrupts the data somehow? But I guess at this pre-go-live state, if it did, one of our checks would catch it!

So I should just add it as a migration? Or you can... I need to finish up a code4lib presentation propsoal, then i'm about to be gone for the day with jury duty tomorrow.

**Comment by eddierubeiz** [comment]
No rush; work on your presentation and I can write the migration.
