### ISSUE TITLE
Production kithe: fixity check errors should alert Honeybadger.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#416]
This functionality is covered in https://github.com/sciencehistory/scihist_digicoll/pull/387 , which is now in production. However, apparently a fixity fixity check that ran at `2019-Oct-13 03:41:12 EDT` on asset https://kithe.sciencehistory.org/admin/asset_files/tx31qj76d failed to notify Honeybadger.

This may or may not be a "real" bug, but we need to spend a bit of time investigating it and this issue covers any time we might spend on it.

**Comment by eddierubeiz** [comment]
On jobs prod console:
```
root@scihist_digicoll-jobs1-production:/opt/scihist_digicoll/current#bin/rails  c
> bad_check = FixityCheck.where(passed:false).first
> FixityCheckFailureService.new(bad_check).send
```

**Comment by jrochkind** [comment]
hmm, I think we saw an alert, I wonder if this is actually working now?
