### ISSUE TITLE
Consider dealing with accidentally committed AWS keys

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#433]
We've now accidentally committed AWS keys to git and pushed to public github twice, once each by different developers. 

While github/AWS's automated alert warns us we have done so asap, AWS requires us to change _all_ of our keys when this happens. (Not sure why, it doens't seem necessary, it's annoying). Which is a fairly annoying, disruptive, time-consuming thing to do. 

It will probably happen again, mistakes seem inevitable. 

We can think of things to do to either:

* a) make it less likely to happen (one example, git pre-commit hook to keep you from doing it), or
* b) make it easier/more painless/automated to rotate all keys when we need to

We'd need to brainstorm possibiltiies, decide which to pursue, and then pursue them.

**Comment by sanfordd** [comment]
It's just an AWS policy, in case a leaked key had permissions that were able to escalate to other areas. We have been lucky, and made our luck, in that most of our keys have very narrow permissions. Most of them aren't a huge risk when they leak as long as we catch it quickly.

I'd note we can also talk about using AWS Roles, though those would require a larger change than simply adding a pre-commit hook or automating some of the rotation steps.

**Comment by jrochkind** [comment]
Here is Amazon's support suggestions, I think some of them are not applicable by some may be. 

---

The most common source of compromise is accidental access key exposure through GitHub. To help prevent that AWS has developed a tool to scrape sensitive info from your code before you commit, called git-secrets. The installation files and documentation are available here:  https://github.com/awslabs/git-secrets
  
If you haven't already, you should enable MFA on your account, and for all IAM users, to virtually eliminate the potential for a password-based compromise. MFA is available for API-Access as well which will dramatically reduce the probability of your IAM Access keys being compromised.  

MFA for Users: http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_enable.html  
MFA for API: http://docs.aws.amazon.com/IAM/latest/UserGuide/MFAProtectedAPI.html
  
Finally, when using IAM you can restrict access to AWS services, regions, and resources so that users are only allowed to carry out their intended tasks. This way, even if the associated Access Key is compromised, the damage that can be done is limited. If you have any IAM users or keys that are not being used, we recommend that you delete them to reduce the total number of ways your account can be accessed.
Here are a few resources I recommend to help you utilize Access Keys and IAM users effectively:
  
IAM Introduction: http://docs.aws.amazon.com/IAM/latest/UserGuide/introduction.html  
IAM Policy Examples: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ExamplePolicies_EC2.html  
IAM Policy Generator: http://awspolicygen.s3.amazonaws.com/policygen.html

**Comment by eddierubeiz** [comment]
I added a pre-commit hook as documented here: https://gist.github.com/nhuray/69cfbc5566ff08a2896ad5f01efcdd78

**Comment by jrochkind** [comment]
I'm moving this back to "Inbox" to discuss bumping up in priority, now that we won't have Dan to help us deal with it when it happens.

**Comment by jrochkind** [comment]
https://medium.com/@nadun1indunil/git-pre-commit-hook-to-prevent-committing-aws-keys-8c6357b64879

**Comment by jrochkind** [comment]
maybe a way to make shared repo githooks automatically... https://github.com/rycus86/githooks

**Comment by jrochkind** [comment]
This script version looks good, has maybe a couple more features, namely it tells you what it identified as an AWS key (makes it easier to grep in your source to find!), and it lets you override to say "commit anyway" if you want to. 

https://gist.github.com/czardoz/b8bb58ad10f4063209bd

**Comment by jrochkind** [comment]
I'm actually not finding any of those regexps to work reliably to find the actual AWS_SECRET_ACCESS_KEY and nothing else.  

Some of them reliably find the AWS_ACCESS_KEY.

Not sure you can reliably recognize AWS_SECRET_ACCESS_KEY template with a regexp although plenty of snippets on the web claim to! Still looking into it.

**Comment by jrochkind** [comment]
Yeah, the secret key is just 40 random characters a-zA-Z0=9 or `/` or `+` or `=`. Say you do a regexp saying it has to have a word boundary on either side (punctuation, space, beginning or end of line). 

We have tons of false positives in our codebase for this. like portions URLs and such that happen to be the right number of chars. 

The actual id (not secret) is a bit more unique, as it's exactly 20 chars of just capital letters or digits. 

I'm not sure we can actually reliably catch the secret. 

We could try scanning for a regexp including the actual key name first? But we can't exclude all uses of key name, since we use that in variables on purpose! But something like `/aws_secret_access_key *[=:]* */` (followed by the 40 chars). 

This starts getting a lot trickier than the examples you find googling. May not be realistic.

**Comment by jrochkind** [comment]
Okay, there's this *app* `git-secrets` from AWS... we could ask every dev to install the app and use it...

We could potentially also steal it's regexps and put them into one of those simpler scripts. The regexps built into it do indeed want to find something looking like a config decleration with key name on same line:

https://github.com/awslabs/git-secrets/blob/80230afa8c8bdeac766a0fece36f95ffaa0be778/git-secrets#L233-L242

**Comment by jrochkind** [comment]
See also for future, https://github.com/gitleaks/gitleaks
