### ISSUE TITLE
Tweaks to staff views

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#435]
Things needing clarification observed when observing staff user using interface:

- * ~Use the word "children" instead of "members"?~  (not for now)
- [x] After "promoting to child work", it drops you into a metadata edit form. There should be a 'flash' message something like "promoted to child work" (and maybe with "would you like to edit metadata"?), to make it less confusing what happened and why you are there
- [x] The display of the "parent" work, when looking at child work, is confusing (I don't think it's actually displaying even as it was intended to i think it's a CSS bug, but it should be bigger and on it's own line and such). 
- [x] "Demote to asset" button is on Work admin page, but missing from 'admin' menu in the list of child works. should be there to be symmetric with "promote to child work".

**Comment by HKativa** [comment]
In reference to point #1, "Members" can include both assets and child works associated with a record/parent work (see ID 9g54xj51s for a good example). In terms of clarification for the staff interface, I think it would be most helpful to update the "Type" from "Work" to "Child Work," while retaining the "Asset" label for those images that haven't been converted to child works.

**Comment by jrochkind** [comment]
Makes sense. I was talking about changing the tab heading "Members" to "Children", and any other place that says "members" as a generic term for both. I have the sense that "children" as a generic term for both (child works, child assets) makes mores sense to more people. Hard to say for sure without spending more time on it.  stAs far as "Type: Child Work" the confusing thing to me is that to me "child work" isn't really the type. The type is work, it just happens to be a child.  But "child" works hae the exact same metadata as "parent" works, the type, which determines what metadata they have is the same either way, "work". Whereas "asset" have entirely different (very limited) metadata, and no children of their own, etc. If "Type: Child Work" makes more sense to staff users we can do it, but it makes me nervous because it doesn't accurately reflect the actual software functionality to me.
