### ISSUE TITLE
Make staff user accounts in new app

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#441]
@HKativa will add list of staff needing accounts

**Comment by HKativa** [comment]
The following staff members need accounts in the new app:

Patrick Shea
Lee Berry
Jim Voelkel
Mary Mark Ockerbloom
Rebecca Kaplan
Molly Sampson

**Comment by jrochkind** [comment]
OK, looking up emails for them all at sciencehistory.org, just to document what I'm creating:

Patrick Shea: PShea
Lee Berry: LBerry
Jim Voelkel: JVoelkel
Mary Mark Ockerbloom
Rebecca Kaplan: RKaplan
Molly Sampson: msampson

OK, those were all predictable!

I am _not_ going to send "password reset" emails to them until the new app is live at "digital.sciencehistory.org", cause I think it would be confusing and unnecessary. 

So will leave this ticket open until they've done so.

**Comment by jrochkind** [comment]
All those accounts are created (without "admin" privileges, just regular staff). 

Will leave this ticket open until after we've gone live, and send password reset emails to them all too.

**Comment by HKativa** [comment]
Update: Email sent to all users with editing privileges re "reopening" of the app. Also, all password reset emails sent. If anyone has trouble logging in, I'll follow up.

**Comment by jrochkind** [comment]
Thanks a lot Hillary! I'm going to close this ticket.
