### ISSUE TITLE
Double-check indexing and sorting for "date created"

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#446]
Filing this bug for Hillary; will ask her to fill in the expected behavior a bit more later.

Compare these two searches:

https://digital.sciencehistory.org/catalog?f%5Bdivision_sim%5D%5B%5D=Library&q=&range%5Byear_facet_isim%5D%5Bbegin%5D=&range%5Byear_facet_isim%5D%5Bend%5D=&search_field=all_fields

https://kithe.sciencehistory.org/catalog?f%5Bdepartment_facet%5D%5B%5D=Library&q=&range%5Byear_facet_isim%5D%5Bbegin%5D=&range%5Byear_facet_isim%5D%5Bend%5D=&search_field=all_fields

Most of recently added Micrographia plates are published and public in the new app, yet they don't show up as "recently added".

Note: this could be a false alarm. Just logging this issue to justify a bit more investigation.

**Comment by jrochkind** [comment]
In both old and new app, the date of publication is not actually recorded, so "recently added" actually means:

* Items that are public, with the most recent _created_ date. 

I think, if I remember right. This may be part of what's going on, it's just an approximation (that some years ago was decided was good enough and not, at the time, in sufia, worth spending more time on to make it more accurate).

**Comment by HKativa** [comment]
I'm wondering if the difference here is that the logic in the new app does not recognize newly-created child works as "recently added" items. In this specific instance, I promoted multiple engravings from the Micrographia (9g54xj51s), which was ingested and made public months ago, to child works.

**Comment by eddierubeiz** [comment]
That should not be difficult to confirm or deny. Can you give a specific example of one of the promoted items?

**Comment by jrochkind** [comment]
That could be related. What it makes me worried about, is it may mean that created/updated dates are not being copied over properly for child works in our data migration. 

This is unfortunately a bit last minute to be discovering that; we are running out of time to diagnose and debug it.

**Comment by jrochkind** [comment]
Okay, the item that is showing up first in chf_sufia is "Diagrams of microscope and assorted optical instruments and devices", https://digital.sciencehistory.org/works/bk128c180

This item does not show up _at all_ in current `kithe.sciencehistory.org` search. It is actually not present in the data -- not just it's not published, nothing with id `bk128c180`(or that title)  is in the database at all. 

@eddierubeiz , what's up with that? Do we have a data sync problem, or was it just created after the last sync? 

Could the data not being _entirely_ sync'd be the entire explanation of this observation?

**Comment by eddierubeiz** [comment]
With the latest data, and accounting for the fact that Kithe still doesn't show unpublished items in the public view to logged-in uses (yet), the items shown are the same. They do appear to be sorted differently when viewed as "Sort by recently added."
Will take a minute to investigate that.

**Comment by eddierubeiz** [comment]
The sort above (
https://digital.sciencehistory.org/catalog?f%5Bdivision_sim%5D%5B%5D=Library&q=&range%5Byear_facet_isim%5D%5Bbegin%5D=&range%5Byear_facet_isim%5D%5Bend%5D=&search_field=all_fields ) is *not* sorted by "recently added", nor by date created, but in fact by date modified.

If, in the new app, you search for the same result set, and request they be sorted by date modified, you do get the results correctly sorted by date modified:

https://kithe.sciencehistory.org/catalog?f%5Bdepartment_facet%5D%5B%5D=Library&q=&range%5Byear_facet_isim%5D%5Bbegin%5D=&range%5Byear_facet_isim%5D%5Bend%5D=&search_field=all_fields&sort=date_modified_desc

(Note that the parent work of recently-modified items -- in this case Micrographia itself (9g54xj51s) -- is listed as "recently modified"  in Kithe but not in Sufia.)

**Comment by HKativa** [comment]
Interesting! @eddierubeiz correct me if I'm wrong, but sorting by "date modified" is an option that's only available when a user is logged into the app. This appears to be true for both Kithe and Sufia. 

Bottom line: if you don't see cause for greater concern, I don't see a need for you to keep working on this or the sorts to match exactly, as long as all works are accounted for.

**Comment by eddierubeiz** [comment]
Yup. The items are the same and the sort is almost the same if you compare apples to apples:

https://digital.sciencehistory.org/catalog?f%5Bdivision_sim%5D%5B%5D=Library&f%5Bvisibility_ssi%5D%5B%5D=open&q=&range%5Byear_facet_isim%5D%5Bbegin%5D=&range%5Byear_facet_isim%5D%5Bend%5D=&search_field=all_fields

https://kithe.sciencehistory.org/catalog?f%5Bdepartment_facet%5D%5B%5D=Library&q=&range%5Byear_facet_isim%5D%5Bbegin%5D=&range%5Byear_facet_isim%5D%5Bend%5D=&search_field=all_fields&sort=date_modified_desc

**Comment by eddierubeiz** [comment]
Yup -- it appears "date modifed" is only a sort permitted to staff users.

**Comment by jrochkind** [comment]
As far as we can tell, the "date modified" values do match in our old system data and data imported into new system. 

So, if "date modified" values match, and the "sort by recently modified" is a sort by "date modified" values... why don't these sorted lists seem to match exactly?

As far as we can tell, it's because there are odd not-yet-diagnosed bugs or interactions-of-fedora-data  in our sufia (old) app. In the couple cases we looked at where they didn't match, the one in the new app seemed to be _correct_.

**Comment by eddierubeiz** [comment]
Correct.

**Comment by eddierubeiz** [comment]
Note: A more thorough discussion of how dates are treated in Fedora, Sufia and scihist_digicoll can be found at https://github.com/sciencehistory/scihist_digicoll/issues/463 .
