### ISSUE TITLE
Public view for private (unpublished) works only displays 1st/representative image for multi-file works

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#449]
When looking at an unpublished work with multiple files in the public view, only the first image is visible. For example, see https://kithe.sciencehistory.org/works/r494vm45w (compare to https://digital.sciencehistory.org/works/r494vm45w in current app). 

For cataloging workflow, it's helpful to have all files associated with a work visible and available for reference.

**Comment by eddierubeiz** [comment]
Fixed in production. See e.g. https://digital.sciencehistory.org/works/vcs937d
