### ISSUE TITLE
The thumbnail won't load for a pdf

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#450]
The thumbnail will not load for the pdf that is attached to this record: https://staging-digital.sciencehistory.org/works/ojmpdm1

Thanks for looking into this!

**Comment by yonyitz** [comment]
Just determined that it automatically selected an audio file as the representative media.  Can it default to selecting the pdf as the representative media, as in the current app?

**Comment by jrochkind** [comment]
I'm not sure what the current app does, but the way representatives work in the new app there's no super easy way to make that happen, but anything can be done with enough work.

**Comment by yonyitz** [comment]
It could just be that the current app had the pdf attached to the record first so it was not an issue.  I'm fine with hand selecting the pdf as needed if it saves work on your end!

**Comment by eddierubeiz** [comment]
This case might fall within the scope of #496 ; they are related for sure.

**Comment by jrochkind** [comment]
I'm not sure if this is a bug at all. It is not what the title says: "The thumbnail won't load for a pdf "

It is also related to #496, but in an odd way. 

What almost certainly happened here was someone did open up an Edit form, that had a representative select in it. If no representative is selected, the select menu is set on the first one in the list, which when you submit the form will set it as a representative. 

I'm not sure how to fix this -- it probably is _not_ right to say you can never choose an audio file as a representative. Sometimes you might want to?

**Comment by eddierubeiz** [comment]
Yeah, the title is wrong. 1) If you select an mp3 as representative, we don't currently have a way of generating a thumbnail for it. 2) There are no current rules that prioritize graphical files over non-graphical ones when selecting a representative on ingest.

**Comment by eddierubeiz** [comment]
And absolutely, this might not be a bug.

**Comment by jrochkind** [comment]
> There are no current rules that prioritize graphical files over non-graphical ones when selecting a representative on ingest.

Right. Keep in mind, that's because a representative is _not selected on ingest at all_. 

Right now, no representative is set until you open an 'edit' form and select one. There is no 'prioritization' at all, it's just whatever is chosen in that 'select' menu.

**Comment by eddierubeiz** [comment]
I don't really think of this as a bug. I'm fine with closing it.
