### ISSUE TITLE
"View in library catalog" link displays twice

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#451]
Link to the OPAC record for the collection associated with this work displays twice in public view on the new app:  https://kithe.sciencehistory.org/works/x346d4432

**Comment by HKativa** [comment]
Note: I think this is affecting older records, where the OPAC link was manually copied and pasted into the "Related URL" field, before the functionality was added to render the "view in library catalog" link using the Bib number in the External ID field. See also:

https://kithe.sciencehistory.org/works/w66343603 
https://kithe.sciencehistory.org/works/8w32r5659
https://kithe.sciencehistory.org/works/pc289j53n

**Comment by jrochkind** [comment]
Thanks for finding and reporting! We can get that fixed.

**Comment by HKativa** [comment]
Update: this issue has been resolved for all of the records cited in the original issue. However, additional examples were found:

https://kithe.sciencehistory.org/works/t722h939f
https://kithe.sciencehistory.org/works/gm80hv33v

**Comment by jrochkind** [comment]
https://digital.sciencehistory.org/works/fb494841c with four link to catalog links displaying,
Has one BibID entered in metadata, for `b1071974`. 

But has FOUR sierra OPAC  URLs entered as "related urls"
* http://othmerlib.sciencehistory.org/record=b1071974
* http://othmerlib.sciencehistory.org/record=b1043344
* http://othmerlib.sciencehistory.org/record=b1069453
* http://othmerlib.sciencehistory.org/record=b1043343

Only one of which matches the BibID.  What does this mean, and is it intentional?

It looks like the old logic in chf_sufia ignored _any_ othmerlib sierra OPAC URLs, if any bibID was entered. So we could make that so in the new app too... but it is ignoring unique content there, related urls to other OPAC records. 

I didn't know that was a use case we might have, putting multiple different OPAC links in there. How would we _want_ them to show up, if at all?

**Comment by jrochkind** [comment]
https://digital.sciencehistory.org/works/t722h939f has two links to catalog showing up. 

It's metadata has bib number `b1069527`, but related URL `http://othmerlib.sciencehistory.org/record=b1069527~S5` -- that weird extra `~S5` on the end, which we don't really understand what it means to Sierra, it's optional in the URL.  I think staff usually tries to enter a URL *without* that `~S5` on the end, but I guess sometimes they slip through. 

In this case, then the code for de-duplication doesn't realize it matches. I can fix to truncate to first 8 chars of bibID in URL. 

https://digital.sciencehistory.org/works/gm80hv33v is exactly the same.

**Comment by HKativa** [comment]
Re https://digital.sciencehistory.org/works/fb494841c with four link to catalog links displaying,
Has one BibID entered in metadata, for b1071974:

Thanks for catching that @jrochkind! In light of the existing issue, I didn't think to check where the links actually went. This is a misuse of the related URL field, as our intent is only to link to the OPAC record from which the digitized item originates, not related collections, which is what's happening with the other three URLs. When editing is re-opened on the app, @yonyitz  and I will update the works accordingly.

**Comment by eddierubeiz** [comment]
Cool!

**Comment by jrochkind** [comment]
If it's a lot of records, we can also bulk edit them for you if you give us IDs. 

My understanding is in general, we don't currently want/need any OPAC urls in "related urls" -- using the just "bib ID" metadata instead -- so we could also remove all related urls from specified records, or all records. 

https://digital.sciencehistory.org/works/t722h939f is now fixed. 

but https://digital.sciencehistory.org/works/gm80hv33v is not, checking it! This one is a lowercase b in one version and a capital B  in another, making the software not realize they are the same. So many things that can be weird! I'll get that one fixed too.

**Comment by jrochkind** [comment]
OK all examples mentioned are now only one "link to catalog" link, **except** the with with extra "related urls" that need to be removed from metadata. 

I will move this ticket to "review", and it's done unless/until we find more examples that are misbehaving!

**Comment by HKativa** [comment]
Update: now that the app is reopened for editing, I've removed the extra "related URLs" from all records in https://digital.sciencehistory.org/collections/g445cd18p.
