### ISSUE TITLE
Odd capitalization in auto-generated citation

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#454]
See "Cite As" for work kw52j8997 (odd capitalization in bold): “Hercules Explosives and Blasting Supplies: Steve Says Iron Mining's Improved - but <b>We'Ll</b> Do It Better Yet.”

Citation appears this way in both Kithe and Sufia. Low-priority issue, but wanted to make note of it for documentation purposes.

**Comment by apinkney0696** [comment]
Low priority.
