### ISSUE TITLE
Consider hiding "Project" facet for non-staff users

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#461]
Comment from @jrochkind on digital-general channel in Slack (11/1/2019): Not urgent, just a thought…. we added a “Project” facet… but there seem to only be 8 items that have a Project assigned.
Is there a sense of how we expect users to use this Project facet limit, what they’d be using it for how?
I wonder if we should consider hiding this facet from non-logged-in (non-staff) users, at least until there are many more items with assigned projects?

Response from @HKativa on digital-general channel in Slack (11/1/2019): Good points and questions all around. Right now, the "Project" facet only applies to oral histories and has very limited utility for public users. I would be inclined to hide it, but it's a low priority thing.

**Comment by jrochkind** [comment]
Obsolete, we're removing "project" attribute and facet altogether in #1492
