### ISSUE TITLE
Recent items on front page: tweak to recipe

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#462]
Hillary has a hunch that the recipe used to pick items listed in the "recent items" has a small bug in it, and I agree.
The code ( scihist_digicoll/app/presenters/recent_items.rb)
uses a variation on:
```Work.where('published = true').order('updated_at').limit(10)```
and I think that does not in fact return a list of recently updated items; I think, in fact, it returns a completely random list.
Should be easy to fix, assuming it is something wrong with that one line in the code.

**Comment by jrochkind** [comment]
If ordering by `updated_at` is _random_... does that mean the updated_at values are random?  That would be disturbing, as they ought not to be!

I wonder if they appear to be becuase the _import_ is accidentally resetting the `updated_at` values???

**Comment by eddierubeiz** [comment]
Oops. They weren't random, far from it. The "recent items" has actually been showing the "stalest items"! Mea maxima culpa.
