### ISSUE TITLE
Possible SSL cert issue on site

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#467]
On newly deployed scihist_digicoll production...

Browsers (MacOS Chrome and FF) don't have any complaints about the SSL cert. 

However, the [honeybadger ping status checker](https://app.honeybadger.io/projects/53196/sites/73800e4e-050a-4cc7-9831-7ad348b77906) is complaining with "SSL cert is invalid". 

Checking in [digicert SSL cert diagnostic tool](https://www.digicert.com/help/), it says:

> TLS Certificate is not trusted
> The certificate is not signed by a trusted authority (checking against Mozilla's root store). If you bought the certificate from a trusted authority, you probably just need to install one or more Intermediate certificates. Contact your certificate provider for assistance doing this for your server platform.

@sanfordd tried a different SSL diagnostic tool that specifically mentioned intermediate certs too, which is mentioned as one possible cause in the digicert message too. 

So we probably need to fix intermediate certs.

**Comment by sanfordd** [comment]
The combined cert has been tested in staging and successfully resolved the ping status check error we were getting.
