### ISSUE TITLE
Preserve creation date when when promoting assets to child works?

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#472]
Quoting from @jrochkind's remarks (see reference below).

The new app _does not_ necessarily _preserve_ creation date when you use the new app function to convert assets to child works and vice versa. If we think that is correct behavior and we _do_ care, we should make new app do that. 

And there are some decisions involved about what is "right" for the "date created" for something converted from asset to work or vice versa -- should it's "date created" stay the same or reset? In terms of administrative metadata for historical/preservation/administrative purposes, as well as UI. 

_Originally posted by @jrochkind in https://github.com/sciencehistory/scihist_digicoll/issues/463#issuecomment-549463430_

**Comment by eddierubeiz** [comment]
Feel free to delete this issue if we decide not to change the behavior in the new app. Just saving this so we have a reference to today's discussion.

**Comment by jrochkind** [comment]
We will not do this, we decided we like the current behavior best after all -- when you promote an Asset to a child Work, the "creation" date of a Child Work is the date it was promoted -- the date the work was created as a work. We'll stick with that for now.
