### ISSUE TITLE
Cannot save new digitization queue item after inputting metadata

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#476]
When attempting to create a new queue item for modern library and archives collections, cannot click "create digitization queue item" after changing digitization queue status.

**Comment by jrochkind** [comment]
reproduced on staging:

1. Go to eg https://staging-digital.sciencehistory.org/admin/digitization_queue_items/rare_books
2. Click on "New Queue item"
3. Enter title
4. Change value in "Digitization Queue Status" select
5. The "save" button titled "Create Digitization queue item" greys out, and is disabled, and can't be clicked. 

Weird. We must have some JS meant to apply in other contexts going wrong. Hm, I have an idea, may be the auto-submitting status menu on non-form pages.

**Comment by jrochkind** [comment]
@yonyitz hopefully will have this fixed shortly,but if you want to work around it, just don't change "digitization queue status" on that menu -- save it with the default, then change the status from the list of items.
