### ISSUE TITLE
Do not allow works to be published unless they have a published representative; prevent the deletion of published works' representatives.

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#496]
Replicated a process that I encountered on the main site in staging and it appears to be a glitch:

1.  Added new image for this record: https://staging-digital.sciencehistory.org/works/f1881m63m
2.  Deleted original image
3.  One needs to go back into edit metadata screen and click "update work" in order for representative member to appear

**Comment by eddierubeiz** [comment]
Otherwise stated, IF you start out with a parent with two member items, and AND you delete one of them, AND this would otherwise leave the parent without a representative, THEN the parent's representative should automatically be set to its sole surviving member.

**Comment by jrochkind** [comment]
In general, we don't have a lot of code right now for ensuring there's always a valid thumbnail, or automatically updating the thumbnail when things change, so it's still valid. 

There are probably a variety of cases that leave you without a good thumbnail. Deleting (which can maybe be done in various paths, considering the possibility of multi-level children), maybe also making non-public. 

We could decide if we want to prioritize work to make this never the case, depending on how inconvenient/time-consuming/subject-to-error it is to have to do manual fixes of these. 

We could potentially resolve this either by code taht hooks into "update" processes to make sure a valid thumbnail is set in `thumbnail_id ` where applicable/possible; *or* at display time we could notice that there's no thumbnail set (or the `thumbnail_id` is not available), and choose another arbitrary one to be representative. 

I think this latter is actually what chf_sufia did -- if no representative was set, it just chose the "first" public one to use as a representative. The challenge *potentially* is doing that in a performance-respecting way, which chf_sufia probably did not; although it might be straightforward.

**Comment by jrochkind** [comment]
* Let's look at what chf_sufia was doing for background
* Let's also make sure the admin pages are more clear feedback on management pages when there is no thumbnail set

**Comment by eddierubeiz** [comment]
Noting also that from the public's standpoint, if the representative is not published, it's just as if it hadn't been set at all. So we should consider that case as well.

**Comment by eddierubeiz** [comment]
See also #450 which is about possibly paying attention to content type when selecting the representative at the time of ingest.

**Comment by eddierubeiz** [comment]
In Sufia, if you delete the representative (or thumbnail), you end up with nil representative (or thumbnail). It's not automatically changed to the most-likely new value; that is left to the user. So, for what it's worth, this problem already existed in Sufia.

**Comment by jrochkind** [comment]
Also this no longer matches the title of this issue -- "Make sure works have a representative after members are deleted" -- that's not actually the problem we are trying to solve anymore?

Change title and/or make different issue?

**Comment by apinkney0696** [comment]
@eddierubeiz I hate to say this, but I have discovered a bit of a snag. @sunicolita just messaged me saying that she couldn't publish an oral history because the private transcript asset was set as the representative. I totally forgot that all of the oral histories in the digital collections, except for those with free access restriction status, have an unpublished transcript asset set as the representative. Is there any way we can tweak this to allow an exception for oral history works? Or maybe turn this into a warning pop-up, without actually blocking the publishing?

I'm so sorry I didn't think of this earlier when I was testing this for you. I was only considering the context of the errors we were having in the Bredig collection. Huge oversight on my part.

**Comment by eddierubeiz** [comment]
We have indeed been using the first page of a private transcript as the thumbnail when the transcript is set as a representative.
We had a quick convo and I'm letting @sunicolita and @apinkney0696 figure out the best way forward.
Possible solutions include:
- using a stock icon instead;
- leaving things as they are and removing the rule, as suggested;
- requiring OH staff to upload a separate public image of the first page to use as a representative.

The current state of affairs assumes that the thumbnail graphic generated from the first page of a private oral history transcript is free of any confidential information. That may well be true in practice for our current holdings, but it's worth thinking about carefully.

**Comment by jrochkind** [comment]
Oops. this goes to show how tricky these automated workflow related things are to get right, and why we keep learning to try to avoid them as much as possible!

Should we revert this logic while we figure out how to fix it? That is a possibility. Let's talk at meeting today. 

if they upload a separate public image to use as a representative, it will show up in the "downloads" list unless we do even _more_ work around that.

**Comment by eddierubeiz** [comment]
OK -- while we think about this, we're removing the requirement of a published representative for publication.
The PR for *adding* the rule is #1433 . 
The PR for *removing* the rule is #1466 .
We are deciding to *not* remove changes to the factory and tests unless they're directly related to this functionality.
