### ISSUE TITLE
Make non-public items visible to logged-in users on collection landing pages

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#509]
For example, see https://digital.sciencehistory.org/collections/b2773v77g: as a logged-in user, I can see that this collection currently has 88 public items out of 158 total items (the remaining 70 are set to "private" while awaiting metadata). However, from the collection page, there is no way to see the private items that are awaiting cataloging. Alternately, I can find these items in the public search (as a logged-in user) by limiting the visibility to "private" and searching by the accession number or another identifier, but it would be more convenient to locate these items directly from the collection page.

**Comment by eddierubeiz** [comment]
Yup. Same deal with featured topics.

**Comment by eddierubeiz** [comment]
Fixed in production. Compare logged-in and not-logged-in views of the following:

https://digital.sciencehistory.org/focus/instruments-and-innovation
https://digital.sciencehistory.org/collections/b2773v77g
