### ISSUE TITLE
Import streamline: load files twice instead of storing IDs in memory.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#51]
The import needs to iterate over GenericWorks twice. Currently the IDs gleaned from the first pass are stored in memory and processed during the second pass.
Instead, store nothing in memory and simply reload the import files during the second pass.
This is more elegant and will simplify the code.

**Comment by jrochkind** [comment]
Completed with the great import refactor.

**Comment by jrochkind** [comment]
@eddierubeiz left a comment saying "completed" above, so I will close this issue.
