### ISSUE TITLE
review of postgres security

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#519]

**Comment by sanfordd** [comment]
Adding some detail here, currently things are locked down but if we start storing more types of information in the database it's worth looking at how we want to secure it.

Currently we have no data we consider sensitive in postgres which reduces some of our security concerns.
Our current security features:
- Database is held on separate server 
- Restrict access to the server via a firewall
- Restrict access to postgres via pg_hba to a limited IP range
- Restrict access to accounts via passwords for postgres database accounts
- Database passwords properly hashed via bcrypt
- Database passwords are hashed when sent over the network via the md5 authentication method (see https://www.postgresql.org/docs/9.5/encryption-options.html under Encrypting Passwords Across A Network)

Security concerns are
- Backup tools use a password in an unencrypted format, potentially allowing someone with server access to view data.
- Data on-disk is not encrypted, allowing accounts with access to the database to view all data, and someone with server access to view data.
- Backup is not encrypted, allowing anyone with backup viewing or restore access to potentially view data.
- Intra-LAN communication is not fully encrypted.

Potential threats are
- Someone gaining access to the backup data and pulling out any sensitive data
- Someone compromising our application 
- Someone compromising our web server directly
- Someone compromising our background jobs server directly
- Someone compromising our database sever directly
- Someone accessing our LAN
- A malicious internal user, currently not an issue we are planning for.

Solutions: 
- We could use pgcrypto to encrypt future sensitive data columns. This solves the issue of sensitive data in backups and reduces the risk of on-disk access from sources outside the application. Our backup user(s) do not need to be able to decrypt the data. We retain vulnerabilities to our application being targeted.

- Switch the backup script to a different account with more limited access, reducing the danger of its password being stolen (this ties in with pgcrypto, if there's sensitive unecrypted data than even a read-only access key presents a potential, if remote, risk). This removes some of the danger if someone accesses the database server.

- Encrypt only backups, which removes performance issues with encrypting data on disk. It does mean backup recovery will need a decrypt step, and does not solve the danger of someone gaining access to the database server.

- Encrypt traffic inside the LAN by forcing SSL connections between servers. Our passwords are already secured but this limits the ability of anyone snooping on our LAN to pull out other data.

- Set up shared SSL certificates on web, job, and database servers to reduce the chance of Man in the Middle (MTM) attacks.

The second solution can be implemented independently of the first even if we don't do anything else, and provides some marginal improvements to security even if we don't add any sensitive data.

If we do include more sensitive data, an initial estimate would be to set encrypted traffic (to foil anyone who may have gained access to the LAN), and preferably encrypt the sensitive columns if we can afford a small performance hit. This may require insuring that sensitive data is not called overly often by the application to minimize performance implications. Encrypting just the backups is also an option, but I think per-column encryption offers more security though at a potential performance cost. Estimating what that will be is essential to deciding if we can afford it. Shared SSL certs may be more than we need at a start for handling sensitive data.

The end result is that the database server itself should have no credentials on it that can read the encrypted data in case it is compromised. We remain at some risk if the application is compromised  or the application server is compromised and application credentials are acquired.
