### ISSUE TITLE
Import streamline: load UUIDs en masse instead of loading each item into memory.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#52]
Streamline the import based on the following two recipes, which Jonathan suggested. Both obviate the need to load batches of items into memory.

**"PLUCK" AN ARRAY OF UUIDS BASED ON AN ARRAY OF FRIENDLIER_IDS AND VICE_VERSA:**
     ```Kithe::Model.where(friendlier_id: array_of_multiple_friendlier_id).pluck(:id) ```

**SET THE CHILDREN OF A PARENT EN MASSE:**
```
    collection.contain_ids
    # two IDs (UUIDs, not friendlier_ids)
    # => ["0e7c2e6d-c000-48ab-8270-765eaf1ef8d2", "cd64795d-66ba-4a12-bda7-78b73169e55c"]

    # Set it to a new array with one but not the other of the old IDs, but plus a new ID
    collection.contain_ids = ["0e7c2e6d-c000-48ab-8270-765eaf1ef8d2", "2c7c17b1-ad69-40ae-943e-5921de02c81a"]
```

Immediately, without/before a `save`, it deletes the join row for the ID you removed in the db, and adds a join row for the ID you added. (Recall this is a many-to-many  that uses a db join table)

You do gotta look up the internal UUIDs for the friendlier_ids you’ve got, but pretty simple and high-performance way to say “make this collection have exactly these members whose IDs I specify, no more and no less” — without actually having to load the members into memory.

**Comment by jrochkind** [comment]
@eddierubeiz Is this still in the cards, or is it either done and/or no longer planned?

**Comment by eddierubeiz** [comment]
You actually ended up doing it. ```target_item.contain_ids = member_ids``` in the collection importer.
