### ISSUE TITLE
Google Analytics Events not being recorded

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#526]
It looks like our events are not being recorded in Google Analytics. Other forms of activity show up normally.

**Comment by jrochkind** [comment]
I see a problem with tracking viewer opens. But download links *looks* like they should be tracked. Confirming, you believe they are not?

**Comment by jrochkind** [comment]
this is tricky to debug, I don’t know how to confirm whether it’s working or not, if the relevant JS does seem to be triggered.

I think I have access to the GA console maybe, can you remind me how I get there @sanfordd ?  And where on there I should see events? I’m not sure how much latency to expect before one showing up though.

**Comment by jrochkind** [comment]
https://analytics.google.com/, then Behavior / Events.

**Comment by sanfordd** [comment]
Correct, we show no downloads for the time after the application launch which is unrealistic. I also can't see anything when I download items.

**Comment by jrochkind** [comment]
I _think_ I have fixed this and deployed to production. @sanfordd can you help confirm it now seems to be recording events for downloads and viewer?

**Comment by sanfordd** [comment]
@jrochkind I've confirmed that it triggered for both downloads and viewer usage.

**Comment by jrochkind** [comment]
Awesome! Considering this done then!
