### ISSUE TITLE
Import streamline: update items, rather than deleting and recreating them.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#53]
Instead of deleting and recreating already-created items, delete all their bibliographic metadata and update them. The _all_ part is important: if we don't delete *all* the appropriate metadata, we get stuck dealing with an accretion of stray metadata left over from a series of imports. _O, that way madness lies._

**Comment by eddierubeiz** [comment]
This is in progress in Dev.

**Comment by eddierubeiz** [comment]
See branch https://github.com/sciencehistory/scihist_digicoll/tree/wipe_instead_of_deleting

**Comment by eddierubeiz** [comment]
Done in dev.

**Comment by jrochkind** [comment]
I don't understand what "done in dev" means. Where is this code, on what branch? I'm not sure what's going on with what branches. Maybe put a link to the commit here? Or not if that's a pain. Just want to make sure "done in dev" means it's committed and merged somewhere.

**Comment by eddierubeiz** [comment]
Sure! It's merged into https://github.com/sciencehistory/scihist_digicoll/tree/import_from_chf_sufia .
