### ISSUE TITLE
Dev AWS key(s) should have read-only access to staging S3 buckets

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#531]
To support #298 , dev keys will need to be able to copy from S3 staging buckets, so it can copy specified items to a dev copy from staging.  (at least originals bucket, but read-only access to all of them seems safe).

**Comment by sanfordd** [comment]
@jrochkind Feel free to test it out, you should have access to GET, GET specific versions, and LIST all active staging buckets now on the dev keys.

**Comment by sanfordd** [comment]
I've tested both GET and LIST requests with a current dev key successfully on the derivative and originals buckets successfully. This has been moved to review.
