### ISSUE TITLE
New dropdown label for 'Genre' field

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#536]
Label: "Specimens" - alphabetical order like existing labels, so after "Slides"

FAST genre heading follows:
http://experimental.worldcat.org/fast/1423861/

**Comment by jrochkind** [comment]
@eddierubeiz when you have a chance please!

**Comment by eddierubeiz** [comment]
Yup.
@yonyitz  -- no need to specify a FAST genre heading. :)
