### ISSUE TITLE
Add digital@sciencehistory.org to the recipients of failed fixity check notifications

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#537]

**Comment by eddierubeiz** [comment]
`digital_tech_email_address` still needs to be added to `local_env.py` in Ansible; will do in early 2020.

**Comment by sanfordd** [comment]
@eddierubeiz It's been added to ansible and should be in staging shortly for testing.

**Comment by eddierubeiz** [comment]
A recent email went out with (among others) the following headers:
```
Date: Thu, 09 Jan 2020 11:19:52 -0500
From: no-reply@sciencehistory.org
To: digital-tech@sciencehistory.org, 
 digital@sciencehistory.org
Message-ID: <5e1752a823456_3e052ab0fe0e59642181c@scihist-digicoll-jobs1-production.mail>
Subject: FIXITY CHECK FAILURE: https://digital.sciencehistory.org,
 "b1057296x1_042.tif" (asset cz30pt621)
Mime-Version: 1.0
Return-Path: no-reply@sciencehistory.org
```
digital-tech@ received the email, but digital@ did not.

**Comment by eddierubeiz** [comment]
Hypothesis: removing the carriage return in the To: field will result in both email messages receiving the mail.

**Comment by eddierubeiz** [comment]
This is a duplicate of #576. Closing.
