### ISSUE TITLE
R&R queue

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#549]
This ticket covers preliminary work on expanding the Digital Collections application to provide R&R queue functionality, currently provided through a Google form and spreadsheet.

**Comment by eddierubeiz** [comment]
**Facts:**
- 3/4 of R&R requests for on-demand digitization result in the ingestion and cataloging of item(s) on the Digital Collections site.
- Currently, for those items, metadata needs to be re-entered into the digitization queue.
- There's significant overlap between the metadata stored on the current R&R spreadsheet with that in the digitization queue.
- When an item requested is marked "closed" in the R&R spreadsheet, it has the equivalent status of "Post-Production completed" in the digitization queue.

**Comment by eddierubeiz** [comment]
**Lining up the metadata**

An R&R form would generate the following metadata:

- Curator or point of contact
- Collecting area (select one of the digitization queues)
- Patron name
- Patron email
- Deadline for digitization
- Ingest into digital collections (options: _yes_, _no_, _uncertain about copyright_)
- Scope (Pages to digitize for R&R only)
- Additional pages for Digital Collections
- Status (see below)
- Bibliographic metadata (OPAC link; External ID; Title; Title; Box/Folder/ Copyright status or holder)

**Comment by eddierubeiz** [comment]
**Statuses for R&R requests**

- Awaiting digitization on cart
- Imaging in process
- Post-production completed
- Files sent to patron
- Closed as an R&R request

Notes:

- The following statuses (currently in the R&R spreadsheet) would not be needed in the new implementation: Batch Metadata Completed; Individual metadata completed; Hold; Re-pull object; Imaging completed; in post production.

**Comment by eddierubeiz** [comment]
**When** an item's status is set to "Closed as an R&R request":
**If** its "Ingest into digital collections" field is set to **yes**, 
**Then** its status is equivalent to "Post-Production Completed" in the regular digitization queue.

It can be considered:
- removed from the R&R queue
- added to the regular digitization queue, ready for description and ingestion.

**Comment by jrochkind** [comment]
Huh, the desire is that something that started out in the R&R queue (with it's different statuses and form fields) -- could sometimes _move_ to one of the other queues (with the original  statuses and form fields)?

That makes sense, but definitely makes the implementation a bit more complicated.

**Comment by eddierubeiz** [comment]
Open questions:
Should closed R&R requests all be visible in one place?
Or, as @HKativa  puts it: "If a DQ item began its life as an R&R request, is it possible for it to live in perpetuity on the list of "closed R&R items, even after it becomes a DQ item in its respective collecting area"?

**Comment by HKativa** [comment]
Great job with the R&R queue @eddierubeiz! Here are a few requested tweaks based on our testing and feedback:

- Add "location" to the list view (FYI, I believe @jrochkind is handling this in issue #603).

- Drop-down menu for "Curator" field on R&R edit form: Remove "Other." R&R  requests always involve a named curator who is responsible for managing a specific collection.

- On the summary page for an R&R request (for example see https://staging-digital.sciencehistory.org/admin/r_and_r_items/7): add status menu/save feature, a la the summary page for a DQ item (for example see https://digital.sciencehistory.org/admin/digitization_queue_items/29).

- When an R&R item is sent to the Digitization Queue: is it possible for the status to default to "post production completed?"

If you have any additional questions or thoughts, let us know!

**Comment by jrochkind** [comment]
Any thoughts about making R&R "Curator" a text entry instead of a drop-down?  The drop-down will add headaches as assigned "Curators" available changes due to staff coming and going, although if it's needed/better it can be left.

**Comment by eddierubeiz** [comment]
@yonyitz  and @HKativa: As of Wednesday morning, if you look at the staging site ( https://staging-digital.sciencehistory.org/admin/r_and_r_items ) you'll see I made the following adjustments covered in Ref #620:

- List page: added "location";
- Drop-down menu for "Curator" field on edit page: removed "Other";
- Show page : added status menu/save feature per Nicole's request;
- When an R&R item is sent to the Digitization Queue: set default status to "post production completed";
- Removed functionality, per our discussion, to hide or disable the button to send items to the digitization queue. It wasn't helping that much and conflicted with the new status menu on the show page.

**Comment by yonyitz** [comment]
Thanks, @eddierubeiz !

Tested those new features and all looks good to go!

**Comment by eddierubeiz** [comment]
@HKativa and @yonyitz  -- let me know if you want the curator field to be a text entry instead of a drop-down!

**Comment by yonyitz** [comment]
Drop-down works just fine for me!

**Comment by yonyitz** [comment]
Text entry is fine with me based on Jonathan's latest mention on Slack "So, for “curator” on R&R — having it be a dropdown as it is adds some headache when staff positions change. We’ll need to keep the list up to date, and we’ll need to remember to make sure the software handles it okay if a name is removed from the list, that already exists in some records. But we can totally keep it if it’s a significant advantage worth the headache; just wanted to check and make sure it was, that a free text entry was not good enough. So a question as to that, rather than if the dropdown is fine, make sense?"
