### ISSUE TITLE
ability for staging server to send email

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#56]
I'm adding accounts and auth protection, so ability to send email so users can get a password reset would be helpful. Not sure if it requires Chuck's involvement.

**Comment by sanfordd** [comment]
If we want to route it through an internal email account like ours, rather than one like no-reply@whatever.xyz than we will if not it won't.

**Comment by jrochkind** [comment]
Looks like in current app it's `no-reply@sciencehistory.org`, so that seems fine for now.

**Comment by jrochkind** [comment]
do we know that one makes it through spam guard? it is important that users get their password reset emails. :)

**Comment by sanfordd** [comment]
It is supposed to, but I'll note that at the moment it's not properly ``no-reply@sciencehistory.org` and is coming out as `please-change-me-at-config-initializers-devise@example.com` and that does get flagged by the spam filter.

**Comment by jrochkind** [comment]
interesting, thanks! I will make sure that is right at least in new app.

**Comment by sanfordd** [comment]
I think it's getting overwritten somewhere, but I am not sure where offhand. As long as that doesn't happen we should be able to keep that email address. I may need to ask Chuck to add an exception for the new application like the old one, I'll see if that's simpler than just rerouting the mail through our mail server.

**Comment by sanfordd** [comment]
Closing this in favor of #62 since it's now using the correct address and sending.
