### ISSUE TITLE
Audio files (and other JS) won't play in MS Edge/IE11

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#560]
I could have sworn we checked/verified this, but currently it looks like our audio player won't work in MS Edge (successor to Internet Explorer), or Internet Explorer itself. 

I tested in a VirtualBox virtual machine. It's possible the failure is an artifact of the VirtualBox, and it would work on other windows machines? We should maybe ask someone with a Windows machine to test. 

On MS Edge:

![Screenshot 2019-12-12 15 39 04](https://user-images.githubusercontent.com/149304/70747243-92949e00-1cf5-11ea-92de-b4f73f77d0b3.png)

On IE 11, it looks like it might work, but doesn't actually play. (This may be unrelated JS error on IE7, not sure if we still need to support IE?).

**Comment by jrochkind** [comment]
We're providing an html5 `<audio>` tag with an audio/mpeg mp3 file, and an audio/webm file. 

eg

```
<audio controls="" controlslist="nodownload" data-role="audio-elem">
                <source src="https://scihist-digicoll-production-derivatives.s3.amazonaws.com/f9bdb82f-51cb-47fb-8ec5-972af4ec905d/small_mp3/5caf1582aaf452f2e753dddeebf889a9.mp3" type="audio/mpeg">
                <source src="https://scihist-digicoll-production-derivatives.s3.amazonaws.com/f9bdb82f-51cb-47fb-8ec5-972af4ec905d/webm/cc5eaf3278d625db7daf0b115cc6ac2c.webm" type="audio/webm">
            </audio>
```

I'm confused by Edge not seeming to be able to use the mp3.  In fact some information I find online suggests that Edge should even be able to use the webm. I wonder if this is an artifact of my VirtualBox VM.

**Comment by jrochkind** [comment]
Ah, indeed may be a false alarm. It seemed to play fine testing in MS Edge with a free trial on browserstack.com . (Free trial didn't let me test in IE11). 

I think the VirtualBox VM for MS Edge was just broken with regard to audio support. :(

**Comment by sanfordd** [comment]
@jrochkind I've tested on two PCs, a Windows 7 PC and a Windows 10 PC.
The Windows 7 PC under IE 11 could not play or download audio files.
The Windows 10 PC worked fine under Edge, but could not play or download audio files under IE 11.

**Comment by sanfordd** [comment]
Adding some details here,
Under IE 11 clicking on the play button doesn't generate an error. It simply fails to start playing. There's no sign of it loading in the progress bar either.

When clicking the download link it takes you to the top of the page as if it was an anchor link, but no drop down with options appears.

I actually tried using IE 11 on a non-oral history page (https://digital.sciencehistory.org/works/tv671ee) and the download and view buttons also failed to work there.

**Comment by jrochkind** [comment]
Hmm, okay, it sounds like we do have some real problems with IE11 then. Odd. But maybe not exactly the problems I thought, involving audio player. 

Next step will be seeing if we can reproduce with browserstack.com, which will make it easier to debug for a dev not on a windows machine. 

We may need to check back and see where to prioritize this issue, now that it's been confirmed. (Also check in and reconfirm that we want/need to support IE11).

**Comment by sanfordd** [comment]
Adding some relevant information on users, from our analytics in the last year we had ~14% of our users on IE of any version. In the last 4 months (Oct-Jan) we had ~25% of our users on IE. 
Over the last year as a whole ~75% were in IE 9, and ~25% on IE 11 (all other IE versions were tiny amounts)
In the last 4 months it was ~91% IE 9, and ~9% IE 11.

IE still is used by a fairly large portion of our userbase, and Edge has been in 5th place for user count on browsers behind Firefox. 

Oddly most of our IE usage seems to be traced to a single geographic location.

**Comment by jrochkind** [comment]
Should possibly re-discuss/decide priority of _fixing_ this, now that @sanfordd has investigated/confirmed it (problem just on IE, not Edge) and other staff will need to allocate time to fix it. @HKativa ?

**Comment by sanfordd** [comment]
The crossout in Zenhub issue has been fixed and the geographic region added to the prior comment.

The IE usage numbers will be increased by people on other browsers who are more likely to have privacy tools or analytic blocking add-ons like NoScript or uBlock.

**Comment by sanfordd** [comment]
In advance of further discussion of the matter, I want to note we still have that anomalous high IE 9 usage from the Chicago region. It represents 16% of our user count, and approximately 90% of our IE user count during the year so far. About 9% of the IE count is IE 11.

The IE 9 users seem to be fairly consistent across all hours of the day, and 99% of them are single session users according to our analytics. At the moment I don't have more useful data to back this up but I'm leaning towards this being an automated tool of some sort. I'd like to get a little more detail to actually be sure of that though.

**Comment by sanfordd** [comment]
We're officially dropping support for IE. We may put a warning banner on the site for IE users.
