### ISSUE TITLE
Multiple jobs servers

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#568]
Right now we have only one jobs server. Sometimes enough background work comes in (primarily from ingests) that there is a big backup in the jobs queue. If there were more jobs servers, it could go through the work faster. 

Right now, our infrastructure isn't necessarily set up to handle more than one jobs server well. One thing we know about is that right now ansible gives all jobs servers a "cronjob" role, so capistrano will end up deploying cronjobs to all of them, leading to double (or triple etc) execution of cron jobs meant only to run once. 

There may be other things that come up when we actually try it first in staging. 

If we had the ability to have multiple jobs servers we could:

1. Manually bring up an additional server when we know/see there's lots of work to do, bring it down when the spike ends. (We'll prob start with just that)
2. Consider increasing number of jobs servers that are always there (would increase our monthly costs, it depends on how often they are just sitting idle vs have work to do)
3. Try to come up with something that *automatically* scales jobs servers up and down when they have extra work to do. This is a lot more work and a lot harder to get right (and has some danger of going terribly wrong; there are a lot of horror stories out there); at any rate, being able to manually scale jobs servers is a pre-requisite before we get there. 

2 and 3 are not part of this ticket, just ability to do do 1. They would be separate tickets.

**Comment by jrochkind** [comment]
Note that once we have more than one jobs server, it makes looking at logs more complicated, so may mean #569 is a higher priority, or should even be done first. We'd have to discuss if we're willing to do this one without #569 first, I'm not sure.

**Comment by sanfordd** [comment]
We'll also want to look at optimizing our build time. Right now our jobs servers are somewhat slow to build since we make IM and VIPS from source. We might want to look at building them into an AMI so we can spin up jobs servers at a more reasonable pace for 3 or for 1 if we don't get a heads up about large tasks.

**Comment by sanfordd** [comment]
Adding a note from slack here, rather than adding a lot of logic to our ansible scripts it may be reasonable to simply make a variable set that builds a "secondary jobs" server which doesn't include the cron role and is a pricier class (like a M type) but can run at 100% out of the gate so our scaling doesn't get choked by CPU credits. It'll mean another place to edit AMIs but should be fairly minimal overhead and involve less complexity that having a script that checks the existing jobs servers and dynamically adjusts the capistrano roles.

**Comment by jrochkind** [comment]
Interesting thing that breaks up is that if we're doing "spot" scaled instances (whether manual or automatic) we might want a separate EC2 type. 

But if we were permanently scaling up our jobs servers, we would probably still want the cheaper instance tuned for uneven loads. 

So my idea that preparatory work  is exactly the same whether we are doing instances that we scale up and down for load OR we are permanently increasing jobs servers... isn't quite right. 

I guess we should plan routines that can handle either, ideally.

**Comment by sanfordd** [comment]
Of the options 2 and 3 are both solving the same issue, maybe we should decide if it's better to look at planning an auto-scaling cluster of some sort with the issues of greater complexity but potentially better costs or if we want to be aiming for multiple always on servers. 

I do think that even in option 2, having a "secondary_jobs" variable set in Ansible is viable we might just use a normal T class instance rather than a M class. The benefit of complicated logic tracking what capistrano roles are in play does prevent someone from fat-fingering the wrong servers up.

**Comment by sanfordd** [comment]
As per our conversation today we're going to focus on option 1 entirely.
The plan is to call it temp_tasks, and have it as an M class server so we don't worry about burst credits.
Right now it'll be getting either no queues, or the same ones as jobs normally has.

**Comment by sanfordd** [comment]
Looking over the documentation, resque-pool supports varying the workers by `RESQUE_ENV`, if we can set that value in the local_env.yml file and then adjust our resque_pool.yml file from
production:
 QUEUES
to something like:
jobs:
  QUEUES
temporary
  QUEUES

And resque-pool should use the value that matches the `RESQUE_ENV` set

**Comment by jrochkind** [comment]
Hey @sanfordd , I think you need to put what you intended to be code examples in markdown codebocks, I'm having trouble understnading what you meant to post above, can you edit it?

Our current resque_pool specifies two queues, each with a number of workers, ie:

```
production:
  "mailers,default": 10
  "on_demand_derivatives": 2
```

I don't understand how you pack all that info into a `RESQUE_ENV` environment variable, is it possible? Can you link to relevant documentation please?

However, we aren't restricted to only using `RESQUE_ENV`. Since resque_pool.yml is passed through ERB, we can put dynamic code in there to take values from wherever we want, including arbitrary shell `ENV` variables, or our existing `ScihistDigicoll::Env` system (which takes from local_env.yml and/or shell ENV).

**Comment by sanfordd** [comment]
@jrochkind  Code blocks modified.
We don't need that all in RESQUE_ENV. We can put the worker list in the resque-pool.yml file, matching our current method.
We add a resque_env variable to local_env.yml and it can be set to jobs, temp, or any other value, and resque-pool reads and acquires the workers based on the matching value in resque-pool.yml
(see: https://github.com/nevans/resque-pool#yaml-file-config)

**Comment by jrochkind** [comment]
@sanfordd Ah, now that you've formatted your example, I see!

It would be like ordinarily it would be using the `production` block from the Rails.env, but by setting `RESQUE_ENV` we could have an entirely different block in the resque_pool.yml. 

that could be a good solution, yeah, good idea!

Do you see a straightforward way to get `RESQUE_ENV` shell env to be set differently on different builds?

**Comment by sanfordd** [comment]
Right now we have a rails.sh file in our profile directory that sets `RAILS_ENV` to production, we could add the `RESQUE_ENV` value there as well. It wouldn't be in the `local_env.yml` file however.

**Comment by jrochkind** [comment]
conditionally add RESQUE_ENV just on the "temp task" hosts I guess. That might be the way. 

Yeah, it would not be local_env.yml, but we can't get resque/resque-pool to use our own local_env.yml, they use what they use.... 

The alterantive would be putting `<% %>` ERB tags in resque_pool.yml to conditionally output different things based on our local_env.yml setup... but the RESQUE_ENV thing you found does seem a very well-suited solution to this, if it works (have to make sure RESQUE_ENV takes precedence over RAILS_ENV for resque; it should), and at least is a standard resque_pool feature, not a separate thing we are inventing.

**Comment by sanfordd** [comment]
Is there a reason we don't want to switch jobs over to the same RESQUE_ENV and not need to worry about the RAILS_ENV when it comes to workers? That avoids any conflict between the two for workers.

**Comment by jrochkind** [comment]
For Rails code to work, `RAILS_ENV` probably needs to be defined -- and our bg jobs run by resque execute Rails code.  
And without us doing lots of extra work, the Rails env needs to be set to `production`. If you don't define RAILS_ENV at all, Rails will default to "development", which is not what we want.  We could do extra work to define a rails environment called `temp_task` which is defined identically to `production`, but that just adds more moving parts, and more confusing in things like honeybadger reports etc. We don't really want a separate set of Rails environment settings, the "production" set is fine, we just want to be able to switch between different groups in resque_pool.yml. 

So, yes, we need the Rails code to know it's Rails environment is "production". 

But hopefuly we can use RESQUE_ENV to control which set of pools from "resque_pool.yml" the resque pool workers use, with that taking precedence over RAILS_ENV for that purpose.

**Comment by sanfordd** [comment]
Let me clarify, what if we don't use RAILS_ENV in the context resque_pool.yml. We can use it elsewhere of course but we don't use production (or any other RAILS_ENV value) in the list of values inside resque_pool as per my first example. We set RESQUE_ENV in both jobs and temporary servers and allow that to be the only deciding factor in queue selection like my example above, where production was removed entirely from the resque-pool.yml file.

**Comment by sanfordd** [comment]
That option does not seem to work given our setup. If RAILS_ENV is defined I can't get resque-pool to select a set of workers based on the RESQUE_ENV.

**Comment by sanfordd** [comment]
After some reading this week and our team discussion here are the options as I see them.

Option 1: We remove resque_pool.yml from github and do what we do with local_env.yml, let ansible manage the file and it puts a link to it in the system for the application as if it was in the current location. This gives us easy control over the file's configuration. The downside is changes to the resque-workers will now involve ansible and not solely capistrano.

Option 2: With no obvious simple gem to enable config file templating, we could as @jrochkind suggested look at adding some code ourselves that would read what server is getting the code and have it edit the resque config file. The benefits are we still have the config file in github and capistrano deployment can still control resque worker numbers. The downsides are possible time investment by staff and it may introduce some complexity to our setup.

If there's another good idea I'm open but those seem like the two main choices we have,

**Comment by jrochkind** [comment]
I don't *think* we need a gem to enable config file templating. I think we can do that already using ERB in the resque_pool.yml to dynamically include values from local_env.yml in it. It's not templated at capistrano deploy time, rather it's just dynamic at application boot time. There's no need for any special gem support, it should just work.  

That's what I'd suggest we do I think, sorry I didn't explain that clearly enough that was what I was thinking.

**Comment by sanfordd** [comment]
Sorry I misunderstood you. I meant there wasn't a good gem that existed. Well in either case we'd be stuck with the issue that resque-workers need to be changed by ansible in the future. In that case I think the difference between the two in outcome is minimal. It's just a question of style and what best fits our practices.

**Comment by sanfordd** [comment]
@eddierubeiz Tagging you on this ticket too. As per our meeting we've decided to use ERB templating in the resque-pool.yml. We'll have 3 options, our mailer/default queue, our on-demand queue, and a "special" or whatever name we like queue.

The local_env.yml file will have 3 variables with a numeric designation for the number of workers each of those is supposed to have. We'll want to test how a given queue works with 0 workers and then also test a new extra jobs server with 0 workers in all three for things like rake tasks.

I can add the three values to local_env easily enough when we decide what we want to call the values.
I think the example @jrochkind gave
`regular_job_worker_count`
sounds like a fair ans easy to grasp name so how does:
regular_job_worker_count, on_demand_job_worker_count, and special_job worker count 
sound as an idea?

**Comment by sanfordd** [comment]
I've tested it out and we now have
`regular_job_worker_count`
`on_demand_job_worker_count`
`special_job_worker_count`
on the staging boxes to work with, defaulting to 0 so web and solr boxes stay worker free.

**Comment by jrochkind** [comment]
> on the staging boxes to work with, defaulting to 0 so web and solr boxes stay worker free.

Wait, do web and solr boxes have resque_pool on them at all? They are not *currently* running workers, I don't think? (Or we'd see them reported in resque admin). Even though they currently do get an app deployed to them with a resque_pool.yml in it.  So I don't think -- hopefully -- it matters what these values are on web and solr boxes, they should not have resque_pool or any workers regardless. I hope? Would be good to confirm. 

but ok, next step is putting ERB in there, and verifying it works to set workers. Also making sure 0 is okay as a value, and seeing what happens with all 0s -- both on machiens taht _do_ have a resque_pool running looking at this file. I believe @eddierubeiz is going to work on that with you?

**Comment by sanfordd** [comment]
They should not have it installed, but was I incorrect in my understanding that the variables need to exist on all the boxes for the application, i.e. that all the local_envs across the various servers will need to have those variables in the file?

**Comment by jrochkind** [comment]
I don't think they should be needed on boxes that will not be using the resque_pool.yml file at all; no reason occurs to me that they would be; I could be missing something!

**Comment by sanfordd** [comment]
Sounds good then.
