### ISSUE TITLE
Better handling of job interuption on stop/restart

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#570]
On jobs server, there are job worker processes running. 

Sometimes something tries to stop them when they might be in the middle of working on a job. This could be because the entire machine needs to be shut down; more likely, it's because when we do a deploy of new software version, it restarts all job workers so they are working with the latest code. 

What happens when this happens?

*Currently* 

* they are stopped potentially in the middle of doing work. (Forget if this is immediate, or if they are given a *few* seconds to finish their work, but if they are given time, it's very often not enough time to finish). 
* They raise an error for being interrupted, which gets reported to honeybadger, and makes them show up as "failed jobs"  in the resque admin page. The exception appears to be something like "Resque::DirtyExit: Child process received unhandled signal"
* We have to notice, and manually click for these failed jobs to be retried, using resque admin. Since all our jobs are idempotent, this should always be fine. 

This situation could be worse, but could be a lot better. Here is a different process based on what my understanding of what `sidekiq` (instead of `resque` would do) when you ask it to restart or stop job workers:

* Tell workers to stop accepting *new* tasks from queue. 
* Wait N (configurable) seconds for jobs-in-progress to complete on their own. It only waits this long if it *needs to* cause jobs are still going, it doesn't slow down all restarts to N seconds, it just is *willing* to wait this long
* If some jobs still aren't complete with their work, it hard-kills them, and *automatically* re-queues them to be re-run after workers restart. 

We could possibly get closer to this with resque and not sidekiq; although it might require sending new code to resque and/or resque-pool.  

It's possible it's not possible/feasible with resque, and would require switching to sidekiq. Although switching to sidekiq has it's own challenges, especially if we try to use free sidekiq. That's for another ticket.

**Comment by sanfordd** [comment]
The work from #242 is highly relevant here. The last few posts include details about how this is handled and some potential options we can look at.

**Comment by jrochkind** [comment]
Another way to make this much less inconvenietn might be simply:  putting something in place to automatically retry all failed jobs; probably not more than once to avoid infinite loops.

Ideally not showing up in failed jobs list unless it’s failed twice and been given up upon.

There might be a way to do this at the resque level, or at the ActiveJob level, possibly with plugin.

**Comment by sanfordd** [comment]
ActiveJob does have a `retry_on` option that may be worth looking at.

**Comment by jrochkind** [comment]
Yeah maybe we don't need this *if* we simply have failed jobs auto-repeat? Since all our jobs are idempotent?

**Comment by jrochkind** [comment]
resque is kind of an unmaintained mess here, but on heroku specifically I think resque documents how to handle this -- including needing an additional gem. 

https://github.com/resque/resque#heroku

**Comment by jrochkind** [comment]
As part of heroku deploy, I spent a lot of time investigating this, and think I have it set up as good as resque can be, which I think does desired behavior (unless there are resque bugs, whichc is possible),
