### ISSUE TITLE
digital@sciencehistory.org is not receiving fixity check failure emails

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#576]
We recently added digital@sciencehistory.org to the list of recipients of failed fixity checks in 537.

A recent email went out with (among others) the following headers:

```
Date: Thu, 09 Jan 2020 11:19:52 -0500
From: no-reply@sciencehistory.org
To: digital-tech@sciencehistory.org, 
 digital@sciencehistory.org
Message-ID: <5e1752a823456_3e052ab0fe0e59642181c@scihist-digicoll-jobs1-production.mail>
Subject: FIXITY CHECK FAILURE: https://digital.sciencehistory.org,
 "b1057296x1_042.tif" (asset cz30pt621)
Mime-Version: 1.0
Return-Path: no-reply@sciencehistory.org
```

`digital-tech@` received the email, but `digital@` did not.

**Comment by eddierubeiz** [comment]
Hypothesis: if we can get the To: header to read 
```
To: digital-tech@sciencehistory.org,  digital@sciencehistory.org
```
without the carriage return, both addresses will receive these messages.

**Comment by jrochkind** [comment]
@eddierubeiz It's unclear how our actual code resulted in a carriage return. But, do you need to be formatting multiple addresses into one string with comma-sepration yourself anyway, or can you just give multiple delivery addresses to the `mail` method as an array? What does that `mail` method actually want/document you to do for multiple delivery addresses? Does it even support delivery to multiple addresses? Things to research.

**Comment by jrochkind** [comment]
Documentation actually says either one should work, separated by commas or an array. 

https://guides.rubyonrails.org/action_mailer_basics.html#sending-email-to-multiple-recipients

**Comment by eddierubeiz** [comment]
The two commands below:
were executed on the production jobs server from the command line
send to only one address
differ only in their destination.

`#5` sends to `digital@sciencehistory.org` It was *not* received.
`#6` sends to `digital-tech@sciencehistory.org`. It *was* received.


```
cd /opt/scihist_digicoll/current/ && bin/rails runner "ActionMailer::Base.mail(from: 'no-reply@sciencehistory.org', to: 'digital@sciencehistory.org',      subject: 'Test message #5 from Eddie. Please ignore.', content_type: 'text/html', body: 'Testing').deliver_now"
cd /opt/scihist_digicoll/current/ && bin/rails runner "ActionMailer::Base.mail(from: 'no-reply@sciencehistory.org', to: 'digital-tech@sciencehistory.org', subject: 'Test message #6 from Eddie. Please ignore.', content_type: 'text/html', body: 'Testing').deliver_now"
```

**Comment by jrochkind** [comment]
what the heck.  No idea what to do here. Wonder if Chuck has any ideas; not sure if he has a github account to tag him here actually. 

Chuck seemed to have some way to track what happened with emails receieved, you might want to put some unique token in the subject and see if he can track it through the system and see what happened to it.

**Comment by eddierubeiz** [comment]
OK -- just to make everything pellucid, I made a shell script at `/home/digcol/test_email.sh`.

The shell script reads:

```
cd /opt/scihist_digicoll/current/
REF=$(cat /dev/urandom | tr -dc 'A-Z' | fold -w 3 | head -n 1)
EMAIL_1='digital@sciencehistory.org'
EMAIL_2='digital-tech@sciencehistory.org'
bin/rails runner "ActionMailer::Base.mail(from: 'no-reply@sciencehistory.org', to: '$EMAIL_1', subject: 'Test message $REF', content_type: 'text/html', body: 'Testing').deliver_now"
bin/rails runner "ActionMailer::Base.mail(from: 'no-reply@sciencehistory.org', to: '$EMAIL_2', subject: 'Test message $REF', content_type: 'text/html', body: 'Testing').deliver_now"
echo "OK, I just sent an email each to $EMAIL_1 and  $EMAIL_2 with reference $REF."
```

And I ran it, and got the following output:

`OK, I just sent an email each to digital@sciencehistory.org and  digital-tech@sciencehistory.org with reference XZA.`

The email in question was then sent to (and received by) digital-tech@sciencehistory.org, but digital@sciencehistory.org didn't get it.

**Comment by eddierubeiz** [comment]
In looking at the message source for the messages that do come through, I'm noting that Sendio does not designate [the IP of the production web server, from which the email is actually sent] as a permitted sender:

```
Received-SPF: SoftFail (sciencehistory.sendio.com: transitioning domain of sciencehistory.org does not designate 54.173.133.90 as permitted sender) client-ip=54.173.133.90; envelope-from="no-reply@sciencehistory.org"; helo=digital.sciencehistory.org; receiver=sciencehistory.sendio.com; mechanism=~all; identity=mailfrom
X-IP-Reputation: 54.173.133.90 neutral, ipclass:T3, risk-level: 70% (high)
X-Sendio-MessageID: 1579013572.28494.1
Received: from unknown (HELO digital.sciencehistory.org) (54.173.133.90)
```

**Comment by sanfordd** [comment]
We should check with Chuck, it should be on the whitelist according to our help desk history. If it wasn't on the whitelist then I assume it would also block on digital-technical or password resets and those do work.

**Comment by eddierubeiz** [comment]
Just emailed him.

**Comment by eddierubeiz** [comment]
It would be great if we could whitelist by something other than the webserver's IP address, of course, since that's subject to change.

**Comment by eddierubeiz** [comment]
@sanfordd I think sendio is scoring the emails (hence the notion of a `SoftFail` and the bit about `risk-level: 70% (high)`) and the scores are slightly different for the two emails. This might explain why one gets through and the other doesn't.

**Comment by jrochkind** [comment]
It's possible Sendio just makes it impossible for us to do this without spending an inordinate amount of time on it. We should check with Chuck before making that determination though, as well as other stakeholders.
