### ISSUE TITLE
What happens when an asset is deleted before its derivatives can be created?

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#577]
Suppose you delete an asset before its derivatives are created. When the derivative creation job comes up for execution, it won't be able to find the asset. You will thus get something like:

`ActiveJob::DeserializationError: Error while trying to deserialize arguments: Couldn't find Asset with 'id'=1a2d8d44-7ea2-4c67-9c5a-c494606fc93b [WHERE "kithe_models"."type" IN ('Asset', 'CollectionThumbAsset')]
`

https://app.honeybadger.io/projects/58989/faults/59431286

**Comment by eddierubeiz** [comment]
Possible courses of action:

- Do nothing; we seldom delete assets.
- Catch the error to provide a more helpful error message to Honeybadger. "It looks like this asset was deleted before its derivatives could be created."
- Iterate over the queue when an asset is deleted, and remove any jobs that refer to its `id`.

**Comment by jrochkind** [comment]
It's not really possible to "remove a job from the queue", there is no public API (in resque or ActiveJob; sidekiq prob wouldn't change this appreciably) for that, also no public API for looking at what jobs are on the queue, or recognizing which ones "go with a certain asset" if you could. 

So this isn't really do-able.  I'm not sure it would be the right approach even if there was public API to support it. 

Instead, perhaps the job(s) need to recognize this condition and recover from it. If you can't find the original flie, rescue the error -- check to see if the database record is also gone (has been deleted) and if so just no-op without raising/complaining (maybe log that you did it, but not an error that would be reported to honeybadger). 

That strikes me as probably the right approach. Alternately, if this happens rarely, we could just ignore it and let it keep happening. But it seems like the errors produced/logged are both confusing and numerous enough that it may cost us annoying stressful time figuring out what happened every time it happens, and maybe we should do something about it.

**Comment by eddierubeiz** [comment]
This just happened again -- https://app.honeybadger.io/projects/58989/faults/59693315

**Comment by jrochkind** [comment]
@yonyitz says:

> Nicole Joniec 10:30 AM
> Yes, I did delete files from a record after inadvertently adding incorrect audio files to a record.  Let me know if you need anything else from me!

I think we probably just want to change the tasks to accept that the file can be deleted, and silently no-op if the file is not found, instead of raising.  They might log the situation, but not error. 

It is important that the tasks remain idempotent.

**Comment by CHF-IT-Staff** [comment]
Maybe we should revisit the discussion on this issue?  There are probably many ways to handle this.  Even preventing file deletion until the derivative creation job runs could be an option?  This is not a suggestion, just an example that came to mind.

**Comment by jrochkind** [comment]
@CHF-IT-Staff We are still in progress of discussing it, we never finished/closed it. There are a variety of brainstorms on how to address it on this ticket you added another; I don't think that particular one is that feasible. We can discuss more in person/teleconference maybe?

**Comment by CHF-IT-Staff** [comment]
Thanks @jrochkind.  I don't think I'll be able to add much - so no need to include me in a discussion.
