### ISSUE TITLE
Changed citation output for circa years

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#578]
If I update one of the dependencies we use for formatting human-readable "Chicago" style citations, it changes how "circa" dates are output. 

Before, the date portion might say just `circa 1990`, now it gets brackets and a question mark: `[circa 1990?]`. 

Eg 

>    Author. Title, [circa 2000?]. Science History Institute. Philadelphia. http://127.0.0.1/works/m37p15b.

Our automated tests caught this when I tried to update `csl-styles` from version `1.0.1.9` to `1.0.1.10`. 

Not sure if this is somehow more correct for chicago style, or is simply a bug; possibly not in csl-styles, but in our own integration code. 

Should we look into this more, and possibly try to maintain previous behavior, or just accept the update with new formatting as is?

Should we look into it more, and possibly try to maintain the previous

**Comment by HKativa** [comment]
Thanks for the heads-up! @yonyitz is going to investigate the Chicago citation style and report back.

**Comment by yonyitz** [comment]
Per Chicago, the date should read "n.d., ca. 1990" for the example above.  See:
https://www.chicagomanualofstyle.org/book/ed17/part3/ch14/psec145.html

**Comment by jrochkind** [comment]
@MDiMeo decided we will just close this for now!
