### ISSUE TITLE
Investigate if large PDF generation can be done in a more RAM-efficient way

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#592]
Re #302, creating our large multi-page PDFs is taking a huge amount of RAM, making resource management/sysadmin more complex. 

Can we create multi-page PDFs in a more RAM efficient way?

* We might want *lower-resolution* PDFs -- this would result in smaller file size for users to download, and might be preferable? currently PDFs can be pretty massive. Although current size is based on trying to give 300dpi for printing. Lower-res PDFs would also result in lower RAM consumption. 

* We could try to use different tools for PDF creation. We are [currently using](https://github.com/sciencehistory/scihist_digicoll/blob/8da4a1a53ba7b963f4c59ecdb5629ebd99c930d5/app/services/work_pdf_creator.rb#L72) [prawn](https://github.com/prawnpdf/prawn). Other tools may be more efficient in their use of RAM or allow "Streaming" PDF writing in some way. That could be the ruby tool [HexaPDF](https://hexapdf.gettalong.org/), or it could be shelling out to a non-ruby command line tool of some kind.

**Comment by jrochkind** [comment]
We actually already did this.

**Comment by jrochkind** [comment]
This is about generating multi-page PDFs, not about generating JPG thumbnails from PDFs. I don't think it's relevant to the other issue... which I don't have at hand and isn't linked here.

**Comment by eddierubeiz** [comment]
Sorry - you're absolutely right!
