### ISSUE TITLE
NetData alerting for OOMs?

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#593]
Right now, if the Linux ["OOM killer"](https://linux-mm.org/OOM_Killer) kills a process due to excessive memory consumption, it can be a fairly silent/mystery event to us. We don't get clear evidence in our app logs that the process was terminated (let alone why) -- because it was forcefully terminated  without being able to log or notify. 

Depending on exactly what proccesses were terminated, they might be restarted on their own by other watchdog processes, or they might remain dead. In either case, app malfunction of various sorts could be happening, and we might not even know, or might not easily be able to diagnose why since it wasn't obvious the OOM was involved. 

Can we get our NetData health monitor to send us an alert when the OOM killer kills something? Perhaps by monitoring system logs where such things are monitored. Perhaps there's an existing NetData feature/package to do this (or not).  The more info we could get about a killed process the better -- just a pid doesn't tell us much, but even that would at least tell us an OOM event happened (and on what machine), and alert us that *something* bad happened.

**Comment by sanfordd** [comment]
@jrochkind I want to follow up here, we're not concerned about the actual lack of RAM (we already have an alert for that) but rather we want to see what OOM had to kill is that correct?

**Comment by jrochkind** [comment]
@sanfordd not sure I understand the question, we can talk on slack or voice if I'm not answering it as you meant? 

I would say my motivations are:

1. When the OOM killer kills something, it may result in a malfunction of our software. We want to know it happened so we can be aware.  If we noticed a malfunction and are trying to debug *why* it happened, doing that without realizing an OOM kill happened is a challenge, if that's part of it. 

2. We don't want the OOM killer to kill things. It means the system is not functioning as intended when it happens, so we want to know it's happening so we can try to keep it from happening if so. 

3. I am not personally sure of the relationship between OOM killer and our current RAM monitoring. I am pretty sure it's possible for RAM alert with no OOM killing having happened? It may also be possible for OOM killer to have killed something without us getting a RAM alert? I'm not sure?  I just know when the OOM killer kills something, it can result in malfunction, and it helps us underestand what's going on to know an OOM kill happened.

**Comment by sanfordd** [comment]
Quick notes from the call
Minimum info we want on the alert:
Did OOM Run
When did it run
What server did it run on

Preferred info if it isn't hard to get:
What did OOM kill

**Comment by jrochkind** [comment]
we retired netdata, so no longer a possibility.
