### ISSUE TITLE
Homepage category: Portraits & People

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#600]
Aggregate using metadata from:

Genre:
Caricatures and cartoons
Oral histories
Portraits

Subject:
African American scientists
African Americans
Alchemists
Astronomers
Biochemists
Biologists
Congresses and conventions
Chemists
Chemists--Biography
Employees
Hispanic American scientists
Industrialists
Information scientists
Inventors
Jewish scientists
Mathematicians
Medical scientists
Muslim scholars
Nobel Prize winners
People with disabilities
Philosophers
Physical scientists
Physicians
Physicists
Portraits
Portraits, American
Portraits, Group
Scientists
Scientists--Biography
Scientists--Portraits
Scientists with disabilities
Women biochemists
Women botanists
Women chemists
Women employees
Women in chemistry
Women in information science
Women in medicine
Women in physics
Women in the social sciences
Women Nobel Prize winners
Women physical scientists
Women physicians
Women physicists
Women scientists
Women in science

Hillary's comments: This list of genres and subjects represents an expanded list from the original 2018 category, in hopes of capturing more inclusive representation across the collection.

**Comment by eddierubeiz** [comment]
We could do a first version and push it to staging, then iterate. :)

**Comment by HKativa** [comment]
@eddierubeiz true! My concern with this topic has always been that it's too big, primarily due to the "employees" subject heading. But that might be a problem that only exists in my mind. ;)

**Comment by HKativa** [comment]
This digital collection features selected formal and informal portraits of notable scientists, including a significant number of Nobel laureates, as well as images of people working in a variety of laboratory and industrial settings. Also included in the collection are oral history interviews with a range of 20th-century scientists, including biochemists, biologists, chemical engineers, chemists, and physicists, as well as materials related to scientists with disabilities.
