### ISSUE TITLE
Display "location" in list view on digitization queue

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#603]
Please add "location" to the fields displayed on the list view of the digitization queue for the following collecting areas:

-  Modern library
- Rare books

**Comment by jrochkind** [comment]
Is it okay if we add it to the list view for all collecting areas? We don't yet have collecting-area-specific logic in Digitization Queue like that, and I'd like to avoid doing it unless we really need it.

**Comment by HKativa** [comment]
Sure, that's not a problem. It's really essential for those two collecting areas and often will be blank in the case of the other collecting areas anyway.

**Comment by jrochkind** [comment]
@HKativa Does this need attention on the R&R queue too, or just on the existing "Digitization Queue" pages?

If I don't hear otherwise, I'll assume just Digitization Queue pages. And as discussed, will put it on all collecting areas, since you said that was acceptable.

**Comment by HKativa** [comment]
@jrochkind we would like to add "location" to the list view on the R&R queue as well. That's on my list of tweaks/feedback for @eddierubeiz.

**Comment by HKativa** [comment]
Also, as discussed at the tech check-in on 2/3/20202, please break out the IDs (bib number, accession number, and object ID(s)) into separate columns, a la the R&R queue.

**Comment by HKativa** [comment]
@jrochkind I'm not seeing "location" on the list view for the various collecting areas in the digitization queue. (I do see "location" on the list view on the R&R queue). I do see that the various IDs were separated out - thanks!

**Comment by jrochkind** [comment]
@HKativa Odd, indeed it isn't, i recall doing it but maybe it slipped through the cracks, nice catch thanks, I'll look into it.

**Comment by eddierubeiz** [comment]
@HKativa  -- deploying this feature to production now.
