### ISSUE TITLE
Error creating thumb for apparent pdf

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#606]
Vips says:

 > vipsthumbnail: unable to thumbnail /tmp/shrine20200129-30267-bzywf3.pdf VipsForeignLoad: "/tmp/shrine20200129-30267-bzywf3.pdf" is not a known file format

This is for:

    gid://scihist-digicoll/Asset/21d67357-3ab7-4968-a551-58b5b7c4e799

On production, that's: https://digital.sciencehistory.org/admin/asset_files/bh0h66x

Based on asset size, seems to be trying to create `thumb_mini`, not sure why that's not evident from the job args/stack trace. 

> [scihist_digicoll/production] TTY::Command::ExitError: Running `vipsthumbnail /tmp/shrine20200129-30267-bzywf3.pdf --eprofile /opt/scihist_digicoll/shared/bundle/ruby/2.6.0/bundler/gems/kithe-1c73ad400611/lib/vendor/icc/sRGB2014.icc --delete --size 52x1000000 -o /tmp/kithe_vips_pdf20200129-30267-dtpwyf.jpg\[Q\=98,interlace,optimize_coding,strip\]` failed with  exit status: 255  stdout: Nothing written  stderr: vipsthumbnail: unable to thumbnail /tmp/shrine20200129-30267-bzywf3.pdfVipsForeignLoad: "/t...

## Backtrace

    line 92 of [PROJECT_ROOT]/app/derivative_transformers/kithe/vips_cli_pdf_to_jpeg.rb: thumbnail
    line 56 of [PROJECT_ROOT]/app/derivative_transformers/kithe/vips_cli_pdf_to_jpeg.rb: call
    line 24 of [PROJECT_ROOT]/app/models/asset.rb: block (2 levels) in <class:Asset>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/58989/faults/60116963)

**Comment by jrochkind** [comment]
vips generally ought to be able to process a PDF, normally with [this class](https://github.com/sciencehistory/scihist_digicoll/blob/ffd708c622b2edfa0cdc2a2e42a04a12f474063a/app/derivative_transformers/kithe/vips_cli_pdf_to_jpeg.rb) which we probably should have moved to kithe out of our local app but haven't yet. 

Why can't it process this one?

The original file does seem to be a good PDF, that Chrome or MacOS Preview can display. I will reproduce the vips command line locally with a locally downloaded version of file....

    vipsthumbnail /Users/jrochkind/Downloads/oral_history_interview_bi97dgt_1_bh0h66x.pdf --eprofile /Users/jrochkind/.gem/ruby/2.6.3/bundler/gems/kithe-1c73ad400611/lib/vendor/icc/sRGB2014.icc --delete --size 52x1000000 -o output.jpg[Q=98,interlace,optimize_coding,strip]

Created thumbnail fine on my local MacOS! 

Let's try to reproduce manually on jobs-staging, with that file....

    vipsthumbnail /home/jrochkind/oral_history_interview_bi97dgt_1_bh0h66x.pdf --eprofile /opt/scihist_digicoll/shared/bundle/ruby/2.6.0/bundler/gems/kithe-1c73ad400611/lib/vendor/icc/sRGB2014.icc --delete --size 52x1000000 -o output.jpg[Q=98,interlace,optimize_coding,strip]

Odd, works fine on staging too. 

So why did it fail?

**Comment by jrochkind** [comment]
OK, going on prod and trying to create derivatives in the rails console *does* error again. WEIRD. 

    asset = Asset.find_by_friendlier_id!("bh0h66x")
    asset.create_derivatives

```
TTY::Command::ExitError (Running `vipsthumbnail /tmp/shrine20200129-1221-1rcr4be.pdf --eprofile /opt/scihist_digicoll/shared/bundle/ruby/2.6.0/bundler/gems/kithe-1c73ad400611/lib/vendor/icc/sRGB2014.icc --delete --size 52x1000000 -o /tmp/kithe_vips_pdf20200129-1221-z6nbq6.jpg\[Q\=98,interlace,optimize_coding,strip\]` failed with)
  exit status: 255
  stdout: Nothing written
  stderr: vipsthumbnail: unable to thumbnail /tmp/shrine20200129-1221-1rcr4be.pdf
VipsForeignLoad: "/tmp/shrine20200129-1221-1rcr4be.pdf" is not a known file format
```

**Comment by jrochkind** [comment]
Aha, doing manual vips command line on jobs prod *does* reproduce problem. 

```
$ vipsthumbnail /home/jrochkind/oral_history_interview_bi97dgt_1_bh0h66x.pdf --eprofile /opt/scihist_digicoll/shared/bundle/ruby/2.6.0/bundler/gems/kithe-1c73ad400611/lib/vendor/icc/sRGB2014.icc --delete --size 52x1000000 -o output.jpg[Q=98,interlace,optimize_coding,strip]

vipsthumbnail: unable to thumbnail /home/jrochkind/oral_history_interview_bi97dgt_1_bh0h66x.pdf
VipsForeignLoad: "/home/jrochkind/oral_history_interview_bi97dgt_1_bh0h66x.pdf" is not a known file format
```

Apparently something on jobs prod vs staging differs?

vips is 8.5.8 on both machines. hmm.

**Comment by jrochkind** [comment]
Does reproduce error on prod with the much simpler:

    vipsthumbnail /home/jrochkind/oral_history_interview_bi97dgt_1_bh0h66x.pdf  -o output.jpg

Mystery is why vips on prod can't handle that PDF (which seems to be a good PDF), when vips on staging can.

**Comment by eddierubeiz** [comment]
Yes, the command is 

The output of `vips -l ` should be identical on both machines, or else.
See also `roles/dzi/tasks/tasks.yml` in ansible-inventory, which compiles vips against 
'libtiff5-dev', 'libtiff5', 'libgsf-1-dev', 'libgsf-bin', 'libexpat1-dev', 'libpoppler-glib8', 'libpoppler-glib8'. As @sanfordd notes, it's probably a mistake that `libpoppler` is listed twice...

**Comment by jrochkind** [comment]
There is a slight difference between `vips -l` output on staging vs prod. 

```
$ diff vips-l-production.txt vips-l-staging.txt
128a129,131
>         VipsForeignLoadPdf (pdfload_base), load PDF with libpoppler, priority=0
>           VipsForeignLoadPdfFile (pdfload), load PDF with libpoppler (.pdf), priority=0, is_a, get_flags, get_flags_filename, header, load
>           VipsForeignLoadPdfBuffer (pdfload_buffer), load PDF with libpoppler, priority=0, is_a_buffer, get_flags, get_flags_filename, header, load
```

It looks like staging output has those lines, and prod output does not. At line 128...

Confirmed these are the only lines where `poppler` shows up in `vips -l` -- and it shows up on staging, but not prod. 

So something differs between them. Can't explain why other PDFs seem to be processable on jobs prod but not this one, with vips apparently not being loaded with poppler. 

But perhaps trying to rebuild vips on jobs-prod (or rebuild the whole machine?) would make sense?

**Comment by eddierubeiz** [comment]
Quoting from the above mentioned ansible role:
```- name: Check whether vips (with PDF support) is installed.
  become: yes
  shell: vips -l | grep libpoppler | cat
  register: vips_with_libpoppler_installed
```

**Comment by jrochkind** [comment]
I went ahead and took a PDF that is already ingested with a thumbnail. I uploaded the original to jobs-prod unix box, just in my personal home directory. I tried to use a vipsthumbnail  command to make a thumb from it --

Got same error, “not a known file format”. 

So when you say “How is vips doing anything with pdfs if poppler is missing?” — the answer seems to be that it is not in fact able to make thumbs out of any PDF?

Something apparently changed recently on jobs-prod, to somehow make vips no longer have poppler available?

**Comment by sanfordd** [comment]
I'm adding notes from Slack onto this.

Our last successfully run PDF was generated in October 3rd, while the production jobs server was made on November 25th so it is possible we have never been able to actually handle pdfs on production for some reason.

**Comment by sanfordd** [comment]
`poppler` is missing on a fresh build of the production jobs server. I'm trying to build staging to see if it appears there.

**Comment by sanfordd** [comment]
On a fresh build `libvips`'s configure is unable to find `poppler` though Ubuntu does claim the package is installed. I'm going to do further testing.

**Comment by sanfordd** [comment]
I tracked the error down, when fixing the loops in the dzi role the two packages
`libpoppler-glib8`, `libpoppler-glib-dev`
were mistakenly changed to 
`libpoppler-glib8`, `libpoppler-glib8`

without the dev library we can't build VIPs with support for pdfs.

**Comment by sanfordd** [comment]
A fix has been applied to the servers and we're back in business.

**Comment by jrochkind** [comment]
and missing derivatives created too. 

Re opening to leave in 'review' to get credit for it at our weekly meeting. :)
