### ISSUE TITLE
EC2 should not be tagged for capistrano auto-discover until the machine is actually ready

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#608]
Or some other way to keep cap from trying to deploy to a machine that is still in progress of being built. 

@sanfordd says:

> Also please do not deploy to prod.

> A new jobs server is being build and if we deploy it'll throw out an error since it's not done.

@jrochkind says:

> That does point out a problem in our infrastructure setup, that a server becomes auto-discovered before it’ ready, so we need to manually coordinate “don’t do a deploy now”. That’s not great.

The goal should be that under ordinary and expeccted circumstances, we don't need out-of-band manual coordination "don't deploy cause a machine is in process of being built" -- auto-discover should only find machines that are ready. 

Which means perhaps the build scripts should not add the EC2 tag that cap auto-discover uses until the FINAL thing in the build process. (And perhaps should have an option for not adding it at all, when an ops person wants to build a machine  that will not be made available to cap autodiscover?)

**Comment by sanfordd** [comment]
The first should be as easy as moving the hostname role (which handles aws tagging as well [consider renaming]) to the end of the playbook.

**Comment by sanfordd** [comment]
The hostname assignment is now placed at the end of a new machine build.
