### ISSUE TITLE
Redesign homepage to accommodate 9 featured topic categories

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#614]
New categories being added: 
Women and Science
Food Science
People and Portraits

Would it be feasible to add these new categories as the first three at the top of the Featured Topics section?

**Comment by jrochkind** [comment]
> Would it be feasible to add these new categories as the first three at the top of the Featured Topics section?

Sure. We'll have to do a bit of design work to fit in 9.  Probably reduce the size of the featured topic thumbs a bit. the order is totally up to us, no problem.

**Comment by jrochkind** [comment]
We decided to begin with no change in size of thumbs, just another row of 3 more.
