### ISSUE TITLE
Password reset emails from kithe staging server not working

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#62]
Net::SMTPServerBusy: 454 4.7.0 TLS not available due to local problem

## Backtrace

    line 55 of [PROJECT_ROOT]/app/controllers/admin/users_controller.rb: send_password_reset

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/58989/faults/45971333)

**Comment by sanfordd** [comment]
@jrochkind This should be fixed now feel free to try it again. Looks like there was a typo in the config file setting.

**Comment by jrochkind** [comment]
@sanfordd Tried it again, still got an error, a new error this time though. 

`OpenSSL::SSL::SSLError: hostname "localhost" does not match the server certificate`

https://app.honeybadger.io/projects/58989/faults/45978858

**Comment by jrochkind** [comment]
That might not be an SMTP setup problem, but a Rails issue of some kind, hmm. Any thoughts on what might be going on?

**Comment by jrochkind** [comment]
Googling.. @sanfordd , can you advise, do you think we want delivery method "SMTP" or "sendmail"? 

Looks like chf-sufia used "sendmail", but I may not have set it in scihist_digicoll. Will try setting it.

**Comment by jrochkind** [comment]
Yep, telling Rails to deliver with sendmail instead of SMTP worked, to have Rails _think_ it sent the email. Let's see if I actually receive it before closing...

**Comment by jrochkind** [comment]
So the Rails app now thinks it's sending mail without error, but the email never appears. Tried sending password reset email to my own sciencehistory email, and to digital-tech. 

I'm not sure where to troubleshoot this next, do you have any insight @sanfordd?

**Comment by jrochkind** [comment]
It's possible it is being delivered but just being blocked by sendio. My sendio report for digital-tech said "Messages Arived: 1; Messages Accepted: 0."  Hard to say if that was the password reset email. It didn't list it as "pending", it apparently just blocked it?

**Comment by sanfordd** [comment]
I tested it on gmail and it came through (though it was marked as possible spam), for our internal system we can mark it as a safe source of email if we'd like I'll just need to talk to IT.

**Comment by jrochkind** [comment]
Awesome, thanks @sanfordd . Can you talk to Chuck about it? 

Will leave this ticket open until we have emails being succesfully delivered to @sciencehistory.org, as that's where most/all of our accounts actually are. (Or until we alternately decide to use a non-email password recovery/setting mechanism).

**Comment by sanfordd** [comment]
Chuck's whitelisted us, so we're good to go for addresses at the @sciencehistory.org addresses.
