### ISSUE TITLE
Changing status and saving feature not working

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#624]
When changing the status of a digitization queue item and clicking the save icon, status does not change. The status should update to status selected after clicking save, and this is not functioning properly.  I attempted to change/save the status of an item on the [modern library queue page](https://digital.sciencehistory.org/admin/digitization_queue_items/modern_library) as well as the page of the [queue item](https://digital.sciencehistory.org/admin/digitization_queue_items/45).

**Comment by yonyitz** [comment]
I keep trying to select "closed" and it keeps reverting back to "batch metadata completed" which is the old status.

**Comment by jrochkind** [comment]
I think I did reproduce on staging, it does seem to be just plain broken. 

I think maybe that menu is doing nothing at all, no JS is executing at all for it. Not sure why haven't debugged more than that.

**Comment by eddierubeiz** [comment]
The code to fix issue https://github.com/sciencehistory/scihist_digicoll/issues/604 changed the rules we use to determine if a DQ item is "valid". Under the new rules, seven items were invalid -- they were just missing a "Location".

https://digital.sciencehistory.org/admin/digitization_queue_items/38
https://digital.sciencehistory.org/admin/digitization_queue_items/39
https://digital.sciencehistory.org/admin/digitization_queue_items/40
https://digital.sciencehistory.org/admin/digitization_queue_items/41
https://digital.sciencehistory.org/admin/digitization_queue_items/43
https://digital.sciencehistory.org/admin/digitization_queue_items/44
https://digital.sciencehistory.org/admin/digitization_queue_items/45

**Comment by eddierubeiz** [comment]
Meanwhile, when you update a DQ item via the dropdown menu, if the item is not deemed "valid" by the underlying code, the item is left unchanged, and no error message is shown to the user.

**Comment by jrochkind** [comment]
Nice job figuring that out. 

So we'llwant a better error condition for an invalid one -- it shouldn't just completely fail silently, it should at least give you some kind of error message.  For invalid or ANY failure to save. 

And of course we'll have to make those valid (which can be easily done just by entering "not entered" or something). 

Also shows the danger of this kind of validation in Rails, that it's universal -- this is why some people don't like model-level validations!

**Comment by eddierubeiz** [comment]
Yup. See PR 625 for a rough draft of how we could do that. (Albeit I'm not a huge fan of rails-ujs based on the docs I saw today.)
