### ISSUE TITLE
Updates to supporting text on metadata form

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#626]
Nicole is drafting updates to supporting text for fields on metadata form (changing "CHF" to "Science History Institute," expanding on "TBD" fields, etc.). Once the updated text is ready, we'll pass the edits along to Eddie and Jonathan.

**Comment by eddierubeiz** [comment]
OK. These are very easy changes, for what it's worth.

**Comment by yonyitz** [comment]
Please find supporting text updates in spreadsheet below:

P:\Othmer Library\Digital Collections - Internal Access\documentation\supporting_text.xlsm

**Comment by eddierubeiz** [comment]
This can probably go live Monday morning, by the way.
