### ISSUE TITLE
Set permissions on code deploy

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#63]
We'll want to have capistrano set the permissions for our accounts on deploy so we don't need to wait for ansible to run. The command to give full read/write/execute permissions should be 
`setfacl -R -m g:lit:rwX /opt/scihist_digicoll/`

**Comment by sanfordd** [comment]
I'll also need to set ansible to allow our capistrano account to run the command.

**Comment by jrochkind** [comment]
After investigation, we think we may need different ACLs set by ansbile, and _might_ not need cap to do anything on deploy. 

For starters, we think that:

* /opt/scihist_digicoll/shared/tmp
* /opt/scihist_digicoll/shared/log

Both need to have default ACLs for files created in them, such that files created in them are writeable by `lit` group.

**Comment by sanfordd** [comment]
This is now fixed.
