### ISSUE TITLE
There isn't a blank field to select if you need to remove a record from a collection

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#630]
When working on the edit metadata page for a work, one cannot select a blank field to reset the collection information.  So once a collection is selected, there is no way to unselect other than to select another collection name.  It seems the blank entry is skipped as selecting a blank entry should clear the field.

**Comment by eddierubeiz** [comment]
The collection field on the edit metadata form is a multiple select field.
I was able to remove https://staging-digital.sciencehistory.org/admin/works/2b88qc21b from the Pratt collection. I can take a look and help you figure out how to do it in your browser - it probably involves using a modifier key to unselect all selected options.

**Comment by yonyitz** [comment]
Eddie just showed me that if you hold down the control button while using Chrome (button may differ on different operating systems or browsers; could also be shift or space bar), then click on the field you want to deselect to deselect selection.

**Comment by eddierubeiz** [comment]
I would consider this a low-priority bug, if it is one at all.  However, here are a couple ideas we might want to consider:
 *  change this to a regular select dropdown, with a "Remove" button next to it and a link named "Add to another collection" under it. This would be more consistent with the functioning of e.g. the "Additional Credit" field;
 * add some language to the instructions for that field;
 * add a button that unselects all collections.

**Comment by jrochkind** [comment]
The reason it's a multi-select field is because the data model supports a work being in more than one collection. 

However, if we don't use that in our app and are fine with the UI not supporting it, we could change it to a single select. We may have to do a bit of controller-side code to make it work, since it might result in a different data structure than the many-to-many association is expecting.

**Comment by HKativa** [comment]
We've chosen to document the workaround in the supporting text for this field and our cataloging documentation rather than undertake any development work. Thus, I am closing this issue!
