### ISSUE TITLE
Digitization queue status menu throws error

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#631]
At e.g. https://digital.sciencehistory.org/admin/works/kasznnp
Attempt to change the status
You will see a JS error alert.
However, the item's status *is* changed, as is apparent if you reload the page.

**Comment by jrochkind** [comment]
Is this HB error the same thing? Or different? https://app.honeybadger.io/projects/58989/faults/60952006

**Comment by eddierubeiz** [comment]
Yes, the HB error is the same.

**Comment by eddierubeiz** [comment]
This is fixed in production as of Wed. afternoon.
