### ISSUE TITLE
Make RAILS_ENV=production default shell env on kithe servers

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#64]
On our deploy servers, we never really want to run any Rails command as anything but `RAILS_ENV=production`. If you forget to do this, when manually doing or testing things or trying to use rails console, it's a confusing error. (currently yarn complains about dependencies not installed). 

Is it feasible to have the ansible machine setup do whatever is the most maintainable thing to make sure that shell env is set in `digcol`, `ubuntu`, and all user accounts?  In an appropriate dotfile or whatever is the best way to do this. Only needs to apply to interactive/login shells, I _think_, although probably just fine if it applies to more, in case there is a difference. (I know just enough about OS env to be dangerous). 

I am asking for this only on `kithe` hosts, but if because of shared ansible setup it is easiest to make it apply to v1 chf-sufia hosts too, that is just fine. If it's easier or less risky to existing production to make it apply only to v2 kithe app hosts, that's fine too.

**Comment by sanfordd** [comment]
Definitely easier to do it in both, it's been put in for all login shells and added to be passed through when you run commands as sudo. That should cover every likely use case.
