### ISSUE TITLE
Detect and warn IE users that we don't support IE and it may or may not work?

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#642]

**Comment by jrochkind** [comment]
@MDiMeo or anyone else, let me know if you have any thoughts on where to put the I’m not sure where to put the “warning we don’t support IE and you are on IE” warning…

Should the "you are on IE and we don't support IE" warning be something you can "dismiss" and never see again even if you keep using it on IE? Or should it show up at the top of every page as you continue to use IE?

We already have a pretty annoying “consent to use cookie” popup showing up on the bottom of the screen for all new users. (We sometimes forget since most of us don’t see it very often). 

I guess it could go, like, on top of that covering it up, so first you click “ok” on IE, and THEN you get the "consent to cookies" warning underneath them. 

Trying to "stack" them one on top of the other is a bit of a technical challenge.

**Comment by jrochkind** [comment]
I think some people said they saw these IE warnings on other sites and appreicated them — if you have an example, I could copy it!

The *easiest* thing to do might just be a Javascript `alert` popup, but it is very ugly and will annoy users it triggers for. (Which we intend to be only IE users, but it can always misfire). So maybe not that.

**Comment by jrochkind** [comment]
Reliably determining browser can be tricky. It is done from user-agent header. 

MDN article https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

There are ruby gems that try to encapsulate the logic for you. 

* https://github.com/fnando/browser => I don't love that it patches a `browser` method into your rails controllers
* https://github.com/gshutler/useragent  => older, simpler, less well documented.  But not maintained so doens't include "edge" for instance. While we don't need edge here... might as well use the maintained one? in case we need more func later, being maintained makes it less likely to have a performance bug or something, etc.

**Comment by jrochkind** [comment]
Note that MS Teams stopped promising it would work with IE in November, and the entire MS 365 suite will stop promissing it will work with IE in August 2021. 

I wonder if they will provide an on-screen notice... 

We don't have access to Microsoft Teams so I can't actually check to see.

**Comment by MDiMeo** [comment]
Yes, I'm someone who has seen this warning, but I cannot remember which sites I've seen it on (and don't have IE anymore anyway to double check it now.) But if my memory serves me correctly, it was on the top of the screen. So yeah, there'd be a bar you have to click out on the top and the bottom, but maybe that's better than two stacked on the bottom. A Javascript pop-up could also work, especially since we don't really care if we annoy them. The point is to tell them the site probably won't work well for them.
