### ISSUE TITLE
combined audio derivative: admin UI 

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#648]
We need UI to create the combined derivative.  There's some placeholder stuff on teh screen here:

https://digital.sciencehistory.org/admin/works/wh246t17v#nav-oral-histories

It should tell you if combined derivative(s) are already created. (Prob verifying we have both of the formats expected). 

It should tell if you if the 'fingerprint' is fresh, maybe putting a big alert in red if it's not. 

It should give you a button (re)create, which kicks off a bg job to create the combined derivs and record them and their metadata in the db. 

* Bg job should remember to delete the Tempfile when it's done with it -- while you can get let ruby GC take care of it, more efficient to do it if you know you're done with it. See https://ruby-doc.org/stdlib-2.4.0/libdoc/tempfile/rdoc/Tempfile.html#class-Tempfile-label-Explicit+close

Anything else you can think of?

**Comment by eddierubeiz** [comment]
I have a basic version of this working. There isn't much of a way for a regular user to find out if the bg job fails for any reason. However, once we mass-create the combined audio derivatives, requesting one to be generated or regenerated will only happen once in a while, so this might not be a huge problem.

**Comment by jrochkind** [comment]
> There isn't much of a way for a regular user to find out if the bg job fails for any reason.

That's true of all our derivatives, really, so may not be a requirement for first pass. 

Although I could imagine adding a column to the oral_history_content table where error information is recorded, if it happens. But rescuing errors to reprot them could interfere in odd ways with things we might do in the future to eg auto retry failed jobs etc.

**Comment by jrochkind** [comment]
> Are you sure? This could take several minutes.

This made me wonder if it was going to occupy my browser for several minutes preventing me from doing other stuff, which of course is not true. 

Under what circumstances would you imagine a staff user confronted with this warning deciding that no, after all, they didn't really want to do it? (because it would take several minutes?).

**Comment by eddierubeiz** [comment]
Excellent point. Will remove the warning.

**Comment by jrochkind** [comment]
Looking at stuff in the staff UI as I sit at Code4Lib. 

Right now, both webm and mp3 are presented, as links on the word. 

I think maybe the user doesn't need webm at all, but I think they need MP3 in a more clear and usable way, such as:

> Use this URL as the OHMS Media URL:
>       http://......

(Make sure you generate that url with `url(public:true)`, since that guarantees a non-expiring S3 URL without a `?` in it, which OHMS insists upon to work!)

Make it easy to copy to clipboard for pasting (could even put the URL in a read-only text input, which can be easier to copy if done right), provide instructions telling them what to do -- no reason user should have to know it's the mp3 they want, and the webm they don't want for anything, when we can just tell them in the interface.

**Comment by jrochkind** [comment]
Also I see once I generate it, I don't get a button to re-generate it. Maybe I would if the fingerprint were judged out of date?

Maybe just give the button anyway, maybe you think it's corrupt in some way and want to re-generate it anyway or whatever? Or not, maybe this doesn't matter.

**Comment by eddierubeiz** [comment]
> Also I see once I generate it, I don't get a button to re-generate it. Maybe I would if the fingerprint were judged out of date?
> 
> Maybe just give the button anyway, maybe you think it's corrupt in some way and want to re-generate it anyway or whatever? Or not, maybe this doesn't matter.

It's checking the fingerprint before showing you the button. I could easily remove this; don't feel that strongly about it either way.
