### ISSUE TITLE
Modify audio player front end to use the new combined audio derivatives

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#649]
To follow up #648

First:

* Create "combined audio derivatives" for all existing OH audio works
  * This could be very time-consuming to do for all OH works, we'll have to see and see if we need to do special thigns to speed it up, like a special jobs server working only on that in parallel or something. 

Then we need to move the UI over to USE them. 

* audio player should load the combined derivative
  * If it's not available, a "Sorry not available" message of some kind, maybe even "Administrator: You need to create the combined derivative", maybe guarded behind a "if logged in user is admin". 
* Clicks on individual download tracks should advance to that portion of the combined derivative, as recorded in the metadata on the oral history content, that was created with the combined audio derivative. 
  * No need for the 'now playing filename" line currently in the player, that gets swapped every time you click on a different link -- just eliminate that whole area. Click on a download filename is just a 'seek' operation. 
  * No need for highlighting the now playing track in the list either I don't think, the JS gets significantly simpler, just a seek!  (Maybe the time to seek to is put in a data attribute on HTML generation? actually maybe can use the same JS that is doing seeks for transcript/index! Oh, except that's not merged yet, so I dunno)

After THAT is done and merged and released, 

* Remove code that creates existing single-file webm derviatives, and delete all existing webm single-file derivatives. Cause we're not using them anymore, they were only used for the player. 
* The single-file mp3 derivatives are currently being offered as downloads -- need to talk to stakeholders about if we should retain these as a download option, or get rid of them too.

**Comment by eddierubeiz** [comment]
Sample code to generate all combined audio derivatives:
```
require 'ruby-progressbar'
progress_bar = ProgressBar.create(total: Work.where("json_attributes -> 'genre' ?  'Oral histories'").count, format: "%a %t: |%B| %R/s %c/%u %p%% %e")

Work.where("json_attributes -> 'genre' ?  'Oral histories'").find_each(batch_size: 10) do |w|
  progress_bar.log("INFO: Starting #{w.title}")
  CreateCombinedAudioDerivativesJob.perform_now(w)
  progress_bar.log("INFO: Done with #{w.title}")
  progress_bar.increment
end
```

**Comment by eddierubeiz** [comment]
Creating all the combined audio derivatives in production should take roughly 36 hours.
In staging, roughly 24 hours after kickoff, most of them are done:
```
irb(main):013:0> Work.where("json_attributes->'genre'?'Oral histories'").count
=> 228
irb(main):014:0> Work.where("json_attributes->'genre'?'Oral histories'").count {|oh| oh.oral_history_content&.combined_audio_fingerprint.present? }
=> 194
```

**Comment by jrochkind** [comment]
I just remembered one danger of doing this is that we use up all our "burst" credits on the EC2 instance, making jobs have trouble for a while in the future. Should we be concerned, @sanfordd ?

(This also means that it may take longer than you think based on past progress, as it will start going a lot slower once burst credits are gone, which they may or may not already be).

**Comment by sanfordd** [comment]
@jrochkind Checking our usage, the combined audio caps out at around 60% usage with a few spikes. After running 24 hours we're pretty far down but not entirely out of burst credits yet. We might get through most of it, and when we do run out we throttle to about 30% CPU max so the remaining content will take about twice as long.

**Comment by eddierubeiz** [comment]
OK. I'm sufficiently convinced that the process is working in staging, so I killed it. Happy to restart if needed, but I don't want to use up any more credits.

**Comment by jrochkind** [comment]
Well, we need to decide if this is an okay way to do it, using up all our burst credits on our existing jobs server. 

If that's fine, there's no reason not to finish it on staging, and then do it on production too.  (Does your process have a way to re-start, only creating missing ones, not re-creating existing ones? If not, that would be a good tweak). 

@sanfordd, can you just decide this for us? Should we not worry about it and just go ahead and use all burst credits on both staging and production? (I am not sure   how negative the consequences of that are in our actual practice). Or should we figure out an alternate approach? 

I suppose the simplest alternate approach is just spinning up a temporary server that has the app on it, but does not have any jobs workers running on it. Then we just run the derivative building there, then shut it down when it's done. Not sure how hard that it is for us to setup, not sure of cost. 

Neitehr approach is probably likely to be disastrous; @sanfordd, I think you know the most about the context here needed to decide, can you just decide for us what we should do?

**Comment by eddierubeiz** [comment]
It skips oral histories that already have up-to-date combined derivs. (see above.)

**Comment by eddierubeiz** [comment]
All derivatives have been created as of 12:39PM today. So it should last roughly 24 hours in production as well.

**Comment by eddierubeiz** [comment]
Lee noted at yesterday's tech meeting that we should estimate the size on disk of the biggest single-file derivatives before turning off the per-segment derivative downloads.
