### ISSUE TITLE
Audio file characterization: store duration

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#652]
We should consider calculating and storing duration for audio files, in addition to size and content type.

Nice to have would also be basic stream info like:
`sample rate:44100 Hz, mono, fltp, 32 kb/s`

If we do this, the combined audio derivative creation process can be simplified somewhat.
Specifically, `app/services/combined_audio_derivative_creator.rb` contains a method `duration_of_audio_file_in_seconds` which we will no longer to invoke, as we will have stored the duration of the file at ingest time.

**Comment by jrochkind** [comment]
What's "fltp" mean?

**Comment by eddierubeiz** [comment]
Low-level metadata about how the numbers are actually stored, looks like -- https://www.metadata2go.com/file-info/sample-fmt .

**Comment by jrochkind** [comment]
For what Rails (as of recently) does, see: https://github.com/rails/rails/pull/42425

it might make sense to base off Rails implementation, in terms of what metadata is captured, or even actual implementation with ffprobe.

**Comment by eddierubeiz** [comment]
No, we're not doing it. I still think this is a good idea, but I'm also fine if we don't do it.

**Comment by jrochkind** [comment]
Aha, right, it's coming back to me now! Cool. 

Me and @apinkney0696 were just reviewing some of the backlog.
