### ISSUE TITLE
Review what we log

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#654]
Assess what we're currently logging and need to store for both metrics and troubleshooting purposes. 
Related to #637 #569

**Comment by sanfordd** [comment]
From our conversation, we have decided that (for developers) the application logs are the primary need. We do prefer INFO level logging, but want to make the logs cleaner, this now relates to #656

There's some distant potential for interest in Redis/Postgres logs, but on the developer side as well.

**Comment by jrochkind** [comment]
I think we've already done some of this, and don't need to do any more at this particular moment. 

(production log level is currently :info)
