### ISSUE TITLE
Add lograge to application

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/scihist_digicoll#656]
Add the lograge gem: https://github.com/roidrage/lograge
This is to reduce the noise of our logs to something more manageable for technical staff to review logs.

**Comment by jrochkind** [comment]
also configure to include user-agent in action logs

**Comment by jrochkind** [comment]
An alternative to lograge is semantic_logger:

https://github.com/rocketjob/rails_semantic_logger

**Comment by eddierubeiz** [comment]
[Semantic logger docs]( https://logger.rocketjob.io/) looks awesome.

**Comment by jrochkind** [comment]
* lograge
  * benefits:
     * can optionally log in a JSON format, which additional log aggregating tools increasingly can understand as structured data 
     * looks pretty customizable
     * Rails-focused
     * seems popular/maintained. Other third party log aggregator services sometimes mention/suggest lograge. 
  * possible disadvantages:
      * in default situation, it doesn't actually even log the complete URL requested, only the path component not query component! That seems weird to me. Also may leave out other things we need. May need substantial config to work for us. 
       * they seem to not want you to log errors, unclear how errors show up in logs, may be hard to associate error in logs with corresponding request

* semantic_logger
  * benefits:
     * also very customizable
  * possible disadvantages:
     * not Rails-specific, which is good if you need that (we don't), but possibly makes it more complicated/confusing to set up for Rails specifically, since it's not Rails-focused. 
     * seems to be less popular
     * also may need custom setup to make sure it's logging everything we want
     * like lograge, anything that collapses each request to one line may make it hard to correlate errors to request they correspond with -- usually you have a logged 'start of request' and 'end of request' which the error in between but with only one logged line, you need to associate error (or any other warn/error log messages) with a subsequent logged request line I guess?

**Comment by jrochkind** [comment]
We've done some other things to reduce logging somewhat, although not as much as lograge. See #906. For now, we don't necessarily want to do lograge, let's close this.
