### ISSUE TITLE
Only create combined audio derivs from public members

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#660]
Three related changes:
* Make sure only public members are used to create **combined audio derivs**
* Make sure only public members are used to create **the fingerprint for combined audio derivs**
* Do not show the audio tag on the front end if the fingerprint is out of date.
This ensures we don't inadvertently show the public any chunks of an oral history that were marked private.

**Comment by jrochkind** [comment]
Ah good call thanks! Moving this to "ready" in Zenhub by executive decision. :)

**Comment by eddierubeiz** [comment]
Yup. It's really part of this week's work.

**Comment by eddierubeiz** [comment]
Discuss how to prevent users from making audio unavailable without knowing about it.

**Comment by eddierubeiz** [comment]
Should the combined audio only be created on publish?

**Comment by jrochkind** [comment]
> Should the combined audio only be created on publish?

I think that's a different issue, right? I would suggest keeping these things separate in smaller steps. 

For completing this issue, combined audio is still created only by manually clicking the button. But it is created only from 'public' members; and it does not show up in public UI if it is 'stale', users should get the existing "not available" message in that case. (I include that in this issue cause you suggested it should be). 

Can you prepare a PR that does only those things, without changing from our current "create combined derivative on manual button press"?

It's always better to have smaller more focused steps, and PRs.

**Comment by eddierubeiz** [comment]
Yeah -- shouldn't have put that here. Agreed: different issue, though related.
