### ISSUE TITLE
Don't allow a user to publish an oral history until / unless there is an up to date combined audio deriv.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#673]
First of several adjustments we'll probably need to make now that we're using the combined audio derivatives in production.

**Comment by jrochkind** [comment]
I think the other half is "don't let staff edit anything that would invalidate a combined derivative, for a published audio oral history."

Those two things might take care of it all nicely?

**Comment by eddierubeiz** [comment]
That is a very good idea.

**Comment by eddierubeiz** [comment]
Very good.

**Comment by jrochkind** [comment]
The implementation is going to be a little bit tricky to get right and reliable though, I'm afraid.
