### ISSUE TITLE
Combined audio derivatives: keeping users posted about the status of these background jobs.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#674]
The combined audio derivatives take a while to complete (often well over 10 minutes.)
We already have them running in a background job. What are some ways we could let users know what state the job is in? Is it:
- Not started yet?
- Started, not complete yet?
- Started, but failed?
Could we provide the user with an estimate of how long the job might take?

**Comment by eddierubeiz** [comment]
@jrochkind  suggests:
"we could add a ‘status’ column to OralHistoryContent.
Set it to “queued” when queuing a job; “in progress” when the job starts; and “complete” or “error” when it’s done or errored.
Then we could show that status on the admin page."

**Comment by eddierubeiz** [comment]
Other idea: keep users posted on start, success or failure via email.

**Comment by eddierubeiz** [comment]
Or just encourage users to check the job queue ?

**Comment by jrochkind** [comment]
I don't expect the job queue is a usable UI for... really anyone, definitely not anyone that's not a developer. Not even totally sure it's possible to identify from a large queue which job corresponds to what thing. 

I don't think emails are much easier and are I think a very substandard UI.

**Comment by jrochkind** [comment]
We could look into/discuss using a 'generic' ActiveJob solution for tracking job status.
