### ISSUE TITLE
OHMS Front End: Scroll behavior when switching tabs while audio is playing (wishlist item)

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#696]
This changed to a 'jump to text' button. 

----
It would be extra spiffy if, when you switch to the TOC or the Transcript tab **while the audio is playing** it drops you as close as it can to where you are in the audio.

Jonathan notes: That’s a pretty complex feature. It might or might not be possible to make it work well with the one or two minute timecode granularities we have. It’s not going to be done for this initial release, but we could consider it in the future.

**Comment by jrochkind** [comment]
@MDiMeo @lsberry16  as I start implementing this... I'm honestly still a bit worried about the usability of it. I think users might find themselves confused about why the scroll is jumping around, find it jumping when they don't want it to and not jumping when they do want it to. 

I wonder if we what *really* want is a checkbox "scroll to match audio" which would try to constantly scroll along in transcript and/or ToC (harder to implement), or a button "jump to audio now" (easy but not sure where to put it on screen) -- tying this behavior to tab-switch when audio is playing (not paused) just doesn't seem right to me...

But I could be wrong, Lee may understand the use case better!

Either way,  I'll try to get it implemented and then we can look at it! I will suggest we spend some time examining it though before just making it live.
