### ISSUE TITLE
Tell the index (and search/filter UI) which works have OHMS

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#707]
Should our user interface for searching and filtering distinguish between works with OHMS metadata and ones without?

Some possible use cases:
- A staff member wants a convenient way to tally the proportion of works that have been OHMSed.
- An educator is browsing through the oral histories to use as the basis for an assignment on a particular topic. Among the search results for that topic, s/he would prefer an OHMS one over a non-OHMS one.
- We are presenting our work at a conference and want to post a QR code to the screen that takes people's cell phones to a list of the latest OHMSed works.

**Comment by lsberry16** [comment]
I think this would be helpful in those situations, for sure. Also, it would be lovely if the button we use on the microsite to link to the Digital Collections record could give a heads-up to users if there's a synchronized transcript/index over there.

**Comment by jrochkind** [comment]
I have wanted this... but I can't figure out where it would go. Adding a whole additional facet to the search results that only applies to oral histories doesn't seem right. 

It makes me think again of the idea to have a separate search form with OH-specific features -- like on the OH collection page. We didn't really like that idea, but it's the only way I can think of to support things like this that really only apply to OH. 

> Also, it would be lovely if the button we use on the microsite to link to the Digital Collections record could give a heads-up to users if there's a synchronized transcript/index over there.

Unfortunately I think that's just up to you to do manually one-by-one on the microsite, @lsberry16. I agree it seems a good idea. Also maybe indicate whether audio or PDF or both are available. 

we aren't familiar with the internals fo the microsite so I'm not sure, but I suspect there's no way make it happen automatically, so not sure how feasible it is to have someone manually updating microsite pages. If it is, we can try to help design what it should look like, if that would be helpful.

**Comment by jrochkind** [comment]
There are related things to this already on our 'brainstorm' list -- a similar one is, even without a 'limit' to restrict to just ones with OHMS content -- should a 'hit' in a result list tell you fi it's got just PDF, or also Audio, or also OHMS synchronized transcript? Already in the brainstorm list.

**Comment by jrochkind** [comment]
We did this!
