### ISSUE TITLE
UI to remove uploaded XML file from oral history record

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#708]
I uploaded Alyea's XML file to the Digital Collection site and then realized the italics in a segment title didn't display properly (separate issue). I was going to take it back down off the site while I fixed the XML and then reupload, but I don't think there's a way to take it back down once I've added it. (Maybe I missed it, though.) We may need to be able to do that easily in the future.

**Comment by jrochkind** [comment]
Yes, there should be a way to remove XML files, I agree. 

For now I will go this manually on the back-end for Alyea record cf95jc49c ...  removed!
