### ISSUE TITLE
OHMS Front End: Italics, bold, underline display in table of contents Segment titles 

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#709]
One of Alyea's segment titles ("Quantum Mechanics Publication Run in Russia") contains a book title ("Quantum Mechanics") which Nicole had put italics coding around (<i></i>) which displayed correctly in the standard OHMS viewer on preview, but which didn't get parsed correctly by our custom viewer. I just removed the italics coding and reuploaded the XML without it, but we might want to consider whether we need this functionality in the custom viewer.

**Comment by jrochkind** [comment]
Can you give us examples or a link to OHMS documentation explaining how you encode italics, bold, or underline in OHMS metadata?  Need to know this in order to get our software to mimic it. Thanks!

**Comment by lsberry16** [comment]
You'll have to be able to log into OHMS to see it, I think, but here's a test I did that shows that italics and underlining do show up in segment titles in the standard OHMS viewer:

https://ohms.uky.edu/preview/?id=89981

I tried attaching the exported XML file here, but that didn't work, so I'll send it along to @jrochkind as an email attachment for him to look at.

I attached the test XML file to the record for Gerald Weissman in staging--the tags show up, they don't do the formatting work:

https://staging-digital.sciencehistory.org/works/1z40kt98n#ohToc

**Comment by jrochkind** [comment]
Great, confirmed that OHMS is just putting `<u>`, `<b>`, and `<i>` tags in text. 

We just need to preserve those as HTML.

**Comment by lsberry16** [comment]
Actually, I manually entered those xml tags when I put in the title. It’s just that the standard ohms viewer seems to know to parse them correctly. I could try manually entering them as html tags instead, if that’s easier.

Sent from my iPad


__________________________________

Lee Berry   (she, her, hers)
Curator of Oral Histories
Center for Oral History
t. +1.215.873.8251

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
Learn about the scientific discoveries that changed our world without leaving home at sciencehistory.org/learn<https://www.sciencehistory.org/learn>

On Apr 19, 2021, at 1:13 PM, Jonathan Rochkind ***@***.***> wrote:

﻿

Great, confirmed that OHMS is just putting <u>, <b>, and <i> tags in text.

We just need to preserve those as HTML.

**Comment by jrochkind** [comment]
Underline and italics I can make work, no problem. 

Bold... the section title is already being displayed as bold in our formatting, at the highest bold level for the font. 

So... I can make it so it doesn't actually show up as bold, but at least the `<b>` tags aren't visible...

OR, I can investigate reduce the bold level of the ordinary title, so actual internal bolded phrases can be bolded. I'll spend some time with that, see if I can make it look good?

**Comment by lsberry16** [comment]
I thought that was what was happening with bold. I'm actually not worried about bold. We really want italics, for titles of works. Let that go; although making sure the tags (if they get entered in error) don't show up is definitely good.

**Comment by jrochkind** [comment]
OK, conversation with Lee confirms -- the OHMS editor doesn't do anything special to support formatting on entry, staff is just manually entering `<i>` in section title in OHMS editor. 

Then the OHMS player does not escape or remove it, it allowed it through. 

And that `<i>` is really the only one we know we have a use case for. 

challenge here is making sure something sane happens if section title needs to include a `<` that isn't meant to be an HTML tag... let's see what ohms editor does in that case...  

OK, standard OHMS is just passing text to browser exactly as is, malformed or improperly escaped HTML and all, and allowing browser to try to recover. While this does result in `<i>` tags being passed through correctly and the browser manages to do the right thing for improperly unescaped `<`.... it's not really good practice. 

I'll mess around with tools in Rails and see how close I can get.

**Comment by jrochkind** [comment]
OK, the Rails::SafeListSanitizer will get us reasonably close enough to existing perceived behavior, we're good.

**Comment by jrochkind** [comment]
The actual out-of-the-box OHMS player will let you do things like enter `<p>` tags or `<table>` tags, and totally disrupt the page. We won't go that far. :)

**Comment by jrochkind** [comment]
To begin wtih, the code just allows `<i>` tags, because that's what we have a known use case for. We can add other simple tags to the "allow" list easily.
