### ISSUE TITLE
Set Asset "filename" to FileSet original filename.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#72]
Also update the audit to reflect this.

**Comment by eddierubeiz** [comment]
Done and pushed to import_from_chf_sufia. Audit checks for this too.

**Comment by jrochkind** [comment]
@eddierubeiz in the new thing at least, the `filename` and `label` are different things, that can be different. (the `label` is `title` in the new thing). 

Are we sure they aren't different in the sufia app too? I thought they were. A FileSet title, vs maybe some metadata on the `File` object in sufia?  I _think_ sufia has these two distinct things too. The `filename` ends up the name of the original file that was ingested when it was ingested, and can't be easily edited in the UI, whereas the title/label is easily editable in the UI. 

I _think_. Maybe?

**Comment by eddierubeiz** [comment]
Did a bit of investigating; it turns out they start out the same (the ingested file's name) but you can change the title, not the label.

- Start here: https://staging.digital.sciencehistory.org/concern/file_sets/f4752h708/edit
- Original: "b1050249x_003.tif"
- Click "Edit this file"
- Change the title to "Changing the title".
- Click "Update attached file."

You now have:
```
FileSet.find('f4752h708').label
=> "b1050249x_003.tif"

FileSet.find('f4752h708').title
=> ["Changing the title"]

FileSet.find('f4752h708').files.first
=> #<Hydra::PCDM::File uri="http://some/uri" >

FileSet.find('f4752h708').files.first.file_title
=> []

FileSet.find('f4752h708').files.first.file_name
=> ["b1050249x_003.tif"]
```

**Comment by eddierubeiz** [comment]
```
FileSet.title   ---->  Asset.title
FileSet.label ---->  Asset.filename
```

**Comment by jrochkind** [comment]
Right on, that matches my memory. 

So need to improve the export/import code to treat these distinctly. 

Also, _importantly_, the audit code to make sure that all FileSets have good matches for both values in the created Assets.

**Comment by jrochkind** [comment]
"label" is a _super confusing_ thing for sufia to call it. i'm still really confused. 

_Just in case_, I wonder if you want to export `files.first.file_name` instead -- except it's not `files.first`, it's going to be something involving the `original_file` method, `original_file.filename`. It may be that `label` always matches `original_file.filename`, but I'd feel more comfortable using `original_file.filename` directly.

**Comment by eddierubeiz** [comment]
Fixed in branch https://github.com/sciencehistory/scihist_digicoll/tree/import_from_chf_sufia .
This includes update to the audit.
