### ISSUE TITLE
Reconcile created_at and date_uploaded.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#73]
The two values are currently *almost* correct, but we need to get them exactly correct, along with time of day and timezone.

Add this to the audit when complete.

**Comment by jrochkind** [comment]
I think this has been done and it's all good? If not, can you provide more info or example data for which it fails or a failing test case?

**Comment by eddierubeiz** [comment]
I think this is complete but I want to double-check and possibly add comments to the code before we close the ticket.

**Comment by jrochkind** [comment]
@eddierubeiz is this complete?

**Comment by eddierubeiz** [comment]
Yes. The audit code documents the mapping:

```    unless metadata['date_uploaded'].nil?
      if item.created_at.nil?
        report_line("Missing created_at")
      else
        confirm(item.created_at == DateTime.parse(metadata['date_uploaded']), "created_at")
      end
    end

    unless metadata['date_modified'].nil?
      if item.updated_at.nil?
        report_line("Missing updated_at")
      else
        confirm(item.updated_at == DateTime.parse(metadata['date_modified']), "updated_at")
      end
    end
```
