### ISSUE TITLE
Thumbnail image for sharing OH content on social media

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#731]
Apparently we don't have a thumbnail image assigned to our oral history content on the Digital Collection for when we share it on social media (or at least Facebook). Do we want to select something other than the default institution logo that shows up now?

**Comment by jrochkind** [comment]
Lee writes in Slack:

> I don't HATE that, but better would be nice. I'm not sure what we pick or what goes into making it the image that goes along with our oral history content. I filed a GitHub issue and we can figure it out. Thanks!

"we" can probably do whatever we want, i"m not sure what is best. Things i can think of are:

1. A better Science History Institute logo. The one it's taking now is white on transparent background, and is just something facebook found that our page is using as a 'watermark' style on the banner, it wasn't meant to be used like this!

2. A logo representing the Center for Oral History. I'm not sure the Center has it's own logo though? A graphic of some kind could be made. 

3. Any sort of graphic we want to represent "oral histories". Compare to the photo used on the [Center web page](https://www.sciencehistory.org/center-for-oral-history) or [oral history digital collection](https://digital.sciencehistory.org/collections/gt54kn818).  Some variation of that formatted to proper size and aspect ratio for facebook could be used. Or we could find appropriate staff (internal or external) to create a different illustration, whether a photo illustration or icon. Or we could find some existing free or licensed image to use. 

Alternately, we could get into a more sophisticated feature that let individual per-oral-history thumbnails be uploaded. Say a portrait of the subject, or other relevant historical photo. 

This would be a more complex feature to develop, especially if we'd want to use that custom per-OH thumb internally to the digital collections app too. It would also require more work on the metadata side, as someone would have to find/select and upload such a thing. I'm not sure we want to create more work on the metadata side, when there is already a large backlog. It might be better to use a generic thumb for all OH's. 

The idea of a per-OH thumb does relate to an idea in our feature brainstorm, to support ingesting graphical content associated with an OH, such as portraits. If we wanted to pursue that for reasons other than thumbnails too, it might make sense to use it for thumbnails as well.

**Comment by jrochkind** [comment]
What it looks like now when shared on facebook:

![Screen Shot 2020-04-28 at 2 29 20 PM](https://user-images.githubusercontent.com/149304/80532967-e9c8a180-896a-11ea-8485-13992686484c.png)

(Other social media shares may be different. If we fix it for a desired image, we could make it consistent accross at least the current social media we are targetting, including twitter, and probably others that use standard mechanisms. Right now we're just kind of leaving it up to the social media site or other re-publisher to guess).

**Comment by jrochkind** [comment]
Oh, and the current facebook situation isn't even reliably that, sometimes I am just getting entirely "invisible" image. 

If we care about what these look like shared on FB at all, we should do something intentional with it.

**Comment by jrochkind** [comment]
The logo that's showing up now is not reliable, sometimes it shows up and other times it doesn't. 

But we could use a standard Science History Institute logo here. Or the image we use as a thumbnail for the Oral History Collection. 

![ohcol.jpeg](https://images.zenhubusercontent.com/5d81444759191331a1462f18/558f2063-9f8d-4a70-bb19-d294fea85bcd)

Those are the two things I  can think of we have available (we could use anything else someone produced too of course). Anyone have a preference for which? @MDiMeo @lsberry16 ?

**Comment by jrochkind** [comment]
The very long and high-res one that's actually the banner on oh.sciencehistory.org right now works pretty well. 

twitter:
![Screen Shot 2021-04-26 at 4 46 55 PM](https://user-images.githubusercontent.com/149304/116148685-35617880-a6af-11eb-8103-81cae3178eb6.png)


facebook:
![Screen Shot 2021-04-26 at 4 46 17 PM](https://user-images.githubusercontent.com/149304/116148687-35617880-a6af-11eb-9897-4979e48f0d99.png)
