### ISSUE TITLE
Oral history transcripts searchable in digital collections search

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#738]
Current To do: 

- [x] Do not deploy this until we have fixed HTML showing up in imported searchable transcripts. 
   * not only do we have to strip HTML tags, but possibly replace `&nbps;` with something reasonable. 
   * #797
- [x] Do not deploy until we've fixed too large full text snippet excerpt, for instance search for "christianity", look at Nico M. Nibbering hit. #794 
- [x]  deal with weird characters (up arrow?) from some of the imported fulltext, around back-of-the-book index terms
   * looks like the weird char is `0x0C`, or ascii "form feed" -- at least in our pg database, not sure if it gets turned into something else when we index it into Solr, from which it's ultimately displayed. Not sure why it shows up as an arrow on some browser/OS. Our best move is probably to strip control characters on input, or at least control characters except for LF and CR?
  * #797
- [x] reindex transcripts in *production* with fixes in #797

https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/846397441/Priorities+for+the+Next+Stage+of+Development+Work

* Includes OHMS-enabled and non-OHMS-enabled -- so we'll have to add another input field for transcript plain text. 
* Search results should give you the 'hit in context' like microsite does. 
  * This involves a new feature in search results, although it only applies to OH content. We'll have to figure out how it should look on the page
  * The implemention will use the Solr [highlighting](https://lucene.apache.org/solr/guide/8_2/highlighting.html) feature. I haven't used that one before, it might take some work to figure out. We will probably want to put these results in their own Solr field, so we can use taht field for highlighting
  * This is tricky becuase our display right now is using only the ActiveRecord postgres model for results. We'll need ot make sure the relevant template is getting the solr response too, and can use it for solr highlighting return results. 
* We'll have to pay attention to how this effects relevancy results in our general search, to have some items with "full text" in the Solr search index, and other items with only metadata
   * There is a danger it will make OH items show up "too well", always being on top of search results; or "not well enough", hardly ever getting full text OH matches. Have to figure out the right balance
   * This can be hard to figure out when we don't *have* the transcripts in there yet to test. So we may want to figure out a way to *automate* import of existing full text from the microsite, so we can actually test it all in staging ASAP (as well as save all that manual labor)
   * We may want to ask other peer institutions if anyone has handled mixed fulltext/metadata-only content in Solr/blacklight, and any tips they have or lessons they've learned 
  * If we *had* to in order to avoid messing up our general search, we could make fulltext only searchable in an OH-specific-search, but we don't want to do that. 

### Future

Once we have plain text pasted in for searching, we *could* deliver it to users (perhaps for accessibility?)

If you want it to be google-searchable it probably would have to be on a page somewhere. 

These would be for some other ticket, not this ticket.

**Comment by jrochkind** [comment]
Okay, here's some steps for getting *transcripts* searchable. Each of these can be done separately (even in parallel by different people), and each but the last can be committed to master and deployed as done. 

1. add a field to the OralHistoryContent for plain text searchable transcript text. This will be used when OHMS XML transcript is *not* available. 

2. bulk migrate all plain text searchable transcript text from OH microsite. 
 
3. Get transcript text *indexed* into solr
  * OHMS xml transcript text if present, otherwise new plain text searchable transcript text field
  * should be in a field that can be boosted lower than anything else. Probably a new field. 

4. Get solr *searching* it
  * should be boosted less than anything else, may have to adjust boosts on present fields (possibly rename some) to allow room at the bottom for something less
  * need to figure out how to use solr search highlighting in our app, to show hit highlights in results for this field
  * this is the only one that should not be merged to master until after experimentation and review -- the others don't effect our UI until this one is done

**Comment by eddierubeiz** [comment]
`P/Othmer Library/Digital Collections - Internal Access/OHMS/transcripts.tar.gz` contains the transcripts as text files.

**Comment by lsberry16** [comment]
Here's what the "Christianity" search results in Nibbering look like to me: 
![image.png](https://images.zenhubusercontent.com/5e8b496e9ded5142cc04d617/0a4064d0-5e27-493a-852e-ffa541fb1ab9)

**Comment by sanfordd** [comment]
Quick note, in Chrome on Linux that arrow is missing but shows up as unrecognized character (blank box).
On Firefox in Linux, there's a blank space but when I pull the text out and check it in another program (plain text editor) the "missing" character is hidden in the blank space.

**Comment by jrochkind** [comment]
- [ ] Do not deploy this until we have fixed HTML showing up in imported searchable transcripts. 
- [ ] Do not deploy until we've fixed too large full text snippet excerpt, for instance search for "christianity", look at Nico M. Nibbering hit. 
- [  ] remove HTML tags from the imported searchable fulltext
- [  ]  deal with weird characters (up arrow?) from some of the imported fulltext, around back-of-the-book index terms

**Comment by jrochkind** [comment]
- [ ] Do not deploy this until we have fixed HTML showing up in imported searchable transcripts. 
- [ ] Do not deploy until we've fixed too large full text snippet excerpt, for instance search for "christianity", look at Nico M. Nibbering hit. 
- [  ] remove HTML tags from the imported searchable fulltext
- [  ]  deal with weird characters (up arrow?) from some of the imported fulltext, around back-of-the-book index terms

**Comment by HKativa** [comment]
Sharing an additional screenshot, which may be another instance of this issue. I first searched "religion" from the homepage and got 55 results. I limited my search by Department, selecting "Center for Oral History." The result pictured below is the 5th item on page 2 of the search results:

![Vestal_Martin_screenshot.jpg](https://images.zenhubusercontent.com/5d8e1dc48e31e4000184141b/5b79082f-7f73-413c-90a7-662996e45984)

**Comment by eddierubeiz** [comment]
To obtain extract the transcripts from the microsite database, run the following query:

```
SELECT
    field_interview_number_value as accession_num,
    field_index_text_value
FROM
    field_data_field_index_text text_table,
    field_data_field_interview_number accession_number_table
WHERE
        accession_number_table.entity_id = text_table.entity_id
    AND
        accession_number_table.revision_id = text_table.revision_id
    AND
        text_table.deleted = 0;
```

**Comment by jrochkind** [comment]
Ran on production, after deploying #797

   ./bin/rake scihist:add_transcripts_to_oral_histories FILES_LOCATION="/home/digcol/oh_transcripts_for_index/" OVERWRITE=true

No errors reported, `236/236`.
