### ISSUE TITLE
Robust validation on footnotes in OHMS xml

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#743]
Footnotes are stored in OHMS following an easy-to-understand syntax (`[[footnote]]` tags need to be closed; each footnote reference should refer to exactly one footnote; footnotes are numbered with consecutive positive integers; and so on).

With dozens of footnotes spread out over hundreds of pages in (soon) dozens of oral histories, small errors will inevitably creep in, leading to bugs that are unpredictable and often tedious to diagnose.

To ensure we won't waste a lot of time in the future hunting down the *one* footnote typo that's breaking a particular oral history, it is worth:

- listing the rules that describe the syntax;
- making sure they are enforced when users upload OHMS XML;
- in certain cases, making sure our display code is somewhat lenient, so it behaves reasonably when a particular rule is broken;
- adding tests to describe how our code responds to each of these rules.

**Comment by jrochkind** [comment]
@eddierubeiz Please link this to the original related issue by mentioning issue number here?

**Comment by eddierubeiz** [comment]
#732 is the general "Footnotes" issue; don't close it before we deal with validation.
