### ISSUE TITLE
Front end display and keyword searching of oral history transcripts/tables of contents without accompanying audio files

### ISSUE THREAD

**Issue by lsberry16** [sciencehistory/scihist_digicoll#744]
There are 7 oral history transcripts in the Digital Collection and another 15 in process which do not have accompanying audio files--they exist in our files as transcript documents only. We will want the display of these transcripts in the Digital Collections to closely match the way the other oral histories are displayed, and we'll want to be able to add segment-level keywords to an OHMS-like Table of Contents tab, so that keyword searching across the collection will work on these oral histories as well as the ones with audio. We can't use OHMS to do this, since it requires an audio or video file link, so presumably we'll need to use an XML editor of some sort and create an XML template that mirrors the OHMS XML standards, but without time coding. Open to other possible solutions, though!

**Comment by lsberry16** [comment]
An example of the display of an oral history without associated audio: https://digital.sciencehistory.org/works/1v53jz08f

**Comment by jrochkind** [comment]
I wonder if there's some way we could use the OHMS editor to create a ToC even without an audio file or timecodes. 

Duplicating that functionality from OHMS is a relatively significant investment, to implement and maintain.

**Comment by jrochkind** [comment]
Here is a feature OHMS claims to have that may be relevant, although I can't figure out how to do it:

> Ability to create an index for offline audio and video. OHMS now has the capability to create an index for audio and video that is played by your local media player. Prior to this release, OHMS required that the audio and video be online and linkable in order to create an index. Now, users can simply play an audio or video file on their computer and create an index, manually typing in the time code for the index segment.

Perhaps we could do that, using some kind of fake timecodes.

**Comment by jrochkind** [comment]
I actually am not really sure how we are going to accomplish this technically. 

Do we try to use the OHMS staff UI somehow even though we don't have an audio file? Not sure how realistic that is. We have to figure out if it's even possible to use the OHMS staff interface without an audio file, 

Or do we just build our own functionality separate from OHMS that allows you to enter a table of contents similar to OHMS? That's a bunch of stuff to develop -- we can definitely do it. But if OHMS ToC gets new features, they won't be automatically mirrored in our own feature. How important is it for these non-audio ToCs to match the audio ones feature-for-feature? Are there actually just a couple features we need? 

We should maybe start making sure we're all on the same page with: What is the purpose/user story for this feature?  What is it actually supposed to *do* when there is no audio to jump to?

Is it simply a list of headings and keywords under the headings? Maybe needs a description too? This might not be so complicated to implement. 

The related question is: How is all this data going to get into our system? Manual entry? That's quite a lot of manual entry. Not sure if the data exists in structured form anywhere to migrate from.

**Comment by jrochkind** [comment]
Mainly meant to apply to the 22 OH's that will neve rhave an audio file (one doesn't exist, or is permanentlylocked down), so will never have OHMS treatment.

**Comment by apinkney0696** [comment]
Closing as it is no longer a priority for COH staff.
