### ISSUE TITLE
Out-of-date code accepted a broken OHMS transcript file.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#751]
Because our staging site was not running the latest version of the code this morning, it mistakenly accepted a file that it should have rejected: a version of the Linus Pauling oral history interview with a footnote section that is truncated mid-footnote. The footnote is not closed; all footnotes after the half-footnote are missing; and the footnotes section is also missing its `[[/footnotes]]` closing section.

This is presumably due to a bug in the OHMS metadata editing tool.
Something is clearly wrong with  https://ohms.uky.edu/sync.php?id=89675 

For now I'm closing this bug as it's solved by #746  -- now deployed to Staging, which complains properly when you attempt do download and re-upload the broken XML.

**Comment by eddierubeiz** [comment]
Final diagnosis: the OHMS editor broke when Lee entered a ü character.

**Comment by jrochkind** [comment]
To be clear, entering a `ü` caused the OHMS editor to corrupt the footnote tags?  That's pretty terrible!  We should definitely make sure to report the bug to OHMS. Has that been done yet, @eddierubeiz @lsberry16?

**Comment by eddierubeiz** [comment]
My understanding is yes, the OHMS editor does not tolerate certain non-ASCII characters. We could easily reproduce the bug by creating a new dummy oral history in OHMS and attempting to add umlauts in various parts of a copy of an existing transcript. I haven't reported any bugs to OHMS, no.
