### ISSUE TITLE
Validate all OHMS transcripts currently in production.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#754]
We recently tightened up the rules for OHMS transcripts: bad footnotes are no longer accepted when you upload the XML file for a transcript. We need to go back and ensure that all items currently in production, including those uploaded before we changed the rules, follow the new rules.

**Comment by jrochkind** [comment]
Do we need to? We can ask @lsberry16

**Comment by eddierubeiz** [comment]
I found two (tiny) footnote errors in staging, and was able to check that they also exist in production. It would be nice to fix them.

It's unlikely that there are any production errors that don't *also* exist in staging, but we'll run the test in production anyway later this week.

[Oral history interview with Malcolm M. Renfrew ( 1n79h560c )](https://digital.sciencehistory.org/works/1n79h560c#ohTranscript) has the following errors:
Missing reference(s) to footnote(s): 25

[Oral history interview with Izaak M. Kolthoff ( fb494945p )](https://digital.sciencehistory.org/works/fb494945p#ohTranscript) has the following errors:
Reference to missing footnote 16

**Comment by MDiMeo** [comment]
@lsberry16 will fix OHMS errors

**Comment by lsberry16** [comment]
Done! There was an error in the coding of Kolthoff's footnotes and Renfrew had added some written addenda in which the missing footnote 26 appeared but these addenda had been omitted from the OHMS transcript. I fixed both transcripts in OHMS added them and reuploaded the OHMS XML to the Digital Collections.

**Comment by eddierubeiz** [comment]
Thanks @lsberry16. I ran the check code after you fixed the two problems above and now there are no problems in production.

**Comment by jrochkind** [comment]
ok based on those reports i am closing this issue.
