### ISSUE TITLE
what features are needed to get regular workflow off staging again?

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#767]
Staging was intended for occasional use to test out new things, not for regular workflow -- we can't commit to it being up and functioning reliably like production, because we use it for testing all sorts of experimental things. 

And until recently it was not used for regular workflow.  

But somehow it's become part of regular workflow for OH/OMHS related content, perhaps for "QA" work? That's not great, because it can be down or broken or working in unexpected ways at any time, and also can have it's data erased at any time. 

We should figure out what features we need to add to production to return regular workflow to production, not staging. Perhaps just the ability to add OHMS XML content to a published work, without the OHMS content being public? A separate toggle for public nature of OHMS XML content?

**Comment by eddierubeiz** [comment]
I am still pretty confident that addressing the issues covered in https://github.com/sciencehistory/scihist_digicoll/issues/712 would make this go away. Happy to discuss.

**Comment by jrochkind** [comment]
@eddierubeiz I don't understand how it could. 

I believe that the issue is: We have hundreds of Oral Histories that are already published, but lack OHMS XML. Staff needs to look at OHMS XML in Digital Collections to make sure it's appropriate *before* publishing the OHMS XML to the public. But we have no way to do that in production for already published OH Works. So they use staging for it, for each OHMS XML, as a step to making it public. 

I don't see how #712 would change this situation?  

But we probably need to talk synchronously with the actual users of this, instead of guessing.

**Comment by eddierubeiz** [comment]
You can add and remove OHMS XML to/from published oral history works.

**Comment by lsberry16** [comment]
Yes, but I think what we'll need to do is UNPUBLISH the oral history for which we're adding XML, then QC the OHMS XML stuff, then REPUBLISH it once it passes muster. Is that doable?

**Comment by eddierubeiz** [comment]
@lsberry16 Certainly. But I suspect the restrictions imposed in #673 and #660 will probably make this unwieldy... unless we also do #712.

**Comment by lsberry16** [comment]
@eddierubeiz Oh, bother. You're right. And 712 is in the backlog.

**Comment by jrochkind** [comment]
Things we will do:

* Stop prohibiting publishing if the software thinks there's not a valid combined derivative -- the software isn't smart enough to know what humans want to do. 
* Don't make you unpublish it to make a change (related to first bullet)
