### ISSUE TITLE
Wrangle time of day and timezones for dates.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#77]
The details are tedious but the goal is to be able to assert in the audit:
`item.created_at == Date.parse(metadata['date_uploaded'])`

**Comment by jrochkind** [comment]
This shouldn't be _too_ hard. 

If you aren't already, I would have the export make sure to output dates in UTC. That will simplify things enormously. As a general principle, all datetimes "in transit" should be UTC. (Like all character data should be unicode!)

Then in the import, make sure you are correctly parsing the thing from the export json file _as_ UTC, when turning it into a date object. 

Comparing them should simply be taking the thing from the db, making sure it's in UTC, and comparing it to the thing parsed from the export file in UTC.

**Comment by eddierubeiz** [comment]
Makes sense! Thanks for the pointer.

**Comment by eddierubeiz** [comment]
Done and merged into export and import branches respectively.
