### ISSUE TITLE
Allow full text of oral histories to be downloaded; uploaded; deleted.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#785]
**Downloads**:
- The UI will be on the oral history admin page (the same one where you can upload OHMS transcripts.).
- Download file name will be the accession  number plus some suffix, e.g. `_full_text.txt`.

**Uploads**:
- You can upload a file with an arbitrary name, as long as it ends in `txt`.
- We will not store the name of uploaded files.
- Minimal validation on the files, but we should probably make sure they have `Content-Type: text/something; charset=UTF-8`
- If a transcript already exist, we will prompt the user to make sure s/he wants to replace it with the contents of the uploaded file.

**Deletes**:
- Just a delete button with a confirmation.

**Comment by jrochkind** [comment]
Nice, thanks @eddierubeiz . I'd say try to get an "MVP" ready FIRST, in a PR, being even more "conservative" with anything that may not be strictly necessary. 

Like set the content-type limit on the HTML file input, sure, but don't bother with back-end validation. (This is staff!).  Don't bother with prompt to make sure you want to replace an existing one (I don't think our OHMS XML has that). 

we can potentially add those things even before merging the PR (or not, I'm not sure how much time/code complexity they are worth), but get the basic MVP functionality first, cool?
