### ISSUE TITLE
Fix Rails autoload problem

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#79]
Probably as simple as renaming module and/or the directory. In the meantime the tests fail.

**Comment by jrochkind** [comment]
That can get a bit tricky, happy to look at it with you. Right now there are no details as to the nature of the problem and how it exhibits on this issue. 

Is this a problem in import routines, or in general, or what?

**Comment by eddierubeiz** [comment]
Appreciate it.

The error is in tests:

`Unable to autoload constant Importer, expected /Users/erubeiz/Work/code/scihist_digicoll/app/importers/importer.rb to define it
`
I think I violated the Rails convention of having modules named after directories within /app : 

```
grep '^module\|^class'  app/importers/generic_work_auditor.rb
module Import
class Import::GenericWorkAuditor < Import::Auditor
```

My guess is that if I rename the either the directory or the module so they match, everything will Just Work. Stay tuned!

**Comment by jrochkind** [comment]
The trick is that the first directory under `app/` is _not_ included in the autoload namespace lookup assumptions. 

So for a class named `Import::GenericWorkAuditor`, it expects you to put it in:

    app/importers/import/generic_work_auditor.rb

(Where the dir name `importers` can be anything). 

Yeah, it's a little bit funky. Alternatetively, you can put it in `./lib/import/generic_work_auditor.rb` -- in lib, there's not that weird "first directory isn't included" thing from app. But you don't get automatic dev-mode autoloading, which may be fine. 

Alternatively, there might be ways to work around what the Rails loader expects the dir hieararchy to be, but prob not worth it.

**Comment by eddierubeiz** [comment]
Fixed by https://github.com/sciencehistory/scihist_digicoll/commit/4026ed0ab0743d9cf204eff791ab7df7a8978f54
