### ISSUE TITLE
cap invoke:rake running on wrong server

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#792]
We use a capistrano plugin to run remote rake tasks. We thought we had configured it to run on `jobs` server, but it seems to be running on web server. 

https://github.com/sciencehistory/scihist_digicoll/blob/5e8fdd398acf58ef18fe84358e5ea6c32bf11aae/config/deploy.rb#L80

And yet:

```
$ ./bin/cap staging invoke:rake TASK=scihist:solr:reindex
Fetching servers from AWS EC2 tag lookup, from servers with tag:Application='scihist_digicoll'   ...

  server '54.89.184.235', roles: :cron, :jobs # name: scihist_digicoll-jobs1-staging
  server '52.7.156.95', roles: :web, :app # name: scihist_digicoll-web1-staging
  server '3.86.210.95', roles: :solr # name: scihist_digicoll-solr1-staging

00:00 invoke:rake
      01 bundle exec rake scihist:solr:reindex
      01
      01 Progress: |

[...]

    ✔ 01 digcol@52.7.156.95 29.692s
```

Note it says it ran on `52.7.156.95`, which was the autodisocvered web/app server, not cron/jobs server. Hmm. 

https://github.com/sheharyarn/capistrano-rake

**Comment by jrochkind** [comment]
I think it might be a bug in capistrano-rake. 

I think: https://github.com/sheharyarn/capistrano-rake/blob/8d9efe6405afaa1b0974f249bd63ca9cd2fdb97b/lib/capistrano/tasks/invoke.rake#L9

`on roles(rake_roles) ` should maybe really be `on roles(*rake_roles)`

Have to figure out how to try out a fix.

**Comment by jrochkind** [comment]
Aha, yeah, capistrano-rake is broken in a couple ways with this feature. Will PR there and link here.

**Comment by jrochkind** [comment]
capistrano_rake is literally just this file:

https://github.com/sheharyarn/capistrano-rake/blob/8d9efe6405afaa1b0974f249bd63ca9cd2fdb97b/lib/capistrano/tasks/invoke.rake

I will submit a PR, but also we can easily copy the task locally and stop using the gem. It's nice to have the gem even for simple code to not have to reinvent the wheel, but if it's not doing what we need, easy enough to copy and modify. 

Another change we could make it making sure it only runs the rake task on ONE server, even if there are multiple jobs servers, which is what we want for our usage.

**Comment by jrochkind** [comment]
https://github.com/sheharyarn/capistrano-rake/pull/7

**Comment by sanfordd** [comment]
Running on only one server seems like a good adjustment to make.
