### ISSUE TITLE
Cannot publish an oral history that doesn't have audio files

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/scihist_digicoll#795]
When attempting to publish an oral history that doesn't include audio files, the following error message appears:

Combined audio derivatives are absent or out of date. Please generate them before publishing this work.

There are oral histories that do not include audio files so you should be able to publish an oral history transcript without audio.  

Thanks!

**Comment by jrochkind** [comment]
I didn't know we were publishing OH without audio files, I thought the plan was that all OH would have audio files attached. 

Can you give the context of the OH that needs to be published without an audio file?

It's possible the display of OH without audio files may need to be improved, since I didn't realize this was a thing we were going to do going forward. 

@lsberry16 @HKativa

**Comment by lsberry16** [comment]
There are a number of oral histories in the collection (around ten or so maybe—I can check) that have no associated audio files, either because they were lost/destroyed/corrupted at some point or because the interview was donated in transcript form without accompanying audio.

**Comment by jrochkind** [comment]
Thanks @lsberry16 -- is there one of those that you are trying to publish right now @yonyitz ?  Now that you remind me, I remember hearing about this -- but I think I had perhaps assumed wrongly that these would be something we'd get to in a future stage of development, not something we were ready to publish right now.

**Comment by yonyitz** [comment]
Hi Jonathan, I don't have anything to publish right now but such a use case could come up at any time, I believe!  No rush!

**Comment by jrochkind** [comment]
OK, cool. 

Before that use case comes up as an urgent matter, we should investigate to make sure the app can actually display such an OH in a reasonable way. I'm not sure it can. 

So if you see that coming down the pipeline, please try to bring it up as something to investigate before it becomes urgent to get such an OH published.

**Comment by yonyitz** [comment]
There are existing OHs that don't have audio files.  Let me know if you'd like to see examples!

**Comment by jrochkind** [comment]
Huh, I mistakenly thought there had been a project to add audio files to all existing published OH's, that had been completed. 

Sure, examples would be great, and also can you say why those existing ones have not had audio files added?

**Comment by yonyitz** [comment]
Copying Lee’s response from above: “There are a number of oral histories in the collection (around ten or so maybe—I can check) that have no associated audio files, either because they were lost/destroyed/corrupted at some point or because the interview was donated in transcript form without accompanying audio.”

Going into back to back meetings so will share examples as soon as I can!

Get Outlook for iOS<https://aka.ms/o0ukef>

Science History Institute
Chemistry • Engineering • Life Sciences
315 Chestnut Street • Philadelphia, PA 19106 • U.S.A.
Learn about the scientific discoveries that changed our world without leaving home at sciencehistory.org/learn<https://www.sciencehistory.org/learn>

__________________________________

Nicole Joniec   (she, her, hers)
Digital Collections and Metadata Librarian
Othmer Library of Chemical History
t. +1.215.873.8216

________________________________

**Comment by jrochkind** [comment]
I see, so some of those ~10 we have already ingested into digital collections and published? That's what I didn't realize. 

I guess if they are displaying acceptably, that's great! I was worried they were not, because I had not been designing for that.

**Comment by yonyitz** [comment]
Here is one:

https://digital.sciencehistory.org/works/1v53jz08f

Looks good to me!

**Comment by jrochkind** [comment]
I think this may be resolved as a result of #821. If someone wants to verify, we can close.

**Comment by yonyitz** [comment]
Ok; will verify tomorrow and will update here!

**Comment by yonyitz** [comment]
I've tested deleting audio files and saving [this record.](https://staging-digital.sciencehistory.org/works/vhfkc4n)  I then unpublished and republished the record.  Everything is copacetic!  Thank you!
