### ISSUE TITLE
Monitoring solution

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#801]
We are shutting down our self-hosted netdata, without a sysadmin on staff we don't think it is sustainable to maintain it.  (Also there were diverse opinions of how successful netadata was as a solution among staff :) ). 

But we do need some monitoring solution in order to keep our systems reliable in a professional way. Perhaps lean more heavily on AWS cloudwatch? Perhaps something else. 

Things we want to be alerted to (@eddierubeiz et al add more?):

* disks approaching full. (That took us down a few times with our sufia app, although hasn't recently. But we want an alarm if any of our EC2 block storage disk is appraoching being full).

**Comment by sanfordd** [comment]
Burst Credit total is a good item to monitor for any sustained CPU use that may drain a server.

**Comment by eddierubeiz** [comment]
I would want to be able to answer questions like: `If I go to location X on server Y, will i find a file whose name matches /z/ and created in the past Y days?`

**Comment by jrochkind** [comment]
@eddierubeiz Can you please be more specific and less abstract, why would you want to do that? What do you *actually* want to monitor, what processes are you trying to monitor with that formulation?

**Comment by eddierubeiz** [comment]
Also I'd want to be regularly reassured that sample HTTP requests (e.g. a basic search on prod for Digital Collections) returned response code `200`  within e.g. less than 1 second.

**Comment by sanfordd** [comment]
Also adding RAM usage and CPU usage may be helpful if set to fairly large tolerances, I know the current ratings we use might be too tight.

**Comment by jrochkind** [comment]
closing, irrelevant in heroku envkronment, any monitoring we need above what we are planning, we will have to figure out in practice after using heroku.
