### ISSUE TITLE
Full-text transcript mismatch(es)

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#807]
Regrettably, in at least one case, the code I wrote to associate full-text transcripts to oral histories attached the wrong file to the wrong oral history.

Paul Weisz https://digital.sciencehistory.org/admin/works/cj82k863f#nav-oral-histories

is the only example we have for now.

**Comment by eddierubeiz** [comment]
Compare:

Paul B. Weisz
https://oh.sciencehistory.org/oral-histories/weisz-paul-b
Interview no.: Oral History 0141

Pouné Saberi
https://oh.sciencehistory.org/oral-histories/saberi-poune
Interview no.: Research Interview 0141

**Comment by eddierubeiz** [comment]
I've removed the transcripts from the following mismatches:
```
    0138
    Roland
    https://digital.sciencehistory.org/admin/works/w37637891#nav-oral-histories

    0139
    Hanford
    https://digital.sciencehistory.org/admin/works/g445cf063#nav-oral-histories

    0141
    Weisz
    https://digital.sciencehistory.org/admin/works/cj82k863f#nav-oral-histories

    0142
    McKennon
    https://digital.sciencehistory.org/admin/works/1v53jz09q#nav-oral-histories

    0147
    Biondi
    https://digital.sciencehistory.org/admin/works/pn89d750s#nav-oral-histories

    0148
    Labovsky
    https://digital.sciencehistory.org/admin/works/pg15bf97z#nav-oral-histories
```

**Comment by jrochkind** [comment]
We forget for sure if we resolved this, @lsberry16 will double check.

**Comment by lsberry16** [comment]
I reviewed all six and successfully added the text files for the ones that were missing them. This ticket can be closed, as far as I'm concerned. :)

**Comment by jrochkind** [comment]
Thanks for reviewing and completing!
