### ISSUE TITLE
update footers

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#815]
From Clare:

Hello,
 
Now that the Institute doesn’t have a Berkeley address anymore, we need to update the sites’ footers. Below are mockups of what we will have on the main site/OH site.
The icons, which Digital doesn’t currently have, would be optional. If you desire, you can also add anchors to the Get in Touch links.
 
https://www.sciencehistory.org/contact-us#west
https://www.sciencehistory.org/contact-us#boston-cambridge
https://www.sciencehistory.org/contact-us#europe
 
And the link for museum hours, to save you a step, is https://www.sciencehistory.org/museum/visit
Yes, it’s a bait-and-switch.
 
We’ve taken this opportunity to add weight to the headings (Headquarters, etc.), font-weight 350, and removed the word “Office.” We also added France to the Europe address to balance the heights.
 
Lastly, the main site’s footer doesn’t include a Pinterest icon in case you want to consider removing the one from Digital Collections.
 
Desktop:

![image001](https://user-images.githubusercontent.com/149304/87575085-61ba8400-c69d-11ea-8eb3-aecdeaf2224a.png)

Mobile:

![image002](https://user-images.githubusercontent.com/149304/87575113-6da64600-c69d-11ea-922f-2030a83646ee.png)

**Comment by jrochkind** [comment]
Asked Clare:

> Do you know at what point you’ll have this live on the main or OH site? And/or on a staging site we can look at? It can often make it quicker/easier on our end to have live HTML to use as a model, instead of just a screenshot, also makes it easier to make sure we’re doing it exactly matching you.

**Comment by cfhirai** [comment]
Definitely no rush on this, but now it's inyour pipeline. I’ll be back with an ETA for you. Thanks!

**Comment by jrochkind** [comment]
Perfect, thanks @cfhirai !

**Comment by cfhirai** [comment]
Hi Jonathan, just to give you an update, we have staging links available as of now, but still working on formatting the font weights a bit. Layout-wise, we're already good, and that's probably the harder part. I'll send you the links as soon as we have it precisely to our liking.

**Comment by cfhirai** [comment]
Hi Jonathan, 

Here is the staging link so you can emulate the footer: [https://sci27footer-sciencehistory.pantheonsite.io/](url)

**Comment by jrochkind** [comment]
Thanks @cfhirai ! note to others: At first I thought that URL wasn't working for me, but it was just very slow to load, after I gave it some time it showed up. 

@eddierubeiz @HKativa We should perhaps discuss scheduling this work on Monday, and if it's me or Eddie that will attend to it.

**Comment by jrochkind** [comment]
@cfhirai I notice now there's now a Boston/Cambridge listing that isn't there currently too (on digital collections or main site). We'll just do our best to copy what's in that staging link, thanks for the link!

**Comment by cfhirai** [comment]
Yep, the addition of Boston/Cambridge was requested by Michael.

**Comment by cfhirai** [comment]
Update! The main site's footer is live, so please refer to that version of the footer instead.

**Comment by jrochkind** [comment]
Footer update should be live on our site, thanks @cfhirai !
