### ISSUE TITLE
Oral history request form, and logging

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#828]
for "free access without internet release". 

Should have:

* name (required)
* email (required)
* institution (optional)
* intended use (required)

Will get logged to back-end. All fields should be kept "encrypted" using same technique we used for R&R. https://github.com/sciencehistory/scihist_digicoll/issues/621  https://bibwild.wordpress.com/2020/03/05/encrypting-patron-data-in-rails-why-and-how/

Staff should be able to download log in spreadsheet form, giving date ranges of requests to include. 

Staff should be able to see "recent" delivered requests in browser. 

Note: our app does not currently support different feature access for different staff, anyone with a staff account *will* be able to see these. 

What happens once you fill out the form will be a different ticket.

**Comment by eddierubeiz** [comment]
Thanks for gathering these requirements, @jrochkind.
