### ISSUE TITLE
Delivering request-form-gated oral history assets

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#829]
See #828  re request form. 

After request form is filled out for these "free access no internet release" histories, the asset files (PDF as well as audio) can be delivered to user without staff intervention. 

How will we deliver?

1.  email with attachments (audio files start getting big)
2.  email including time-limited non-guessable private URLs
3.  just getting those time-limited non-guessable private URLs in browser after filling out form
4. Combination of 2 and 3, get it in the browser, but also get it in email in case you close your browser but haven't gotten em yet? 

We are leaning toward 3 or maybe 4.

**Comment by jrochkind** [comment]
Thought of another thing: What address should the email come from?

I think it's time to move on from our `no-reply` email with our emails that actually go to users. Why not give them an email address they can actually reply to if they need help?

`digital@sciencehistory.org` might be the obvious one -- it already appears on https://digital.sciencehistory.org/contact, so just save them the step of having to look it up, and let them reply. 

Or if OH team would rather an email addr that goes right to them for these OH emails specifically, their choice.

**Comment by eddierubeiz** [comment]
Sending it from digital@ for now -- easy to change.
