### ISSUE TITLE
staff UX for publishing should not automatically (un)publish all children

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#838]
Right now the publish/unpublish buttons will automatically publish/unpublish all children, because (we thought) that matched desired workflow universally. 

But at least with oral histories, it does not. 

We need that not to be automatic. In sufia, after changing visibility status of a work, you got a confirmation form asking you if you wanted to apply that to all children. That would be one possibilty. 

Or instead, we could move from a button in the navbar, to a control somewhere with more room, that has a checkbox or radio button that lets you select "apply to all children" yourself. Possibly also a control to publish/unpublish all children without changing status of parent. 

(Does this need to be 'transitive', applying through an entire tree of multi-level children? Probably? Was it before in our app? Is it in sufia/hyrax?)

**Comment by jrochkind** [comment]
This change doesn't actually look like it's in production to me, even though #844 looks merged, and master was deployed to production. 

Not sure what's going on, we need to figure it out before closing this. 

I thought when clicking on 'publish' or 'unpublish' on a work, you should get a popup select menu asking if you want it to apply to children or not? That does not seem to be happening to me. 

It's tricky to experiment with in production, since you don't want to actually publish or unpublish anything. The one test record we have in production at w37636967 may be helpful.

**Comment by eddierubeiz** [comment]
Logged into production; did not see the feature; redeployed master to production; now the feature is visible. Is it possible you thought you had deployed master to production but somehow you didn't?

**Comment by jrochkind** [comment]
I guess it is possible! Thanks! I didn't mean for you to have to interrupt other work to do that it wasn't urgent, but I guess we can close this now!
