### ISSUE TITLE
Import audit 2: check Fedora directly from scihist-digicoll.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#84]
Broadly speaking, at the end of a successful import, we want to be able to assert:
- All the items Fedora knows about now exist in scihist-digicoll. (No items were missed.)
- The metadata for all ingested items corresponds accurately to the Fedora metadata for the same items.

**Comment by jrochkind** [comment]
I wonder if we also want to save/preserve some kind of "fedora export" forever, just in case it had data we were missing. I am not sure in what format that would be, or how we'd get it. An RDF export of all of fedora? Is that possible, is that useful?

Just a "fedora backup" is not useful, if it requires standing up fedora to "restore" -- we might want to look at the original data, we're never going to want to stand up fedora again. :)

**Comment by eddierubeiz** [comment]
Yes, it's surprisingly easy to get Fedora to export all its RDF to one giant XML file. That was the basis for this project: parse that file and perform the checks described above. I have the recipe lying around somewhere or could probably recreate it -- basically you do a GET request for the entire Fedora repo and it all comes out -- collections, generic works, filesets,  all the metadata.

**Comment by jrochkind** [comment]
Cool, we might want to consider archiving that export somewhere after we migrate. 

But I am not sure you are going to be able to successfully parse that whole file in memory with ruby/nokogiri, it's going to be pretty big. But you can try! 

Which, if you can't, also limits it's utility as a preservation backup, hmm.

**Comment by eddierubeiz** [comment]
As I recall, it did parse just fine as a stream, which was fine for my purposes. But good call, we should put the xml on one of The Drives so we can refer back to it.

**Comment by jrochkind** [comment]
The tools for XML stream parsing in ruby are somewhat underdeveloped.

**Comment by sanfordd** [comment]
I'd recommend we place the XML file in an S3 bucket, that way we can easily move it to new servers when they're built.
