### ISSUE TITLE
No Google Analytics events for in browser view/listen on Oral History download page

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#843]
If you choose a "download" link on Oral History Downloads tab, it gets recorded in a Google Analytics custom action. 

![Screen Shot 2020-08-10 at 3 22 45 PM](https://user-images.githubusercontent.com/149304/89821982-77e12600-db1d-11ea-9100-c3ed9b79c4ec.png)

But if you click to view the PDF in-browser:

![Screen Shot 2020-08-10 at 3 24 04 PM](https://user-images.githubusercontent.com/149304/89822085-9e9f5c80-db1d-11ea-87fa-e47bae6eca4f.png)

No Google Analytics event is generated. Is this a problem? @HKativa 

(note, there are also no Google Analytics events being generated for in-browser audio player listens, that's a separate issue that can be created).

**Comment by HKativa** [comment]
Hmm, we're tracking "view" for all other works so we should do the same for oral history PDFs. With regards to the in-browser audio player listens, it seems worthwhile to track these as well, but I'd also like to hear what @lsberry16 thinks as the stakeholder.

**Comment by jrochkind** [comment]
Makes sense, but please just remember to ask us to prioritize this at a Monday meeting, for us to work on it.

**Comment by jrochkind** [comment]
Makes sense, I don't think anyone would not want that!

The issue is more priorities. Should we work on this *now*, instead of focusing on limited access oral histories and in general on trying to replace OH microsite features, or should we just leave this in the backlog for later?

Just let us know when you'd like us to work on it is all.

**Comment by jrochkind** [comment]
Also just do a review/audit of all relevant links on our new OH "audio"/OHMS page, to make sure they are google analytics tracked.
