### ISSUE TITLE
Fix S3 derivative "orphan" file checker, and run checkers regularly as cronjob, with report

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#864]
We had created a tool that checks through all files on S3 to find any that *aren't* referenced by our DB. This is a bit cumbersome to do (and has some cost to S3 every run, although probably trivial). But seemed good. 

But we weren't running it regularly. And the derivative file checker specifically has gotten out of date in it's logic, and reports some false positives with the combined audio derivatives being stored in different file paths than the orphan checker expects. 

It could be fixed to not mis-attribute the combined audio derivaitves as orphaned; and also to actually check the combined audio derivatives for real orphans separately. 

Additionally, we probably ought to be running these checkers (not just derivatives but originals too?) regularly, and reporting on things found (both in dashboard and in notifications of orphaned files found?) 

This becomes more important with our work to have public vs restricted derivatives, as oprhaned files could hypothetically be restricted/confidential info that ought not to be on a public bucket. 

This is kind of convoluted stuff, and could be a  week or two to implement.

**Comment by eddierubeiz** [comment]
I've been working on the first part of this: making the orphan derivative checker detect and delete combined audio derivatives correctly.

**Comment by eddierubeiz** [comment]
I split this into 3 sub-tickets, as it's pretty broad.

**Comment by eddierubeiz** [comment]
Yeah, I'm going to close this.
