### ISSUE TITLE
Improvements to the Ansible code that builds the management server

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#865]
The following improvements should be made (although this is not a high priority) to the Ansible code that builds the Management server:

- [ ] The automatic sync-from-production-to-staging cron job is currently disabled. Do we want to run it automatically or not?
    If yes, reinstate and document
    If no, remove altogether and document
- [ ] Examine roles/ansible/templates/ which looks shady / out of date.
- [ ] Ditto group_vars/manage
- [ ] Refactor the shell scripts so that the settings and the code are all in the same file.
    Instead of update_staging.sh -f, 
    we would invoke the script as update.sh -staging -f.
- [ ]  { role: git_project } can probably be removed from create_manage.yml and update_manage.yml

**Comment by eddierubeiz** [comment]
We will not be making these improvements: the management server will be obsolete after we move to Heroku. Closing this issue.

**Comment by eddierubeiz** [comment]
Reopening, but let's close this after migrating to Heroku.

**Comment by jrochkind** [comment]
closing, irrelevant in heroku envkronment
