### ISSUE TITLE
Analysis of access control issues with S3 backup buckets

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#866]
Pulling out from #832 this specific issue for more analysis. 

_If you change derivatives storage from public to restricted, we need to make sure any copies from derivative *backup* bucket get properly deleted too. Also DZI backup bucket. Also how does this apply to version history_

Some questions involved:

* If an object is deleted from the derivative bucket or dzi, does that deletion get automatically replicated to backup bucket already?

* Even if so, it might still be there in version history. Are the *versions* publically available, so they need to be purged too?

**Comment by jrochkind** [comment]
Note we don't have backup buckets (derivatives, dzi, originals) for staging, only for production.

**Comment by jrochkind** [comment]
OK, here's some analysis. Did this with a test object on production, since staging doesn't use backup buckets. 

1. Created an asset on public derivatives. 

2. Verified that derivatives *were* automatically replicated to backup bucket `scihist-digicoll-production-derivatives-backup` (although had to wait for a couple minutes for them all to replicate)

3. Using staff UI, changed derivatives storage to "restricted"

4. Verified that derivatives were gone from derivatives bucket `scihist-digicoll-production-derivatives`

5. They were NOT deleted from the backup bucket. Do our replication rules not replicate deletes? Or did I just not wait long enough for replication to happen?

6. Just to see what happened, *manually* deleted a derivative from backup bucket. 

7. The older version in version history **IS** still there and **IS** publicly accessible if you know the URL!
  * The URL is even more obscure. In addition to a fairly random URL, you'd ALSO have to have the fairly random `versionID` that goes on the end of the URL.  Eg: `https://scihist-digicoll-production-derivatives-backup.s3-us-west-2.amazonaws.com/0014db87-8949-47f6-bdf2-5b6541eeeb5b/download_small/375450757aca863d65156b1441e35c53.jpeg?versionId=SexTgv_pQAtUS8QGBIlTY4eKmANAYwHT`. But anyone that does have this URL can access the thing, even though it was deleted, the version is still there at that URL. 
  * Why does our derivatives backup bucket keep version history for 30 days? (It only keeps old versions for 30 days). Not sure, not sure we need it. But we are not looking to changing policy decisions like this in a hurry as part of the OH feature implementation, especially since without Dan we don't necessarily have all the context. 

So, I think my analysis is that our code *does* need to go ahead and explicitly delete derivatives from backup bucket -- including deleting version history!  -- when changing derivatives from "public" to "restricted". 

@CHF-IT-Staff  and @eddierubeiz , confirm?

**Comment by jrochkind** [comment]
To actually delete all versions... I think maybe we'll need to use the SDK API to *list* all versions that may exist, and delete them one by one. Phew! 

I wonder if we should consider turning off versioning on the derivatives backup bucket at least; I am not sure what it's for, especially if the backup bucket isn't replicating deletes! (although we're not sure of that)

**Comment by jrochkind** [comment]
This seems suprisingly tricky. To delete a version, you have to supply a versionID to the delete call:

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Object.html#delete-instance_method

But I haven't figured out how to list all versions available for a given object, even though the console will easily show it to you.

**Comment by jrochkind** [comment]
Aha, you might need to use client#list_object_versions with the whole key as a "prefix"? OK. 

https://www.rubydoc.info/gems/aws-sdk-s3/1.8.2/Aws%2FS3%2FClient:list_object_versions

**Comment by jrochkind** [comment]
I wonder if it makes sense to change our bucket configuration slightly after all. What if we change it so deletes ARE replicated to backup buckets and backup buckets do NOT keep version history. Then the app might not need to worry about taking care of backup copy purging itself. 

I'm not sure why we are not replicating deletes and/or keeping versions, for these derivative and dzi backup buckets. For originals it might make sense just to be extra special safe not to lose anything. But here maybe not needed? If we can't come up with the reason it's needed, maybe okay to disable, and make the logic a lot simpler?

Could use some feedback @eddierubeiz and @CHF-IT-Staff

**Comment by eddierubeiz** [comment]
I can't see any real value to keeping multiple versions of *derivatives* or *dzi tiles* in *backup* buckets.

**Comment by eddierubeiz** [comment]
Or, likewise, holding on to deleted derivatives or dzi tiles in backup buckets. Not needed.

**Comment by jrochkind** [comment]
I'm not actually sure why deletes aren't being replicated or how to change that, but am trying to figure it out.

**Comment by jrochkind** [comment]
Oh wait, replication may *require* versioning to be set up, also!  That could explain why we have versioning.

**Comment by jrochkind** [comment]
So it looks like S3 replication actually does both these things by design!

* S3 replication does not replicate deletes
* S3 replication requires versioning to be turned on. (Although I think we could have versions automatically expire after 1 day instead of 30 like present)

**Comment by CHF-IT-Staff** [comment]
I did some research and yes, I see that S3 replication does not replicate deletes and S3 replication requires versioning to be turned on.  Based on how we (might) use the backup, I don't see a problem with expiring older versions after 1 day.

**Comment by jrochkind** [comment]
There is a really hacky way to get S3 to replicate deletes, by convincing it to use an older "v1" setup for replication. The older "v1" setup replicated deletes, but newer replication implementation does not. 

But it's really hacky, you kind of have to "trick" S3 into using older V1 setup. It is documented (confusingly) by Amazon, looks like they realized some people needed this feature for legal compliance issues etc, after they removed it in "v2", and sort of provided a workaround for now. 

Not sure if I'm thrilled about that solution either, but it might be better than the alternatives. I'm having a lot of trouble getting this into code in a maintainable way. 

As far as switching to "v1" replication, it doesn't help that the replication setup isn't actually currently controlled by ansible, it's just manual. So makes it harder to avoid accidentally "un-doing" a switch later, doesn't leave us a place to document why we did it, etc. 

https://aws.amazon.com/blogs/storage/managing-delete-marker-replication-in-amazon-s3/

https://rtfm.co.ua/en/aws-s3-cross-region-replication-configuration-and-objects-deletemarkers-replication/

**Comment by jrochkind** [comment]
The "delete from backups too" logic is just messy to implement. And will make it harder to move to a situation where derivatives are on a prefix on a shared bucket, like we'd like to, as it's another thing making assumptions about how things are set up.
