### ISSUE TITLE
Backups in Heroku world: turn on cron at launch; adjust destination s3 file.

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#876]
**NOTE: leaving this issue open until after we launch Heroku and have backups functioning in production again.**

Heroku postgres has it’s own built-in backups, including ability to easily rollback to previous point in time. Do we still want to do our own backups of postgres? Probably! But we should wrap our head the heroku backups and how they relate to ours, and update our documentation. 

I don't think we're currently backing up anything but postgres and S3? 

If we do want to continue our manual backups, we'll have to adjust the routine to find and backup our heroku-hosted postgres db! And where will it run? (our own EC2? A heroku scheduled task somehow?)

**Comment by eddierubeiz** [comment]
We have a good workflow to database backups set up in: #938. However, a couple things will need to happen as part of the Heroku launch sequence to actually turn it on:

- Something (either a Heroku scheduler *or* a Github action) needs to invoke the rake task every night

- The destination file on s3 should be changed from `FILE_PATH=PGSql/digcol_backup_2.sql` to `FILE_PATH=PGSql/digcol_backup.sql`. The latter is where the cronjob on the pre-Heroku DB server uploads the db dump.

**Comment by jrochkind** [comment]
Also make sure to document.

**Comment by jrochkind** [comment]
#938 also says:

> Note that Heroku also offers physical backups which are fast and useful for short-term DB maneuvers. This workflow is meant to supplement, not replace, those backups.

That heroku backup should be included in documentation.

**Comment by jrochkind** [comment]
I have some concern that the backups being created, it may not be possible to restore to heroku?

https://help.heroku.com/F5367R6T/magic-string-errors-while-attempting-to-restore-a-postgres-backup

And the built-in heroku backups DO seem to be "logical" -- I think they are just compressed?  Which should be fine? We may want to reconsider the way we are using the heroku built-in backups. Or not.

**Comment by eddierubeiz** [comment]
`heroku pg:psql --app scihist_digicoll_production < last-night.sql` works fine with the backups being created.

**Comment by jrochkind** [comment]
> heroku pg:psql --app scihist_digicoll_production < last-night.sql works fine with the backups being created.

Sweet! Are we sure that overwrites any existing data in the db, or do you need to drop data first? Like if there are rows in the db that don't exist in the `backup.sql`, will they be gone after you run the import to `backup.sql`?

**Comment by eddierubeiz** [comment]
Yup! That's what the --clean option does.
