### ISSUE TITLE
"Nice-looking" outgoing HTML emails [low priority]

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#904]
These might include include some or all of the following:
- [ ] A header image;
- [ ] Official on-brand font for the text and links;
- [ ] A rectangular box around the text of the email;
- [ ] A standard footer at the bottom of the email;
**Challenges:**
Getting this right will probably require us to figure out how to get a dev instance to send dozens of outgoing emails, and testing said emails in several clients.

**Comment by jrochkind** [comment]
We did this actually
