### ISSUE TITLE
Background jobs on Heroku

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#907]
End goals:
    Recommend a functioning configuration: how many workers? What type of dyno would they be running on?
    Estimate cost for actual production use

TODO: 
 - [x]  Install `mediainfo` and `vips` and `imagemagick` and `ffmpeg`
    - let's try using the heroku buildpack for `apt`, and then installing these via apt
- [x]    Get ingest working; turn off indexing on save work, so that SOLR doesn't prevent us from testing.
- [x]    Figure out / documenting Heroku / Redis memory usage and errors
- [x]    How many workers do we actually need in production? (to know this, you need to get a handle on looking at how much memory we're using, see above. How many workers can we fit in a given size dyno?) 
    *  It looks like we can fit 3 resque workers in a heroku standard-2x dyno, with some comfortable headroom. (4 sometimes produces memory quota exceeded errors). And 4 standard-2x dynos can process an ingest in about the same amount of time as our current infrastructure -- although this can vary since heroku standard dynos can have such variable performance. 
- [ ]    Possibly switch to Sidekiq ?
- [x] PDF creation causes error when more than a few pages. This is PROBABLY a too much RAM error. We may have to rewrite how we do PDF creation, to do it in a different way using a different PDF creating package, that can create large PDFs without using lots of RAM. 
- [x] determine which vendor and size of redis we want to give us what we need at best value. Current redis usage is pretty tiny, and recorded [here](https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1009582081/Heroku+Consideration#Redis) along with notes about possible future expansion.

**Comment by jrochkind** [comment]
While it's possible sidekiq could make more efficient use of heroku dyno resources, and get us more job processing for less cost -- resque seems to be working out reasonably. We could talk about switching to resque as a separate possible improvement, it does not seem to be necessary for heroku. 

(It's also possible switching to sidekiq wouldn't give us much, if the workers are maxing out available CPU already anyway. Not sure).
