### ISSUE TITLE
Finalize the copy pertaining to rights and licensing for restricted oral histories.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#912]
This is a non-technical issue.

Eddie will work with Lee to make sure the verbiage on the work page, the form and the patron email are all consistent with each other and with our legal stance.

This work will obviously need to happen before we actually publish any OHs that have any of their contents behind a release form.

**Comment by eddierubeiz** [comment]
OK! As of early 2021, the copy in production reads as follows:

**Work page** (see e.g. https://digital.sciencehistory.org/works/r5v7ntm )
    At the top:
```
        "NON-COMMERCIAL USE PERMITTED"
        Link to: https://rightsstatements.org/page/InC-NC/1.0/?language=en
```

In the metadata:

```
        Rights:  In Copyright - Non-Commercial Use Permitted
        Rights holder:       Science History Institute

```
------
**Form:**

At the top:

```
"NON-COMMERCIAL USE PERMITTED"
Link to: https://rightsstatements.org/page/InC-NC/1.0/?language=en
```    

... but then:

_Your receipt of an electronic copy of an oral history indicates your agreement to abide by U.S. copyright law with regard to the reproduction and dissemination of the oral history. You are receiving a copy of this oral history and you are not permitted to reproduce it in any way without the permission of the Science History Institute.
We consider your personal information confidential. We will only use it for our records, and we will not share it with anyone outside the Science History Institute.
If you have any questions about transcripts, recordings, or usage permissions, please contact the Center for Oral History._

------
**Email to patron:**

 Dear [recipient],

Thanks for your recent visit to the Science History Institute's digital collections website. At [date and time], you requested access to the files for Oral history interview with <person>. Good news: the files are ready for you to download.

Files for Oral history interview with [person]:
        [links]

You can download the files any time in the week. After that, these links will no longer work.

**Comment by MDiMeo** [comment]
Once we close ticket #973 we should update the copy on the form and the email to match the CC license. 
After clicking "Request Access", the top of the form [https://staging-digital.sciencehistory.org/works/ym8smcv/request_oral_history_access] should be edited to read:

Your receipt of an electronic copy of this oral history indicates your agreement to abide by the terms of a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0) license. [Hyperlink to license] Please credit the “Science History Institute.”

We consider your personal information confidential. We will only use it for our records, and we will not share it with anyone outside the Science History Institute.

If you have any questions about transcripts, recordings, or usage permissions, please contact the Center for Oral History at oralhistory@sciencehistory.org. 


Then the email they receive should be edited to read: 
Dear [Name from form],
Thanks for your recent visit to the Science History Institute’s Digital Collections [hyperlink site]. Here are your requested files for the Oral history interview with Helen Murray Free [hyperlink to interview record]:
•	free_hm_0176_1-1.mp3 (MP3 — 31.7 MB)
•	free_hm_0176_1-2.mp3 (MP3 — 30.2 MB)
•	free_hm_0176_1-3.mp3 (MP3 — 31.5 MB)
•	free_hm_0176_1-4.mp3 (MP3 — 30.7 MB)
•	free_hm_0176_1-5.mp3 (MP3 — 34.6 MB)
•	free_hm_0176_1-6.mp3 (MP3 — 30.3 MB)
•	free_hm_0176_FULL.pdf (PDF — 986 KB)
These links are only valid until [DATE-- one week is fine]. Please download your files before the links expire.

Your receipt of an electronic copy of this oral history indicates your agreement to abide by the terms of a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0) license. [Hyperlink to license] Please credit the “Science History Institute.”

If you have any questions about transcripts, recordings, or usage permissions, please contact the Center for Oral History at oralhistory@sciencehistory.org.

**Comment by jrochkind** [comment]
We could perhaps dynamically insert in the terms of whatever rights/license is actually set on the work, to make it flexible for potential future use, and make sure it matches.

**Comment by jrochkind** [comment]
@MDiMeo @lsberry16 

Here's where I ended up, on "Request Access" form:

![Screen Shot 2021-02-16 at 4 13 38 PM](https://user-images.githubusercontent.com/149304/108122240-f7722380-7071-11eb-92da-b0b6ba4f72b6.png)

Email:

![Screen Shot 2021-02-16 at 4 14 12 PM](https://user-images.githubusercontent.com/149304/108122276-078a0300-7072-11eb-996d-10abf0a29064.png)

Note if you do use a different value in "rights" that shows up in both places with appropriate link, eg:

![Screen Shot 2021-02-16 at 4 15 01 PM](https://user-images.githubusercontent.com/149304/108122372-2d170c80-7072-11eb-8c88-5a27aedfaf2f.png)

(Hmm, that blue-hyperlink-on-blue isn't working very well, probably should fix that...)
