### ISSUE TITLE
export is missing lifecycle dates

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#92]
fileset and collection exports both need `date_uploaded` and `date_modified` in export, so we can sync them on import.

**Comment by eddierubeiz** [comment]
First crack at this in: https://github.com/sciencehistory/chf-sufia/commit/82e8b6cc6b27b2a5e5fd47c4113fe9bbe784f8ba

**Comment by eddierubeiz** [comment]
As of this morning exported filesets are showing e.g.
"date_uploaded":"2017-05-16 19:36:45 UTC","date_modified":"2017-05-16 19:36:45 UTC"
and I expect this to work for genericworks and collections as well.
See e.g. jobs1-stage:/opt/export/chf-sufia/tmp/export/filesets/kw52j8512.json

**Comment by eddierubeiz** [comment]
Working for generic works...
```
$grep -o '"date_uploaded":"[^"]*"'  /opt/export/chf-sufia/tmp/export/genericworks/kw52j8890.json
"date_uploaded":"2018-01-22 19:49:21 UTC"
$ grep -o '"date_modified":"[^"]*"'  /opt/export/chf-sufia/tmp/export/genericworks/kw52j8890.json
"date_modified":"2018-01-22 19:49:25 UTC"
```

**Comment by eddierubeiz** [comment]
... but NOT for collections. I suspect the metadata for collections is different in Sufia, but I'll have to come back to this.

**Comment by eddierubeiz** [comment]
We did fix this.
