### ISSUE TITLE
Blacklight throws error if a page is requested with an "Accept: application/json" header

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#924]
`curl -i -H "Accept: application/json" https://digital.sciencehistory.org/catalog` will result in a 500 error ( see the stack trace at https://app.honeybadger.io/projects/58989/faults/57865973#notice-trace for details).

Meanwhile, `curl -i -H "Accept: application/json" https://digital.sciencehistory.org/` will return a `Status: 406 Not Acceptable`.

**Comment by eddierubeiz** [comment]
See also: https://app.honeybadger.io/projects/58989/faults/59505958

**Comment by jrochkind** [comment]
that's a blacklight feature to return json. 

The way we've done things somewhat non-Blacklight-y on results pages may have broken the json result. 

We can fix it to succesfully return a json result, or, if we don't really care about that anyway, we can fix it to just return an HTTP 406 response without trying and logging a fatal error. 

Curious what is requesting json there, if the user-agent is interesting at all, or any other clues.

**Comment by jrochkind** [comment]
Broken JSON response was noted as an issue to consider in #201 from July 2019 when we first implemented new app. That issue is still open, we never circled back to it.

**Comment by eddierubeiz** [comment]
Ah, OK. So technically this is a duplicate. I'm leaning towards not supporting JSON in search results and returning a 406.

**Comment by jrochkind** [comment]
Not a duplicate, just a more specific item that's part of that umbrella. 

If we haven't had a need for JSON search results in the last year, it does seem like at least for now we should just make it cleanly 406. But it's up to product owner/stakeholders, it would be good to review that overall "APIs" issue.
