### ISSUE TITLE
Scheduled jobs in heroku

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#931]
It looks to me like the heroku free scheduler plugin is sufficient after all. 

It only lets you do nightly (or hourly) jobs, not weekly jobs -- we only create the google sitemap weekly, but it doesn't hurt to do it nightly. 

One downside is there scheduled job configuration will live purely on heroku accessible only via human web dashboard, there is no API for it, so we lose being able to track/control that configuration in source code. (We know do it with the `whenever` gem for configuring cron jobs in ruby, that get deployed to cron by capistrano). 

Additionally our code will no longer "know" when the nightly are jobs are scheduled -- only minor place this comes up now is the abliity for the fixity dashboard to say "these run every night at 2:30am", and have that be correct without having to keep it synchronized. That's not a huge deal.

**Comment by jrochkind** [comment]
I guess we just make these by hand. Note that heroku scheduler uses UTC -- have to calculate what time we want in ET ourselves. And remember it will change by an hour when daylight savings goes on/off!  I think this is fine for our tasks, ti doesn't matter if they run at 2:30am during half the year and 3:30am the other half, although a bit annoying. 

Add comment to our `schedule.rb` (currently used by `capistrano-whenever`) that this doesn't effect heroku -- then remove the file entirely after we go live on heroku?

**Comment by eddierubeiz** [comment]
Sounds good.

**Comment by eddierubeiz** [comment]
Actually, instead of adding an actual comment to `schedule.rb`, I just created #1222 to cover the work of removing `whenever` and all references to it. It turns up in at least 2 or 3 places, and that's a distinct task that we can take care of well after launch, if I understand correctly.

**Comment by eddierubeiz** [comment]
The sitemap creation rake task currently runs weekly. but the Heroku scheduler doesn't allow for weekly tasks. We should probably modify the task to end early unless it's Tuesday and run *that* nightly. Until we take care of that I'm fine with running the task manually for a couple weeks. @jrochkind  - other ideas welcome.

**Comment by eddierubeiz** [comment]
I've added all the tasks except sitemap creation to https://dashboard.heroku.com/apps/scihist-digicoll-production/scheduler, so they'll be running nightly from now on.

**Comment by jrochkind** [comment]
Oh, annoying! 

There are other scheduler-add-ons that cost money that are more powerful. 

But also, it runs weekly because it doesn't need to run more often than weekly, but it doesn't hurt it to run nightly. Just run it nightly?

**Comment by jrochkind** [comment]
Also, at least some of these tasks should be set in staging too, yes? If they all were in staging previously, then maybe all of them, just for staging-prod parity?

**Comment by eddierubeiz** [comment]
Oh, I thought it would cost us a ton of money to run nightly. If not, yeah, I'll add it to the scheduler.

**Comment by jrochkind** [comment]
I don't know how much money it will cost, I think it only takes a few minutes to run? 

Also, per comment above:

> Note that heroku scheduler uses UTC -- have to calculate what time we want in ET ourselves. And remember it will change by an hour when daylight savings goes on/off! I think this is fine for our tasks, ti doesn't matter if they run at 2:30am during half the year and 3:30am the other half, although a bit annoying.

In the end I don't know how much it matters, but you have scheduled the jobs in UTC so they'll run at pretty different times than we have been running them, was that intentional?

**Comment by eddierubeiz** [comment]
Great -- added  sitemap creation to our nightly stuff.
Adjusted times so they're correct in UTC.
Added all jobs to staging.
Prefixed everything with `HONEYBADGER_EXCEPTIONS_RESCUE_RAKE=true` (see https://github.com/honeybadger-io/honeybadger-ruby/issues/258 )
For now, I'm leaving out the explicit path declaration and the `--silent` that `whenever` adds in.

**Comment by jrochkind** [comment]
oh nice catch on honeybadger. That's kind of a mess, I wonder if it's really still necessary? but we had it in the old `schedule.rb`, so might as well keep things equivalent. 

Ugh, another thing that gets  kind of messier on heroku. :(

**Comment by jrochkind** [comment]
Reading all that lengthy GH issue by me, I think it's possible the `HONEYBADGER_EXCEPTIONS_RESCUE_RAKE` is not going to be required. How excited would you be to make a rake task that intentionally raises and schedule it on heroku staging to test if honeybadger picks it up? :)

**Comment by eddierubeiz** [comment]
rake "blacklight:delete_old_searches[goat]"

**Comment by eddierubeiz** [comment]
Yes, the `HONEYBADGER_EXCEPTIONS_RESCUE_RAKE` is needed.
 - heroku run bash --app scihist-digicoll-production
 - then compare the results of `HONEYBADGER_EXCEPTIONS_RESCUE_RAKE=true bundle exec rake blacklight:delete_old_searches[GOAT]` and `bundle exec rake blacklight:delete_old_searches[GOAT]'.
 - Only the first actually results in a HB error.

**Comment by jrochkind** [comment]
So... based on refreshing my memory by reading that long GH issue...  honeybadger is supposed to try to detect if it's an "interactive" run or not, and not report exceptions if it is. 

If you are running it manually in a bash shell, I'd expect it to detect "interactive" and  not report. HONEYBADGER_EXCEPTIONS_RESCUE_RAKE may override that. 

BUT... what if we `heroku run rake blacklight:delete_old_searches[GOAT]` instead? (Assuming this matches closer to what scheduler does, without an interactive bash shell).  Does honeybadger properly detect this as "non-interactive" and report anyway, without the ENV needed?

**Comment by eddierubeiz** [comment]
Unfortunately HB doesn't report that.
I can actually schedule the test to run every 10 minutes and we can find out for 100% sure.

**Comment by jrochkind** [comment]
Yup, seems to be so. How messy!

Should we document this somewhere? That every scheduled task needs this?

Oh wait! Another option... we can just add `HONEYBADGER_EXCEPTIONS_RESCUE_RAKE=true` as a heroku config variable?!  I guess that would make it apply to manually run `heroku run rake` tasks too, which is probably ok? 

I'm not sure what is best. I kind of want to debug this further and get it to work right, where it reports for cronjobs but not for manual runs! 

If you do leave that in every scheduled task, yes, let's document it!  Since we can't add a "comment" to heroku scheduler tasks, we should leave a document somewhere...  I guess on https://chemheritage.atlassian.net/wiki/spaces/HDC/pages/1915748368/Heroku+Operational+Components+Overview ? Maybe in the "addons" section, some more nested bullet points under scheduler, or pull out a separate sub-section in "addons" section?

**Comment by jrochkind** [comment]
Ah, okay. honeybadger has a config exceptions.rescue_rake. And a magic system that for any config turns a HONEYBADGER_ env like that into config default. 

So, alternately, we can perhaps just set that HB config value in our HB config in app, instead of relying on an ENV set. If we can get that to work, then we’ll get HB reports even for manual rake tasks, but we don’t have to include the ENV in every scheduled job, or in heroku config vars, or document it — it’s all in our code.

**Comment by jrochkind** [comment]
I actually think it's quite possible HB is going to report from "Scheduler" jobs even though it doens't from `run bash` or `run rake`. HB tries to decide whether to report or not based on `STDOUT.tty?`, whether the STDOUT stream reports being attached to a "tty" -- 

I have confirmed it does not if you run `heroku run:detached rake...`, so I think that should actually report to HB, and I think scheduler maybe should too, without us having to do anything! Trying to test it to confirm...

**Comment by jrochkind** [comment]
Yup, I think I just confirmed that an uncaught exception from (eg) a rake task run via heroku **scheduler**  will result in a honeybadger report! We don't need to do anything special, it just works. https://app.honeybadger.io/projects/58989/faults/80069412

And I think I understand why this works, when errors from `heroku run bash` or `heroku run rake` do not -- the detection of an attached TTY!  `heroku run rake --no-tty` will report, as will `heroku run:detached ...` -- it is correctly detecting "Hey, this isn't running in a console where any human can see it, so we'll decide to report to HB"

**Comment by jrochkind** [comment]
Re: `bin/rails runner -e production 'AssetDerivativeStorageTypeAuditor.new.perform!'` -- I wouldn't predict you'd need the `-e production`, it should default to production just the same as all the rest of our app (web and worker dynos etc) do -- because of heroku config var `RAILS_ENV=production`.  But did you find you needed it?

**Comment by eddierubeiz** [comment]
Re the `-e production`: I would like to try removing it.
Only reason I added it is because it was (for whatever reason) added by `whenever` to the crontab.

**Comment by eddierubeiz** [comment]
"Yup, I think I just confirmed that an uncaught exception from (eg) a rake task run via heroku scheduler will result in a honeybadger report! We don't need to do anything special, it just works." I have confirmed what you confirmed! :)
