### ISSUE TITLE
Database backup from Heroku to S3.

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#934]
Currently our postgres database is backed up by a cronjob `scihist-digicoll-backup.sh` running on the production database server, to an S3 bucket; namely, `s3://chf-hydra-backup/PGSql/digcol_backup.sql`.

This S3 bucket is "versioned" and keeps 30 days worth of past versions.

The DB server is going away, and so are the cronjobs on that server. What's the simplest way to regularly copy the Heroku DB to a particular location on S3?

For now, let's have it go to: `s3://chf-hydra-backup/PGSql/test_heroku_backup.sql`

**Comment by jrochkind** [comment]
It would need to be running *somewhere*. I guess one possibility is continuing to run an EC2 for that purpose, but that's not very attractive. 

Perhaps a heroku scheduled job? 

We also need to look at what backup facilities are built into heroku. They will make certain backups for us. Is that enough? Is there any facility already built into heroku to ask for postgres backups to an S3 location of your choice? Maybe not, but maybe there are some facilities there to make this easier?

https://devcenter.heroku.com/articles/heroku-postgres-data-safety-and-continuous-protection

https://devcenter.heroku.com/articles/heroku-postgres-backups

Hmm, wait

> Both pg_dump and pg_restore running on Heroku are available through Heroku Postgres. During a scheduled run of PGBackups or manual run of heroku pg:backups:capture, PGBackups will launch a dedicated dyno to take a dump of your database and upload it to S3. 

Not totally sure what this means, but it sounds promissing?

**Comment by jrochkind** [comment]
@jrochkind and @eddierubeiz will demo doing the cronjob on github actions to compare and contrast.
