### ISSUE TITLE
"Profile incompatible with image" problem with thumbnail creation for certain TIFF files

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#942]
`vipsthumbnail` is reporting a "profile incompatible with image problem" and failing to generate a thumbnail for the TIFF at https://digital.sciencehistory.org/works/yj7tsjw .

The image looks normal enough. Output from `file` is:
`TIFF image data, little-endian, direntries=20, height=4512, bps=8, compression=none, PhotometricIntepretation=BlackIsZero, orientation=upper-left, width=5347`

Honeybadger report: https://app.honeybadger.io/projects/58989/faults/73028093

Note: we'll leave this issue open until a permanent solution is in place.

**Comment by eddierubeiz** [comment]
Easy to reproduce in staging: ```vipsthumbnail test.tiff --eprofile /opt/scihist_digicoll/shared/bundle/ruby/2.6.0/bundler/gems/kithe-b4e4e18b61fa/lib/vendor/icc/sRGB2014.icc```

**Comment by eddierubeiz** [comment]
@HKativa, this could be a colorspace problem. The files we're talking about appear to be grayscale, and it looks like our thumbnail creation recipe assumes sRGB. Could it be that that our scanning workflow normally results in sRGB files, but somehow these particular ones ended up being saved in grayscale instead?

**Comment by HKativa** [comment]
@eddierubeiz Thanks for looking into this! The files are definitely grayscale - the originals are b&w negatives, which were digitized on the Epson scanner, not the overhead camera. You're right that the normal workflow results in sRGB files, but we do have occasion to save certain materials in grayscale, even if it's rare. What solution would you recommend - changing the creation recipe or the profile for the files themselves?

**Comment by eddierubeiz** [comment]
The former, absolutely.

**Comment by HKativa** [comment]
Excellent, sounds good to me. I wonder if the recipe was re-written at some point because I've definitely ingested digitized negatives in the past, albeit back in the Hydra/Samvera days.

**Comment by eddierubeiz** [comment]
Yeah, we've messed around with thumbnail creation quite a bit -- balancing speed and memory use vs. nice-looking thumbnails.

There are several ways we can get around this. I have reason to suspect the latest version of VIPS doesn't have this problem (my laptop, which has 8.10 instead of 8.9, creates the thumbnails without any drama.) We could not use a colorspace `.icc` file at all for a bit -- yeah, that fixes it too. We could also check the colorspace of the files and use an appropriate color profile file - color for color and grayscale for grayscale.

Stay tuned -- I know you want these in a social media post shortly...

**Comment by HKativa** [comment]
Sounds good - do your thing! :)

**Comment by eddierubeiz** [comment]
Note to self: this bug might not exist on Heroku. Object lesson!

**Comment by eddierubeiz** [comment]
I have a band-aid working in staging (see https://staging-digital.sciencehistory.org/works/5mg4uul) but we'll need a more permanent solution, too.

**Comment by eddierubeiz** [comment]
@HKativa: I deployed the band-aid to production and generated derivatives for the following:
https://digital.sciencehistory.org/works/frc2gjq
https://digital.sciencehistory.org/works/9duelmb
https://digital.sciencehistory.org/works/yj7tsjw
https://digital.sciencehistory.org/works/zzf5tv3
I'll be doing some more work on a more permanent solution in the coming days, but you should be able to continue working as usual.

**Comment by HKativa** [comment]
Great, thanks for the update @eddierubeiz!
