### ISSUE TITLE
Extend file retention on S3 from 7 to 30 days

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#950]
Files copied over from the "Ready to Ingest" folder on M to S3 are currently deleted from S3 after a period of 7 days. Our workflow sometimes necessitates a longer period between digitization and ingest, particularly for interns and staff working remotely. Accordingly, please extend the retention period to 30 days.

**Comment by eddierubeiz** [comment]
The retention policy is not in code; it's a lifecycle rule for s3 bucket `scihist-digicoll-production-ingest-mount` named "Expire files".

**Comment by eddierubeiz** [comment]
I've updated the rule and ingested items should now stick around for 30 days.

**Comment by jrochkind** [comment]
@eddierubeiz Hypothetically the configuration of our S3 buckets is controlled by S3 playbook -- although I don't know if this rule ever made it into the playbook. If it did it needs to be changed there too... ideally it would be changed there *first*, then the playbook run to change in actual deployed S3. 

It looks like it may be, eg:

```
  "scihist-digicoll-production-ingest-mount":
    region: us-east-1
    versioning: no
    tag_service: kithe
    tag_use: upload
    expiration_date: 7
    cors: upload
    block_public_access: true
```

Change that `expiration_date` from 7 to 30 maybe?

**Comment by eddierubeiz** [comment]
That makes a lot of sense, and of course I'll change the number in Ansible. There is a `create_kithe_s3` role too, that invokes the code. If there were a corresponding `update_kithe_s3` role... I'd run that and change the numbers that way. But *creating* s3 buckets seems a bad idea to me.

**Comment by jrochkind** [comment]
done
