### ISSUE TITLE
configuration-as-code for S3 buckets

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#957]
We have a somewhat complicated set of S3 buckets with diverse configuration to support our app. 

Currently our ansible playbooks try to manage these. It may not be working 100%, not sure the setup captured in the playbook captures with accuracy or completeness the actual live S3 buckets. 

The idea, as with all of ansible, is infrastructure-as-code, or less mysteriously in this case we could say "configuration as code". We want the configuration of all these S3 buckets checked into our git repo as code, in such a way we can "execute" it to (re)-create and (re)-configure the buckets. This makes the configuration transparent, reproducible, version-controlled, etc. 

So, anyway, if we move to heroku (or any other options that abandon self-managed AWS), we won't use the majority of our current ansible playbook(s). 

But we still want configuration-as-code for our S3 buckets!

We could extract just the S3 part from the current ansible playbook. 

Or, I would suggest, let's instead develop `terraform` plans just for S3. I think it will work better than ansible for for S3 management, it's really desiged for tasks like this. And just managing S3 is a pretty simple terraform case, it's a good way for us to get our feet wet with terraform, a good learning exersize for terraform. 

See also #875

**Comment by eddierubeiz** [comment]
Duplicate of #1023, I believe.

**Comment by jrochkind** [comment]
and dup of #875! I'll leave that one open.
