### ISSUE TITLE
Limited-access oral histories: "Request Access" does not generate email file delivery

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#967]
After ingesting and publishing this limited-access oral history (https://digital.sciencehistory.org/works/r5v7ntm), I used the Request Access form to request an electronic copy of the oral history. The request was logged on the "Oral History Requests" menu, but I did not receive the email file delivery. I verified that the email is not stuck in my Sendio queue.

After some discussion with @jrochkind we're unsure where development of this feature left off. Note, on the Oral History tab for the work, the following message appears under the Un-Published Assets Available by Request header: "This feature is under construction and not yet functional."

**Comment by jrochkind** [comment]
Here's a staging URL to test, that Hillary also made: https://staging-digital.sciencehistory.org/works/ym8smcv

I would recommend using the staging url to test instead of production. Among other things, we don't want to fill up the Production log of requests sent with tests -- I don't think theres' any way to delete them from the list right now!

In my memory "This feature is under construction and not yet functional" refers to the fact that we don't yet support *mediated* requests, where staff has to approve them. 

I *think* the feature for these unmediated requests was intended to be working, although I think it could use some review and still has some sharp edges. But in my memory, we thought it was functional.

**Comment by eddierubeiz** [comment]
This should be working, yes.
See https://digital.sciencehistory.org/admin/oral_history_access_requests -- your request was logged, Hillary.
It looks like emails are not going out for whatever reason. This is a bug as far as I'm concerned.

**Comment by HKativa** [comment]
@eddierubeiz yes, I saw the request was logged. That's what I described (inexpertly) above. ;)

**Comment by jrochkind** [comment]
I tested password reset function from both staging and production, to verify both servers can send email. I successfully received password reset email to my @sciencehistory.org account from each. So both are able to send email, and to @sciencehistory.org in the case of password reset. 

From *staging*, I used the OH request feature, and entered **my gmail account** as the email. I did receive that email! So if you'd like to test the feature, for now you may be able to do so with a non-sciencehistory.org email address?   Please confirm if this works for anyone other than me. 

When I try requesting OH with my @sciencehistory.org email address... I do **not** get the email. And I can't find any evidence of it trapped in sendio. I have tried several times, same. 

I am not sure why this would be. 

Email can be weird. Unfortunately, Dan was the one of us with the best skillset at diagnosing this kind of failure. 

One differnece -- the password reset email is sent from `no-reply@sciencehistory.org`, but the OH delivery is from `digital@sciencehistory.org`. 

@CHF-IT-Staff (Chuck), is it possible that emails from digital@sciencehistory.org are getting caught in some kind of anti-spam filter, even though I don't see them in my sendio dashboard? Do some things get filtered out so we don't even see them in personal sendio dashboard? Do you have any other tools to look for that?

The good news is, our actual users will probably not have @sciencehistory.org emails, and the email seemed to get to gmail just fine?

**Comment by HKativa** [comment]
@jrochkind I can confirm that I submitted a request using my Gmail account and successfully received the files!

**Comment by eddierubeiz** [comment]
This was definitely working in staging, and approved by @lsberry16, as of late October (see https://github.com/sciencehistory/scihist_digicoll/pull/901 ). I'm disappointed it's no longer working.

We might not have tested it thoroughly in production, but Lee and I tested the email feature from staging, and did indeed receive files.

**Comment by jrochkind** [comment]
@eddierubeiz I see no reason to think it is a production/staging issue. My above account is of testing in staging. 

Please do *not* test this in production, so we don't fill up the Requests list with test requests that mess up request counts in production.

**Comment by jrochkind** [comment]
Ok, unfortunately I think this is a problem on @sciencehistory.org end, where it is deciding our emails our spam. 

We were hoping that switching email sending to Amazon SES would make that less likely in general. It's possible @sciencehistory.org is unusual and we won't generally have a problem with email delivery. 

If we generally have a problem with email delivery, the next step would be moving from Amazon SES to a more expensive email delivery service like sendgrid. In this day and age, it can be difficult to ensure email delivery, there are so many systems trying to figure out if you are spam or not.

**Comment by jrochkind** [comment]
i wonder if our email system has a problem with emails from digital@sciencehistory.org precisely because it knows that is one of it's own email addresses, and this email didn't technically come from it!

We thought it made sense to send from this email address, so if people have a question or problem they can reply and get a human. But we can have it sent from whatever email address we want to specify.

**Comment by jrochkind** [comment]
Just a problem of @sciencehistory.org `from` sent to science history addresses need to be whitelisted by chuck.

**Comment by jrochkind** [comment]
let's change these to come from oralhistory@sciencehistory.org; then we need to file help desk ticket to ask IT to allow-list that as a `from` address, much like `no-reply`.

**Comment by jrochkind** [comment]
Submitted help desk ticket 17706
