### ISSUE TITLE
Make CC BY-NC-ND 4.0 license an option in the Rights Metadata field

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/scihist_digicoll#973]
In the Rights Metadata field, creation an option that says "Creative Commons Attribution-NonCommercial-NoDerivs". This should be hyperlinked to the license deed: https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by jrochkind** [comment]
@MDiMeo  Just double-checking, are certain we should Rights, instead of making a separate field for CC license?

I would have expected this to be be "rights: In Copyright" with a CC-by license.

But, I guess, a CC license does kind of imply InCopyright, that's the only way you can offer a CC license in the first place, so I guess maybe it does make sense as one field after all. Is that what other cultural heritage orgs do, or what PA Digital/DPLA recommends, they want the CC license in the "rights" field?

OK! Just double-checking. 

(And I woudln't necessarily have expected "no derivatives" as a general rule for our CC's, although maybe on OH's. But in general, we're happy when people do things like make the music video derivative, no? Should we add some other CC's while we're at it, or not yet?)

**Comment by jrochkind** [comment]
Actually this will take a bit of work on *display* end, as right now we have things laid out to render the "rightsstatement.org" style logos, and CC is a different style of logo, we'll have to make sure the rendering renders it properly or uses a graphic or what have you. 

but it can be done.

**Comment by jrochkind** [comment]
We'll have to decide how we want the CC license to *look* to the public on the display end too. If you have any thoughts or suggestions, or we'll just come up with something. 

The existing rights statements use a template like this, based on how rightsstatements.org shows them:

![Screen Shot 2021-02-08 at 5 33 28 PM](https://user-images.githubusercontent.com/149304/107289985-d38c5d80-6a33-11eb-9e34-7efd7c6cff67.png)
![Screen Shot 2021-02-08 at 5 33 07 PM](https://user-images.githubusercontent.com/149304/107289986-d38c5d80-6a33-11eb-966e-b4a577c144a0.png)

But CC does not use that same template. They seem to have ready-made icons. We could use those icons? With words also?

**Comment by MDiMeo** [comment]
We were following the example of what we did already for Public Domain, which is technically following the CC rules and offering the Public Doman License instead of the No Copyright rights statement. I haven't done a ton of digging to see what our peers are doing in this regard -- just following what we did with Public Domain.

The logo from CC is ugly but there is on one the license:
![image](https://user-images.githubusercontent.com/11823009/107400392-c3c25700-6acf-11eb-840d-6f8e63c8ffb3.png)

**Comment by MDiMeo** [comment]
OK, didn't show for some reason. I was pointing to the images on the top of the license page: https://creativecommons.org/licenses/by-nc-nd/4.0/

**Comment by jrochkind** [comment]
In text shown to the user, the CC website recommends a long form with a few more words:

> This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.

https://creativecommons.org/choose/results-one?license_code=by-nc-nd&amp;jurisdiction=&amp;version=4.0&amp;lang=en

So I might add on the "4.0 International License" language in the staff input box too, for consistency and simplicity. I'm still playing around with different ways to display the CC license in the 2 or 3 user-facing places that we currently put rights statements (on the work show page; in the download menu; etc).

**Comment by jrochkind** [comment]
OK, for end-user display, I tried to do some things that seemed reasonable, and were in line with CC recommendations/examples. 

I wasn't comfortable usign *just* the somewhat impenetrable CC license-specific icons. So there are a lot more words required than on our "rights statements" logo types; I compensated by using the generic (cc) icon circular that kind of matches our rights statement ones for consistency. The words then explain the actual license, using wording and marking recommended by CC. 

![Screen Shot 2021-02-10 at 4 01 10 PM](https://user-images.githubusercontent.com/149304/107571661-36f3c800-6bb9-11eb-8a81-ecc04aedb093.png)

The Oral Histories we plan to use these with don't have Download menus with rights statements included, but I made sure if this rights term *were* used with something that did, it would still look okay -- in that case, I use the abbreviated form, but it is still a link to the CC license description of course. 

![Screen Shot 2021-02-10 at 4 02 35 PM](https://user-images.githubusercontent.com/149304/107571819-699dc080-6bb9-11eb-9520-9383ce1281e9.png)

This is now built out so we can easily add other CC licenses if we want them to; and should be able to apply these liceneses to any kind of work -- not just specific Oral Histories -- and have it display intelligibly.

**Comment by jrochkind** [comment]
Alternately, on the "show" page, we could use all the CC graphic icons to indicate BY-NC-ND pictorially. Which I think requires putting the textual explanation on another line -- so it takes up somewhat more vertical space on the page. 

In this case I also made the text smaller. What do you think, better or worse than above?

![Screen Shot 2021-02-11 at 10 19 07 AM](https://user-images.githubusercontent.com/149304/107657030-c00b0d80-6c52-11eb-8240-5cf1e4883793.png)

**Comment by jrochkind** [comment]
@MDiMeo I think the second one, with the CC pictographs, is better and @lsberry16 and @eddierubeiz agreed, so I'm going to go ahead and work on implementing it.
