### ISSUE TITLE
Basic display of OH interviewee metadata in a new tab on the work admin section

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#977]
We'll start out very simple with just a table listing birth / death place and date, education, career, and awards.
No form for editing any of this yet.
None of this metadata will be shown to users on the public-facing pages yet.

**Comment by jrochkind** [comment]
See #996 on "role" in our Dig Coll data model

**Comment by MDiMeo** [comment]
When we're ready to discuss the front-end design of the metadata pages, please reach out to @HKativa for feedback when you need it.
