### ISSUE TITLE
Make "Oral Histories" pre-heading link to Oral History Collection page, instead of genre-limited search.

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#988]
Our search results (and show pages) have a little "pre-heading" listing their genre(s). 

Eg the "Advertisements, Epherma" in:

![Screen Shot 2021-02-22 at 2 55 49 PM](https://user-images.githubusercontent.com/149304/108762439-1400d680-751e-11eb-99a6-bb76c18aa6e6.png)

Normally that links to search results limited to that genre, like if you clicked on "Advertisements", you'd get [this](https://digital.sciencehistory.org/catalog?f%5Bgenre_facet%5D%5B%5D=Advertisements)

But as part of "custom-homing" Oral Histories into Digital Collections, I wonder if when you click on it for "Oral Histories", you actually go to the Oral History Collection page instead: https://digital.sciencehistory.org/collections/gt54kn818

This week I was looking for some very small tweaks to Oral Histories in Dig Coll to clean it up and make it nicer. This is potentially such. Does this seem like a good idea, @MDiMeo  and @lsberry16 ?

**Comment by lsberry16** [comment]
I think that would be great. Is there any other "Collection" landing page similar to Oral History's? Are other such pages envisioned?

**Comment by jrochkind** [comment]
There aren't any others I can think of, currently or envisioned. This is kind of a special purpose thing. 

The fact that there is a "genre" term ("Oral Histories") that matches one-to-one with a "Collection" ("Oral History Collection") -- everything in one is in the other and nothing else and vice versa -- is at the moment I think only true of oral histories.
