### ISSUE TITLE
"Format" shows up twice on the work display page, once mislabeled "Medium".

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#99]
The underlying metadata is sound, and the labeling on the metadata edit form is correct.

**Comment by jrochkind** [comment]
i'm not understanding what this issue means, can you provide an example?

**Comment by eddierubeiz** [comment]
Sure -- go to https://kithe.sciencehistory.org/admin/works/gh93h0373/ and note that 
Format: image
[...]
Medium: image

Image is the format; there's no medium defined for this work.

**Comment by jrochkind** [comment]
Ah, might not be related to the import, might just be a bug in the view code rendering those fields? That seems likely, the view code might have just been a copy-and-paste that wasn't fixed properly, and is rendering the wrong thing under the label "Medium". Want to take a look and fix it in the app? Get your feet wet in the app. :)

**Comment by eddierubeiz** [comment]
Yeah this is just a template problem . That's what I meant by "The underlying metadata is sound" :)
