### ISSUE TITLE
"Add from Cloud" option for .txt files

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#992]
Currently, the only option for uploading a searchable transcript text file (.txt) to an oral history record is a local upload.

 
![image](https://user-images.githubusercontent.com/39598789/108897877-8936df00-75e4-11eb-8281-1f56a6a69f0c.png)

Could we add "Add from Cloud" as an additional option for uploading .txt files, mirroring the functionality for uploading new members to a work?

![image](https://user-images.githubusercontent.com/39598789/108898158-de72f080-75e4-11eb-8b1c-5a23d61ab820.png)

Some background: currently, oral histories are "packaged" for ingest, with PDF, audio, and text files stored together in a single folder corresponding to each interviewee. These folders are then copied onto S3. Connecting the .txt upload to the cloud would streamline the upload process, saving users the extra step of saving copies of the .txt files locally or working through the Citrix desktop when uploading these files.

**Comment by jrochkind** [comment]
Unfortunately, this is more tricky to implement than it should be, our "add from cloud" functionality (using the samvera community `browse_everything` gem) isn't as easily re-usable as it should be. 

I'll see if I can figure out some context as to how we might do this. We (@MDiMeo ) should discuss prioritizing it at our next weekly prioritization meeting, it's unfortunately significant work.

**Comment by MDiMeo** [comment]
Hillary worked out another solution with Chuck. We decided not to implement this.
