### ISSUE TITLE
Bulk edit: OH rights field

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/scihist_digicoll#999]
For all oral history interviews where rights status is “In Copyright Non-Commercial Use Permitted,” change rights status to CC-BY-NC-ND license option.

**Comment by jrochkind** [comment]
Using my judgement to take this from inbox to work on now, without official product owner prioritization.

**Comment by jrochkind** [comment]
@HKativa Can I clarify, *all* Oral Histories should have rights status `CC-BY-NC-ND` when complete, correct?

**Comment by jrochkind** [comment]
Done!

For future developer reference, here is the somewhat hacky but it worked way I did this in console:

```
Work.include AttrJson::Record::QueryScopes

Work.jsonb_contains(genre: "Oral histories", rights: "http://rightsstatements.org/vocab/InC-NC/1.0/").each {|w| puts w.rights = "https://creativecommons.org/licenses/by-nc-nd/4.0/"; w.save! }
```

That `AttrJson::Record::QueryScopes` functionality is useful for not having to manually write the jsonb contains stuff, maybe we should include it in our models usually.

**Comment by eddierubeiz** [comment]
Great.
See also https://github.com/sciencehistory/scihist_digicoll/issues/372#issuecomment-563386360
